/*
 * PROJECT:         ReactOS ACPI Time and Alarm driver interface
 * LICENSE:         GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 */

#pragma once

/* {80174F25-2503-43B5-9885-D05AAEDEC2EC} */
DEFINE_GUID(GUID_DEVINTERFACE_REACTOS_ACPITIME,
    0x80174F25, 0x2503, 0x43B5,
    0x98, 0x85, 0xD0, 0x5A, 0xAE, 0xDE, 0xC2, 0xEC);

#define ACPITIME_DRIVER_INTERFACE_VERSION 1

#define ACPITIME_CAP_AC_WAKE              0x00000001
#define ACPITIME_CAP_DC_WAKE              0x00000002
#define ACPITIME_CAP_REAL_TIME            0x00000004
#define ACPITIME_CAP_MILLISECOND_TIME      0x00000008
#define ACPITIME_CAP_S4_S5_WAKE_STATUS     0x00000010
#define ACPITIME_CAP_S4_AC_WAKE            0x00000020
#define ACPITIME_CAP_S5_AC_WAKE            0x00000040
#define ACPITIME_CAP_S4_DC_WAKE            0x00000080
#define ACPITIME_CAP_S5_DC_WAKE            0x00000100
#define ACPITIME_CAP_VALID_MASK            0x000001FF

#define ACPITIME_TIMER_AC 0
#define ACPITIME_TIMER_DC 1
#define ACPITIME_TIMER_DISABLED MAXULONG

typedef struct _ACPITIME_DEVICE_INFORMATION
{
    ULONG Version;
    ULONG Capabilities;
} ACPITIME_DEVICE_INFORMATION, *PACPITIME_DEVICE_INFORMATION;

typedef struct _ACPITIME_TIME_INFORMATION
{
    USHORT Year;
    UCHAR Month;
    UCHAR Day;
    UCHAR Hour;
    UCHAR Minute;
    UCHAR Second;
    UCHAR Valid;
    USHORT Milliseconds;
    SHORT Timezone;
    UCHAR Daylight;
    UCHAR Reserved[3];
} ACPITIME_TIME_INFORMATION, *PACPITIME_TIME_INFORMATION;

typedef struct _ACPITIME_TIMER_INFORMATION
{
    ULONG Timer;
    ULONG Status;
    ULONG Value;
    ULONG Policy;
} ACPITIME_TIMER_INFORMATION, *PACPITIME_TIMER_INFORMATION;

typedef struct _ACPITIME_TIMER_SET
{
    ULONG Timer;
    ULONG Value;
    ULONG Policy;
} ACPITIME_TIMER_SET, *PACPITIME_TIMER_SET;

#define IOCTL_ACPITIME_QUERY_INFORMATION CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_ACPITIME_GET_TIME CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_ACPITIME_SET_TIME CTL_CODE(FILE_DEVICE_UNKNOWN, 0x902, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_ACPITIME_GET_TIMER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x903, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_ACPITIME_SET_TIMER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x904, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_ACPITIME_CLEAR_STATUS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x905, METHOD_BUFFERED, FILE_WRITE_ACCESS)
