/*
 * PROJECT:     ReactOS Intel GPIO driver interface
 * LICENSE:     LGPL-2.1-or-later
 */

#pragma once

#include <guiddef.h>

DEFINE_GUID(GUID_DEVINTERFACE_INTEL_GPIO, 0x6dc99608, 0x52ef, 0x4fd5, 0xa7, 0x6a, 0x3d, 0x78, 0x67, 0x71, 0x71, 0x31);

#define INTELGPIO_INTERFACE_VERSION 1
#define INTELGPIO_DEBOUNCE_PRESERVE 0xffffffffUL

#define IOCTL_INTELGPIO_QUERY_PIN CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_INTELGPIO_CONFIGURE_PIN CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_INTELGPIO_WRITE_PIN CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_INTELGPIO_CONFIGURE_INTERRUPT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_INTELGPIO_WAIT_INTERRUPT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_READ_ACCESS)

#define INTELGPIO_ANY_PIN 0xffffffffUL

#define INTELGPIO_PIN_STATE_HOST_OWNED 0x00000001
#define INTELGPIO_PIN_STATE_ACPI_MODE 0x00000002
#define INTELGPIO_PIN_STATE_CONFIG_LOCKED 0x00000004
#define INTELGPIO_PIN_STATE_TX_LOCKED 0x00000008
#define INTELGPIO_PIN_STATE_GPIO_MODE 0x00000010
#define INTELGPIO_PIN_STATE_INPUT_ENABLED 0x00000020
#define INTELGPIO_PIN_STATE_OUTPUT_ENABLED 0x00000040

typedef enum _INTELGPIO_DIRECTION
{
    IntelGpioDirectionInput = 1,
    IntelGpioDirectionOutput = 2,
    IntelGpioDirectionInputOutput = 3
} INTELGPIO_DIRECTION;

typedef enum _INTELGPIO_PULL_CONFIGURATION
{
    IntelGpioPullPreserve = 0,
    IntelGpioPullNone = 1,
    IntelGpioPullUp20K = 2,
    IntelGpioPullDown20K = 3
} INTELGPIO_PULL_CONFIGURATION;

typedef enum _INTELGPIO_INTERRUPT_MODE
{
    IntelGpioInterruptDisabled,
    IntelGpioInterruptLevelHigh,
    IntelGpioInterruptLevelLow,
    IntelGpioInterruptEdgeRising,
    IntelGpioInterruptEdgeFalling,
    IntelGpioInterruptEdgeBoth
} INTELGPIO_INTERRUPT_MODE;

typedef struct _INTELGPIO_PIN_INFORMATION
{
    ULONG Version;
    ULONG PinNumber;
    ULONG State;
    ULONG Value;
    ULONG PadConfiguration0;
    ULONG PadConfiguration1;
    ULONG PadConfiguration2;
} INTELGPIO_PIN_INFORMATION, *PINTELGPIO_PIN_INFORMATION;

typedef struct _INTELGPIO_PIN_CONFIGURATION
{
    ULONG Version;
    ULONG PinNumber;
    ULONG Direction;
    ULONG InitialValue;
    ULONG PullConfiguration;
    ULONG DebounceExponent;
} INTELGPIO_PIN_CONFIGURATION, *PINTELGPIO_PIN_CONFIGURATION;

typedef struct _INTELGPIO_PIN_WRITE
{
    ULONG Version;
    ULONG PinNumber;
    ULONG Value;
} INTELGPIO_PIN_WRITE, *PINTELGPIO_PIN_WRITE;

typedef struct _INTELGPIO_INTERRUPT_CONFIGURATION
{
    ULONG Version;
    ULONG PinNumber;
    ULONG Mode;
} INTELGPIO_INTERRUPT_CONFIGURATION, *PINTELGPIO_INTERRUPT_CONFIGURATION;

typedef struct _INTELGPIO_INTERRUPT_WAIT
{
    ULONG Version;
    ULONG PinNumber;
    ULONG TimeoutMilliseconds;
    ULONG TriggeredPin;
} INTELGPIO_INTERRUPT_WAIT, *PINTELGPIO_INTERRUPT_WAIT;
