/*
 * PROJECT:         ReactOS sensor provider interface
 * COPYRIGHT:       Copyright 2026 Ahmed ARIF <arif.ing@outlook.com>
 * LICENSE:         GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later)
 */

#pragma once

/* {DE16EBA7-2E25-462F-BC46-139828F56E6E} */
DEFINE_GUID(GUID_DEVINTERFACE_REACTOS_SENSOR_PROVIDER,
    0xDE16EBA7, 0x2E25, 0x462F,
    0xBC, 0x46, 0x13, 0x98, 0x28, 0xF5, 0x6E, 0x6E);

#define REACTOS_SENSOR_PROVIDER_INTERFACE_VERSION 1
#define REACTOS_SENSOR_PROVIDER_MAX_CHANNELS 16
#define REACTOS_SENSOR_PROVIDER_STRING_LENGTH 64

#define REACTOS_SENSOR_PROVIDER_FLAG_READ_ONLY 0x00000001

#define REACTOS_SENSOR_TYPE_VOLTAGE 1
#define REACTOS_SENSOR_TYPE_TEMPERATURE 2
#define REACTOS_SENSOR_TYPE_FAN_SPEED 3

#define REACTOS_SENSOR_UNIT_MICROVOLTS 1
#define REACTOS_SENSOR_UNIT_MICRODEGREES_CELSIUS 2
#define REACTOS_SENSOR_UNIT_REVOLUTIONS_PER_MINUTE 3

#define REACTOS_SENSOR_CHANNEL_FLAG_READ_ONLY 0x00000001
#define REACTOS_SENSOR_CHANNEL_FLAG_INTERNAL 0x00000002
#define REACTOS_SENSOR_CHANNEL_FLAG_UNCALIBRATED 0x00000004

typedef struct _REACTOS_SENSOR_CHANNEL_INFORMATION
{
    GUID SensorId;
    ULONG Type;
    ULONG Unit;
    ULONG Flags;
    ULONG Reserved;
    LONGLONG Resolution;
    WCHAR Name[REACTOS_SENSOR_PROVIDER_STRING_LENGTH];
} REACTOS_SENSOR_CHANNEL_INFORMATION, *PREACTOS_SENSOR_CHANNEL_INFORMATION;

typedef struct _REACTOS_SENSOR_PROVIDER_INFORMATION
{
    ULONG Version;
    ULONG Size;
    GUID ProviderId;
    ULONG Flags;
    ULONG ChannelCount;
    WCHAR Manufacturer[REACTOS_SENSOR_PROVIDER_STRING_LENGTH];
    WCHAR Model[REACTOS_SENSOR_PROVIDER_STRING_LENGTH];
    REACTOS_SENSOR_CHANNEL_INFORMATION Channels[REACTOS_SENSOR_PROVIDER_MAX_CHANNELS];
} REACTOS_SENSOR_PROVIDER_INFORMATION, *PREACTOS_SENSOR_PROVIDER_INFORMATION;

typedef struct _REACTOS_SENSOR_READ_INPUT
{
    ULONG Version;
    ULONG Size;
    ULONG ChannelIndex;
    ULONG Reserved;
} REACTOS_SENSOR_READ_INPUT, *PREACTOS_SENSOR_READ_INPUT;

typedef struct _REACTOS_SENSOR_READING
{
    ULONG Version;
    ULONG Size;
    GUID SensorId;
    ULONG Type;
    ULONG Unit;
    ULONG Flags;
    ULONG RawValue;
    LONGLONG Value;
    LONGLONG Timestamp;
} REACTOS_SENSOR_READING, *PREACTOS_SENSOR_READING;

#define IOCTL_REACTOS_SENSOR_QUERY_PROVIDER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x930, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_REACTOS_SENSOR_READ_CHANNEL CTL_CODE(FILE_DEVICE_UNKNOWN, 0x931, METHOD_BUFFERED, FILE_READ_ACCESS)
