/*
 * PROJECT:         ReactOS TPM 2.0 driver interface
 * LICENSE:         GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 */

#pragma once

/* {C43A14B0-914F-4D3C-9F1A-16B9E60D79BC} */
DEFINE_GUID(GUID_DEVINTERFACE_REACTOS_TPM2,
    0xC43A14B0, 0x914F, 0x4D3C,
    0x9F, 0x1A, 0x16, 0xB9, 0xE6, 0x0D, 0x79, 0xBC);

#define TPM2_DRIVER_INTERFACE_VERSION 1
#define TPM2_INTERFACE_CRB 1
#define TPM2_INTERFACE_TIS 2

typedef struct _TPM2_DEVICE_INFORMATION
{
    ULONG Version;
    ULONG InterfaceType;
    ULONG StartMethod;
    ULONG MaximumCommandSize;
    ULONG MaximumResponseSize;
    ULONG Manufacturer;
    ULONG FirmwareVersion1;
    ULONG FirmwareVersion2;
} TPM2_DEVICE_INFORMATION, *PTPM2_DEVICE_INFORMATION;

#define IOCTL_TPM2_QUERY_INFORMATION CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_TPM2_SUBMIT_COMMAND CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_TPM2_CANCEL_COMMAND CTL_CODE(FILE_DEVICE_UNKNOWN, 0x902, METHOD_BUFFERED, FILE_WRITE_ACCESS)
