/*
 * PROJECT:     ReactOS Display Driver Model
 * LICENSE:     MIT (https://spdx.org/licenses/MIT)
 * PURPOSE:     Dxgkrnl callbacks header
 * COPYRIGHT:   Copyright 2023 Justin Miller <justin.miller@reactos.org>
 */

#pragma once

#include <d3dkmddi.h>
#include <d3dkmthk.h>

/*
 * Every structure in here is shared across two or more modules and doesn't currently
 * match a single Windows version/update.
 *
 * These structures DO have variants in Windows, I just would like to track what
 * we don't match 1:1 yet. Or haven't bother attempting to do so.
 */

/* \Device\DxgKrnl IOCTL device type (win32k <-> dxgkrnl). */
#define DXGKRNL_DEVICE_TYPE     0x23

/*
 * Kernel-to-kernel interface exchange (IRP_MJ_INTERNAL_DEVICE_CONTROL): win32k
 * sends its version at initialization, dxgkrnl validates it and returns the
 * REACTOS_WIN32K_DXGKRNL_INTERFACE callback table.
 */
#define IOCTL_DXGKRNL_EXCHANGE_INTERFACE \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x200, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define DXGKRNL_INTERFACE_VERSION_1        1
#define DXGKRNL_INTERFACE_VERSION_2        2
#define DXGKRNL_INTERFACE_VERSION_3        3
#define DXGKRNL_INTERFACE_VERSION_4        4
#define DXGKRNL_INTERFACE_VERSION_5        5
#define DXGKRNL_INTERFACE_VERSION_CURRENT  DXGKRNL_INTERFACE_VERSION_5

typedef struct _DXGKRNL_INTERFACE_EXCHANGE_IN
{
    ULONG Version;      /* Highest interface version understood by caller. */
    ULONG Size;         /* Bytes available for that version's callback table. */
} DXGKRNL_INTERFACE_EXCHANGE_IN, *PDXGKRNL_INTERFACE_EXCHANGE_IN;

/* REACTOS_WIN32K_DXGKRNL_INTERFACE function Pointers: */

typedef
NTSTATUS
DXGADAPTER_CREATEALLOCATION(_Inout_ D3DKMT_CREATEALLOCATION* unnamedParam1);

typedef DXGADAPTER_CREATEALLOCATION *PDXGADAPTER_CREATEALLOCATION;

typedef
NTSTATUS
DXGADAPTER_CREATEALLOCATION2(_Inout_ D3DKMT_CREATEALLOCATION* unnamedParam1);

typedef DXGADAPTER_CREATEALLOCATION2 *PDXGADAPTER_CREATEALLOCATION2;

typedef
NTSTATUS
DXGADAPTER_CHECKMONITORPOWERSTATE(_In_ const D3DKMT_CHECKMONITORPOWERSTATE* unnamedParam1);

typedef DXGADAPTER_CHECKMONITORPOWERSTATE *PDXGADAPTER_CHECKMONITORPOWERSTATE;

typedef
NTSTATUS
DXGADAPTER_CHECKOCCLUSION(_In_ const D3DKMT_CHECKOCCLUSION* unnamedParam1);

typedef DXGADAPTER_CHECKOCCLUSION *PDXGADAPTER_CHECKOCCLUSION;

typedef
NTSTATUS
DXGADAPTER_CLOSEADAPTER(_In_ const D3DKMT_CLOSEADAPTER* unnamedParam1);

typedef DXGADAPTER_CLOSEADAPTER *PDXGADAPTER_CLOSEADAPTER;

typedef
NTSTATUS
DXGADAPTER_CREATECONTEXT(_Inout_ D3DKMT_CREATECONTEXT* unnamedParam1);

typedef DXGADAPTER_CREATECONTEXT *PDXGADAPTER_CREATECONTEXT;

typedef
NTSTATUS
DXGADAPTER_CREATEDEVICE(_Inout_ D3DKMT_CREATEDEVICE* unnamedParam1);

typedef DXGADAPTER_CREATEDEVICE *PDXGADAPTER_CREATEDEVICE;

typedef
NTSTATUS
DXGADAPTER_CREATEOVERLAY(_Inout_ D3DKMT_CREATEOVERLAY* unnamedParam1);

typedef DXGADAPTER_CREATEOVERLAY *PDXGADAPTER_CREATEOVERLAY;

typedef
NTSTATUS
DXGADAPTER_CREATESYNCHRONIZATIONOBJECT(_Inout_ D3DKMT_CREATESYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_CREATESYNCHRONIZATIONOBJECT *PDXGADAPTER_CREATESYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
DXGADAPTER_DESTROYALLOCATION(_In_ const D3DKMT_DESTROYALLOCATION* unnamedParam1);

typedef DXGADAPTER_DESTROYALLOCATION *PDXGADAPTER_DESTROYALLOCATION;

typedef
NTSTATUS
DXGADAPTER_DESTROYCONTEXT(_In_ const D3DKMT_DESTROYCONTEXT* unnamedParam1);

typedef DXGADAPTER_DESTROYCONTEXT *PDXGADAPTER_DESTROYCONTEXT;

typedef
NTSTATUS
DXGADAPTER_DESTROYDEVICE(_In_ const D3DKMT_DESTROYDEVICE* unnamedParam1);

typedef DXGADAPTER_DESTROYDEVICE *PDXGADAPTER_DESTROYDEVICE;

typedef
NTSTATUS
DXGADAPTER_DESTROYOVERLAY(_In_ const D3DKMT_DESTROYOVERLAY* unnamedParam1);

typedef DXGADAPTER_DESTROYOVERLAY *PDXGADAPTER_DESTROYOVERLAY;

typedef
NTSTATUS
DXGADAPTER_DESTROYSYNCHRONIZATIONOBJECT(_In_ const D3DKMT_DESTROYSYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_DESTROYSYNCHRONIZATIONOBJECT *PDXGADAPTER_DESTROYSYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
DXGADAPTER_ESCAPE(_In_ const D3DKMT_ESCAPE* unnamedParam1);

typedef DXGADAPTER_ESCAPE *PDXGADAPTER_ESCAPE;

typedef
NTSTATUS
DXGADAPTER_FLIPOVERLAY(_In_ const D3DKMT_FLIPOVERLAY* unnamedParam1);

typedef DXGADAPTER_FLIPOVERLAY *PDXGADAPTER_FLIPOVERLAY;

typedef
NTSTATUS
DXGADAPTER_GETCONTEXTSCHEDULINGPRIORITY(_Inout_ D3DKMT_GETCONTEXTSCHEDULINGPRIORITY* unnamedParam1);

typedef DXGADAPTER_GETCONTEXTSCHEDULINGPRIORITY *PDXGADAPTER_GETCONTEXTSCHEDULINGPRIORITY;

typedef
NTSTATUS
DXGADAPTER_GETDEVICESTATE(_Inout_ D3DKMT_GETDEVICESTATE* unnamedParam1);

typedef DXGADAPTER_GETDEVICESTATE *PDXGADAPTER_GETDEVICESTATE;

typedef
NTSTATUS
DXGADAPTER_GETDISPLAYMODELIST(_Inout_ D3DKMT_GETDISPLAYMODELIST* unnamedParam1);

typedef DXGADAPTER_GETDISPLAYMODELIST *PDXGADAPTER_GETDISPLAYMODELIST;

typedef
NTSTATUS
DXGADAPTER_GETMULTISAMPLEMETHODLIST(_Inout_ D3DKMT_GETMULTISAMPLEMETHODLIST* unnamedParam1);

typedef DXGADAPTER_GETMULTISAMPLEMETHODLIST *PDXGADAPTER_GETMULTISAMPLEMETHODLIST;

typedef
NTSTATUS
DXGADAPTER_GETRUNTIMEDATA(_Inout_ CONST D3DKMT_GETRUNTIMEDATA* unnamedParam1);

typedef DXGADAPTER_GETRUNTIMEDATA *PDXGADAPTER_GETRUNTIMEDATA;

typedef
NTSTATUS
DXGADAPTER_GETSCANLINE(_Inout_ D3DKMT_GETSCANLINE* unnamedParam1);

typedef DXGADAPTER_GETSCANLINE *PDXGADAPTER_GETSCANLINE;

typedef
NTSTATUS
DXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT(_In_ const D3DKMT_SIGNALSYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT *PDXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
DXGADAPTER_WAITFORVERTICALBLANKEVENT(_In_ const D3DKMT_WAITFORVERTICALBLANKEVENT* unnamedParam1);

typedef DXGADAPTER_WAITFORVERTICALBLANKEVENT *PDXGADAPTER_WAITFORVERTICALBLANKEVENT;

typedef
NTSTATUS
DXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT(_In_ const D3DKMT_WAITFORSYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT *PDXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
DXGADAPTER_SETVIDPNSOURCEOWNER(_In_ const D3DKMT_SETVIDPNSOURCEOWNER* unnamedParam1);

typedef DXGADAPTER_SETVIDPNSOURCEOWNER *PDXGADAPTER_SETVIDPNSOURCEOWNER;

typedef
NTSTATUS
DXGADAPTER_WAITFORIDLE(_In_ const D3DKMT_WAITFORIDLE* unnamedParam1);

typedef DXGADAPTER_WAITFORIDLE *PDXGADAPTER_WAITFORIDLE;

typedef
NTSTATUS
DXGADAPTER_UPDATEOVERLAY(_In_ const D3DKMT_UPDATEOVERLAY* unnamedParam1);

typedef DXGADAPTER_UPDATEOVERLAY *PDXGADAPTER_UPDATEOVERLAY;

typedef
NTSTATUS
DXGADAPTER_SETQUEUEDLIMIT(_In_ const D3DKMT_SETQUEUEDLIMIT* unnamedParam1);

typedef DXGADAPTER_SETQUEUEDLIMIT *PDXGADAPTER_SETQUEUEDLIMIT;

typedef
NTSTATUS
DXGADAPTER_SETGAMMARAMP(_In_ const D3DKMT_SETGAMMARAMP* unnamedParam1);

typedef DXGADAPTER_SETGAMMARAMP *PDXGADAPTER_SETGAMMARAMP;

typedef
NTSTATUS
DXGADAPTER_SETDISPLAYMODE(_In_ const D3DKMT_SETDISPLAYMODE* unnamedParam1);

typedef DXGADAPTER_SETDISPLAYMODE *PDXGADAPTER_SETDISPLAYMODE;

typedef
NTSTATUS
DXGADAPTER_SETDISPLAYPRIVATEDRIVERFORMAT(_In_ const D3DKMT_SETDISPLAYPRIVATEDRIVERFORMAT* unnamedParam1);

typedef DXGADAPTER_SETDISPLAYPRIVATEDRIVERFORMAT *PDXGADAPTER_SETDISPLAYPRIVATEDRIVERFORMAT;


typedef
NTSTATUS
DXGADAPTER_SETGAMMARAMP(_In_ const D3DKMT_SETGAMMARAMP* unnamedParam1);

typedef DXGADAPTER_SETGAMMARAMP *PDXGADAPTER_SETGAMMARAMP;

typedef
NTSTATUS
DXGADAPTER_SETQUEUEDLIMIT(_In_ const D3DKMT_SETQUEUEDLIMIT* unnamedParam1);

typedef DXGADAPTER_SETQUEUEDLIMIT *PDXGADAPTER_SETQUEUEDLIMIT;

typedef
NTSTATUS
DXGADAPTER_SETVIDPNSOURCEOWNER(_In_ const D3DKMT_SETVIDPNSOURCEOWNER* unnamedParam1);

typedef DXGADAPTER_SETVIDPNSOURCEOWNER *PDXGADAPTER_SETVIDPNSOURCEOWNER;

typedef
NTSTATUS
DXGADAPTER_UNLOCK(_In_ const D3DKMT_UNLOCK* unnamedParam1);

typedef DXGADAPTER_UNLOCK *PDXGADAPTER_UNLOCK;

typedef
NTSTATUS
DXGADAPTER_UPDATEOVERLAY(_In_ const D3DKMT_UPDATEOVERLAY* unnamedParam1);

typedef DXGADAPTER_UPDATEOVERLAY *PDXGADAPTER_UPDATEOVERLAY;

typedef
NTSTATUS
DXGADAPTER_WAITFORIDLE(_In_ const D3DKMT_WAITFORIDLE* unnamedParam1);

typedef DXGADAPTER_WAITFORIDLE *PDXGADAPTER_WAITFORIDLE;

typedef
NTSTATUS
DXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT(_In_ const D3DKMT_WAITFORSYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT *PDXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
DXGADAPTER_WAITFORVERTICALBLANKEVENT(_In_ const D3DKMT_WAITFORVERTICALBLANKEVENT* unnamedParam1);

typedef DXGADAPTER_WAITFORVERTICALBLANKEVENT *PDXGADAPTER_WAITFORVERTICALBLANKEVENT;

typedef
NTSTATUS
DXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT(_In_ const D3DKMT_SIGNALSYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT *PDXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
DXGADAPTER_QUERYRESOURCEINFO(_Inout_ D3DKMT_QUERYRESOURCEINFO* unnamedParam1);

typedef DXGADAPTER_QUERYRESOURCEINFO *PDXGADAPTER_QUERYRESOURCEINFO;

typedef
NTSTATUS
DXGADAPTER_GETPRESENTHISTORY(_Inout_ D3DKMT_GETPRESENTHISTORY* unnamedParam1);

typedef DXGADAPTER_GETPRESENTHISTORY *PDXGADAPTER_GETPRESENTHISTORY;

typedef
NTSTATUS
DXGADAPTER_SETALLOCATIONPRIORITY(_In_ const D3DKMT_SETALLOCATIONPRIORITY* unnamedParam1);

typedef DXGADAPTER_SETALLOCATIONPRIORITY *PDXGADAPTER_SETALLOCATIONPRIORITY;

typedef
NTSTATUS
DXGADAPTER_INVALIDATEACTIVEVIDPN(_In_ const D3DKMT_INVALIDATEACTIVEVIDPN* unnamedParam1);

typedef DXGADAPTER_INVALIDATEACTIVEVIDPN *PDXGADAPTER_INVALIDATEACTIVEVIDPN;

typedef
NTSTATUS
DXGADAPTER_GETSHAREDPRIMARYHANDLE(_In_ D3DKMT_GETSHAREDPRIMARYHANDLE* unnamedParam1);

typedef DXGADAPTER_GETSHAREDPRIMARYHANDLE *PDXGADAPTER_GETSHAREDPRIMARYHANDLE;

typedef
NTSTATUS
DXGADAPTER_LOCK(_In_ D3DKMT_LOCK* unnamedParam1);

typedef DXGADAPTER_LOCK *PDXGADAPTER_LOCK;

typedef
NTSTATUS
DXGADAPTER_POLLDISPLAYCHILDREN(_In_ const D3DKMT_POLLDISPLAYCHILDREN* unnamedParam1);

typedef DXGADAPTER_POLLDISPLAYCHILDREN *PDXGADAPTER_POLLDISPLAYCHILDREN;

typedef
NTSTATUS
DXGADAPTER_OPENRESOURCE(_Inout_ D3DKMT_OPENRESOURCE* unnamedParam1);

typedef DXGADAPTER_OPENRESOURCE *PDXGADAPTER_OPENRESOURCE;

typedef
NTSTATUS
DXGADAPTER_PRESENT(_In_ D3DKMT_PRESENT* unnamedParam1);

typedef DXGADAPTER_PRESENT *PDXGADAPTER_PRESENT;

typedef
NTSTATUS
DXGADAPTER_QUERYADAPTERINFO(_Inout_ CONST D3DKMT_QUERYADAPTERINFO* unnamedParam1);

typedef DXGADAPTER_QUERYADAPTERINFO *PDXGADAPTER_QUERYADAPTERINFO;

typedef
NTSTATUS
DXGADAPTER_QUERYALLOCATIONRESIDENCY(_In_ const D3DKMT_QUERYALLOCATIONRESIDENCY* unnamedParam1);

typedef DXGADAPTER_QUERYALLOCATIONRESIDENCY *PDXGADAPTER_QUERYALLOCATIONRESIDENCY;

typedef
NTSTATUS
DXGADAPTER_QUERYSTATISTICS(_Inout_ CONST D3DKMT_QUERYSTATISTICS* unnamedParam1);

typedef DXGADAPTER_QUERYSTATISTICS *PDXGADAPTER_QUERYSTATISTICS;

typedef
NTSTATUS
DXGADAPTER_RELEASEPROCESSVIDPNSOURCEOWNERS(_In_ HANDLE unnamedParam1);

typedef DXGADAPTER_RELEASEPROCESSVIDPNSOURCEOWNERS *PDXGADAPTER_RELEASEPROCESSVIDPNSOURCEOWNERS;

typedef
NTSTATUS
DXGADAPTER_RENDER(_In_ D3DKMT_RENDER* unnamedParam1);

typedef DXGADAPTER_RENDER *PDXGADAPTER_RENDER;

typedef
NTSTATUS
DXGADAPTER_SETCONTEXTSCHEDULINGPRIORITY(_In_ const D3DKMT_SETCONTEXTSCHEDULINGPRIORITY* unnamedParam1);

typedef DXGADAPTER_SETCONTEXTSCHEDULINGPRIORITY *PDXGADAPTER_SETCONTEXTSCHEDULINGPRIORITY;

/*
 * WDDM 1.2 (Win8) type fallbacks.
 *
 * These D3DKMT types are guarded by DXGKDDI_INTERFACE_VERSION >= WIN8 in
 * d3dkmthk.h, but we need them here regardless of the miniport DDI version
 * because they are used in the user-mode D3DKMT plumbing (gdi32 -> win32k).
 *
 * The guard below fires when either macro is undefined (win32k/d3dkmt_stubs.c
 * compiles without dispmprt.h) or when the interface version is below Win8.
 */
#if !defined(DXGKDDI_INTERFACE_VERSION) || !defined(DXGKDDI_INTERFACE_VERSION_WIN8) || \
    (DXGKDDI_INTERFACE_VERSION < DXGKDDI_INTERFACE_VERSION_WIN8)

#ifndef MAX_ENUM_ADAPTERS
#define MAX_ENUM_ADAPTERS   16
#endif

#ifndef _D3DKMT_ADAPTERINFO_DEFINED
#define _D3DKMT_ADAPTERINFO_DEFINED
typedef struct _D3DKMT_ADAPTERINFO
{
    D3DKMT_HANDLE       hAdapter;
    LUID                AdapterLuid;
    ULONG               NumOfSources;
    BOOL                bPrecisePresentRegionsPreferred;
} D3DKMT_ADAPTERINFO;
#endif

#ifndef _D3DKMT_ENUMADAPTERS_DEFINED
#define _D3DKMT_ENUMADAPTERS_DEFINED
typedef struct _D3DKMT_ENUMADAPTERS
{
    ULONG               NumAdapters;
    D3DKMT_ADAPTERINFO  Adapters[MAX_ENUM_ADAPTERS];
} D3DKMT_ENUMADAPTERS;
#endif

#ifndef _D3DKMT_ENUMADAPTERS2_DEFINED
#define _D3DKMT_ENUMADAPTERS2_DEFINED
typedef struct _D3DKMT_ENUMADAPTERS2
{
    ULONG               NumAdapters;       /* in/out: capacity / count enumerated */
    D3DKMT_ADAPTERINFO *pAdapters;         /* out: caller buffer of NumAdapters elements */
} D3DKMT_ENUMADAPTERS2;
#endif

#ifndef _D3DKMT_OPENADAPTERFROMLUID_DEFINED
#define _D3DKMT_OPENADAPTERFROMLUID_DEFINED
typedef struct _D3DKMT_OPENADAPTERFROMLUID
{
    LUID                AdapterLuid;
    D3DKMT_HANDLE       hAdapter;
} D3DKMT_OPENADAPTERFROMLUID;
#endif

#ifndef _D3DKMT_OFFERALLOCATIONS_DEFINED
#define _D3DKMT_OFFERALLOCATIONS_DEFINED
typedef enum _D3DKMT_OFFER_PRIORITY
{
    D3DKMT_OFFER_PRIORITY_LOW = 1,
    D3DKMT_OFFER_PRIORITY_NORMAL,
    D3DKMT_OFFER_PRIORITY_HIGH,
    D3DKMT_OFFER_PRIORITY_AUTO,
} D3DKMT_OFFER_PRIORITY;

typedef struct _D3DKMT_OFFERALLOCATIONS
{
    D3DKMT_HANDLE       hDevice;
    D3DKMT_HANDLE      *pResources;
    const D3DKMT_HANDLE *HandleList;
    UINT                NumAllocations;
    D3DKMT_OFFER_PRIORITY Priority;
} D3DKMT_OFFERALLOCATIONS;
#endif

#ifndef _D3DKMT_RECLAIMALLOCATIONS_DEFINED
#define _D3DKMT_RECLAIMALLOCATIONS_DEFINED
typedef struct _D3DKMT_RECLAIMALLOCATIONS
{
    D3DKMT_HANDLE       hDevice;
    D3DKMT_HANDLE      *pResources;
    D3DKMT_HANDLE      *HandleList;
    BOOL               *pDiscarded;
    UINT                NumAllocations;
} D3DKMT_RECLAIMALLOCATIONS;
#endif

#ifndef _D3DKMT_VIDPNSOURCEOWNER_FLAGS_DEFINED
#define _D3DKMT_VIDPNSOURCEOWNER_FLAGS_DEFINED
typedef struct _D3DKMT_VIDPNSOURCEOWNER_FLAGS
{
    union
    {
        struct
        {
            UINT AllowOutputDuplication : 1;
            UINT DisableDWMVirtualMode  : 1;
            UINT UseNtHandles           : 1;
            UINT Reserved               : 29;
        };
        UINT Value;
    };
} D3DKMT_VIDPNSOURCEOWNER_FLAGS;
#endif

#ifndef _D3DKMT_SETVIDPNSOURCEOWNER1_DEFINED
#define _D3DKMT_SETVIDPNSOURCEOWNER1_DEFINED
typedef struct _D3DKMT_SETVIDPNSOURCEOWNER1
{
    D3DKMT_SETVIDPNSOURCEOWNER      Version0;
    D3DKMT_VIDPNSOURCEOWNER_FLAGS   Flags;
} D3DKMT_SETVIDPNSOURCEOWNER1;
#endif

/*
 * WDDM 2.0 type fallbacks.
 *
 * These public types live behind DXGKDDI_INTERFACE_VERSION >= WDDM2_0 guards
 * in d3dkmthk.h / d3dukmdt.h.  dxgkrnl pins the interface version to WIN7, so
 * they are unavailable there even though the user-mode D3DKMT plumbing needs
 * them.  Layout matches the public (_WIN32) definitions exactly so the IOCTL
 * marshalling between win32k (WDDM3_0 public structs) and dxgkrnl is binary
 * compatible.
 */
/*
 * Two guard classes, and they are not the same one.  <d3dkmthk.h> gates the
 * D3DDDI_* types below on D3D_UMD_INTERFACE_VERSION and the D3DKMT_* ones on
 * DXGKDDI_INTERFACE_VERSION.  A single guard over both means raising either
 * version duplicates half of this block and leaves the other half missing,
 * which is exactly what happens with one #ifndef around the lot.
 */
#if (D3D_UMD_INTERFACE_VERSION < D3D_UMD_INTERFACE_VERSION_WDDM2_0)
typedef enum D3DDDI_PAGINGQUEUE_PRIORITY
{
    D3DDDI_PAGINGQUEUE_PRIORITY_BELOW_NORMAL = -1,
    D3DDDI_PAGINGQUEUE_PRIORITY_NORMAL       = 0,
    D3DDDI_PAGINGQUEUE_PRIORITY_ABOVE_NORMAL = 1,
} D3DDDI_PAGINGQUEUE_PRIORITY;

typedef struct D3DDDI_DESTROYPAGINGQUEUE
{
    D3DKMT_HANDLE               hPagingQueue;
} D3DDDI_DESTROYPAGINGQUEUE;

/*
 * D3DKMT_MEMORY_SEGMENT_GROUP is declared unconditionally in d3dkmthk.h
 * (no interface-version guard), so it is always available — do not redefine it.
 */

typedef struct D3DDDI_MAKERESIDENT_FLAGS
{
    union
    {
        struct
        {
            UINT CantTrimFurther : 1;
            UINT MustSucceed     : 1;
            UINT Reserved        : 30;
        };
        UINT Value;
    };
} D3DDDI_MAKERESIDENT_FLAGS;

typedef struct D3DDDI_MAKERESIDENT
{
    D3DKMT_HANDLE               hPagingQueue;
    UINT                        NumAllocations;
    CONST D3DKMT_HANDLE        *AllocationList;
    CONST UINT                 *PriorityList;
    D3DDDI_MAKERESIDENT_FLAGS   Flags;
    UINT64                      PagingFenceValue;
    UINT64                      NumBytesToTrim;
} D3DDDI_MAKERESIDENT;

typedef struct D3DDDI_EVICT_FLAGS
{
    union
    {
        struct
        {
            UINT EvictOnlyIfNecessary : 1;
            UINT NotWrittenTo         : 1;
            UINT Reserved             : 30;
        };
        UINT Value;
    };
} D3DDDI_EVICT_FLAGS;

typedef struct _D3DDDI_RESERVEGPUVIRTUALADDRESS
{
    union
    {
        D3DKMT_HANDLE           hPagingQueue;
        D3DKMT_HANDLE           hAdapter;
    };
    D3DGPU_VIRTUAL_ADDRESS      BaseAddress;
    D3DGPU_VIRTUAL_ADDRESS      MinimumAddress;
    D3DGPU_VIRTUAL_ADDRESS      MaximumAddress;
    UINT64                      Size;
    UINT                        ReservationType;
    UINT64                      DriverProtection;
    D3DGPU_VIRTUAL_ADDRESS      VirtualAddress;
    UINT64                      PagingFenceValue;
} D3DDDI_RESERVEGPUVIRTUALADDRESS;

typedef struct _D3DDDI_MAPGPUVIRTUALADDRESS
{
    D3DKMT_HANDLE               hPagingQueue;
    D3DGPU_VIRTUAL_ADDRESS      BaseAddress;
    D3DGPU_VIRTUAL_ADDRESS      MinimumAddress;
    D3DGPU_VIRTUAL_ADDRESS      MaximumAddress;
    D3DKMT_HANDLE               hAllocation;
    UINT64                      OffsetInPages;
    UINT64                      SizeInPages;
    UINT64                      Protection;
    UINT64                      DriverProtection;
    UINT                        Reserved0;
    UINT64                      Reserved1;
    D3DGPU_VIRTUAL_ADDRESS      VirtualAddress;
    UINT64                      PagingFenceValue;
} D3DDDI_MAPGPUVIRTUALADDRESS;

#endif /* D3D_UMD_INTERFACE_VERSION < WDDM2_0 */

#if (DXGKDDI_INTERFACE_VERSION < DXGKDDI_INTERFACE_VERSION_WDDM2_0)
typedef struct _D3DKMT_CREATEPAGINGQUEUE
{
    D3DKMT_HANDLE               hDevice;
    D3DDDI_PAGINGQUEUE_PRIORITY Priority;
    D3DKMT_HANDLE               hPagingQueue;
    D3DKMT_HANDLE               hSyncObject;
    VOID                       *FenceValueCPUVirtualAddress;
    UINT                        PhysicalAdapterIndex;
} D3DKMT_CREATEPAGINGQUEUE;

typedef struct _D3DKMT_QUERYVIDEOMEMORYINFO
{
    HANDLE                      hProcess;
    D3DKMT_HANDLE               hAdapter;
    D3DKMT_MEMORY_SEGMENT_GROUP MemorySegmentGroup;
    UINT64                      Budget;
    UINT64                      CurrentUsage;
    UINT64                      CurrentReservation;
    UINT64                      AvailableForReservation;
    UINT                        PhysicalAdapterIndex;
} D3DKMT_QUERYVIDEOMEMORYINFO;

typedef struct _D3DKMT_EVICT
{
    D3DKMT_HANDLE               hDevice;
    UINT                        NumAllocations;
    CONST D3DKMT_HANDLE        *AllocationList;
    D3DDDI_EVICT_FLAGS          Flags;
    UINT64                      NumBytesToTrim;
} D3DKMT_EVICT;

/*
 * GPU virtual addressing.  Layouts are byte-for-byte identical to the public
 * (_WIN32) WDDM 2.0 structures and to the dxgkrnl-private *_LOCAL copies, so
 * the win32k <-> dxgkrnl IOCTL marshalling is binary compatible.  Bitfield
 * protection/flags fields are represented by their backing scalar.
 */
typedef struct _D3DKMT_FREEGPUVIRTUALADDRESS
{
    D3DKMT_HANDLE               hAdapter;
    D3DGPU_VIRTUAL_ADDRESS      BaseAddress;
    UINT64                      Size;
} D3DKMT_FREEGPUVIRTUALADDRESS;

typedef struct _D3DKMT_UPDATEGPUVIRTUALADDRESS
{
    D3DKMT_HANDLE               hDevice;
    D3DKMT_HANDLE               hContext;
    D3DKMT_HANDLE               hFenceObject;
    UINT                        NumOperations;
    VOID                       *Operations;
    UINT64                      Reserved0;
    UINT64                      Reserved1;
    UINT64                      FenceValue;
    union
    {
        struct
        {
            UINT DoNotWait : 1;
            UINT Reserved  : 31;
        };
        UINT Value;
    } Flags;
} D3DKMT_UPDATEGPUVIRTUALADDRESS;

/*
 * Monitored-fence CPU wait/signal.  Flags fields are represented by their
 * backing UINT (the public D3DDDICB_SIGNALFLAGS / *_FROMCPU_FLAGS are UINT
 * sized) so the layout matches without pulling in the guarded flag types.
 */
typedef struct _D3DKMT_WAITFORSYNCHRONIZATIONOBJECTFROMCPU
{
    D3DKMT_HANDLE               hDevice;
    UINT                        ObjectCount;
    CONST D3DKMT_HANDLE        *ObjectHandleArray;
    CONST UINT64               *FenceValueArray;
    HANDLE                      hAsyncEvent;
    UINT                        Flags;
} D3DKMT_WAITFORSYNCHRONIZATIONOBJECTFROMCPU;

typedef struct _D3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMCPU
{
    D3DKMT_HANDLE               hDevice;
    UINT                        ObjectCount;
    CONST D3DKMT_HANDLE        *ObjectHandleArray;
    CONST UINT64               *FenceValueArray;
    UINT                        Flags;
} D3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMCPU;

#endif /* DXGKDDI_INTERFACE_VERSION < WDDM2_0 */



#endif /* WDDM 1.2 type fallbacks */

/*
 * D3DKMT_WAITFORVERTICALBLANKEVENT2 is always defined in d3dkmthk.h
 * (not behind any interface-version guard), so no fallback is needed.
 */

/* WDDM 1.2 callback types */

typedef
NTSTATUS
DXGADAPTER_ENUMADAPTERS(_Inout_ D3DKMT_ENUMADAPTERS* unnamedParam1);

typedef DXGADAPTER_ENUMADAPTERS *PDXGADAPTER_ENUMADAPTERS;

typedef
NTSTATUS
DXGADAPTER_OPENADAPTERFROMLUID(_Inout_ D3DKMT_OPENADAPTERFROMLUID* unnamedParam1);

typedef DXGADAPTER_OPENADAPTERFROMLUID *PDXGADAPTER_OPENADAPTERFROMLUID;

typedef
NTSTATUS
DXGADAPTER_OFFERALLOCATIONS(_In_ const D3DKMT_OFFERALLOCATIONS* unnamedParam1);

typedef DXGADAPTER_OFFERALLOCATIONS *PDXGADAPTER_OFFERALLOCATIONS;

typedef
NTSTATUS
DXGADAPTER_RECLAIMALLOCATIONS(_Inout_ D3DKMT_RECLAIMALLOCATIONS* unnamedParam1);

typedef DXGADAPTER_RECLAIMALLOCATIONS *PDXGADAPTER_RECLAIMALLOCATIONS;

typedef
NTSTATUS
DXGADAPTER_SETVIDPNSOURCEOWNER1(_In_ const D3DKMT_SETVIDPNSOURCEOWNER1* unnamedParam1);

typedef DXGADAPTER_SETVIDPNSOURCEOWNER1 *PDXGADAPTER_SETVIDPNSOURCEOWNER1;

typedef
NTSTATUS
DXGADAPTER_WAITFORVERTICALBLANKEVENT2(_In_ const D3DKMT_WAITFORVERTICALBLANKEVENT2* unnamedParam1);

typedef DXGADAPTER_WAITFORVERTICALBLANKEVENT2 *PDXGADAPTER_WAITFORVERTICALBLANKEVENT2;

typedef
NTSTATUS
DXGADAPTER_CREATESYNCHRONIZATIONOBJECT2(_Inout_ D3DKMT_CREATESYNCHRONIZATIONOBJECT2* unnamedParam1);

typedef DXGADAPTER_CREATESYNCHRONIZATIONOBJECT2 *PDXGADAPTER_CREATESYNCHRONIZATIONOBJECT2;

typedef
NTSTATUS
DXGADAPTER_OPENSYNCHRONIZATIONOBJECT(_Inout_ D3DKMT_OPENSYNCHRONIZATIONOBJECT* unnamedParam1);

typedef DXGADAPTER_OPENSYNCHRONIZATIONOBJECT *PDXGADAPTER_OPENSYNCHRONIZATIONOBJECT;

typedef
NTSTATUS
DXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT2(_In_ const D3DKMT_WAITFORSYNCHRONIZATIONOBJECT2* unnamedParam1);

typedef DXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT2 *PDXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT2;

typedef
NTSTATUS
DXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT2(_In_ const D3DKMT_SIGNALSYNCHRONIZATIONOBJECT2* unnamedParam1);

typedef DXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT2 *PDXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT2;

/* WDDM 2.0 additions */

typedef
NTSTATUS
DXGADAPTER_MAKERESIDENT(_Inout_ D3DDDI_MAKERESIDENT* unnamedParam1);

typedef DXGADAPTER_MAKERESIDENT *PDXGADAPTER_MAKERESIDENT;

typedef
NTSTATUS
DXGADAPTER_EVICT(_Inout_ D3DKMT_EVICT* unnamedParam1);

typedef DXGADAPTER_EVICT *PDXGADAPTER_EVICT;

typedef
NTSTATUS
DXGADAPTER_QUERYVIDEOMEMORYINFO(_Inout_ D3DKMT_QUERYVIDEOMEMORYINFO* unnamedParam1);

typedef DXGADAPTER_QUERYVIDEOMEMORYINFO *PDXGADAPTER_QUERYVIDEOMEMORYINFO;

typedef
NTSTATUS
DXGADAPTER_CREATEPAGINGQUEUE(_Inout_ D3DKMT_CREATEPAGINGQUEUE* unnamedParam1);

typedef DXGADAPTER_CREATEPAGINGQUEUE *PDXGADAPTER_CREATEPAGINGQUEUE;

typedef
NTSTATUS
DXGADAPTER_DESTROYPAGINGQUEUE(_Inout_ D3DDDI_DESTROYPAGINGQUEUE* unnamedParam1);

typedef DXGADAPTER_DESTROYPAGINGQUEUE *PDXGADAPTER_DESTROYPAGINGQUEUE;

typedef
NTSTATUS
DXGADAPTER_RESERVEGPUVIRTUALADDRESS(_Inout_ D3DDDI_RESERVEGPUVIRTUALADDRESS* unnamedParam1);

typedef DXGADAPTER_RESERVEGPUVIRTUALADDRESS *PDXGADAPTER_RESERVEGPUVIRTUALADDRESS;

typedef
NTSTATUS
DXGADAPTER_MAPGPUVIRTUALADDRESS(_Inout_ D3DDDI_MAPGPUVIRTUALADDRESS* unnamedParam1);

typedef DXGADAPTER_MAPGPUVIRTUALADDRESS *PDXGADAPTER_MAPGPUVIRTUALADDRESS;

typedef
NTSTATUS
DXGADAPTER_FREEGPUVIRTUALADDRESS(_In_ const D3DKMT_FREEGPUVIRTUALADDRESS* unnamedParam1);

typedef DXGADAPTER_FREEGPUVIRTUALADDRESS *PDXGADAPTER_FREEGPUVIRTUALADDRESS;

typedef
NTSTATUS
DXGADAPTER_UPDATEGPUVIRTUALADDRESS(_In_ const D3DKMT_UPDATEGPUVIRTUALADDRESS* unnamedParam1);

typedef DXGADAPTER_UPDATEGPUVIRTUALADDRESS *PDXGADAPTER_UPDATEGPUVIRTUALADDRESS;

typedef
NTSTATUS
DXGADAPTER_WAITFORSYNCHRONIZATIONOBJECTFROMCPU(_In_ const D3DKMT_WAITFORSYNCHRONIZATIONOBJECTFROMCPU* unnamedParam1);

typedef DXGADAPTER_WAITFORSYNCHRONIZATIONOBJECTFROMCPU *PDXGADAPTER_WAITFORSYNCHRONIZATIONOBJECTFROMCPU;

typedef
NTSTATUS
DXGADAPTER_SIGNALSYNCHRONIZATIONOBJECTFROMCPU(_In_ const D3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMCPU* unnamedParam1);

typedef DXGADAPTER_SIGNALSYNCHRONIZATIONOBJECTFROMCPU *PDXGADAPTER_SIGNALSYNCHRONIZATIONOBJECTFROMCPU;

/* Version 2 additions. */

/* Keep these tags visible even in builds whose public D3DKMT header target is
 * older than WDDM 2.0 and therefore does not define the complete structures. */
struct _D3DKMT_CREATECONTEXTVIRTUAL;
struct _D3DKMT_SUBMITCOMMAND;
struct _D3DKMT_GETALLOCATIONPRIORITY;

typedef NTSTATUS
(*PDXGADAPTER_CREATECONTEXTVIRTUAL)(
    _Inout_ struct _D3DKMT_CREATECONTEXTVIRTUAL* unnamedParam1);

typedef NTSTATUS
(*PDXGADAPTER_SUBMITCOMMAND)(
    _In_ const struct _D3DKMT_SUBMITCOMMAND* unnamedParam1);

typedef NTSTATUS
(*PDXGADAPTER_GETALLOCATIONPRIORITY)(
    _In_ const struct _D3DKMT_GETALLOCATIONPRIORITY* unnamedParam1);

/*
 * This structure is the callbacks list that exist between DXGKNRL and Win32k.
 * This private interface is undocumented and changes with every Windows update
 * that remotely touches WDDM.
 *
 * Reversing this isn't possible until we can throw our DxgKrnl into vista or above at runtime.
 * But this cannot happen without us first supporting watchdog.
 */
typedef struct _REACTOS_WIN32K_DXGKRNL_INTERFACE
{
    PDXGADAPTER_PRESENT RxgkIntPfnPresent;
    PDXGADAPTER_QUERYADAPTERINFO RxgkIntPfnQueryAdapterInfo;
    PDXGADAPTER_QUERYALLOCATIONRESIDENCY RxgkIntPfnQueryAllocationResidency;
    PDXGADAPTER_QUERYSTATISTICS RxgkIntPfnQueryStatistics;
    PDXGADAPTER_RELEASEPROCESSVIDPNSOURCEOWNERS RxgkIntPfnReleaseProcessVidPnSourceOwners;
    PDXGADAPTER_RENDER RxgkIntPfnRender;
    PDXGADAPTER_SETCONTEXTSCHEDULINGPRIORITY RxgkIntPfnSetContextSchedulingPriority;
    PDXGADAPTER_OPENRESOURCE RxgkIntPfnOpenResource;
    PDXGADAPTER_POLLDISPLAYCHILDREN RxgkIntPfnPollDisplayChildren;
    PDXGADAPTER_LOCK RxgkIntPfnLock;
    PDXGADAPTER_GETSHAREDPRIMARYHANDLE RxgkIntPfnGetSharedPrimaryHandle;
    PDXGADAPTER_INVALIDATEACTIVEVIDPN RxgkIntPfnInvalidateActiveVidPn;
    PDXGADAPTER_SETALLOCATIONPRIORITY RxgkIntPfnSetAllocationPriority;
    PDXGADAPTER_GETPRESENTHISTORY RxgkIntPfnGetPresentHistory;
    PDXGADAPTER_QUERYRESOURCEINFO RxgkIntPfnQueryResourceInfo;
    PDXGADAPTER_CREATEALLOCATION RxgkIntPfnCreateAllocation;
    PDXGADAPTER_CHECKMONITORPOWERSTATE RxgkIntPfnCheckMonitorPowerState;
    PDXGADAPTER_CHECKOCCLUSION RxgkIntPfnCheckOcclusion;
    PDXGADAPTER_CLOSEADAPTER RxgkIntPfnCloseAdapter;
    PDXGADAPTER_CREATECONTEXT RxgkIntPfnCreateContext;
    PDXGADAPTER_CREATEDEVICE RxgkIntPfnCreateDevice;
    PDXGADAPTER_CREATEOVERLAY RxgkIntPfnCreateOverlay;
    PDXGADAPTER_CREATESYNCHRONIZATIONOBJECT RxgkIntPfnCreateSynchronizationObject;
    PDXGADAPTER_DESTROYCONTEXT RxgkIntPfnDestroyContext;
    PDXGADAPTER_DESTROYDEVICE RxgkIntPfnDestroyDevice;
    PDXGADAPTER_DESTROYOVERLAY RxgkIntPfnDestroyOverlay;
    PDXGADAPTER_DESTROYSYNCHRONIZATIONOBJECT RxgkIntPfnDestroySynchronizationObject;
    PDXGADAPTER_ESCAPE RxgkIntPfnEscape;
    PDXGADAPTER_DESTROYALLOCATION RxgkIntPfnDestroyAllocation;
    PDXGADAPTER_FLIPOVERLAY RxgkIntPfnFlipOverlay;
    PDXGADAPTER_GETCONTEXTSCHEDULINGPRIORITY RxgkIntPfnGetContextSchedulingPriority;
    PDXGADAPTER_GETDEVICESTATE RxgkIntPfnGetDeviceState;
    PDXGADAPTER_GETDISPLAYMODELIST RxgkIntPfnGetDisplayModeList;
    PDXGADAPTER_GETMULTISAMPLEMETHODLIST RxgkIntPfnGetMultisampleMethodList;
    PDXGADAPTER_GETRUNTIMEDATA RxgkIntPfnGetRuntimeData;
    PDXGADAPTER_GETSCANLINE RxgkIntPfnGetScanLine;
    PDXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT RxgkIntPfnSignalSynchronizationObject;
    PDXGADAPTER_WAITFORVERTICALBLANKEVENT RxgkIntPfnWaitForVerticalBlankEvent;
    PDXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT RxgkIntPfnWaitForSynchronizationObject;
    PDXGADAPTER_SETVIDPNSOURCEOWNER RxgkIntPfnSetVidPnSourceOwner;
    PDXGADAPTER_WAITFORIDLE RxgkIntPfnWaitForIdle;
    PDXGADAPTER_UPDATEOVERLAY RxgkIntPfnUpdateOverlay;
    PDXGADAPTER_SETQUEUEDLIMIT RxgkIntPfnSetQueuedLimit;
    PDXGADAPTER_SETGAMMARAMP RxgkIntPfnSetGammaRamp;
    PDXGADAPTER_SETDISPLAYMODE RxgkIntPfnSetDisplayMode;
    PDXGADAPTER_SETDISPLAYPRIVATEDRIVERFORMAT RxgkIntPfnSetDisplayPrivateDriverFormat;
    PDXGADAPTER_UNLOCK RxgkIntPfnUnlock;

    /* WDDM 1.2 additions */
    PDXGADAPTER_ENUMADAPTERS RxgkIntPfnEnumAdapters;
    PDXGADAPTER_OPENADAPTERFROMLUID RxgkIntPfnOpenAdapterFromLuid;
    PDXGADAPTER_OFFERALLOCATIONS RxgkIntPfnOfferAllocations;
    PDXGADAPTER_RECLAIMALLOCATIONS RxgkIntPfnReclaimAllocations;
    PDXGADAPTER_SETVIDPNSOURCEOWNER1 RxgkIntPfnSetVidPnSourceOwner1;
    PDXGADAPTER_WAITFORVERTICALBLANKEVENT2 RxgkIntPfnWaitForVerticalBlankEvent2;
    PDXGADAPTER_CREATESYNCHRONIZATIONOBJECT2 RxgkIntPfnCreateSynchronizationObject2;
    PDXGADAPTER_WAITFORSYNCHRONIZATIONOBJECT2 RxgkIntPfnWaitForSynchronizationObject2;
    PDXGADAPTER_SIGNALSYNCHRONIZATIONOBJECT2 RxgkIntPfnSignalSynchronizationObject2;

    /* WDDM 2.0 additions */
    PDXGADAPTER_MAKERESIDENT RxgkIntPfnMakeResident;
    PDXGADAPTER_EVICT RxgkIntPfnEvict;
    PDXGADAPTER_QUERYVIDEOMEMORYINFO RxgkIntPfnQueryVideoMemoryInfo;
    PDXGADAPTER_CREATEPAGINGQUEUE RxgkIntPfnCreatePagingQueue;
    PDXGADAPTER_DESTROYPAGINGQUEUE RxgkIntPfnDestroyPagingQueue;
    PDXGADAPTER_RESERVEGPUVIRTUALADDRESS RxgkIntPfnReserveGpuVirtualAddress;
    PDXGADAPTER_MAPGPUVIRTUALADDRESS RxgkIntPfnMapGpuVirtualAddress;
    PDXGADAPTER_FREEGPUVIRTUALADDRESS RxgkIntPfnFreeGpuVirtualAddress;
    PDXGADAPTER_UPDATEGPUVIRTUALADDRESS RxgkIntPfnUpdateGpuVirtualAddress;
    PDXGADAPTER_WAITFORSYNCHRONIZATIONOBJECTFROMCPU RxgkIntPfnWaitForSynchronizationObjectFromCpu;
    PDXGADAPTER_SIGNALSYNCHRONIZATIONOBJECTFROMCPU RxgkIntPfnSignalSynchronizationObjectFromCpu;

    /* Private interface version 2 additions; append-only ABI. */
    PDXGADAPTER_CREATECONTEXTVIRTUAL RxgkIntPfnCreateContextVirtual;
    PDXGADAPTER_SUBMITCOMMAND RxgkIntPfnSubmitCommand;

    /* Private interface version 3 additions; append-only ABI. */
    PDXGADAPTER_CREATEALLOCATION2 RxgkIntPfnCreateAllocation2;

    /* Private interface version 4 additions; append-only ABI. */
    PDXGADAPTER_GETALLOCATIONPRIORITY RxgkIntPfnGetAllocationPriority;

    /* Private interface version 5 additions; append-only ABI. */
    PDXGADAPTER_OPENSYNCHRONIZATIONOBJECT RxgkIntPfnOpenSynchronizationObject;
} REACTOS_WIN32K_DXGKRNL_INTERFACE, *PREACTOS_WIN32K_DXGKRNL_INTERFACE;

/* Sizes used to negotiate the append-only callback table. */
#define DXGKRNL_INTERFACE_VERSION_1_SIZE \
    FIELD_OFFSET(REACTOS_WIN32K_DXGKRNL_INTERFACE, RxgkIntPfnCreateContextVirtual)
#define DXGKRNL_INTERFACE_VERSION_2_SIZE \
    FIELD_OFFSET(REACTOS_WIN32K_DXGKRNL_INTERFACE, RxgkIntPfnCreateAllocation2)
#define DXGKRNL_INTERFACE_VERSION_3_SIZE \
    FIELD_OFFSET(REACTOS_WIN32K_DXGKRNL_INTERFACE, RxgkIntPfnGetAllocationPriority)
#define DXGKRNL_INTERFACE_VERSION_4_SIZE \
    FIELD_OFFSET(REACTOS_WIN32K_DXGKRNL_INTERFACE, RxgkIntPfnOpenSynchronizationObject)
#define DXGKRNL_INTERFACE_VERSION_5_SIZE \
    sizeof(REACTOS_WIN32K_DXGKRNL_INTERFACE)
