/* Automatically generated by make depend; DO NOT EDIT!! */

#define STANDALONE
#include <wine/test.h>

extern void func_hostname(void);

const struct test winetest_testlist[] =
{
    { "hostname", func_hostname },
    { 0, 0 }
};
