@ stdcall NtUserBuildHwndList(long long long long long long ptr ptr)
@ stdcall NtUserDisplayConfigGetDeviceInfo(ptr)
@ stdcall NtUserEnableMouseInPointer(long)
@ stdcall NtUserGetPointerDeviceRects(long ptr ptr)
@ stdcall NtUserGetPointerInfoList(long long long long long ptr ptr ptr)
@ stdcall NtUserGetProcessDpiAwarenessContext(long)
@ stdcall NtUserGetProp(long wstr)
@ stdcall NtUserIsMouseInPointerEnabled()
@ stdcall NtUserSetProcessDpiAwarenessContext(long long)
@ stdcall NtUserSetTimer(long long long ptr long)
