/*
 * PROJECT:     ReactOS SDK
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Direct3D 10/11 user-mode driver adapter and allocation types
 * COPYRIGHT:   Copyright 2026 ReactOS WDDM Team
 *
 * Keep values and field order aligned with the public Windows 11 24H2 WDK
 * contract.
 */

#pragma once

#include <windef.h>
#include <dxgicommon.h>
#include <dxgiddi.h>
#include <d3dumddi.h>
#include <d3d10tokenizedprogramformat.hpp>

/* Public D3D10 UMD interface identifiers used by OpenAdapter10[_2]. */
#define D3D10_DDI_MAJOR_VERSION 10
#define D3D10_0_DDI_MINOR_VERSION 1
#define D3D10_0_DDI_INTERFACE_VERSION ((D3D10_DDI_MAJOR_VERSION << 16) | D3D10_0_DDI_MINOR_VERSION)
#define D3D10_0_DDI_BUILD_VERSION 4
#define D3D10_0_DDI_SUPPORTED ((((UINT64)D3D10_0_DDI_INTERFACE_VERSION) << 32) | (((UINT64)D3D10_0_DDI_BUILD_VERSION) << 16))

#define D3D10_1_DDI_MINOR_VERSION 2
#define D3D10_1_DDI_INTERFACE_VERSION ((D3D10_DDI_MAJOR_VERSION << 16) | D3D10_1_DDI_MINOR_VERSION)
#define D3D10_1_DDI_BUILD_VERSION 1
#define D3D10_1_DDI_SUPPORTED ((((UINT64)D3D10_1_DDI_INTERFACE_VERSION) << 32) | (((UINT64)D3D10_1_DDI_BUILD_VERSION) << 16))

#define D3D10_0_x_DDI_MINOR_VERSION 6
#define D3D10_0_x_DDI_INTERFACE_VERSION ((D3D10_DDI_MAJOR_VERSION << 16) | D3D10_0_x_DDI_MINOR_VERSION)
#define D3D10_0_x_DDI_BUILD_VERSION 0
#define D3D10_0_x_DDI_SUPPORTED ((((UINT64)D3D10_0_x_DDI_INTERFACE_VERSION) << 32) | (((UINT64)D3D10_0_x_DDI_BUILD_VERSION) << 16))

#define D3D10_1_x_DDI_MINOR_VERSION 7
#define D3D10_1_x_DDI_INTERFACE_VERSION ((D3D10_DDI_MAJOR_VERSION << 16) | D3D10_1_x_DDI_MINOR_VERSION)
#define D3D10_1_x_DDI_BUILD_VERSION 0
#define D3D10_1_x_DDI_SUPPORTED ((((UINT64)D3D10_1_x_DDI_INTERFACE_VERSION) << 32) | (((UINT64)D3D10_1_x_DDI_BUILD_VERSION) << 16))

#define D3D10_0_7_DDI_MINOR_VERSION 9
#define D3D10_0_7_DDI_INTERFACE_VERSION ((D3D10_DDI_MAJOR_VERSION << 16) | D3D10_0_7_DDI_MINOR_VERSION)
#define D3D10_0_7_DDI_BUILD_VERSION 0
#define D3D10_0_7_DDI_SUPPORTED ((((UINT64)D3D10_0_7_DDI_INTERFACE_VERSION) << 32) | (((UINT64)D3D10_0_7_DDI_BUILD_VERSION) << 16))

#define D3D10_1_7_DDI_MINOR_VERSION 10
#define D3D10_1_7_DDI_INTERFACE_VERSION ((D3D10_DDI_MAJOR_VERSION << 16) | D3D10_1_7_DDI_MINOR_VERSION)
#define D3D10_1_7_DDI_BUILD_VERSION 0
#define D3D10_1_7_DDI_SUPPORTED ((((UINT64)D3D10_1_7_DDI_INTERFACE_VERSION) << 32) | (((UINT64)D3D10_1_7_DDI_BUILD_VERSION) << 16))

typedef struct D3D10DDI_HADAPTER
{
    VOID *pDrvPrivate;
} D3D10DDI_HADAPTER;

typedef struct D3D10DDI_HRTADAPTER
{
    VOID *handle;
} D3D10DDI_HRTADAPTER;

typedef struct D3D10DDIARG_CALCPRIVATEDEVICESIZE D3D10DDIARG_CALCPRIVATEDEVICESIZE;
typedef struct D3D10DDIARG_CREATEDEVICE D3D10DDIARG_CREATEDEVICE;
typedef enum D3D10_2DDICAPS_TYPE
{
    D3D11DDICAPS_THREADING = 128,
    D3D11DDICAPS_SHADER = 129,
    D3D11DDICAPS_3DPIPELINESUPPORT = 130,
} D3D10_2DDICAPS_TYPE;

typedef struct D3D10_2DDIARG_GETCAPS
{
    D3D10_2DDICAPS_TYPE Type;
    VOID *pInfo;
    VOID *pData;
    UINT DataSize;
} D3D10_2DDIARG_GETCAPS;

typedef struct D3D11DDI_3DPIPELINESUPPORT_CAPS
{
    UINT Caps;
} D3D11DDI_3DPIPELINESUPPORT_CAPS;

typedef struct D3D11DDI_THREADING_CAPS
{
    UINT Caps;
} D3D11DDI_THREADING_CAPS;

#define D3D11DDICAPS_FREETHREADED 0x1
#define D3D11DDICAPS_COMMANDLISTS 0x2
#define D3D11DDICAPS_COMMANDLISTS_BUILD_2 0x4

typedef struct D3D11DDI_SHADER_CAPS
{
    UINT Caps;
} D3D11DDI_SHADER_CAPS;

#define D3D11DDICAPS_SHADER_DOUBLES 0x1
#define D3D11DDICAPS_SHADER_COMPUTE_PLUS_RAW_AND_STRUCTURED_BUFFERS_IN_SHADER_4_X 0x2
#define D3D11DDICAPS_SHADER_DEBUGGABLE 0x4

typedef enum D3D11DDI_3DPIPELINELEVEL
{
    D3D11DDI_3DPIPELINELEVEL_10_0 = 0,
    D3D11DDI_3DPIPELINELEVEL_10_1 = 1,
    D3D11DDI_3DPIPELINELEVEL_11_0 = 2,
} D3D11DDI_3DPIPELINELEVEL;

#define D3D11DDI_ENCODE_3DPIPELINESUPPORT_CAP(Level) (1u << (Level))

struct _D3DDDI_ADAPTERCALLBACKS;

typedef SIZE_T (APIENTRY *PFND3D10DDI_CALCPRIVATEDEVICESIZE)(D3D10DDI_HADAPTER, const D3D10DDIARG_CALCPRIVATEDEVICESIZE *);
typedef HRESULT (APIENTRY *PFND3D10DDI_CREATEDEVICE)(D3D10DDI_HADAPTER, D3D10DDIARG_CREATEDEVICE *);
typedef HRESULT (APIENTRY *PFND3D10DDI_CLOSEADAPTER)(D3D10DDI_HADAPTER);
typedef HRESULT (APIENTRY *PFND3D10_2DDI_GETSUPPORTEDVERSIONS)(D3D10DDI_HADAPTER, UINT32 *, UINT64 *);
typedef HRESULT (APIENTRY *PFND3D10_2DDI_GETCAPS)(D3D10DDI_HADAPTER, const D3D10_2DDIARG_GETCAPS *);

typedef struct D3D10DDI_ADAPTERFUNCS
{
    PFND3D10DDI_CALCPRIVATEDEVICESIZE pfnCalcPrivateDeviceSize;
    PFND3D10DDI_CREATEDEVICE pfnCreateDevice;
    PFND3D10DDI_CLOSEADAPTER pfnCloseAdapter;
} D3D10DDI_ADAPTERFUNCS;

typedef struct D3D10_2DDI_ADAPTERFUNCS
{
    PFND3D10DDI_CALCPRIVATEDEVICESIZE pfnCalcPrivateDeviceSize;
    PFND3D10DDI_CREATEDEVICE pfnCreateDevice;
    PFND3D10DDI_CLOSEADAPTER pfnCloseAdapter;
    PFND3D10_2DDI_GETSUPPORTEDVERSIONS pfnGetSupportedVersions;
    PFND3D10_2DDI_GETCAPS pfnGetCaps;
} D3D10_2DDI_ADAPTERFUNCS;

typedef struct D3D10DDIARG_OPENADAPTER
{
    D3D10DDI_HRTADAPTER hRTAdapter;
    D3D10DDI_HADAPTER hAdapter;
    UINT Interface;
    UINT Version;
    const struct _D3DDDI_ADAPTERCALLBACKS *pAdapterCallbacks;
    union
    {
        D3D10DDI_ADAPTERFUNCS *pAdapterFuncs;
        D3D10_2DDI_ADAPTERFUNCS *pAdapterFuncs_2;
    };
} D3D10DDIARG_OPENADAPTER;

typedef HRESULT (APIENTRY *PFND3D10DDI_OPENADAPTER)(D3D10DDIARG_OPENADAPTER *);

typedef enum D3D10DDIRESOURCE_TYPE
{
    D3D10DDIRESOURCE_BUFFER = 1,
    D3D10DDIRESOURCE_TEXTURE1D = 2,
    D3D10DDIRESOURCE_TEXTURE2D = 3,
    D3D10DDIRESOURCE_TEXTURE3D = 4,
    D3D10DDIRESOURCE_TEXTURECUBE = 5,
    D3D11DDIRESOURCE_BUFFEREX = 6,
} D3D10DDIRESOURCE_TYPE;

typedef enum D3D10_DDI_RESOURCE_USAGE
{
    D3D10_DDI_USAGE_DEFAULT = 0,
    D3D10_DDI_USAGE_IMMUTABLE = 1,
    D3D10_DDI_USAGE_DYNAMIC = 2,
    D3D10_DDI_USAGE_STAGING = 3,
} D3D10_DDI_RESOURCE_USAGE;

typedef enum D3D10_DDI_RESOURCE_BIND_FLAG
{
    D3D10_DDI_BIND_VERTEX_BUFFER = 0x00000001L,
    D3D10_DDI_BIND_INDEX_BUFFER = 0x00000002L,
    D3D10_DDI_BIND_CONSTANT_BUFFER = 0x00000004L,
    D3D10_DDI_BIND_SHADER_RESOURCE = 0x00000008L,
    D3D10_DDI_BIND_STREAM_OUTPUT = 0x00000010L,
    D3D10_DDI_BIND_RENDER_TARGET = 0x00000020L,
    D3D10_DDI_BIND_DEPTH_STENCIL = 0x00000040L,
    D3D10_DDI_BIND_PIPELINE_MASK = 0x0000007FL,
    D3D10_DDI_BIND_PRESENT = 0x00000080L,
    D3D10_DDI_BIND_MASK = 0x000000FFL,
    D3D11_DDI_BIND_UNORDERED_ACCESS = 0x00000100L,
    D3D11_DDI_BIND_PIPELINE_MASK = 0x0000017FL,
    D3D11_DDI_BIND_MASK = 0x000001FFL,
} D3D10_DDI_RESOURCE_BIND_FLAG;

typedef enum D3D10_DDI_RESOURCE_MISC_FLAG
{
    D3D10_DDI_RESOURCE_AUTO_GEN_MIP_MAP = 0x00000001L,
    D3D10_DDI_RESOURCE_MISC_SHARED = 0x00000002L,
    D3D10_DDI_RESOURCE_MISC_DISCARD_ON_PRESENT = 0x00000008L,
    D3D11_DDI_RESOURCE_MISC_DRAWINDIRECT_ARGS = 0x00000010L,
    D3D11_DDI_RESOURCE_MISC_BUFFER_ALLOW_RAW_VIEWS = 0x00000020L,
    D3D11_DDI_RESOURCE_MISC_BUFFER_STRUCTURED = 0x00000040L,
    D3D11_DDI_RESOURCE_MISC_RESOURCE_CLAMP = 0x00000080L,
    D3D10_DDI_RESOURCE_MISC_REMOTE = 0x00000400L,
} D3D10_DDI_RESOURCE_MISC_FLAG;

typedef enum D3D10_DDI_MAP
{
    D3D10_DDI_MAP_READ = 1,
    D3D10_DDI_MAP_WRITE = 2,
    D3D10_DDI_MAP_READWRITE = 3,
    D3D10_DDI_MAP_WRITE_DISCARD = 4,
    D3D10_DDI_MAP_WRITE_NOOVERWRITE = 5,
} D3D10_DDI_MAP;

typedef struct D3D10DDI_MIPINFO
{
    UINT TexelWidth;
    UINT TexelHeight;
    UINT TexelDepth;
    UINT PhysicalWidth;
    UINT PhysicalHeight;
    UINT PhysicalDepth;
} D3D10DDI_MIPINFO;

typedef struct D3D10DDIARG_CREATERESOURCE
{
    const D3D10DDI_MIPINFO *pMipInfoList;
    const struct D3D10_DDIARG_SUBRESOURCE_UP *pInitialDataUP;
    D3D10DDIRESOURCE_TYPE ResourceDimension;
    UINT Usage;
    UINT BindFlags;
    UINT MapFlags;
    UINT MiscFlags;
    DXGI_FORMAT Format;
    DXGI_SAMPLE_DESC SampleDesc;
    UINT MipLevels;
    UINT ArraySize;
    DXGI_DDI_PRIMARY_DESC *pPrimaryDesc;
} D3D10DDIARG_CREATERESOURCE;

/* Direct3D 11 device DDI. Function table order is part of the driver ABI. */
typedef struct D3D10DDI_HBLENDSTATE { void *pDrvPrivate; } D3D10DDI_HBLENDSTATE;

typedef struct D3D10DDI_HDEPTHSTENCILSTATE { void *pDrvPrivate; } D3D10DDI_HDEPTHSTENCILSTATE;

typedef struct D3D10DDI_HDEPTHSTENCILVIEW { void *pDrvPrivate; } D3D10DDI_HDEPTHSTENCILVIEW;

typedef struct D3D10DDI_HRTDEVICE { void *handle; } D3D10DDI_HRTDEVICE;

typedef struct D3D10DDI_HDEVICE { void *pDrvPrivate; } D3D10DDI_HDEVICE;

typedef struct D3D10DDI_HELEMENTLAYOUT { void *pDrvPrivate; } D3D10DDI_HELEMENTLAYOUT;

typedef struct D3D10DDI_HKMRESOURCE { D3DKMT_HANDLE handle; } D3D10DDI_HKMRESOURCE;

typedef struct D3D10DDI_HQUERY { void *pDrvPrivate; } D3D10DDI_HQUERY;

typedef struct D3D10DDI_HRASTERIZERSTATE { void *pDrvPrivate; } D3D10DDI_HRASTERIZERSTATE;

typedef struct D3D10DDI_HRENDERTARGETVIEW { void *pDrvPrivate; } D3D10DDI_HRENDERTARGETVIEW;

typedef struct D3D10DDI_HRESOURCE { void *pDrvPrivate; } D3D10DDI_HRESOURCE;

typedef struct D3D10DDI_HRTBLENDSTATE { void *handle; } D3D10DDI_HRTBLENDSTATE;

typedef struct D3D10DDI_HRTCORELAYER { void *handle; } D3D10DDI_HRTCORELAYER;

typedef struct D3D10DDI_HRTDEPTHSTENCILSTATE { void *handle; } D3D10DDI_HRTDEPTHSTENCILSTATE;

typedef struct D3D10DDI_HRTDEPTHSTENCILVIEW { void *handle; } D3D10DDI_HRTDEPTHSTENCILVIEW;

typedef struct D3D10DDI_HRTELEMENTLAYOUT { void *handle; } D3D10DDI_HRTELEMENTLAYOUT;

typedef struct D3D10DDI_HRTQUERY { void *handle; } D3D10DDI_HRTQUERY;

typedef struct D3D10DDI_HRTRASTERIZERSTATE { void *handle; } D3D10DDI_HRTRASTERIZERSTATE;

typedef struct D3D10DDI_HRTRENDERTARGETVIEW { void *handle; } D3D10DDI_HRTRENDERTARGETVIEW;

typedef struct D3D10DDI_HRTRESOURCE { void *handle; } D3D10DDI_HRTRESOURCE;

typedef struct D3D10DDI_HRTSAMPLER { void *handle; } D3D10DDI_HRTSAMPLER;

typedef struct D3D10DDI_HRTSHADER { void *handle; } D3D10DDI_HRTSHADER;

typedef struct D3D10DDI_HRTSHADERRESOURCEVIEW { void *handle; } D3D10DDI_HRTSHADERRESOURCEVIEW;

typedef struct D3D10DDI_HSAMPLER { void *pDrvPrivate; } D3D10DDI_HSAMPLER;

typedef struct D3D10DDI_HSHADER { void *pDrvPrivate; } D3D10DDI_HSHADER;

typedef struct D3D10DDI_HSHADERRESOURCEVIEW { void *pDrvPrivate; } D3D10DDI_HSHADERRESOURCEVIEW;

typedef struct D3D11DDI_HANDLESIZE { void *pDrvPrivate; } D3D11DDI_HANDLESIZE;

typedef struct D3D11DDI_HCOMMANDLIST { void *pDrvPrivate; } D3D11DDI_HCOMMANDLIST;

typedef struct D3D11DDI_HRTCOMMANDLIST { void *handle; } D3D11DDI_HRTCOMMANDLIST;

typedef struct D3D11DDI_HRTUNORDEREDACCESSVIEW { void *handle; } D3D11DDI_HRTUNORDEREDACCESSVIEW;

typedef struct D3D11DDI_HUNORDEREDACCESSVIEW { void *pDrvPrivate; } D3D11DDI_HUNORDEREDACCESSVIEW;

typedef struct D3D10DDIARG_VERTEXPIPELINEOUTPUT D3D10DDIARG_VERTEXPIPELINEOUTPUT;

typedef struct D3D10DDI_COUNTER_INFO D3D10DDI_COUNTER_INFO;

typedef struct D3D10DDI_DEVICEFUNCS D3D10DDI_DEVICEFUNCS;

typedef struct D3D10_1DDI_DEVICEFUNCS D3D10_1DDI_DEVICEFUNCS;

typedef struct D3D11DDIARG_CALCPRIVATEDEFERREDCONTEXTSIZE D3D11DDIARG_CALCPRIVATEDEFERREDCONTEXTSIZE;

typedef struct D3D11DDIARG_CREATECOMMANDLIST D3D11DDIARG_CREATECOMMANDLIST;

typedef struct D3D11DDIARG_CREATEDEFERREDCONTEXT D3D11DDIARG_CREATEDEFERREDCONTEXT;

typedef struct D3D11DDIARG_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT D3D11DDIARG_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT;

typedef struct D3D11DDIARG_POINTERDATA D3D11DDIARG_POINTERDATA;

typedef struct D3D11DDI_DEVICEFUNCS D3D11DDI_DEVICEFUNCS;

typedef struct D3D11DDI_HANDLESIZE D3D11DDI_HANDLESIZE;

typedef enum D3D10_DDI_INPUT_CLASSIFICATION
{
    D3D10_DDI_INPUT_PER_VERTEX_DATA = 0,
    D3D10_DDI_INPUT_PER_INSTANCE_DATA = 1
} D3D10_DDI_INPUT_CLASSIFICATION;

typedef enum D3D10_DDI_FILTER
{

    D3D10_DDI_FILTER_MIN_MAG_MIP_POINT = 0x00000000,
    D3D10_DDI_FILTER_MIN_MAG_POINT_MIP_LINEAR = 0x00000001,
    D3D10_DDI_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x00000004,
    D3D10_DDI_FILTER_MIN_POINT_MAG_MIP_LINEAR = 0x00000005,
    D3D10_DDI_FILTER_MIN_LINEAR_MAG_MIP_POINT = 0x00000010,
    D3D10_DDI_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x00000011,
    D3D10_DDI_FILTER_MIN_MAG_LINEAR_MIP_POINT = 0x00000014,
    D3D10_DDI_FILTER_MIN_MAG_MIP_LINEAR = 0x00000015,
    D3D10_DDI_FILTER_ANISOTROPIC = 0x00000055,
    D3D10_DDI_FILTER_COMPARISON_MIN_MAG_MIP_POINT = 0x00000080,
    D3D10_DDI_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR = 0x00000081,
    D3D10_DDI_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x00000084,
    D3D10_DDI_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR = 0x00000085,
    D3D10_DDI_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT = 0x00000090,
    D3D10_DDI_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x00000091,
    D3D10_DDI_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT = 0x00000094,
    D3D10_DDI_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR = 0x00000095,
    D3D10_DDI_FILTER_COMPARISON_ANISOTROPIC = 0x000000d5,

    D3DWDDM1_3DDI_FILTER_MINIMUM_MIN_MAG_MIP_POINT = 0x00000100,
    D3DWDDM1_3DDI_FILTER_MINIMUM_MIN_MAG_POINT_MIP_LINEAR = 0x00000101,
    D3DWDDM1_3DDI_FILTER_MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x00000104,
    D3DWDDM1_3DDI_FILTER_MINIMUM_MIN_POINT_MAG_MIP_LINEAR = 0x00000105,
    D3DWDDM1_3DDI_FILTER_MINIMUM_MIN_LINEAR_MAG_MIP_POINT = 0x00000110,
    D3DWDDM1_3DDI_FILTER_MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x00000111,
    D3DWDDM1_3DDI_FILTER_MINIMUM_MIN_MAG_LINEAR_MIP_POINT = 0x00000114,
    D3DWDDM1_3DDI_FILTER_MINIMUM_MIN_MAG_MIP_LINEAR = 0x00000115,
    D3DWDDM1_3DDI_FILTER_MINIMUM_ANISOTROPIC = 0x00000155,
    D3DWDDM1_3DDI_FILTER_MAXIMUM_MIN_MAG_MIP_POINT = 0x00000180,
    D3DWDDM1_3DDI_FILTER_MAXIMUM_MIN_MAG_POINT_MIP_LINEAR = 0x00000181,
    D3DWDDM1_3DDI_FILTER_MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x00000184,
    D3DWDDM1_3DDI_FILTER_MAXIMUM_MIN_POINT_MAG_MIP_LINEAR = 0x00000185,
    D3DWDDM1_3DDI_FILTER_MAXIMUM_MIN_LINEAR_MAG_MIP_POINT = 0x00000190,
    D3DWDDM1_3DDI_FILTER_MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x00000191,
    D3DWDDM1_3DDI_FILTER_MAXIMUM_MIN_MAG_LINEAR_MIP_POINT = 0x00000194,
    D3DWDDM1_3DDI_FILTER_MAXIMUM_MIN_MAG_MIP_LINEAR = 0x00000195,
    D3DWDDM1_3DDI_FILTER_MAXIMUM_ANISOTROPIC = 0x000001d5,

    D3D10_DDI_FILTER_TEXT_1BIT = 0x80000000

} D3D10_DDI_FILTER;

typedef enum D3D10_DDI_FILTER_TYPE
{
    D3D10_DDI_FILTER_TYPE_POINT = 0,
    D3D10_DDI_FILTER_TYPE_LINEAR = 1,
} D3D10_DDI_FILTER_TYPE;

#define D3D10_DDI_FILTER_TYPE_MASK 0x00000003
#define D3D10_DDI_MIN_FILTER_SHIFT 4
#define D3D10_DDI_MAG_FILTER_SHIFT 2
#define D3D10_DDI_MIP_FILTER_SHIFT 0
#define D3D10_DDI_COMPARISON_FILTERING_BIT 0x00000080
#define D3D10_DDI_ANISOTROPIC_FILTERING_BIT 0x00000040
#define D3D10_DDI_TEXT_1BIT_BIT 0x80000000

#define D3D10_DDI_DECODE_MIN_FILTER(Filter) \
    ((D3D10_DDI_FILTER_TYPE)(((Filter) >> D3D10_DDI_MIN_FILTER_SHIFT) & D3D10_DDI_FILTER_TYPE_MASK))
#define D3D10_DDI_DECODE_MAG_FILTER(Filter) \
    ((D3D10_DDI_FILTER_TYPE)(((Filter) >> D3D10_DDI_MAG_FILTER_SHIFT) & D3D10_DDI_FILTER_TYPE_MASK))
#define D3D10_DDI_DECODE_MIP_FILTER(Filter) \
    ((D3D10_DDI_FILTER_TYPE)(((Filter) >> D3D10_DDI_MIP_FILTER_SHIFT) & D3D10_DDI_FILTER_TYPE_MASK))
#define D3D10_DDI_DECODE_IS_COMPARISON_FILTER(Filter) \
    ((Filter) & D3D10_DDI_COMPARISON_FILTERING_BIT)
#define D3D10_DDI_DECODE_IS_ANISOTROPIC_FILTER(Filter) \
    (((Filter) & D3D10_DDI_ANISOTROPIC_FILTERING_BIT) && \
     D3D10_DDI_DECODE_MIN_FILTER(Filter) == D3D10_DDI_FILTER_TYPE_LINEAR && \
     D3D10_DDI_DECODE_MAG_FILTER(Filter) == D3D10_DDI_FILTER_TYPE_LINEAR && \
     D3D10_DDI_DECODE_MIP_FILTER(Filter) == D3D10_DDI_FILTER_TYPE_LINEAR)
#define D3D10_DDI_DECODE_IS_TEXT_1BIT_FILTER(Filter) \
    ((Filter) == D3D10_DDI_TEXT_1BIT_BIT)

typedef enum D3D10_DDI_COMPARISON_FUNC
{
    D3D10_DDI_COMPARISON_NEVER = 1,
    D3D10_DDI_COMPARISON_LESS = 2,
    D3D10_DDI_COMPARISON_EQUAL = 3,
    D3D10_DDI_COMPARISON_LESS_EQUAL = 4,
    D3D10_DDI_COMPARISON_GREATER = 5,
    D3D10_DDI_COMPARISON_NOT_EQUAL = 6,
    D3D10_DDI_COMPARISON_GREATER_EQUAL = 7,
    D3D10_DDI_COMPARISON_ALWAYS = 8
} D3D10_DDI_COMPARISON_FUNC;

typedef enum D3D10_DDI_TEXTURE_ADDRESS_MODE
{
    D3D10_DDI_TEXTURE_ADDRESS_WRAP = 1,
    D3D10_DDI_TEXTURE_ADDRESS_MIRROR = 2,
    D3D10_DDI_TEXTURE_ADDRESS_CLAMP = 3,
    D3D10_DDI_TEXTURE_ADDRESS_BORDER = 4,
    D3D10_DDI_TEXTURE_ADDRESS_MIRRORONCE = 5
} D3D10_DDI_TEXTURE_ADDRESS_MODE;

typedef enum D3D10DDI_QUERY
{
    D3D10DDI_QUERY_EVENT = 0,
    D3D10DDI_QUERY_OCCLUSION,
    D3D10DDI_QUERY_TIMESTAMP,
    D3D10DDI_QUERY_TIMESTAMPDISJOINT,
    D3D10DDI_QUERY_PIPELINESTATS,
    D3D10DDI_QUERY_OCCLUSIONPREDICATE,
    D3D10DDI_QUERY_STREAMOUTPUTSTATS,
    D3D10DDI_QUERY_STREAMOVERFLOWPREDICATE,

    D3D11DDI_QUERY_PIPELINESTATS,
    D3D11DDI_QUERY_STREAMOUTPUTSTATS_STREAM0,
    D3D11DDI_QUERY_STREAMOUTPUTSTATS_STREAM1,
    D3D11DDI_QUERY_STREAMOUTPUTSTATS_STREAM2,
    D3D11DDI_QUERY_STREAMOUTPUTSTATS_STREAM3,
    D3D11DDI_QUERY_STREAMOVERFLOWPREDICATE_STREAM0,
    D3D11DDI_QUERY_STREAMOVERFLOWPREDICATE_STREAM1,
    D3D11DDI_QUERY_STREAMOVERFLOWPREDICATE_STREAM2,
    D3D11DDI_QUERY_STREAMOVERFLOWPREDICATE_STREAM3,

    D3D10DDI_COUNTER_GPU_IDLE = 0x1000,
    D3D10DDI_COUNTER_VERTEX_PROCESSING,
    D3D10DDI_COUNTER_GEOMETRY_PROCESSING,
    D3D10DDI_COUNTER_PIXEL_PROCESSING,
    D3D10DDI_COUNTER_OTHER_GPU_PROCESSING,
    D3D10DDI_COUNTER_HOST_ADAPTER_BANDWIDTH_UTILIZATION,
    D3D10DDI_COUNTER_LOCAL_VIDMEM_BANDWIDTH_UTILIZATION,
    D3D10DDI_COUNTER_VERTEX_THROUGHPUT_UTILIZATION,
    D3D10DDI_COUNTER_TRISETUP_THROUGHPUT_UTILIZATION,
    D3D10DDI_COUNTER_FILLRATE_THROUGHPUT_UTILIZATION,
    D3D10DDI_COUNTER_VERTEXSHADER_MEMORY_LIMITED,
    D3D10DDI_COUNTER_VERTEXSHADER_COMPUTATION_LIMITED,
    D3D10DDI_COUNTER_GEOMETRYSHADER_MEMORY_LIMITED,
    D3D10DDI_COUNTER_GEOMETRYSHADER_COMPUTATION_LIMITED,
    D3D10DDI_COUNTER_PIXELSHADER_MEMORY_LIMITED,
    D3D10DDI_COUNTER_PIXELSHADER_COMPUTATION_LIMITED,
    D3D10DDI_COUNTER_POST_TRANSFORM_CACHE_HIT_RATE,
    D3D10DDI_COUNTER_TEXTURE_CACHE_HIT_RATE,

    D3D10DDI_COUNTER_DEVICE_DEPENDENT_0 = 0x40000000,
} D3D10DDI_QUERY;

typedef struct D3D10_DDI_QUERY_DATA_TIMESTAMP_DISJOINT
{
    UINT64 Frequency;
    BOOL Disjoint;
} D3D10_DDI_QUERY_DATA_TIMESTAMP_DISJOINT;

typedef struct D3D10_DDI_QUERY_DATA_PIPELINE_STATISTICS
{
    UINT64 IAVertices;
    UINT64 IAPrimitives;
    UINT64 VSInvocations;
    UINT64 GSInvocations;
    UINT64 GSPrimitives;
    UINT64 CInvocations;
    UINT64 CPrimitives;
    UINT64 PSInvocations;
} D3D10_DDI_QUERY_DATA_PIPELINE_STATISTICS;

typedef struct D3D10_DDI_QUERY_DATA_SO_STATISTICS
{
    UINT64 NumPrimitivesWritten;
    UINT64 PrimitivesStorageNeeded;
} D3D10_DDI_QUERY_DATA_SO_STATISTICS;

#define D3D10DDI_QUERY_MISCFLAG_PREDICATEHINT 0x1

typedef enum D3D10_DDI_GET_DATA_FLAG
{
    D3D10_DDI_GET_DATA_DO_NOT_FLUSH = 0x01L,
} D3D10_DDI_GET_DATA_FLAG;

typedef enum D3D10DDI_COUNTER_TYPE
{
    D3D10DDI_COUNTER_TYPE_FLOAT32,
    D3D10DDI_COUNTER_TYPE_UINT16,
    D3D10DDI_COUNTER_TYPE_UINT32,
    D3D10DDI_COUNTER_TYPE_UINT64,
} D3D10DDI_COUNTER_TYPE;

struct D3D10DDI_COUNTER_INFO
{
    D3D10DDI_QUERY LastDeviceDependentCounter;
    UINT NumSimultaneousCounters;
    UINT8 NumDetectableParallelUnits;
};

#define D3D10_DDI_FORMAT_SUPPORT_SHADER_SAMPLE            0x00000001
#define D3D10_DDI_FORMAT_SUPPORT_RENDERTARGET             0x00000002
#define D3D10_DDI_FORMAT_SUPPORT_BLENDABLE                0x00000004
#define D3D10_DDI_FORMAT_SUPPORT_MULTISAMPLE_RENDERTARGET 0x00000008
#define D3D10_DDI_FORMAT_SUPPORT_MULTISAMPLE_LOAD         0x00000010
#define D3D11_1DDI_FORMAT_SUPPORT_DECODER_OUTPUT          0x00000020
#define D3D11_1DDI_FORMAT_SUPPORT_VIDEO_PROCESSOR_OUTPUT  0x00000040
#define D3D11_1DDI_FORMAT_SUPPORT_VIDEO_PROCESSOR_INPUT   0x00000080
#define D3D11_1DDI_FORMAT_SUPPORT_VERTEX_BUFFER           0x00000100
#define D3D11_1DDI_FORMAT_SUPPORT_UAV_WRITES              0x00000200
#define D3D11_1DDI_FORMAT_SUPPORT_BUFFER                  0x00000400
#define D3D11_1DDI_FORMAT_SUPPORT_CAPTURE                 0x00000800
#define D3D11_1DDI_FORMAT_SUPPORT_VIDEO_ENCODER           0x00001000
#define D3D11_1DDI_FORMAT_SUPPORT_OUTPUT_MERGER_LOGIC_OP  0x00002000
#define D3D11_1DDI_FORMAT_SUPPORT_SHADER_GATHER           0x00004000
#define D3D11_1DDI_FORMAT_SUPPORT_MULTIPLANE_OVERLAY      0x00008000
#define D3DWDDM1_3DDI_FORMAT_SUPPORT_TILED                0x00010000
#define D3DWDDM2_0DDI_FORMAT_SUPPORT_UAV_READS            0x00020000
#define D3D10_DDI_FORMAT_SUPPORT_NOT_SUPPORTED            0x80000000

typedef enum D3D10_DDI_CLEAR_FLAG
{
    D3D10_DDI_CLEAR_DEPTH = 0x01L,
    D3D10_DDI_CLEAR_STENCIL = 0x02L,
    D3D10_DDI_CLEAR_FLAG_MASK = 0x03L,
} D3D10_DDI_CLEAR_FLAG;

typedef enum D3D10_DDI_PRIMITIVE_TOPOLOGY
{
    D3D10_DDI_PRIMITIVE_TOPOLOGY_UNDEFINED = 0,
    D3D10_DDI_PRIMITIVE_TOPOLOGY_POINTLIST = 1,
    D3D10_DDI_PRIMITIVE_TOPOLOGY_LINELIST = 2,
    D3D10_DDI_PRIMITIVE_TOPOLOGY_LINESTRIP = 3,
    D3D10_DDI_PRIMITIVE_TOPOLOGY_TRIANGLELIST = 4,
    D3D10_DDI_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = 5,

    D3D10_DDI_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = 10,
    D3D10_DDI_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = 11,
    D3D10_DDI_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = 12,
    D3D10_DDI_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = 13,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST = 33,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST = 34,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST = 35,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST = 36,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST = 37,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST = 38,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST = 39,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST = 40,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST = 41,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST = 42,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST = 43,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST = 44,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST = 45,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST = 46,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST = 47,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST = 48,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST = 49,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST = 50,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST = 51,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST = 52,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST = 53,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST = 54,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST = 55,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST = 56,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST = 57,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST = 58,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST = 59,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST = 60,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST = 61,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST = 62,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST = 63,
    D3D11_DDI_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST = 64,

} D3D10_DDI_PRIMITIVE_TOPOLOGY;

typedef enum D3D10_DDI_DEPTH_WRITE_MASK
{
    D3D10_DDI_DEPTH_WRITE_MASK_ZERO = 0,
    D3D10_DDI_DEPTH_WRITE_MASK_ALL = 1
} D3D10_DDI_DEPTH_WRITE_MASK;

typedef enum D3D10_DDI_STENCIL_OP
{
    D3D10_DDI_STENCIL_OP_KEEP = 1,
    D3D10_DDI_STENCIL_OP_ZERO = 2,
    D3D10_DDI_STENCIL_OP_REPLACE = 3,
    D3D10_DDI_STENCIL_OP_INCR_SAT = 4,
    D3D10_DDI_STENCIL_OP_DECR_SAT = 5,
    D3D10_DDI_STENCIL_OP_INVERT = 6,
    D3D10_DDI_STENCIL_OP_INCR = 7,
    D3D10_DDI_STENCIL_OP_DECR = 8
} D3D10_DDI_STENCIL_OP;

typedef enum D3D10_DDI_FILL_MODE
{

    D3D10_DDI_FILL_WIREFRAME = 2,
    D3D10_DDI_FILL_SOLID = 3
} D3D10_DDI_FILL_MODE;

typedef enum D3D10_DDI_CULL_MODE
{
    D3D10_DDI_CULL_NONE = 1,
    D3D10_DDI_CULL_FRONT = 2,
    D3D10_DDI_CULL_BACK = 3
} D3D10_DDI_CULL_MODE;

typedef enum D3D10_DDI_BLEND
{
    D3D10_DDI_BLEND_ZERO = 1,
    D3D10_DDI_BLEND_ONE = 2,
    D3D10_DDI_BLEND_SRC_COLOR = 3,
    D3D10_DDI_BLEND_INV_SRC_COLOR = 4,
    D3D10_DDI_BLEND_SRC_ALPHA = 5,
    D3D10_DDI_BLEND_INV_SRC_ALPHA = 6,
    D3D10_DDI_BLEND_DEST_ALPHA = 7,
    D3D10_DDI_BLEND_INV_DEST_ALPHA = 8,
    D3D10_DDI_BLEND_DEST_COLOR = 9,
    D3D10_DDI_BLEND_INV_DEST_COLOR = 10,
    D3D10_DDI_BLEND_SRC_ALPHASAT = 11,

    D3D10_DDI_BLEND_BLEND_FACTOR = 14,
    D3D10_DDI_BLEND_INVBLEND_FACTOR = 15,
    D3D10_DDI_BLEND_SRC1_COLOR = 16,
    D3D10_DDI_BLEND_INV_SRC1_COLOR = 17,
    D3D10_DDI_BLEND_SRC1_ALPHA = 18,
    D3D10_DDI_BLEND_INV_SRC1_ALPHA = 19,
} D3D10_DDI_BLEND;

typedef enum D3D10_DDI_BLEND_OP
{
    D3D10_DDI_BLEND_OP_ADD = 1,
    D3D10_DDI_BLEND_OP_SUBTRACT = 2,
    D3D10_DDI_BLEND_OP_REV_SUBTRACT = 3,
    D3D10_DDI_BLEND_OP_MIN = 4,
    D3D10_DDI_BLEND_OP_MAX = 5,
} D3D10_DDI_BLEND_OP;

#define D3D10_DDI_SIMULTANEOUS_RENDER_TARGET_COUNT 8

typedef struct D3D10_DDI_BLEND_DESC
{
    BOOL AlphaToCoverageEnable;
    BOOL BlendEnable[D3D10_DDI_SIMULTANEOUS_RENDER_TARGET_COUNT];
    D3D10_DDI_BLEND SrcBlend;
    D3D10_DDI_BLEND DestBlend;
    D3D10_DDI_BLEND_OP BlendOp;
    D3D10_DDI_BLEND SrcBlendAlpha;
    D3D10_DDI_BLEND DestBlendAlpha;
    D3D10_DDI_BLEND_OP BlendOpAlpha;
    UINT8 RenderTargetWriteMask[D3D10_DDI_SIMULTANEOUS_RENDER_TARGET_COUNT];
} D3D10_DDI_BLEND_DESC;

typedef enum D3D11DDI_HANDLETYPE
{
    D3D10DDI_HT_RESOURCE,
    D3D10DDI_HT_SHADERRESOURCEVIEW,
    D3D10DDI_HT_RENDERTARGETVIEW,
    D3D10DDI_HT_DEPTHSTENCILVIEW,
    D3D10DDI_HT_SHADER,
    D3D10DDI_HT_ELEMENTLAYOUT,
    D3D10DDI_HT_BLENDSTATE,
    D3D10DDI_HT_DEPTHSTENCILSTATE,
    D3D10DDI_HT_RASTERIZERSTATE,
    D3D10DDI_HT_SAMPLERSTATE,
    D3D10DDI_HT_QUERY,
    D3D11DDI_HT_COMMANDLIST,
    D3D11DDI_HT_UNORDEREDACCESSVIEW,
    D3D11_1DDI_HT_DECODE,
    D3D11_1DDI_HT_VIDEOPROCESSORENUM,
    D3D11_1DDI_HT_VIDEOPROCESSOR,
    D3D11_1DDI_HT_VIDEODECODEROUTPUTVIEW,
    D3D11_1DDI_HT_VIDEOPROCESSORINPUTVIEW,
    D3D11_1DDI_HT_VIDEOPROCESSOROUTPUTVIEW,
    D3DWDDM2_2DDI_HT_CACHESESSION,
} D3D11DDI_HANDLETYPE;

typedef enum D3D11_DDI_VIDEO_DECODER_BUFFER_TYPE
{
    D3D11_1DDI_VIDEO_DECODER_BUFFER_UNKNOWN = 0,
    D3D11_1DDI_VIDEO_DECODER_BUFFER_PICTURE_PARAMETERS = 1,
    D3D11_1DDI_VIDEO_DECODER_BUFFER_MACROBLOCK_CONTROL = 2,
    D3D11_1DDI_VIDEO_DECODER_BUFFER_RESIDUAL_DIFFERENCE = 3,
    D3D11_1DDI_VIDEO_DECODER_BUFFER_DEBLOCKING_CONTROL = 4,
    D3D11_1DDI_VIDEO_DECODER_BUFFER_INVERSE_QUANTIZATION_MATRIX = 5,
    D3D11_1DDI_VIDEO_DECODER_BUFFER_SLICE_CONTROL = 6,
    D3D11_1DDI_VIDEO_DECODER_BUFFER_BITSTREAM = 7,
    D3D11_1DDI_VIDEO_DECODER_BUFFER_MOTION_VECTOR = 8,
    D3D11_1DDI_VIDEO_DECODER_BUFFER_FILM_GRAIN = 9
} D3D11_1DDI_VIDEO_DECODER_BUFFER_TYPE;

typedef enum D3DWDDM2_0DDI_TEXTURE_LAYOUT
{
    D3DWDDM2_0DDI_TL_UNDEFINED = 0,
    D3DWDDM2_0DDI_TL_ROW_MAJOR = 1,
    D3DWDDM2_0DDI_TL_STANDARD_SWIZZLE_64K_TILE = 3,
    D3DWDDM2_0DDI_TL_DEVICE_DEPENDENT_SWIZZLE_0 = 0x100,
} D3DWDDM2_0DDI_TEXTURE_LAYOUT;

typedef struct D3D10_DDIARG_SUBRESOURCE_UP
{
    VOID* pSysMem;
    UINT SysMemPitch;
    UINT SysMemSlicePitch;
} D3D10_DDIARG_SUBRESOURCE_UP;

typedef struct D3D10DDIARG_OPENRESOURCE
{
    UINT NumAllocations;
    union {
    D3DDDI_OPENALLOCATIONINFO* pOpenAllocationInfo;
    D3DDDI_OPENALLOCATIONINFO2* pOpenAllocationInfo2;
    };
    D3D10DDI_HKMRESOURCE hKMResource;
    VOID* pPrivateDriverData;
    UINT PrivateDriverDataSize;
} D3D10DDIARG_OPENRESOURCE;

typedef struct D3D10DDI_MAPPED_SUBRESOURCE
{
    void * pData;
    UINT RowPitch;
    UINT DepthPitch;
} D3D10DDI_MAPPED_SUBRESOURCE;

typedef struct D3D10DDIARG_BUFFER_SHADERRESOURCEVIEW
{
    union
{
    UINT FirstElement;
    UINT ElementOffset;
};
    union
{
    UINT NumElements;
    UINT ElementWidth;
};
} D3D10DDIARG_BUFFER_SHADERRESOURCEVIEW;

typedef struct D3D10DDIARG_TEX1D_SHADERRESOURCEVIEW
{
    UINT MostDetailedMip;
    UINT FirstArraySlice;
    UINT MipLevels;
    UINT ArraySize;
} D3D10DDIARG_TEX1D_SHADERRESOURCEVIEW;

typedef struct D3D10DDIARG_TEX2D_SHADERRESOURCEVIEW
{
    UINT MostDetailedMip;
    UINT FirstArraySlice;
    UINT MipLevels;
    UINT ArraySize;
} D3D10DDIARG_TEX2D_SHADERRESOURCEVIEW;

typedef struct D3D10DDIARG_TEX3D_SHADERRESOURCEVIEW
{
    UINT MostDetailedMip;
    UINT MipLevels;
} D3D10DDIARG_TEX3D_SHADERRESOURCEVIEW;

typedef struct D3D10DDIARG_TEXCUBE_SHADERRESOURCEVIEW
{
    UINT MostDetailedMip;
    UINT MipLevels;
} D3D10DDIARG_TEXCUBE_SHADERRESOURCEVIEW;

typedef struct D3D10DDIARG_CREATESHADERRESOURCEVIEW
{
    D3D10DDI_HRESOURCE hDrvResource;
    DXGI_FORMAT Format;
    D3D10DDIRESOURCE_TYPE ResourceDimension;
    union
    {
        D3D10DDIARG_BUFFER_SHADERRESOURCEVIEW Buffer;
        D3D10DDIARG_TEX1D_SHADERRESOURCEVIEW Tex1D;
        D3D10DDIARG_TEX2D_SHADERRESOURCEVIEW Tex2D;
        D3D10DDIARG_TEX3D_SHADERRESOURCEVIEW Tex3D;
        D3D10DDIARG_TEXCUBE_SHADERRESOURCEVIEW TexCube;
    };
} D3D10DDIARG_CREATESHADERRESOURCEVIEW;

typedef struct D3D10DDIARG_BUFFER_RENDERTARGETVIEW
{
    union
{
    UINT FirstElement;
    UINT ElementOffset;
};
    union
{
    UINT NumElements;
    UINT ElementWidth;
};
} D3D10DDIARG_BUFFER_RENDERTARGETVIEW;

typedef struct D3D10DDIARG_TEX1D_RENDERTARGETVIEW
{
    UINT MipSlice;
    UINT FirstArraySlice;
    UINT ArraySize;
} D3D10DDIARG_TEX1D_RENDERTARGETVIEW;

typedef struct D3D10DDIARG_TEX2D_RENDERTARGETVIEW
{
    UINT MipSlice;
    UINT FirstArraySlice;
    UINT ArraySize;
} D3D10DDIARG_TEX2D_RENDERTARGETVIEW;

typedef struct D3D10DDIARG_TEX3D_RENDERTARGETVIEW
{
    UINT MipSlice;
    UINT FirstW;
    UINT WSize;
} D3D10DDIARG_TEX3D_RENDERTARGETVIEW;

typedef struct D3D10DDIARG_TEXCUBE_RENDERTARGETVIEW
{
    UINT MipSlice;
    UINT FirstArraySlice;
    UINT ArraySize;
} D3D10DDIARG_TEXCUBE_RENDERTARGETVIEW;

typedef struct D3D10DDIARG_CREATERENDERTARGETVIEW
{
    D3D10DDI_HRESOURCE hDrvResource;
    DXGI_FORMAT Format;
    D3D10DDIRESOURCE_TYPE ResourceDimension;

    union
{
    D3D10DDIARG_BUFFER_RENDERTARGETVIEW Buffer;
    D3D10DDIARG_TEX1D_RENDERTARGETVIEW Tex1D;
    D3D10DDIARG_TEX2D_RENDERTARGETVIEW Tex2D;
    D3D10DDIARG_TEX3D_RENDERTARGETVIEW Tex3D;
    D3D10DDIARG_TEXCUBE_RENDERTARGETVIEW TexCube;
};
} D3D10DDIARG_CREATERENDERTARGETVIEW;

typedef struct D3D10DDIARG_TEX1D_DEPTHSTENCILVIEW
{
    UINT MipSlice;
    UINT FirstArraySlice;
    UINT ArraySize;
} D3D10DDIARG_TEX1D_DEPTHSTENCILVIEW;

typedef struct D3D10DDIARG_TEX2D_DEPTHSTENCILVIEW
{
    UINT MipSlice;
    UINT FirstArraySlice;
    UINT ArraySize;
} D3D10DDIARG_TEX2D_DEPTHSTENCILVIEW;

typedef struct D3D10DDIARG_TEXCUBE_DEPTHSTENCILVIEW
{
    UINT MipSlice;
    UINT FirstArraySlice;
    UINT ArraySize;
} D3D10DDIARG_TEXCUBE_DEPTHSTENCILVIEW;

typedef struct D3D10DDIARG_CREATEDEPTHSTENCILVIEW
{
    D3D10DDI_HRESOURCE hDrvResource;
    DXGI_FORMAT Format;
    D3D10DDIRESOURCE_TYPE ResourceDimension;
    union
    {
        D3D10DDIARG_TEX1D_DEPTHSTENCILVIEW Tex1D;
        D3D10DDIARG_TEX2D_DEPTHSTENCILVIEW Tex2D;
        D3D10DDIARG_TEXCUBE_DEPTHSTENCILVIEW TexCube;
    };
} D3D10DDIARG_CREATEDEPTHSTENCILVIEW;

typedef struct D3D11DDIARG_CREATEDEPTHSTENCILVIEW
{
    D3D10DDI_HRESOURCE hDrvResource;
    DXGI_FORMAT Format;
    D3D10DDIRESOURCE_TYPE ResourceDimension;
    UINT Flags;

    union
{
    D3D10DDIARG_TEX1D_DEPTHSTENCILVIEW Tex1D;
    D3D10DDIARG_TEX2D_DEPTHSTENCILVIEW Tex2D;
    D3D10DDIARG_TEXCUBE_DEPTHSTENCILVIEW TexCube;
};
} D3D11DDIARG_CREATEDEPTHSTENCILVIEW;

typedef struct D3D10DDIARG_INPUT_ELEMENT_DESC
{
    UINT InputSlot;
    UINT AlignedByteOffset;
    DXGI_FORMAT Format;
    D3D10_DDI_INPUT_CLASSIFICATION InputSlotClass;
    UINT InstanceDataStepRate;
    UINT InputRegister;
} D3D10DDIARG_INPUT_ELEMENT_DESC;

typedef struct D3D10DDIARG_CREATEELEMENTLAYOUT
{
    const D3D10DDIARG_INPUT_ELEMENT_DESC* pVertexElements;
    UINT NumElements;
} D3D10DDIARG_CREATEELEMENTLAYOUT;

typedef struct D3D10DDIARG_STREAM_OUTPUT_DECLARATION_ENTRY
{
    UINT OutputSlot;
    UINT RegisterIndex;
    BYTE RegisterMask;
} D3D10DDIARG_STREAM_OUTPUT_DECLARATION_ENTRY;

typedef struct D3D10DDIARG_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT
{
    const UINT *pShaderCode;
    const D3D10DDIARG_STREAM_OUTPUT_DECLARATION_ENTRY *pOutputStreamDecl;
    UINT NumEntries;
    UINT StreamOutputStrideInBytes;
} D3D10DDIARG_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT;

typedef struct D3D11DDIARG_STREAM_OUTPUT_DECLARATION_ENTRY
{
    UINT Stream;
    UINT OutputSlot;
    UINT RegisterIndex;
    BYTE RegisterMask;
} D3D11DDIARG_STREAM_OUTPUT_DECLARATION_ENTRY;

struct D3D11DDIARG_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT
{
    const UINT *pShaderCode;
    const D3D11DDIARG_STREAM_OUTPUT_DECLARATION_ENTRY *pOutputStreamDecl;
    UINT NumEntries;
    const UINT *BufferStridesInBytes;
    UINT NumStrides;
    UINT RasterizedStream;
};

typedef struct D3D10DDIARG_SIGNATURE_ENTRY
{
    UINT SystemValue;
    UINT Register;
    BYTE Mask;
} D3D10DDIARG_SIGNATURE_ENTRY;

typedef struct D3D10DDIARG_STAGE_IO_SIGNATURES
{

    D3D10DDIARG_SIGNATURE_ENTRY* pInputSignature;
    UINT NumInputSignatureEntries;
    D3D10DDIARG_SIGNATURE_ENTRY* pOutputSignature;
    UINT NumOutputSignatureEntries;
} D3D10DDIARG_STAGE_IO_SIGNATURES;

typedef struct D3D10_DDI_SAMPLER_DESC
{
    D3D10_DDI_FILTER Filter;
    D3D10_DDI_TEXTURE_ADDRESS_MODE AddressU;
    D3D10_DDI_TEXTURE_ADDRESS_MODE AddressV;
    D3D10_DDI_TEXTURE_ADDRESS_MODE AddressW;
    FLOAT MipLODBias;
    UINT MaxAnisotropy;
    D3D10_DDI_COMPARISON_FUNC ComparisonFunc;
    FLOAT BorderColor[4];
    FLOAT MinLOD;
    FLOAT MaxLOD;
} D3D10_DDI_SAMPLER_DESC;

typedef struct D3D10DDIARG_CREATEQUERY
{
    D3D10DDI_QUERY Query;
    UINT MiscFlags;
} D3D10DDIARG_CREATEQUERY;

typedef struct D3D10_DDI_VIEWPORT
{
    FLOAT TopLeftX;
    FLOAT TopLeftY;
    FLOAT Width;
    FLOAT Height;
    FLOAT MinDepth;
    FLOAT MaxDepth;
} D3D10_DDI_VIEWPORT;

typedef RECT D3D10_DDI_RECT;

typedef struct D3D10_DDI_BOX
{
    LONG left;
    LONG top;
    LONG front;
    LONG right;
    LONG bottom;
    LONG back;
} D3D10_DDI_BOX;

typedef struct D3D10_DDI_DEPTH_STENCILOP_DESC
{
    D3D10_DDI_STENCIL_OP StencilFailOp;
    D3D10_DDI_STENCIL_OP StencilDepthFailOp;
    D3D10_DDI_STENCIL_OP StencilPassOp;
    D3D10_DDI_COMPARISON_FUNC StencilFunc;
} D3D10_DDI_DEPTH_STENCILOP_DESC;

typedef struct D3D10_DDI_DEPTH_STENCIL_DESC
{
    BOOL DepthEnable;
    D3D10_DDI_DEPTH_WRITE_MASK DepthWriteMask;
    D3D10_DDI_COMPARISON_FUNC DepthFunc;
    BOOL StencilEnable;
    BOOL FrontEnable;
    BOOL BackEnable;
    UINT8 StencilReadMask;
    UINT8 StencilWriteMask;
    D3D10_DDI_DEPTH_STENCILOP_DESC FrontFace;
    D3D10_DDI_DEPTH_STENCILOP_DESC BackFace;
} D3D10_DDI_DEPTH_STENCIL_DESC;

typedef struct D3D10_DDI_RASTERIZER_DESC
{
    D3D10_DDI_FILL_MODE FillMode;
    D3D10_DDI_CULL_MODE CullMode;
    BOOL FrontCounterClockwise;
    INT32 DepthBias;
    FLOAT DepthBiasClamp;
    FLOAT SlopeScaledDepthBias;
    BOOL DepthClipEnable;
    BOOL ScissorEnable;
    BOOL MultisampleEnable;
    BOOL AntialiasedLineEnable;
} D3D10_DDI_RASTERIZER_DESC;

typedef VOID ( APIENTRY* PFND3D10DDI_DRAW )(
    D3D10DDI_HDEVICE, UINT, UINT );

typedef VOID ( APIENTRY* PFND3D10DDI_DRAWINDEXED )(
    D3D10DDI_HDEVICE, UINT, UINT, INT );

typedef VOID ( APIENTRY* PFND3D10DDI_DRAWINSTANCED )(
    D3D10DDI_HDEVICE, UINT, UINT, UINT, UINT );

typedef VOID ( APIENTRY* PFND3D10DDI_DRAWINDEXEDINSTANCED )(
    D3D10DDI_HDEVICE, UINT, UINT, UINT, INT, UINT );

typedef VOID ( APIENTRY* PFND3D10DDI_DRAWAUTO )(
    D3D10DDI_HDEVICE );

typedef VOID ( APIENTRY* PFND3D10DDI_IA_SETTOPOLOGY )(
    D3D10DDI_HDEVICE, D3D10_DDI_PRIMITIVE_TOPOLOGY );

typedef VOID ( APIENTRY* PFND3D10DDI_IA_SETVERTEXBUFFERS )(
    D3D10DDI_HDEVICE, UINT StartSlot, UINT NumBuffers, const D3D10DDI_HRESOURCE*, const UINT*, const UINT* );

typedef VOID ( APIENTRY* PFND3D10DDI_IA_SETINDEXBUFFER )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, DXGI_FORMAT, UINT );

typedef VOID ( APIENTRY* PFND3D10DDI_SETSHADER )(
    D3D10DDI_HDEVICE, D3D10DDI_HSHADER );

typedef VOID ( APIENTRY* PFND3D10DDI_SETINPUTLAYOUT )(
    D3D10DDI_HDEVICE, D3D10DDI_HELEMENTLAYOUT );

typedef VOID ( APIENTRY* PFND3D10DDI_SETSHADERRESOURCES )(
    D3D10DDI_HDEVICE, UINT StartSlot, UINT NumViews, const D3D10DDI_HSHADERRESOURCEVIEW* );

typedef VOID ( APIENTRY* PFND3D10DDI_SETCONSTANTBUFFERS )(
    D3D10DDI_HDEVICE, UINT StartSlot, UINT NumBuffers, const D3D10DDI_HRESOURCE* );

typedef VOID ( APIENTRY* PFND3D10DDI_SETSAMPLERS )(
    D3D10DDI_HDEVICE, UINT StartSlot, UINT NumSamplers, const D3D10DDI_HSAMPLER* );

typedef VOID ( APIENTRY* PFND3D10DDI_SO_SETTARGETS )(
    D3D10DDI_HDEVICE, UINT NumBuffers, UINT ClearTargets, const D3D10DDI_HRESOURCE*, const UINT* );

typedef VOID ( APIENTRY* PFND3D10DDI_SETBLENDSTATE )(
    D3D10DDI_HDEVICE, D3D10DDI_HBLENDSTATE, const FLOAT[4], UINT );

typedef VOID ( APIENTRY* PFND3D10DDI_SETDEPTHSTENCILSTATE )(
    D3D10DDI_HDEVICE, D3D10DDI_HDEPTHSTENCILSTATE, UINT );

typedef VOID ( APIENTRY* PFND3D10DDI_SETRASTERIZERSTATE )(
    D3D10DDI_HDEVICE, D3D10DDI_HRASTERIZERSTATE );

typedef VOID ( APIENTRY* PFND3D10DDI_SETVIEWPORTS )(
    D3D10DDI_HDEVICE, UINT NumViewports, UINT ClearViewports, const D3D10_DDI_VIEWPORT* );

typedef VOID ( APIENTRY* PFND3D10DDI_SETSCISSORRECTS )(
    D3D10DDI_HDEVICE, UINT NumRects, UINT ClearRects, const D3D10_DDI_RECT* );

typedef VOID ( APIENTRY* PFND3D10DDI_SETPREDICATION )(
    D3D10DDI_HDEVICE, D3D10DDI_HQUERY, BOOL );

typedef VOID ( APIENTRY* PFND3D10DDI_QUERYBEGIN )(
    D3D10DDI_HDEVICE, D3D10DDI_HQUERY );

typedef VOID ( APIENTRY* PFND3D10DDI_QUERYEND )(
    D3D10DDI_HDEVICE, D3D10DDI_HQUERY );

typedef VOID ( APIENTRY* PFND3D10DDI_QUERYGETDATA )(
    D3D10DDI_HDEVICE, D3D10DDI_HQUERY, VOID*, UINT DataSize, UINT );

typedef VOID ( APIENTRY* PFND3D10DDI_CLEARRENDERTARGETVIEW )(
    D3D10DDI_HDEVICE, D3D10DDI_HRENDERTARGETVIEW, FLOAT[4] );

typedef VOID ( APIENTRY* PFND3D10DDI_CLEARDEPTHSTENCILVIEW )(
    D3D10DDI_HDEVICE, D3D10DDI_HDEPTHSTENCILVIEW, UINT, FLOAT, UINT8 );

typedef VOID ( APIENTRY* PFND3D10DDI_FLUSH )(
    D3D10DDI_HDEVICE );

typedef VOID ( APIENTRY* PFND3D10DDI_GENMIPS )(
    D3D10DDI_HDEVICE, D3D10DDI_HSHADERRESOURCEVIEW );

typedef VOID ( APIENTRY* PFND3D10DDI_RESOURCEMAP )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, D3D10_DDI_MAP, UINT, D3D10DDI_MAPPED_SUBRESOURCE* );

typedef VOID ( APIENTRY* PFND3D10DDI_RESOURCEUNMAP )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT );

typedef VOID ( APIENTRY* PFND3D10DDI_RESOURCEREADAFTERWRITEHAZARD )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE );

typedef VOID ( APIENTRY* PFND3D10DDI_SHADERRESOURCEVIEWREADAFTERWRITEHAZARD )(
    D3D10DDI_HDEVICE, D3D10DDI_HSHADERRESOURCEVIEW, D3D10DDI_HRESOURCE );

typedef VOID ( APIENTRY* PFND3D10DDI_RESOURCECOPYREGION )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, UINT, UINT, UINT, D3D10DDI_HRESOURCE, UINT, const D3D10_DDI_BOX* );

typedef VOID ( APIENTRY* PFND3D10DDI_RESOURCECOPY )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, D3D10DDI_HRESOURCE );

typedef VOID ( APIENTRY* PFND3D10DDI_RESOURCERESOLVESUBRESOURCE )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, D3D10DDI_HRESOURCE, UINT, DXGI_FORMAT );

typedef VOID ( APIENTRY* PFND3D10DDI_RESOURCEUPDATESUBRESOURCEUP )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, const D3D10_DDI_BOX*, const VOID*, UINT, UINT );

typedef VOID ( APIENTRY* PFND3D10DDI_SETTEXTFILTERSIZE )(
    D3D10DDI_HDEVICE, UINT, UINT );

typedef BOOL ( APIENTRY* PFND3D10DDI_RESOURCEISSTAGINGBUSY )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE );

typedef SIZE_T ( APIENTRY* PFND3D10DDI_CALCPRIVATEOPENEDRESOURCESIZE )(
    D3D10DDI_HDEVICE, const D3D10DDIARG_OPENRESOURCE* );

typedef VOID ( APIENTRY* PFND3D10DDI_OPENRESOURCE )(
    D3D10DDI_HDEVICE, const D3D10DDIARG_OPENRESOURCE*, D3D10DDI_HRESOURCE, D3D10DDI_HRTRESOURCE );

typedef VOID ( APIENTRY* PFND3D10DDI_DESTROYRESOURCE )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE );

typedef VOID ( APIENTRY* PFND3D10DDI_DESTROYSHADERRESOURCEVIEW )(
    D3D10DDI_HDEVICE, D3D10DDI_HSHADERRESOURCEVIEW );

typedef SIZE_T ( APIENTRY* PFND3D10DDI_CALCPRIVATERENDERTARGETVIEWSIZE )(
    D3D10DDI_HDEVICE, const D3D10DDIARG_CREATERENDERTARGETVIEW* );

typedef VOID ( APIENTRY* PFND3D10DDI_CREATERENDERTARGETVIEW )(
    D3D10DDI_HDEVICE, const D3D10DDIARG_CREATERENDERTARGETVIEW*, D3D10DDI_HRENDERTARGETVIEW, D3D10DDI_HRTRENDERTARGETVIEW );

typedef VOID ( APIENTRY* PFND3D10DDI_DESTROYRENDERTARGETVIEW )(
    D3D10DDI_HDEVICE, D3D10DDI_HRENDERTARGETVIEW );

typedef VOID ( APIENTRY* PFND3D10DDI_DESTROYDEPTHSTENCILVIEW )(
    D3D10DDI_HDEVICE, D3D10DDI_HDEPTHSTENCILVIEW );

typedef SIZE_T ( APIENTRY* PFND3D10DDI_CALCPRIVATEELEMENTLAYOUTSIZE )(
    D3D10DDI_HDEVICE, const D3D10DDIARG_CREATEELEMENTLAYOUT* );

typedef VOID ( APIENTRY* PFND3D10DDI_CREATEELEMENTLAYOUT )(
    D3D10DDI_HDEVICE, const D3D10DDIARG_CREATEELEMENTLAYOUT*, D3D10DDI_HELEMENTLAYOUT, D3D10DDI_HRTELEMENTLAYOUT );

typedef VOID ( APIENTRY* PFND3D10DDI_DESTROYELEMENTLAYOUT )(
    D3D10DDI_HDEVICE, D3D10DDI_HELEMENTLAYOUT );

typedef VOID ( APIENTRY* PFND3D10DDI_DESTROYBLENDSTATE )(
    D3D10DDI_HDEVICE, D3D10DDI_HBLENDSTATE );

typedef SIZE_T ( APIENTRY* PFND3D10DDI_CALCPRIVATEDEPTHSTENCILSTATESIZE )(
    D3D10DDI_HDEVICE, const D3D10_DDI_DEPTH_STENCIL_DESC* );

typedef VOID ( APIENTRY* PFND3D10DDI_CREATEDEPTHSTENCILSTATE )(
    D3D10DDI_HDEVICE, const D3D10_DDI_DEPTH_STENCIL_DESC*, D3D10DDI_HDEPTHSTENCILSTATE, D3D10DDI_HRTDEPTHSTENCILSTATE );

typedef VOID ( APIENTRY* PFND3D10DDI_DESTROYDEPTHSTENCILSTATE )(
    D3D10DDI_HDEVICE, D3D10DDI_HDEPTHSTENCILSTATE );

typedef SIZE_T ( APIENTRY* PFND3D10DDI_CALCPRIVATERASTERIZERSTATESIZE )(
    D3D10DDI_HDEVICE, const D3D10_DDI_RASTERIZER_DESC* );

typedef VOID ( APIENTRY* PFND3D10DDI_CREATERASTERIZERSTATE )(
    D3D10DDI_HDEVICE, const D3D10_DDI_RASTERIZER_DESC*, D3D10DDI_HRASTERIZERSTATE, D3D10DDI_HRTRASTERIZERSTATE );

typedef VOID ( APIENTRY* PFND3D10DDI_DESTROYRASTERIZERSTATE )(
    D3D10DDI_HDEVICE, D3D10DDI_HRASTERIZERSTATE );

typedef SIZE_T ( APIENTRY* PFND3D10DDI_CALCPRIVATESHADERSIZE )(
    D3D10DDI_HDEVICE, const UINT* pShaderCode, const D3D10DDIARG_STAGE_IO_SIGNATURES* );

typedef VOID ( APIENTRY* PFND3D10DDI_CREATEVERTEXSHADER )(
    D3D10DDI_HDEVICE, const UINT* pShaderCode, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER, const D3D10DDIARG_STAGE_IO_SIGNATURES* );

typedef VOID ( APIENTRY* PFND3D10DDI_CREATEGEOMETRYSHADER )(
    D3D10DDI_HDEVICE, const UINT* pShaderCode, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER, const D3D10DDIARG_STAGE_IO_SIGNATURES* );

typedef VOID ( APIENTRY* PFND3D10DDI_CREATEPIXELSHADER )(
    D3D10DDI_HDEVICE, const UINT* pShaderCode, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER, const D3D10DDIARG_STAGE_IO_SIGNATURES* );

typedef VOID ( APIENTRY* PFND3D10DDI_DESTROYSHADER )(
    D3D10DDI_HDEVICE, D3D10DDI_HSHADER );

typedef SIZE_T ( APIENTRY* PFND3D10DDI_CALCPRIVATESAMPLERSIZE )(
    D3D10DDI_HDEVICE, const D3D10_DDI_SAMPLER_DESC* );

typedef VOID ( APIENTRY* PFND3D10DDI_CREATESAMPLER )(
    D3D10DDI_HDEVICE, const D3D10_DDI_SAMPLER_DESC*, D3D10DDI_HSAMPLER, D3D10DDI_HRTSAMPLER );

typedef VOID ( APIENTRY* PFND3D10DDI_DESTROYSAMPLER )(
    D3D10DDI_HDEVICE, D3D10DDI_HSAMPLER );

typedef SIZE_T ( APIENTRY* PFND3D10DDI_CALCPRIVATEQUERYSIZE )(
    D3D10DDI_HDEVICE, const D3D10DDIARG_CREATEQUERY* );

typedef VOID ( APIENTRY* PFND3D10DDI_CREATEQUERY )(
    D3D10DDI_HDEVICE, const D3D10DDIARG_CREATEQUERY*, D3D10DDI_HQUERY, D3D10DDI_HRTQUERY );

typedef VOID ( APIENTRY* PFND3D10DDI_DESTROYQUERY )(
    D3D10DDI_HDEVICE, D3D10DDI_HQUERY );

typedef VOID ( APIENTRY* PFND3D10DDI_CHECKFORMATSUPPORT )(
    D3D10DDI_HDEVICE, DXGI_FORMAT, UINT* );

typedef VOID ( APIENTRY* PFND3D10DDI_CHECKMULTISAMPLEQUALITYLEVELS )(
    D3D10DDI_HDEVICE, DXGI_FORMAT, UINT, UINT* );

typedef VOID ( APIENTRY* PFND3D10DDI_CHECKCOUNTERINFO )(
    D3D10DDI_HDEVICE, D3D10DDI_COUNTER_INFO* );

typedef VOID ( APIENTRY* PFND3D10DDI_CHECKCOUNTER )(
    D3D10DDI_HDEVICE, D3D10DDI_QUERY, D3D10DDI_COUNTER_TYPE*, UINT*,
    LPSTR, UINT* pNameLength,
    LPSTR, UINT* pUnitsLength,
    LPSTR, UINT* pDescriptionLength);

typedef VOID ( APIENTRY* PFND3D10DDI_DESTROYDEVICE )(
    D3D10DDI_HDEVICE );

typedef VOID ( APIENTRY* PFND3D10DDI_RESETPRIMITIVEID)(
    D3D10DDI_HDEVICE, BOOL );

typedef VOID ( APIENTRY* PFND3D10DDI_SETVERTEXPIPELINEOUTPUT)(
    D3D10DDI_HDEVICE, const D3D10DDIARG_VERTEXPIPELINEOUTPUT* );

typedef VOID (APIENTRY *PFND3D10DDI_SETRENDERTARGETS)(
    D3D10DDI_HDEVICE, const D3D10DDI_HRENDERTARGETVIEW *, UINT, UINT,
    D3D10DDI_HDEPTHSTENCILVIEW);

typedef VOID (APIENTRY *PFND3D10DDI_RELOCATEDEVICEFUNCS)(
    D3D10DDI_HDEVICE, struct D3D10DDI_DEVICEFUNCS *);

typedef SIZE_T (APIENTRY *PFND3D10DDI_CALCPRIVATERESOURCESIZE)(
    D3D10DDI_HDEVICE, const D3D10DDIARG_CREATERESOURCE *);

typedef VOID (APIENTRY *PFND3D10DDI_CREATERESOURCE)(
    D3D10DDI_HDEVICE, const D3D10DDIARG_CREATERESOURCE *,
    D3D10DDI_HRESOURCE, D3D10DDI_HRTRESOURCE);

typedef SIZE_T (APIENTRY *PFND3D10DDI_CALCPRIVATESHADERRESOURCEVIEWSIZE)(
    D3D10DDI_HDEVICE, const D3D10DDIARG_CREATESHADERRESOURCEVIEW *);

typedef VOID (APIENTRY *PFND3D10DDI_CREATESHADERRESOURCEVIEW)(
    D3D10DDI_HDEVICE, const D3D10DDIARG_CREATESHADERRESOURCEVIEW *,
    D3D10DDI_HSHADERRESOURCEVIEW, D3D10DDI_HRTSHADERRESOURCEVIEW);

typedef SIZE_T (APIENTRY *PFND3D10DDI_CALCPRIVATEDEPTHSTENCILVIEWSIZE)(
    D3D10DDI_HDEVICE, const D3D10DDIARG_CREATEDEPTHSTENCILVIEW *);

typedef VOID (APIENTRY *PFND3D10DDI_CREATEDEPTHSTENCILVIEW)(
    D3D10DDI_HDEVICE, const D3D10DDIARG_CREATEDEPTHSTENCILVIEW *,
    D3D10DDI_HDEPTHSTENCILVIEW, D3D10DDI_HRTDEPTHSTENCILVIEW);

typedef SIZE_T (APIENTRY *PFND3D10DDI_CALCPRIVATEBLENDSTATESIZE)(
    D3D10DDI_HDEVICE, const D3D10_DDI_BLEND_DESC *);

typedef VOID (APIENTRY *PFND3D10DDI_CREATEBLENDSTATE)(
    D3D10DDI_HDEVICE, const D3D10_DDI_BLEND_DESC *,
    D3D10DDI_HBLENDSTATE, D3D10DDI_HRTBLENDSTATE);

typedef SIZE_T (APIENTRY *PFND3D10DDI_CALCPRIVATEGEOMETRYSHADERWITHSTREAMOUTPUT)(
    D3D10DDI_HDEVICE,
    const D3D10DDIARG_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT *,
    const D3D10DDIARG_STAGE_IO_SIGNATURES *);

typedef VOID (APIENTRY *PFND3D10DDI_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT)(
    D3D10DDI_HDEVICE,
    const D3D10DDIARG_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT *,
    D3D10DDI_HSHADER, D3D10DDI_HRTSHADER,
    const D3D10DDIARG_STAGE_IO_SIGNATURES *);

/* Direct3D 10.0 device dispatch table. Member order is ABI. */
struct D3D10DDI_DEVICEFUNCS
{
    PFND3D10DDI_RESOURCEUPDATESUBRESOURCEUP pfnDefaultConstantBufferUpdateSubresourceUP;
    PFND3D10DDI_SETCONSTANTBUFFERS pfnVsSetConstantBuffers;
    PFND3D10DDI_SETSHADERRESOURCES pfnPsSetShaderResources;
    PFND3D10DDI_SETSHADER pfnPsSetShader;
    PFND3D10DDI_SETSAMPLERS pfnPsSetSamplers;
    PFND3D10DDI_SETSHADER pfnVsSetShader;
    PFND3D10DDI_DRAWINDEXED pfnDrawIndexed;
    PFND3D10DDI_DRAW pfnDraw;
    PFND3D10DDI_RESOURCEMAP pfnDynamicIABufferMapNoOverwrite;
    PFND3D10DDI_RESOURCEUNMAP pfnDynamicIABufferUnmap;
    PFND3D10DDI_RESOURCEMAP pfnDynamicConstantBufferMapDiscard;
    PFND3D10DDI_RESOURCEMAP pfnDynamicIABufferMapDiscard;
    PFND3D10DDI_RESOURCEUNMAP pfnDynamicConstantBufferUnmap;
    PFND3D10DDI_SETCONSTANTBUFFERS pfnPsSetConstantBuffers;
    PFND3D10DDI_SETINPUTLAYOUT pfnIaSetInputLayout;
    PFND3D10DDI_IA_SETVERTEXBUFFERS pfnIaSetVertexBuffers;
    PFND3D10DDI_IA_SETINDEXBUFFER pfnIaSetIndexBuffer;
    PFND3D10DDI_DRAWINDEXEDINSTANCED pfnDrawIndexedInstanced;
    PFND3D10DDI_DRAWINSTANCED pfnDrawInstanced;
    PFND3D10DDI_RESOURCEMAP pfnDynamicResourceMapDiscard;
    PFND3D10DDI_RESOURCEUNMAP pfnDynamicResourceUnmap;
    PFND3D10DDI_SETCONSTANTBUFFERS pfnGsSetConstantBuffers;
    PFND3D10DDI_SETSHADER pfnGsSetShader;
    PFND3D10DDI_IA_SETTOPOLOGY pfnIaSetTopology;
    PFND3D10DDI_RESOURCEMAP pfnStagingResourceMap;
    PFND3D10DDI_RESOURCEUNMAP pfnStagingResourceUnmap;
    PFND3D10DDI_SETSHADERRESOURCES pfnVsSetShaderResources;
    PFND3D10DDI_SETSAMPLERS pfnVsSetSamplers;
    PFND3D10DDI_SETSHADERRESOURCES pfnGsSetShaderResources;
    PFND3D10DDI_SETSAMPLERS pfnGsSetSamplers;
    PFND3D10DDI_SETRENDERTARGETS pfnSetRenderTargets;
    PFND3D10DDI_SHADERRESOURCEVIEWREADAFTERWRITEHAZARD pfnShaderResourceViewReadAfterWriteHazard;
    PFND3D10DDI_RESOURCEREADAFTERWRITEHAZARD pfnResourceReadAfterWriteHazard;
    PFND3D10DDI_SETBLENDSTATE pfnSetBlendState;
    PFND3D10DDI_SETDEPTHSTENCILSTATE pfnSetDepthStencilState;
    PFND3D10DDI_SETRASTERIZERSTATE pfnSetRasterizerState;
    PFND3D10DDI_QUERYEND pfnQueryEnd;
    PFND3D10DDI_QUERYBEGIN pfnQueryBegin;
    PFND3D10DDI_RESOURCECOPYREGION pfnResourceCopyRegion;
    PFND3D10DDI_RESOURCEUPDATESUBRESOURCEUP pfnResourceUpdateSubresourceUP;
    PFND3D10DDI_SO_SETTARGETS pfnSoSetTargets;
    PFND3D10DDI_DRAWAUTO pfnDrawAuto;
    PFND3D10DDI_SETVIEWPORTS pfnSetViewports;
    PFND3D10DDI_SETSCISSORRECTS pfnSetScissorRects;
    PFND3D10DDI_CLEARRENDERTARGETVIEW pfnClearRenderTargetView;
    PFND3D10DDI_CLEARDEPTHSTENCILVIEW pfnClearDepthStencilView;
    PFND3D10DDI_SETPREDICATION pfnSetPredication;
    PFND3D10DDI_QUERYGETDATA pfnQueryGetData;
    PFND3D10DDI_FLUSH pfnFlush;
    PFND3D10DDI_GENMIPS pfnGenMips;
    PFND3D10DDI_RESOURCECOPY pfnResourceCopy;
    PFND3D10DDI_RESOURCERESOLVESUBRESOURCE pfnResourceResolveSubresource;
    PFND3D10DDI_RESOURCEMAP pfnResourceMap;
    PFND3D10DDI_RESOURCEUNMAP pfnResourceUnmap;
    PFND3D10DDI_RESOURCEISSTAGINGBUSY pfnResourceIsStagingBusy;
    PFND3D10DDI_RELOCATEDEVICEFUNCS pfnRelocateDeviceFuncs;
    PFND3D10DDI_CALCPRIVATERESOURCESIZE pfnCalcPrivateResourceSize;
    PFND3D10DDI_CALCPRIVATEOPENEDRESOURCESIZE pfnCalcPrivateOpenedResourceSize;
    PFND3D10DDI_CREATERESOURCE pfnCreateResource;
    PFND3D10DDI_OPENRESOURCE pfnOpenResource;
    PFND3D10DDI_DESTROYRESOURCE pfnDestroyResource;
    PFND3D10DDI_CALCPRIVATESHADERRESOURCEVIEWSIZE pfnCalcPrivateShaderResourceViewSize;
    PFND3D10DDI_CREATESHADERRESOURCEVIEW pfnCreateShaderResourceView;
    PFND3D10DDI_DESTROYSHADERRESOURCEVIEW pfnDestroyShaderResourceView;
    PFND3D10DDI_CALCPRIVATERENDERTARGETVIEWSIZE pfnCalcPrivateRenderTargetViewSize;
    PFND3D10DDI_CREATERENDERTARGETVIEW pfnCreateRenderTargetView;
    PFND3D10DDI_DESTROYRENDERTARGETVIEW pfnDestroyRenderTargetView;
    PFND3D10DDI_CALCPRIVATEDEPTHSTENCILVIEWSIZE pfnCalcPrivateDepthStencilViewSize;
    PFND3D10DDI_CREATEDEPTHSTENCILVIEW pfnCreateDepthStencilView;
    PFND3D10DDI_DESTROYDEPTHSTENCILVIEW pfnDestroyDepthStencilView;
    PFND3D10DDI_CALCPRIVATEELEMENTLAYOUTSIZE pfnCalcPrivateElementLayoutSize;
    PFND3D10DDI_CREATEELEMENTLAYOUT pfnCreateElementLayout;
    PFND3D10DDI_DESTROYELEMENTLAYOUT pfnDestroyElementLayout;
    PFND3D10DDI_CALCPRIVATEBLENDSTATESIZE pfnCalcPrivateBlendStateSize;
    PFND3D10DDI_CREATEBLENDSTATE pfnCreateBlendState;
    PFND3D10DDI_DESTROYBLENDSTATE pfnDestroyBlendState;
    PFND3D10DDI_CALCPRIVATEDEPTHSTENCILSTATESIZE pfnCalcPrivateDepthStencilStateSize;
    PFND3D10DDI_CREATEDEPTHSTENCILSTATE pfnCreateDepthStencilState;
    PFND3D10DDI_DESTROYDEPTHSTENCILSTATE pfnDestroyDepthStencilState;
    PFND3D10DDI_CALCPRIVATERASTERIZERSTATESIZE pfnCalcPrivateRasterizerStateSize;
    PFND3D10DDI_CREATERASTERIZERSTATE pfnCreateRasterizerState;
    PFND3D10DDI_DESTROYRASTERIZERSTATE pfnDestroyRasterizerState;
    PFND3D10DDI_CALCPRIVATESHADERSIZE pfnCalcPrivateShaderSize;
    PFND3D10DDI_CREATEVERTEXSHADER pfnCreateVertexShader;
    PFND3D10DDI_CREATEGEOMETRYSHADER pfnCreateGeometryShader;
    PFND3D10DDI_CREATEPIXELSHADER pfnCreatePixelShader;
    PFND3D10DDI_CALCPRIVATEGEOMETRYSHADERWITHSTREAMOUTPUT pfnCalcPrivateGeometryShaderWithStreamOutput;
    PFND3D10DDI_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT pfnCreateGeometryShaderWithStreamOutput;
    PFND3D10DDI_DESTROYSHADER pfnDestroyShader;
    PFND3D10DDI_CALCPRIVATESAMPLERSIZE pfnCalcPrivateSamplerSize;
    PFND3D10DDI_CREATESAMPLER pfnCreateSampler;
    PFND3D10DDI_DESTROYSAMPLER pfnDestroySampler;
    PFND3D10DDI_CALCPRIVATEQUERYSIZE pfnCalcPrivateQuerySize;
    PFND3D10DDI_CREATEQUERY pfnCreateQuery;
    PFND3D10DDI_DESTROYQUERY pfnDestroyQuery;
    PFND3D10DDI_CHECKFORMATSUPPORT pfnCheckFormatSupport;
    PFND3D10DDI_CHECKMULTISAMPLEQUALITYLEVELS pfnCheckMultisampleQualityLevels;
    PFND3D10DDI_CHECKCOUNTERINFO pfnCheckCounterInfo;
    PFND3D10DDI_CHECKCOUNTER pfnCheckCounter;
    PFND3D10DDI_DESTROYDEVICE pfnDestroyDevice;
    PFND3D10DDI_SETTEXTFILTERSIZE pfnSetTextFilterSize;
};

typedef struct D3D10_1DDIARG_TEXCUBE_SHADERRESOURCEVIEW
{
    UINT MostDetailedMip;
    UINT MipLevels;
    UINT First2DArrayFace;
    UINT NumCubes;
} D3D10_1DDIARG_TEXCUBE_SHADERRESOURCEVIEW;

typedef struct D3D10_1DDIARG_CREATESHADERRESOURCEVIEW
{
    D3D10DDI_HRESOURCE hDrvResource;
    DXGI_FORMAT Format;
    D3D10DDIRESOURCE_TYPE ResourceDimension;
    union
    {
        D3D10DDIARG_BUFFER_SHADERRESOURCEVIEW Buffer;
        D3D10DDIARG_TEX1D_SHADERRESOURCEVIEW Tex1D;
        D3D10DDIARG_TEX2D_SHADERRESOURCEVIEW Tex2D;
        D3D10DDIARG_TEX3D_SHADERRESOURCEVIEW Tex3D;
        D3D10_1DDIARG_TEXCUBE_SHADERRESOURCEVIEW TexCube;
    };
} D3D10_1DDIARG_CREATESHADERRESOURCEVIEW;

typedef struct D3D10_DDI_RENDER_TARGET_BLEND_DESC1
{
    BOOL BlendEnable;
    D3D10_DDI_BLEND SrcBlend;
    D3D10_DDI_BLEND DestBlend;
    D3D10_DDI_BLEND_OP BlendOp;
    D3D10_DDI_BLEND SrcBlendAlpha;
    D3D10_DDI_BLEND DestBlendAlpha;
    D3D10_DDI_BLEND_OP BlendOpAlpha;
    UINT8 RenderTargetWriteMask;
} D3D10_DDI_RENDER_TARGET_BLEND_DESC1;

typedef struct D3D10_1_DDI_BLEND_DESC
{
    BOOL AlphaToCoverageEnable;
    BOOL IndependentBlendEnable;
    D3D10_DDI_RENDER_TARGET_BLEND_DESC1 RenderTarget[8];
} D3D10_1_DDI_BLEND_DESC;

typedef SIZE_T ( APIENTRY* PFND3D10_1DDI_CALCPRIVATEBLENDSTATESIZE )(
    D3D10DDI_HDEVICE, const D3D10_1_DDI_BLEND_DESC* );

typedef VOID ( APIENTRY* PFND3D10_1DDI_CREATEBLENDSTATE )(
    D3D10DDI_HDEVICE, const D3D10_1_DDI_BLEND_DESC*, D3D10DDI_HBLENDSTATE, D3D10DDI_HRTBLENDSTATE );

typedef struct D3D11DDIARG_TESSELLATION_IO_SIGNATURES
{

    D3D10DDIARG_SIGNATURE_ENTRY* pInputSignature;
    UINT NumInputSignatureEntries;
    D3D10DDIARG_SIGNATURE_ENTRY* pOutputSignature;
    UINT NumOutputSignatureEntries;
    D3D10DDIARG_SIGNATURE_ENTRY* pPatchConstantSignature;
    UINT NumPatchConstantSignatureEntries;
} D3D11DDIARG_TESSELLATION_IO_SIGNATURES;

typedef struct D3D11DDIARG_CREATERESOURCE
{
    const D3D10DDI_MIPINFO* pMipInfoList;
    const D3D10_DDIARG_SUBRESOURCE_UP* pInitialDataUP;
    D3D10DDIRESOURCE_TYPE ResourceDimension;

    UINT Usage;
    UINT BindFlags;
    UINT MapFlags;
    UINT MiscFlags;

    DXGI_FORMAT Format;
    DXGI_SAMPLE_DESC SampleDesc;
    UINT MipLevels;
    UINT ArraySize;

    DXGI_DDI_PRIMARY_DESC* pPrimaryDesc;

    UINT ByteStride;
    D3D11_1DDI_VIDEO_DECODER_BUFFER_TYPE DecoderBufferType;

    D3DWDDM2_0DDI_TEXTURE_LAYOUT TextureLayout;

} D3D11DDIARG_CREATERESOURCE;

typedef struct D3D11DDIARG_BUFFEREX_SHADERRESOURCEVIEW
{
    union
{
    UINT FirstElement;
    UINT ElementOffset;
};
    union
{
    UINT NumElements;
    UINT ElementWidth;
};
    UINT Flags;
} D3D11DDIARG_BUFFEREX_SHADERRESOURCEVIEW;

typedef struct D3D11DDIARG_CREATESHADERRESOURCEVIEW
{
    D3D10DDI_HRESOURCE hDrvResource;
    DXGI_FORMAT Format;
    D3D10DDIRESOURCE_TYPE ResourceDimension;

    union
{
    D3D10DDIARG_BUFFER_SHADERRESOURCEVIEW Buffer;
    D3D10DDIARG_TEX1D_SHADERRESOURCEVIEW Tex1D;
    D3D10DDIARG_TEX2D_SHADERRESOURCEVIEW Tex2D;
    D3D10DDIARG_TEX3D_SHADERRESOURCEVIEW Tex3D;
    D3D10_1DDIARG_TEXCUBE_SHADERRESOURCEVIEW TexCube;
    D3D11DDIARG_BUFFEREX_SHADERRESOURCEVIEW BufferEx;
};
} D3D11DDIARG_CREATESHADERRESOURCEVIEW;

typedef struct D3D11DDIARG_BUFFER_UNORDEREDACCESSVIEW
{
    UINT FirstElement;
    UINT NumElements;
    UINT Flags;
} D3D11DDIARG_BUFFER_UNORDEREDACCESSVIEW;

typedef struct D3D11DDIARG_TEX1D_UNORDEREDACCESSVIEW
{
    UINT MipSlice;
    UINT FirstArraySlice;
    UINT ArraySize;
} D3D11DDIARG_TEX1D_UNORDEREDACCESSVIEW;

typedef struct D3D11DDIARG_TEX2D_UNORDEREDACCESSVIEW
{
    UINT MipSlice;
    UINT FirstArraySlice;
    UINT ArraySize;
} D3D11DDIARG_TEX2D_UNORDEREDACCESSVIEW;

typedef struct D3D11DDIARG_TEX3D_UNORDEREDACCESSVIEW
{
    UINT MipSlice;
    UINT FirstW;
    UINT WSize;
} D3D11DDIARG_TEX3D_UNORDEREDACCESSVIEW;

typedef struct D3D11DDIARG_CREATEUNORDEREDACCESSVIEW
{
    D3D10DDI_HRESOURCE hDrvResource;
    DXGI_FORMAT Format;
    D3D10DDIRESOURCE_TYPE ResourceDimension;

    union
{
    D3D11DDIARG_BUFFER_UNORDEREDACCESSVIEW Buffer;
    D3D11DDIARG_TEX1D_UNORDEREDACCESSVIEW Tex1D;
    D3D11DDIARG_TEX2D_UNORDEREDACCESSVIEW Tex2D;
    D3D11DDIARG_TEX3D_UNORDEREDACCESSVIEW Tex3D;
};
} D3D11DDIARG_CREATEUNORDEREDACCESSVIEW;

typedef VOID ( APIENTRY* PFND3D11DDI_RELOCATEDEVICEFUNCS )(
    D3D10DDI_HDEVICE, struct D3D11DDI_DEVICEFUNCS* );

typedef SIZE_T ( APIENTRY* PFND3D11DDI_CALCPRIVATEGEOMETRYSHADERWITHSTREAMOUTPUT )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT*, const D3D10DDIARG_STAGE_IO_SIGNATURES* );

typedef VOID ( APIENTRY* PFND3D11DDI_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT*, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER, const D3D10DDIARG_STAGE_IO_SIGNATURES* );

typedef VOID ( APIENTRY* PFND3D11DDI_DRAWINDEXEDINSTANCEDINDIRECT )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT );

typedef VOID ( APIENTRY* PFND3D11DDI_DRAWINSTANCEDINDIRECT )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT );

typedef SIZE_T ( APIENTRY* PFND3D11DDI_CALCPRIVATETESSELLATIONSHADERSIZE )(
    D3D10DDI_HDEVICE, const UINT* pShaderCode, const D3D11DDIARG_TESSELLATION_IO_SIGNATURES* );

typedef VOID ( APIENTRY* PFND3D11DDI_CREATEHULLSHADER )(
    D3D10DDI_HDEVICE, const UINT* pShaderCode, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER, const D3D11DDIARG_TESSELLATION_IO_SIGNATURES* );

typedef VOID ( APIENTRY* PFND3D11DDI_CREATEDOMAINSHADER )(
    D3D10DDI_HDEVICE, const UINT* pShaderCode, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER, const D3D11DDIARG_TESSELLATION_IO_SIGNATURES* );

typedef VOID ( APIENTRY* PFND3D11DDI_CHECKDEFERREDCONTEXTHANDLESIZES )(
    D3D10DDI_HDEVICE, UINT* pHSizes, D3D11DDI_HANDLESIZE* );

typedef SIZE_T ( APIENTRY* PFND3D11DDI_CALCDEFERREDCONTEXTHANDLESIZE )(
    D3D10DDI_HDEVICE, D3D11DDI_HANDLETYPE, VOID* );

typedef SIZE_T ( APIENTRY* PFND3D11DDI_CALCPRIVATEDEFERREDCONTEXTSIZE )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CALCPRIVATEDEFERREDCONTEXTSIZE* );

typedef VOID ( APIENTRY* PFND3D11DDI_CREATEDEFERREDCONTEXT )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATEDEFERREDCONTEXT* );

typedef HRESULT ( APIENTRY* PFND3D11DDI_RECYCLECREATEDEFERREDCONTEXT )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATEDEFERREDCONTEXT* );

typedef VOID ( APIENTRY* PFND3D11DDI_ABANDONCOMMANDLIST )(
    D3D10DDI_HDEVICE );

typedef SIZE_T ( APIENTRY* PFND3D11DDI_CALCPRIVATECOMMANDLISTSIZE )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATECOMMANDLIST* );

typedef VOID ( APIENTRY* PFND3D11DDI_CREATECOMMANDLIST )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATECOMMANDLIST*, D3D11DDI_HCOMMANDLIST, D3D11DDI_HRTCOMMANDLIST );

typedef VOID ( APIENTRY* PFND3D11DDI_RECYCLECOMMANDLIST )( D3D10DDI_HDEVICE , D3D11DDI_HCOMMANDLIST );

typedef HRESULT ( APIENTRY* PFND3D11DDI_RECYCLECREATECOMMANDLIST )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATECOMMANDLIST*, D3D11DDI_HCOMMANDLIST, D3D11DDI_HRTCOMMANDLIST );

typedef VOID ( APIENTRY* PFND3D11DDI_DESTROYCOMMANDLIST )(
    D3D10DDI_HDEVICE, D3D11DDI_HCOMMANDLIST );

typedef VOID ( APIENTRY* PFND3D11DDI_COMMANDLISTEXECUTE )(
    D3D10DDI_HDEVICE, D3D11DDI_HCOMMANDLIST );

typedef VOID ( APIENTRY* PFND3D11DDI_SETSHADER_WITH_IFACES )(
    D3D10DDI_HDEVICE, D3D10DDI_HSHADER, UINT NumClassInstances, const UINT*, const D3D11DDIARG_POINTERDATA* );

typedef VOID ( APIENTRY* PFND3D11DDI_SETRENDERTARGETS )
    (
    D3D10DDI_HDEVICE,
    const D3D10DDI_HRENDERTARGETVIEW*,
    UINT NumRTVs,
    UINT ClearSlots,
    D3D10DDI_HDEPTHSTENCILVIEW,
    const D3D11DDI_HUNORDEREDACCESSVIEW*,
    const UINT*,

    UINT UAVStartSlot,
    UINT NumUAVs,
    UINT UAVRangeStart,
    UINT UAVRangeSize
    );

typedef VOID ( APIENTRY* PFND3D11DDI_SETUNORDEREDACCESSVIEWS )(
    D3D10DDI_HDEVICE, UINT StartSlot, UINT NumViews, const D3D11DDI_HUNORDEREDACCESSVIEW*, const UINT* );

typedef SIZE_T ( APIENTRY* PFND3D11DDI_CALCPRIVATERESOURCESIZE )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATERESOURCE* );

typedef VOID ( APIENTRY* PFND3D11DDI_CREATERESOURCE )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATERESOURCE*, D3D10DDI_HRESOURCE, D3D10DDI_HRTRESOURCE );

typedef SIZE_T ( APIENTRY* PFND3D11DDI_CALCPRIVATESHADERRESOURCEVIEWSIZE )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATESHADERRESOURCEVIEW* );

typedef VOID ( APIENTRY* PFND3D11DDI_CREATESHADERRESOURCEVIEW )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATESHADERRESOURCEVIEW*, D3D10DDI_HSHADERRESOURCEVIEW, D3D10DDI_HRTSHADERRESOURCEVIEW );

typedef SIZE_T ( APIENTRY* PFND3D11DDI_CALCPRIVATEUNORDEREDACCESSVIEWSIZE )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATEUNORDEREDACCESSVIEW* );

typedef VOID ( APIENTRY* PFND3D11DDI_CREATEUNORDEREDACCESSVIEW )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATEUNORDEREDACCESSVIEW*, D3D11DDI_HUNORDEREDACCESSVIEW, D3D11DDI_HRTUNORDEREDACCESSVIEW );

typedef VOID ( APIENTRY* PFND3D11DDI_DESTROYUNORDEREDACCESSVIEW )(
    D3D10DDI_HDEVICE, D3D11DDI_HUNORDEREDACCESSVIEW );

typedef VOID ( APIENTRY* PFND3D11DDI_CLEARUNORDEREDACCESSVIEWUINT )(
    D3D10DDI_HDEVICE, D3D11DDI_HUNORDEREDACCESSVIEW, const UINT[4] );

typedef VOID ( APIENTRY* PFND3D11DDI_CLEARUNORDEREDACCESSVIEWFLOAT )(
    D3D10DDI_HDEVICE, D3D11DDI_HUNORDEREDACCESSVIEW, const FLOAT[4] );

typedef VOID ( APIENTRY* PFND3D11DDI_CREATECOMPUTESHADER )(
    D3D10DDI_HDEVICE, const UINT* pShaderCode, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER );

typedef VOID ( APIENTRY* PFND3D11DDI_DISPATCH )(
    D3D10DDI_HDEVICE, UINT, UINT, UINT );

typedef VOID ( APIENTRY* PFND3D11DDI_DISPATCHINDIRECT )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT );

typedef VOID ( APIENTRY* PFND3D11DDI_SETRESOURCEMINLOD)(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, FLOAT );

typedef SIZE_T ( APIENTRY* PFND3D11DDI_CALCPRIVATEDEPTHSTENCILVIEWSIZE )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATEDEPTHSTENCILVIEW* );

typedef VOID ( APIENTRY* PFND3D11DDI_CREATEDEPTHSTENCILVIEW )(
    D3D10DDI_HDEVICE, const D3D11DDIARG_CREATEDEPTHSTENCILVIEW*, D3D10DDI_HDEPTHSTENCILVIEW, D3D10DDI_HRTDEPTHSTENCILVIEW );

typedef VOID ( APIENTRY* PFND3D11DDI_COPYSTRUCTURECOUNT )(
    D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, D3D11DDI_HUNORDEREDACCESSVIEW );

typedef struct D3D11DDI_DEVICEFUNCS
{

    PFND3D10DDI_RESOURCEUPDATESUBRESOURCEUP pfnDefaultConstantBufferUpdateSubresourceUP;
    PFND3D10DDI_SETCONSTANTBUFFERS pfnVsSetConstantBuffers;
    PFND3D10DDI_SETSHADERRESOURCES pfnPsSetShaderResources;
    PFND3D10DDI_SETSHADER pfnPsSetShader;
    PFND3D10DDI_SETSAMPLERS pfnPsSetSamplers;
    PFND3D10DDI_SETSHADER pfnVsSetShader;
    PFND3D10DDI_DRAWINDEXED pfnDrawIndexed;
    PFND3D10DDI_DRAW pfnDraw;
    PFND3D10DDI_RESOURCEMAP pfnDynamicIABufferMapNoOverwrite;
    PFND3D10DDI_RESOURCEUNMAP pfnDynamicIABufferUnmap;
    PFND3D10DDI_RESOURCEMAP pfnDynamicConstantBufferMapDiscard;
    PFND3D10DDI_RESOURCEMAP pfnDynamicIABufferMapDiscard;
    PFND3D10DDI_RESOURCEUNMAP pfnDynamicConstantBufferUnmap;
    PFND3D10DDI_SETCONSTANTBUFFERS pfnPsSetConstantBuffers;
    PFND3D10DDI_SETINPUTLAYOUT pfnIaSetInputLayout;
    PFND3D10DDI_IA_SETVERTEXBUFFERS pfnIaSetVertexBuffers;
    PFND3D10DDI_IA_SETINDEXBUFFER pfnIaSetIndexBuffer;

    PFND3D10DDI_DRAWINDEXEDINSTANCED pfnDrawIndexedInstanced;
    PFND3D10DDI_DRAWINSTANCED pfnDrawInstanced;
    PFND3D10DDI_RESOURCEMAP pfnDynamicResourceMapDiscard;
    PFND3D10DDI_RESOURCEUNMAP pfnDynamicResourceUnmap;
    PFND3D10DDI_SETCONSTANTBUFFERS pfnGsSetConstantBuffers;
    PFND3D10DDI_SETSHADER pfnGsSetShader;
    PFND3D10DDI_IA_SETTOPOLOGY pfnIaSetTopology;
    PFND3D10DDI_RESOURCEMAP pfnStagingResourceMap;
    PFND3D10DDI_RESOURCEUNMAP pfnStagingResourceUnmap;
    PFND3D10DDI_SETSHADERRESOURCES pfnVsSetShaderResources;
    PFND3D10DDI_SETSAMPLERS pfnVsSetSamplers;
    PFND3D10DDI_SETSHADERRESOURCES pfnGsSetShaderResources;
    PFND3D10DDI_SETSAMPLERS pfnGsSetSamplers;
    PFND3D11DDI_SETRENDERTARGETS pfnSetRenderTargets;
    PFND3D10DDI_SHADERRESOURCEVIEWREADAFTERWRITEHAZARD pfnShaderResourceViewReadAfterWriteHazard;
    PFND3D10DDI_RESOURCEREADAFTERWRITEHAZARD pfnResourceReadAfterWriteHazard;
    PFND3D10DDI_SETBLENDSTATE pfnSetBlendState;
    PFND3D10DDI_SETDEPTHSTENCILSTATE pfnSetDepthStencilState;
    PFND3D10DDI_SETRASTERIZERSTATE pfnSetRasterizerState;
    PFND3D10DDI_QUERYEND pfnQueryEnd;
    PFND3D10DDI_QUERYBEGIN pfnQueryBegin;
    PFND3D10DDI_RESOURCECOPYREGION pfnResourceCopyRegion;
    PFND3D10DDI_RESOURCEUPDATESUBRESOURCEUP pfnResourceUpdateSubresourceUP;
    PFND3D10DDI_SO_SETTARGETS pfnSoSetTargets;
    PFND3D10DDI_DRAWAUTO pfnDrawAuto;
    PFND3D10DDI_SETVIEWPORTS pfnSetViewports;
    PFND3D10DDI_SETSCISSORRECTS pfnSetScissorRects;
    PFND3D10DDI_CLEARRENDERTARGETVIEW pfnClearRenderTargetView;
    PFND3D10DDI_CLEARDEPTHSTENCILVIEW pfnClearDepthStencilView;
    PFND3D10DDI_SETPREDICATION pfnSetPredication;
    PFND3D10DDI_QUERYGETDATA pfnQueryGetData;
    PFND3D10DDI_FLUSH pfnFlush;
    PFND3D10DDI_GENMIPS pfnGenMips;
    PFND3D10DDI_RESOURCECOPY pfnResourceCopy;
    PFND3D10DDI_RESOURCERESOLVESUBRESOURCE pfnResourceResolveSubresource;

    PFND3D10DDI_RESOURCEMAP pfnResourceMap;
    PFND3D10DDI_RESOURCEUNMAP pfnResourceUnmap;
    PFND3D10DDI_RESOURCEISSTAGINGBUSY pfnResourceIsStagingBusy;
    PFND3D11DDI_RELOCATEDEVICEFUNCS pfnRelocateDeviceFuncs;
    PFND3D11DDI_CALCPRIVATERESOURCESIZE pfnCalcPrivateResourceSize;
    PFND3D10DDI_CALCPRIVATEOPENEDRESOURCESIZE pfnCalcPrivateOpenedResourceSize;
    PFND3D11DDI_CREATERESOURCE pfnCreateResource;
    PFND3D10DDI_OPENRESOURCE pfnOpenResource;
    PFND3D10DDI_DESTROYRESOURCE pfnDestroyResource;
    PFND3D11DDI_CALCPRIVATESHADERRESOURCEVIEWSIZE pfnCalcPrivateShaderResourceViewSize;
    PFND3D11DDI_CREATESHADERRESOURCEVIEW pfnCreateShaderResourceView;
    PFND3D10DDI_DESTROYSHADERRESOURCEVIEW pfnDestroyShaderResourceView;
    PFND3D10DDI_CALCPRIVATERENDERTARGETVIEWSIZE pfnCalcPrivateRenderTargetViewSize;
    PFND3D10DDI_CREATERENDERTARGETVIEW pfnCreateRenderTargetView;
    PFND3D10DDI_DESTROYRENDERTARGETVIEW pfnDestroyRenderTargetView;
    PFND3D11DDI_CALCPRIVATEDEPTHSTENCILVIEWSIZE pfnCalcPrivateDepthStencilViewSize;
    PFND3D11DDI_CREATEDEPTHSTENCILVIEW pfnCreateDepthStencilView;
    PFND3D10DDI_DESTROYDEPTHSTENCILVIEW pfnDestroyDepthStencilView;
    PFND3D10DDI_CALCPRIVATEELEMENTLAYOUTSIZE pfnCalcPrivateElementLayoutSize;
    PFND3D10DDI_CREATEELEMENTLAYOUT pfnCreateElementLayout;
    PFND3D10DDI_DESTROYELEMENTLAYOUT pfnDestroyElementLayout;
    PFND3D10_1DDI_CALCPRIVATEBLENDSTATESIZE pfnCalcPrivateBlendStateSize;
    PFND3D10_1DDI_CREATEBLENDSTATE pfnCreateBlendState;
    PFND3D10DDI_DESTROYBLENDSTATE pfnDestroyBlendState;
    PFND3D10DDI_CALCPRIVATEDEPTHSTENCILSTATESIZE pfnCalcPrivateDepthStencilStateSize;
    PFND3D10DDI_CREATEDEPTHSTENCILSTATE pfnCreateDepthStencilState;
    PFND3D10DDI_DESTROYDEPTHSTENCILSTATE pfnDestroyDepthStencilState;
    PFND3D10DDI_CALCPRIVATERASTERIZERSTATESIZE pfnCalcPrivateRasterizerStateSize;
    PFND3D10DDI_CREATERASTERIZERSTATE pfnCreateRasterizerState;
    PFND3D10DDI_DESTROYRASTERIZERSTATE pfnDestroyRasterizerState;
    PFND3D10DDI_CALCPRIVATESHADERSIZE pfnCalcPrivateShaderSize;
    PFND3D10DDI_CREATEVERTEXSHADER pfnCreateVertexShader;
    PFND3D10DDI_CREATEGEOMETRYSHADER pfnCreateGeometryShader;
    PFND3D10DDI_CREATEPIXELSHADER pfnCreatePixelShader;
    PFND3D11DDI_CALCPRIVATEGEOMETRYSHADERWITHSTREAMOUTPUT pfnCalcPrivateGeometryShaderWithStreamOutput;
    PFND3D11DDI_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT pfnCreateGeometryShaderWithStreamOutput;
    PFND3D10DDI_DESTROYSHADER pfnDestroyShader;
    PFND3D10DDI_CALCPRIVATESAMPLERSIZE pfnCalcPrivateSamplerSize;
    PFND3D10DDI_CREATESAMPLER pfnCreateSampler;
    PFND3D10DDI_DESTROYSAMPLER pfnDestroySampler;
    PFND3D10DDI_CALCPRIVATEQUERYSIZE pfnCalcPrivateQuerySize;
    PFND3D10DDI_CREATEQUERY pfnCreateQuery;
    PFND3D10DDI_DESTROYQUERY pfnDestroyQuery;

    PFND3D10DDI_CHECKFORMATSUPPORT pfnCheckFormatSupport;
    PFND3D10DDI_CHECKMULTISAMPLEQUALITYLEVELS pfnCheckMultisampleQualityLevels;
    PFND3D10DDI_CHECKCOUNTERINFO pfnCheckCounterInfo;
    PFND3D10DDI_CHECKCOUNTER pfnCheckCounter;

    PFND3D10DDI_DESTROYDEVICE pfnDestroyDevice;
    PFND3D10DDI_SETTEXTFILTERSIZE pfnSetTextFilterSize;

    PFND3D10DDI_RESOURCECOPY pfnResourceConvert;
    PFND3D10DDI_RESOURCECOPYREGION pfnResourceConvertRegion;

    PFND3D11DDI_DRAWINDEXEDINSTANCEDINDIRECT pfnDrawIndexedInstancedIndirect;
    PFND3D11DDI_DRAWINSTANCEDINDIRECT pfnDrawInstancedIndirect;
    PFND3D11DDI_COMMANDLISTEXECUTE pfnCommandListExecute;
    PFND3D10DDI_SETSHADERRESOURCES pfnHsSetShaderResources;
    PFND3D10DDI_SETSHADER pfnHsSetShader;
    PFND3D10DDI_SETSAMPLERS pfnHsSetSamplers;
    PFND3D10DDI_SETCONSTANTBUFFERS pfnHsSetConstantBuffers;
    PFND3D10DDI_SETSHADERRESOURCES pfnDsSetShaderResources;
    PFND3D10DDI_SETSHADER pfnDsSetShader;
    PFND3D10DDI_SETSAMPLERS pfnDsSetSamplers;
    PFND3D10DDI_SETCONSTANTBUFFERS pfnDsSetConstantBuffers;
    PFND3D11DDI_CREATEHULLSHADER pfnCreateHullShader;
    PFND3D11DDI_CREATEDOMAINSHADER pfnCreateDomainShader;
    PFND3D11DDI_CHECKDEFERREDCONTEXTHANDLESIZES pfnCheckDeferredContextHandleSizes;
    PFND3D11DDI_CALCDEFERREDCONTEXTHANDLESIZE pfnCalcDeferredContextHandleSize;
    PFND3D11DDI_CALCPRIVATEDEFERREDCONTEXTSIZE pfnCalcPrivateDeferredContextSize;
    PFND3D11DDI_CREATEDEFERREDCONTEXT pfnCreateDeferredContext;
    PFND3D11DDI_ABANDONCOMMANDLIST pfnAbandonCommandList;
    PFND3D11DDI_CALCPRIVATECOMMANDLISTSIZE pfnCalcPrivateCommandListSize;
    PFND3D11DDI_CREATECOMMANDLIST pfnCreateCommandList;
    PFND3D11DDI_DESTROYCOMMANDLIST pfnDestroyCommandList;
    PFND3D11DDI_CALCPRIVATETESSELLATIONSHADERSIZE pfnCalcPrivateTessellationShaderSize;
    PFND3D11DDI_SETSHADER_WITH_IFACES pfnPsSetShaderWithIfaces;
    PFND3D11DDI_SETSHADER_WITH_IFACES pfnVsSetShaderWithIfaces;
    PFND3D11DDI_SETSHADER_WITH_IFACES pfnGsSetShaderWithIfaces;
    PFND3D11DDI_SETSHADER_WITH_IFACES pfnHsSetShaderWithIfaces;
    PFND3D11DDI_SETSHADER_WITH_IFACES pfnDsSetShaderWithIfaces;
    PFND3D11DDI_SETSHADER_WITH_IFACES pfnCsSetShaderWithIfaces;
    PFND3D11DDI_CREATECOMPUTESHADER pfnCreateComputeShader;
    PFND3D10DDI_SETSHADER pfnCsSetShader;
    PFND3D10DDI_SETSHADERRESOURCES pfnCsSetShaderResources;
    PFND3D10DDI_SETSAMPLERS pfnCsSetSamplers;
    PFND3D10DDI_SETCONSTANTBUFFERS pfnCsSetConstantBuffers;
    PFND3D11DDI_CALCPRIVATEUNORDEREDACCESSVIEWSIZE pfnCalcPrivateUnorderedAccessViewSize;
    PFND3D11DDI_CREATEUNORDEREDACCESSVIEW pfnCreateUnorderedAccessView;
    PFND3D11DDI_DESTROYUNORDEREDACCESSVIEW pfnDestroyUnorderedAccessView;
    PFND3D11DDI_CLEARUNORDEREDACCESSVIEWUINT pfnClearUnorderedAccessViewUint;
    PFND3D11DDI_CLEARUNORDEREDACCESSVIEWFLOAT pfnClearUnorderedAccessViewFloat;
    PFND3D11DDI_SETUNORDEREDACCESSVIEWS pfnCsSetUnorderedAccessViews;
    PFND3D11DDI_DISPATCH pfnDispatch;
    PFND3D11DDI_DISPATCHINDIRECT pfnDispatchIndirect;
    PFND3D11DDI_SETRESOURCEMINLOD pfnSetResourceMinLOD;
    PFND3D11DDI_COPYSTRUCTURECOUNT pfnCopyStructureCount;

    PFND3D11DDI_RECYCLECOMMANDLIST pfnRecycleCommandList;
    PFND3D11DDI_RECYCLECREATECOMMANDLIST pfnRecycleCreateCommandList;
    PFND3D11DDI_RECYCLECREATEDEFERREDCONTEXT pfnRecycleCreateDeferredContext;
    PFND3D11DDI_DESTROYCOMMANDLIST pfnRecycleDestroyCommandList;

} D3D11DDI_DEVICEFUNCS;

typedef VOID (APIENTRY *PFND3D10DDI_SETERROR_CB)( D3D10DDI_HRTCORELAYER, HRESULT );

typedef void (APIENTRY *PFND3D10DDI_STATE_VS_CONSTBUF_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D10DDI_STATE_PS_SRV_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D10DDI_STATE_PS_SHADER_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_PS_SAMPLER_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D10DDI_STATE_VS_SHADER_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_PS_CONSTBUF_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D10DDI_STATE_IA_INPUTLAYOUT_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_IA_VERTEXBUF_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D10DDI_STATE_IA_INDEXBUF_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_GS_CONSTBUF_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D10DDI_STATE_GS_SHADER_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_IA_PRIMITIVE_TOPOLOGY_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_VS_SRV_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D10DDI_STATE_VS_SAMPLER_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D10DDI_STATE_GS_SRV_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D10DDI_STATE_GS_SAMPLER_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D10DDI_STATE_OM_RENDERTARGETS_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_OM_BLENDSTATE_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_OM_DEPTHSTATE_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_RS_RASTSTATE_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_SO_TARGETS_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_RS_VIEWPORTS_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_RS_SCISSOR_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_STATE_TEXTFILTERSIZE_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D10DDI_DISABLE_DEFERRED_STAGING_RESOURCE_DESTRUCTION_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D11DDI_STATE_HS_SRV_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D11DDI_STATE_HS_SHADER_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D11DDI_STATE_HS_SAMPLER_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D11DDI_STATE_HS_CONSTBUF_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D11DDI_STATE_DS_SRV_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D11DDI_STATE_DS_SHADER_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D11DDI_STATE_DS_SAMPLER_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D11DDI_STATE_DS_CONSTBUF_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D11DDI_PERFORM_AMORTIZED_PROCESSING_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D11DDI_STATE_CS_SRV_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D11DDI_STATE_CS_UAV_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D11DDI_STATE_CS_SHADER_CB)( D3D10DDI_HRTCORELAYER );

typedef void (APIENTRY *PFND3D11DDI_STATE_CS_SAMPLER_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef void (APIENTRY *PFND3D11DDI_STATE_CS_CONSTBUF_CB)( D3D10DDI_HRTCORELAYER, UINT, UINT );

typedef struct D3D10DDI_CORELAYER_DEVICECALLBACKS
{
    PFND3D10DDI_SETERROR_CB pfnSetErrorCb;
    PFND3D10DDI_STATE_VS_CONSTBUF_CB pfnStateVsConstBufCb;
    PFND3D10DDI_STATE_PS_SRV_CB pfnStatePsSrvCb;
    PFND3D10DDI_STATE_PS_SHADER_CB pfnStatePsShaderCb;
    PFND3D10DDI_STATE_PS_SAMPLER_CB pfnStatePsSamplerCb;
    PFND3D10DDI_STATE_VS_SHADER_CB pfnStateVsShaderCb;
    PFND3D10DDI_STATE_PS_CONSTBUF_CB pfnStatePsConstBufCb;
    PFND3D10DDI_STATE_IA_INPUTLAYOUT_CB pfnStateIaInputLayoutCb;
    PFND3D10DDI_STATE_IA_VERTEXBUF_CB pfnStateIaVertexBufCb;
    PFND3D10DDI_STATE_IA_INDEXBUF_CB pfnStateIaIndexBufCb;
    PFND3D10DDI_STATE_GS_CONSTBUF_CB pfnStateGsConstBufCb;
    PFND3D10DDI_STATE_GS_SHADER_CB pfnStateGsShaderCb;
    PFND3D10DDI_STATE_IA_PRIMITIVE_TOPOLOGY_CB pfnStateIaPrimitiveTopologyCb;
    PFND3D10DDI_STATE_VS_SRV_CB pfnStateVsSrvCb;
    PFND3D10DDI_STATE_VS_SAMPLER_CB pfnStateVsSamplerCb;
    PFND3D10DDI_STATE_GS_SRV_CB pfnStateGsSrvCb;
    PFND3D10DDI_STATE_GS_SAMPLER_CB pfnStateGsSamplerCb;
    PFND3D10DDI_STATE_OM_RENDERTARGETS_CB pfnStateOmRenderTargetsCb;
    PFND3D10DDI_STATE_OM_BLENDSTATE_CB pfnStateOmBlendStateCb;
    PFND3D10DDI_STATE_OM_DEPTHSTATE_CB pfnStateOmDepthStateCb;
    PFND3D10DDI_STATE_RS_RASTSTATE_CB pfnStateRsRastStateCb;
    PFND3D10DDI_STATE_SO_TARGETS_CB pfnStateSoTargetsCb;
    PFND3D10DDI_STATE_RS_VIEWPORTS_CB pfnStateRsViewportsCb;
    PFND3D10DDI_STATE_RS_SCISSOR_CB pfnStateRsScissorCb;
    PFND3D10DDI_DISABLE_DEFERRED_STAGING_RESOURCE_DESTRUCTION_CB pfnDisableDeferredStagingResourceDestruction;
    PFND3D10DDI_STATE_TEXTFILTERSIZE_CB pfnStateTextFilterSizeCb;
} D3D10DDI_CORELAYER_DEVICECALLBACKS;

typedef struct D3D11DDI_CORELAYER_DEVICECALLBACKS
{
    PFND3D10DDI_SETERROR_CB pfnSetErrorCb;
    PFND3D10DDI_STATE_VS_CONSTBUF_CB pfnStateVsConstBufCb;
    PFND3D10DDI_STATE_PS_SRV_CB pfnStatePsSrvCb;
    PFND3D10DDI_STATE_PS_SHADER_CB pfnStatePsShaderCb;
    PFND3D10DDI_STATE_PS_SAMPLER_CB pfnStatePsSamplerCb;
    PFND3D10DDI_STATE_VS_SHADER_CB pfnStateVsShaderCb;
    PFND3D10DDI_STATE_PS_CONSTBUF_CB pfnStatePsConstBufCb;
    PFND3D10DDI_STATE_IA_INPUTLAYOUT_CB pfnStateIaInputLayoutCb;
    PFND3D10DDI_STATE_IA_VERTEXBUF_CB pfnStateIaVertexBufCb;
    PFND3D10DDI_STATE_IA_INDEXBUF_CB pfnStateIaIndexBufCb;
    PFND3D10DDI_STATE_GS_CONSTBUF_CB pfnStateGsConstBufCb;
    PFND3D10DDI_STATE_GS_SHADER_CB pfnStateGsShaderCb;
    PFND3D10DDI_STATE_IA_PRIMITIVE_TOPOLOGY_CB pfnStateIaPrimitiveTopologyCb;
    PFND3D10DDI_STATE_VS_SRV_CB pfnStateVsSrvCb;
    PFND3D10DDI_STATE_VS_SAMPLER_CB pfnStateVsSamplerCb;
    PFND3D10DDI_STATE_GS_SRV_CB pfnStateGsSrvCb;
    PFND3D10DDI_STATE_GS_SAMPLER_CB pfnStateGsSamplerCb;
    PFND3D10DDI_STATE_OM_RENDERTARGETS_CB pfnStateOmRenderTargetsCb;
    PFND3D10DDI_STATE_OM_BLENDSTATE_CB pfnStateOmBlendStateCb;
    PFND3D10DDI_STATE_OM_DEPTHSTATE_CB pfnStateOmDepthStateCb;
    PFND3D10DDI_STATE_RS_RASTSTATE_CB pfnStateRsRastStateCb;
    PFND3D10DDI_STATE_SO_TARGETS_CB pfnStateSoTargetsCb;
    PFND3D10DDI_STATE_RS_VIEWPORTS_CB pfnStateRsViewportsCb;
    PFND3D10DDI_STATE_RS_SCISSOR_CB pfnStateRsScissorCb;
    PFND3D10DDI_DISABLE_DEFERRED_STAGING_RESOURCE_DESTRUCTION_CB pfnDisableDeferredStagingResourceDestruction;
    PFND3D10DDI_STATE_TEXTFILTERSIZE_CB pfnStateTextFilterSizeCb;
    PFND3D11DDI_STATE_HS_SRV_CB pfnStateHsSrvCb;
    PFND3D11DDI_STATE_HS_SHADER_CB pfnStateHsShaderCb;
    PFND3D11DDI_STATE_HS_SAMPLER_CB pfnStateHsSamplerCb;
    PFND3D11DDI_STATE_HS_CONSTBUF_CB pfnStateHsConstBufCb;
    PFND3D11DDI_STATE_DS_SRV_CB pfnStateDsSrvCb;
    PFND3D11DDI_STATE_DS_SHADER_CB pfnStateDsShaderCb;
    PFND3D11DDI_STATE_DS_SAMPLER_CB pfnStateDsSamplerCb;
    PFND3D11DDI_STATE_DS_CONSTBUF_CB pfnStateDsConstBufCb;
    PFND3D11DDI_PERFORM_AMORTIZED_PROCESSING_CB pfnPerformAmortizedProcessingCb;
    PFND3D11DDI_STATE_CS_SRV_CB pfnStateCsSrvCb;
    PFND3D11DDI_STATE_CS_UAV_CB pfnStateCsUavCb;
    PFND3D11DDI_STATE_CS_SHADER_CB pfnStateCsShaderCb;
    PFND3D11DDI_STATE_CS_SAMPLER_CB pfnStateCsSamplerCb;
    PFND3D11DDI_STATE_CS_CONSTBUF_CB pfnStateCsConstBufCb;
} D3D11DDI_CORELAYER_DEVICECALLBACKS;

#define D3D11_DDI_MAJOR_VERSION 11
#define D3D11_0_DDI_MINOR_VERSION 10
#define D3D11_0_DDI_INTERFACE_VERSION ((D3D11_DDI_MAJOR_VERSION << 16) | D3D11_0_DDI_MINOR_VERSION)
#define D3D11_0_DDI_BUILD_VERSION 2
#define D3D11_0_DDI_SUPPORTED ((((UINT64)D3D11_0_DDI_INTERFACE_VERSION) << 32) | (((UINT64)D3D11_0_DDI_BUILD_VERSION) << 16))

#define D3D11_0_7_DDI_MINOR_VERSION 11
#define D3D11_0_7_DDI_INTERFACE_VERSION ((D3D11_DDI_MAJOR_VERSION << 16) | D3D11_0_7_DDI_MINOR_VERSION)
#define D3D11_0_7_DDI_BUILD_VERSION 2
#define D3D11_0_7_DDI_SUPPORTED ((((UINT64)D3D11_0_7_DDI_INTERFACE_VERSION) << 32) | (((UINT64)D3D11_0_7_DDI_BUILD_VERSION) << 16))

struct D3D10DDIARG_CALCPRIVATEDEVICESIZE
{
    UINT Interface;
    UINT Version;
    UINT Flags;
};

typedef HRESULT (APIENTRY *PFND3D10DDI_RETRIEVESUBOBJECT)(D3D10DDI_HDEVICE, UINT, SIZE_T, void **);

struct D3D10DDIARG_CREATEDEVICE
{
    D3D10DDI_HRTDEVICE hRTDevice;
    UINT Interface;
    UINT Version;
    const D3DDDI_DEVICECALLBACKS *pKTCallbacks;
    union
    {
        D3D10DDI_DEVICEFUNCS *pDeviceFuncs;
        D3D10_1DDI_DEVICEFUNCS *p10_1DeviceFuncs;
        D3D11DDI_DEVICEFUNCS *p11DeviceFuncs;
    };
    D3D10DDI_HDEVICE hDrvDevice;
    DXGI_DDI_BASE_ARGS DXGIBaseDDI;
    D3D10DDI_HRTCORELAYER hRTCoreLayer;
    union
    {
        const D3D10DDI_CORELAYER_DEVICECALLBACKS *pUMCallbacks;
        const D3D11DDI_CORELAYER_DEVICECALLBACKS *p11UMCallbacks;
    };
    UINT Flags;
    PFND3D10DDI_RETRIEVESUBOBJECT *ppfnRetrieveSubObject;
};
