/*
 * PROJECT:     ReactOS SDK
 * LICENSE:     GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later)
 * PURPOSE:     Direct3D 10 tokenized shader program declarations
 * COPYRIGHT:   Copyright 2026 Ahmed ARIF <arif193@gmail.com>
 *
 * The numeric protocol declarations below are derived from the public DXBC
 * format and the MIT/Apache-2.0 winapi 0.3.9 projection.  This is the D3D10
 * subset consumed by user-mode display drivers.
 */

#pragma once

typedef enum D3D10_SB_TOKENIZED_PROGRAM_TYPE
{
    D3D10_SB_PIXEL_SHADER = 0,
    D3D10_SB_VERTEX_SHADER = 1,
    D3D10_SB_GEOMETRY_SHADER = 2,
} D3D10_SB_TOKENIZED_PROGRAM_TYPE;

typedef enum D3D10_SB_OPCODE_TYPE
{
    D3D10_SB_OPCODE_ADD = 0,
    D3D10_SB_OPCODE_AND,
    D3D10_SB_OPCODE_BREAK,
    D3D10_SB_OPCODE_BREAKC,
    D3D10_SB_OPCODE_CALL,
    D3D10_SB_OPCODE_CALLC,
    D3D10_SB_OPCODE_CASE,
    D3D10_SB_OPCODE_CONTINUE,
    D3D10_SB_OPCODE_CONTINUEC,
    D3D10_SB_OPCODE_CUT,
    D3D10_SB_OPCODE_DEFAULT,
    D3D10_SB_OPCODE_DERIV_RTX,
    D3D10_SB_OPCODE_DERIV_RTY,
    D3D10_SB_OPCODE_DISCARD,
    D3D10_SB_OPCODE_DIV,
    D3D10_SB_OPCODE_DP2,
    D3D10_SB_OPCODE_DP3,
    D3D10_SB_OPCODE_DP4,
    D3D10_SB_OPCODE_ELSE,
    D3D10_SB_OPCODE_EMIT,
    D3D10_SB_OPCODE_EMITTHENCUT,
    D3D10_SB_OPCODE_ENDIF,
    D3D10_SB_OPCODE_ENDLOOP,
    D3D10_SB_OPCODE_ENDSWITCH,
    D3D10_SB_OPCODE_EQ,
    D3D10_SB_OPCODE_EXP,
    D3D10_SB_OPCODE_FRC,
    D3D10_SB_OPCODE_FTOI,
    D3D10_SB_OPCODE_FTOU,
    D3D10_SB_OPCODE_GE,
    D3D10_SB_OPCODE_IADD,
    D3D10_SB_OPCODE_IF,
    D3D10_SB_OPCODE_IEQ,
    D3D10_SB_OPCODE_IGE,
    D3D10_SB_OPCODE_ILT,
    D3D10_SB_OPCODE_IMAD,
    D3D10_SB_OPCODE_IMAX,
    D3D10_SB_OPCODE_IMIN,
    D3D10_SB_OPCODE_IMUL,
    D3D10_SB_OPCODE_INE,
    D3D10_SB_OPCODE_INEG,
    D3D10_SB_OPCODE_ISHL,
    D3D10_SB_OPCODE_ISHR,
    D3D10_SB_OPCODE_ITOF,
    D3D10_SB_OPCODE_LABEL,
    D3D10_SB_OPCODE_LD,
    D3D10_SB_OPCODE_LD_MS,
    D3D10_SB_OPCODE_LOG,
    D3D10_SB_OPCODE_LOOP,
    D3D10_SB_OPCODE_LT,
    D3D10_SB_OPCODE_MAD,
    D3D10_SB_OPCODE_MIN,
    D3D10_SB_OPCODE_MAX,
    D3D10_SB_OPCODE_CUSTOMDATA,
    D3D10_SB_OPCODE_MOV,
    D3D10_SB_OPCODE_MOVC,
    D3D10_SB_OPCODE_MUL,
    D3D10_SB_OPCODE_NE,
    D3D10_SB_OPCODE_NOP,
    D3D10_SB_OPCODE_NOT,
    D3D10_SB_OPCODE_OR,
    D3D10_SB_OPCODE_RESINFO,
    D3D10_SB_OPCODE_RET,
    D3D10_SB_OPCODE_RETC,
    D3D10_SB_OPCODE_ROUND_NE,
    D3D10_SB_OPCODE_ROUND_NI,
    D3D10_SB_OPCODE_ROUND_PI,
    D3D10_SB_OPCODE_ROUND_Z,
    D3D10_SB_OPCODE_RSQ,
    D3D10_SB_OPCODE_SAMPLE,
    D3D10_SB_OPCODE_SAMPLE_C,
    D3D10_SB_OPCODE_SAMPLE_C_LZ,
    D3D10_SB_OPCODE_SAMPLE_L,
    D3D10_SB_OPCODE_SAMPLE_D,
    D3D10_SB_OPCODE_SAMPLE_B,
    D3D10_SB_OPCODE_SQRT,
    D3D10_SB_OPCODE_SWITCH,
    D3D10_SB_OPCODE_SINCOS,
    D3D10_SB_OPCODE_UDIV,
    D3D10_SB_OPCODE_ULT,
    D3D10_SB_OPCODE_UGE,
    D3D10_SB_OPCODE_UMUL,
    D3D10_SB_OPCODE_UMAD,
    D3D10_SB_OPCODE_UMAX,
    D3D10_SB_OPCODE_UMIN,
    D3D10_SB_OPCODE_USHR,
    D3D10_SB_OPCODE_UTOF,
    D3D10_SB_OPCODE_XOR,
    D3D10_SB_OPCODE_DCL_RESOURCE,
    D3D10_SB_OPCODE_DCL_CONSTANT_BUFFER,
    D3D10_SB_OPCODE_DCL_SAMPLER,
    D3D10_SB_OPCODE_DCL_INDEX_RANGE,
    D3D10_SB_OPCODE_DCL_GS_OUTPUT_PRIMITIVE_TOPOLOGY,
    D3D10_SB_OPCODE_DCL_GS_INPUT_PRIMITIVE,
    D3D10_SB_OPCODE_DCL_MAX_OUTPUT_VERTEX_COUNT,
    D3D10_SB_OPCODE_DCL_INPUT,
    D3D10_SB_OPCODE_DCL_INPUT_SGV,
    D3D10_SB_OPCODE_DCL_INPUT_SIV,
    D3D10_SB_OPCODE_DCL_INPUT_PS,
    D3D10_SB_OPCODE_DCL_INPUT_PS_SGV,
    D3D10_SB_OPCODE_DCL_INPUT_PS_SIV,
    D3D10_SB_OPCODE_DCL_OUTPUT,
    D3D10_SB_OPCODE_DCL_OUTPUT_SGV,
    D3D10_SB_OPCODE_DCL_OUTPUT_SIV,
    D3D10_SB_OPCODE_DCL_TEMPS,
    D3D10_SB_OPCODE_DCL_INDEXABLE_TEMP,
    D3D10_SB_OPCODE_DCL_GLOBAL_FLAGS,
    D3D10_SB_OPCODE_RESERVED0,
    D3D10_1_SB_OPCODE_LOD,
    D3D10_1_SB_OPCODE_GATHER4,
    D3D10_1_SB_OPCODE_SAMPLE_POS,
    D3D10_1_SB_OPCODE_SAMPLE_INFO,
    D3D10_SB_NUM_OPCODES,
} D3D10_SB_OPCODE_TYPE;

typedef enum D3D10_SB_RESINFO_INSTRUCTION_RETURN_TYPE
{
    D3D10_SB_RESINFO_INSTRUCTION_RETURN_FLOAT = 0,
    D3D10_SB_RESINFO_INSTRUCTION_RETURN_RCPFLOAT = 1,
    D3D10_SB_RESINFO_INSTRUCTION_RETURN_UINT = 2,
} D3D10_SB_RESINFO_INSTRUCTION_RETURN_TYPE;

typedef enum D3D10_SB_INSTRUCTION_TEST_BOOLEAN
{
    D3D10_SB_INSTRUCTION_TEST_ZERO = 0,
    D3D10_SB_INSTRUCTION_TEST_NONZERO = 1,
} D3D10_SB_INSTRUCTION_TEST_BOOLEAN;

typedef enum D3D10_SB_EXTENDED_OPCODE_TYPE
{
    D3D10_SB_EXTENDED_OPCODE_EMPTY = 0,
    D3D10_SB_EXTENDED_OPCODE_SAMPLE_CONTROLS = 1,
} D3D10_SB_EXTENDED_OPCODE_TYPE;

typedef enum D3D10_SB_IMMEDIATE_ADDRESS_OFFSET_COORD
{
    D3D10_SB_IMMEDIATE_ADDRESS_OFFSET_U = 0,
    D3D10_SB_IMMEDIATE_ADDRESS_OFFSET_V = 1,
    D3D10_SB_IMMEDIATE_ADDRESS_OFFSET_W = 2,
} D3D10_SB_IMMEDIATE_ADDRESS_OFFSET_COORD;

typedef enum D3D10_SB_CUSTOMDATA_CLASS
{
    D3D10_SB_CUSTOMDATA_COMMENT = 0,
    D3D10_SB_CUSTOMDATA_DEBUGINFO,
    D3D10_SB_CUSTOMDATA_OPAQUE,
    D3D10_SB_CUSTOMDATA_DCL_IMMEDIATE_CONSTANT_BUFFER,
} D3D10_SB_CUSTOMDATA_CLASS;

typedef enum D3D10_SB_OPERAND_NUM_COMPONENTS
{
    D3D10_SB_OPERAND_0_COMPONENT = 0,
    D3D10_SB_OPERAND_1_COMPONENT = 1,
    D3D10_SB_OPERAND_4_COMPONENT = 2,
    D3D10_SB_OPERAND_N_COMPONENT = 3,
} D3D10_SB_OPERAND_NUM_COMPONENTS;

typedef enum D3D10_SB_OPERAND_4_COMPONENT_SELECTION_MODE
{
    D3D10_SB_OPERAND_4_COMPONENT_MASK_MODE = 0,
    D3D10_SB_OPERAND_4_COMPONENT_SWIZZLE_MODE = 1,
    D3D10_SB_OPERAND_4_COMPONENT_SELECT_1_MODE = 2,
} D3D10_SB_OPERAND_4_COMPONENT_SELECTION_MODE;

typedef enum D3D10_SB_4_COMPONENT_NAME
{
    D3D10_SB_4_COMPONENT_X = 0,
    D3D10_SB_4_COMPONENT_Y = 1,
    D3D10_SB_4_COMPONENT_Z = 2,
    D3D10_SB_4_COMPONENT_W = 3,
    D3D10_SB_4_COMPONENT_R = 0,
    D3D10_SB_4_COMPONENT_G = 1,
    D3D10_SB_4_COMPONENT_B = 2,
    D3D10_SB_4_COMPONENT_A = 3,
} D3D10_SB_4_COMPONENT_NAME;

typedef enum D3D10_SB_OPERAND_TYPE
{
    D3D10_SB_OPERAND_TYPE_TEMP = 0,
    D3D10_SB_OPERAND_TYPE_INPUT,
    D3D10_SB_OPERAND_TYPE_OUTPUT,
    D3D10_SB_OPERAND_TYPE_INDEXABLE_TEMP,
    D3D10_SB_OPERAND_TYPE_IMMEDIATE32,
    D3D10_SB_OPERAND_TYPE_IMMEDIATE64,
    D3D10_SB_OPERAND_TYPE_SAMPLER,
    D3D10_SB_OPERAND_TYPE_RESOURCE,
    D3D10_SB_OPERAND_TYPE_CONSTANT_BUFFER,
    D3D10_SB_OPERAND_TYPE_IMMEDIATE_CONSTANT_BUFFER,
    D3D10_SB_OPERAND_TYPE_LABEL,
    D3D10_SB_OPERAND_TYPE_INPUT_PRIMITIVEID,
    D3D10_SB_OPERAND_TYPE_OUTPUT_DEPTH,
    D3D10_SB_OPERAND_TYPE_NULL,
    D3D10_SB_OPERAND_TYPE_RASTERIZER,
    D3D10_SB_OPERAND_TYPE_OUTPUT_COVERAGE_MASK,
} D3D10_SB_OPERAND_TYPE;

typedef enum D3D10_SB_OPERAND_INDEX_DIMENSION
{
    D3D10_SB_OPERAND_INDEX_0D = 0,
    D3D10_SB_OPERAND_INDEX_1D,
    D3D10_SB_OPERAND_INDEX_2D,
    D3D10_SB_OPERAND_INDEX_3D,
} D3D10_SB_OPERAND_INDEX_DIMENSION;

typedef enum D3D10_SB_OPERAND_INDEX_REPRESENTATION
{
    D3D10_SB_OPERAND_INDEX_IMMEDIATE32 = 0,
    D3D10_SB_OPERAND_INDEX_IMMEDIATE64,
    D3D10_SB_OPERAND_INDEX_RELATIVE,
    D3D10_SB_OPERAND_INDEX_IMMEDIATE32_PLUS_RELATIVE,
    D3D10_SB_OPERAND_INDEX_IMMEDIATE64_PLUS_RELATIVE,
} D3D10_SB_OPERAND_INDEX_REPRESENTATION;

typedef enum D3D10_SB_EXTENDED_OPERAND_TYPE
{
    D3D10_SB_EXTENDED_OPERAND_EMPTY = 0,
    D3D10_SB_EXTENDED_OPERAND_MODIFIER = 1,
} D3D10_SB_EXTENDED_OPERAND_TYPE;

typedef enum D3D10_SB_OPERAND_MODIFIER
{
    D3D10_SB_OPERAND_MODIFIER_NONE = 0,
    D3D10_SB_OPERAND_MODIFIER_NEG,
    D3D10_SB_OPERAND_MODIFIER_ABS,
    D3D10_SB_OPERAND_MODIFIER_ABSNEG,
} D3D10_SB_OPERAND_MODIFIER;

typedef enum D3D10_SB_SAMPLER_MODE
{
    D3D10_SB_SAMPLER_MODE_DEFAULT = 0,
    D3D10_SB_SAMPLER_MODE_COMPARISON,
    D3D10_SB_SAMPLER_MODE_MONO,
} D3D10_SB_SAMPLER_MODE;

typedef enum D3D10_SB_CONSTANT_BUFFER_ACCESS_PATTERN
{
    D3D10_SB_CONSTANT_BUFFER_IMMEDIATE_INDEXED = 0,
    D3D10_SB_CONSTANT_BUFFER_DYNAMIC_INDEXED = 1,
} D3D10_SB_CONSTANT_BUFFER_ACCESS_PATTERN;

typedef enum D3D10_SB_INTERPOLATION_MODE
{
    D3D10_SB_INTERPOLATION_UNDEFINED = 0,
    D3D10_SB_INTERPOLATION_CONSTANT,
    D3D10_SB_INTERPOLATION_LINEAR,
    D3D10_SB_INTERPOLATION_LINEAR_CENTROID,
    D3D10_SB_INTERPOLATION_LINEAR_NOPERSPECTIVE,
    D3D10_SB_INTERPOLATION_LINEAR_NOPERSPECTIVE_CENTROID,
    D3D10_SB_INTERPOLATION_LINEAR_SAMPLE,
    D3D10_SB_INTERPOLATION_LINEAR_NOPERSPECTIVE_SAMPLE,
} D3D10_SB_INTERPOLATION_MODE;

typedef enum D3D10_SB_PRIMITIVE_TOPOLOGY
{
    D3D10_SB_PRIMITIVE_TOPOLOGY_UNDEFINED = 0,
    D3D10_SB_PRIMITIVE_TOPOLOGY_POINTLIST = 1,
    D3D10_SB_PRIMITIVE_TOPOLOGY_LINELIST = 2,
    D3D10_SB_PRIMITIVE_TOPOLOGY_LINESTRIP = 3,
    D3D10_SB_PRIMITIVE_TOPOLOGY_TRIANGLELIST = 4,
    D3D10_SB_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = 5,
    D3D10_SB_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = 10,
    D3D10_SB_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = 11,
    D3D10_SB_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = 12,
    D3D10_SB_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = 13,
} D3D10_SB_PRIMITIVE_TOPOLOGY;

typedef enum D3D10_SB_PRIMITIVE
{
    D3D10_SB_PRIMITIVE_UNDEFINED = 0,
    D3D10_SB_PRIMITIVE_POINT = 1,
    D3D10_SB_PRIMITIVE_LINE = 2,
    D3D10_SB_PRIMITIVE_TRIANGLE = 3,
    D3D10_SB_PRIMITIVE_LINE_ADJ = 6,
    D3D10_SB_PRIMITIVE_TRIANGLE_ADJ = 7,
} D3D10_SB_PRIMITIVE;

typedef enum D3D10_SB_NAME
{
    D3D10_SB_NAME_UNDEFINED = 0,
    D3D10_SB_NAME_POSITION,
    D3D10_SB_NAME_CLIP_DISTANCE,
    D3D10_SB_NAME_CULL_DISTANCE,
    D3D10_SB_NAME_RENDER_TARGET_ARRAY_INDEX,
    D3D10_SB_NAME_VIEWPORT_ARRAY_INDEX,
    D3D10_SB_NAME_VERTEX_ID,
    D3D10_SB_NAME_PRIMITIVE_ID,
    D3D10_SB_NAME_INSTANCE_ID,
    D3D10_SB_NAME_IS_FRONT_FACE,
    D3D10_SB_NAME_SAMPLE_INDEX,
    D3D11_SB_NAME_FINAL_QUAD_U_EQ_0_EDGE_TESSFACTOR = 11,
    D3D11_SB_NAME_FINAL_QUAD_V_EQ_0_EDGE_TESSFACTOR = 12,
    D3D11_SB_NAME_FINAL_QUAD_U_EQ_1_EDGE_TESSFACTOR = 13,
    D3D11_SB_NAME_FINAL_QUAD_V_EQ_1_EDGE_TESSFACTOR = 14,
    D3D11_SB_NAME_FINAL_QUAD_U_INSIDE_TESSFACTOR = 15,
    D3D11_SB_NAME_FINAL_QUAD_V_INSIDE_TESSFACTOR = 16,
    D3D11_SB_NAME_FINAL_TRI_U_EQ_0_EDGE_TESSFACTOR = 17,
    D3D11_SB_NAME_FINAL_TRI_V_EQ_0_EDGE_TESSFACTOR = 18,
    D3D11_SB_NAME_FINAL_TRI_W_EQ_0_EDGE_TESSFACTOR = 19,
    D3D11_SB_NAME_FINAL_TRI_INSIDE_TESSFACTOR = 20,
    D3D11_SB_NAME_FINAL_LINE_DETAIL_TESSFACTOR = 21,
    D3D11_SB_NAME_FINAL_LINE_DENSITY_TESSFACTOR = 22,
} D3D10_SB_NAME;

typedef enum D3D10_SB_RESOURCE_DIMENSION
{
    D3D10_SB_RESOURCE_DIMENSION_UNKNOWN = 0,
    D3D10_SB_RESOURCE_DIMENSION_BUFFER,
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE1D,
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE2D,
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE2DMS,
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE3D,
    D3D10_SB_RESOURCE_DIMENSION_TEXTURECUBE,
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE1DARRAY,
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE2DARRAY,
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE2DMSARRAY,
    D3D10_SB_RESOURCE_DIMENSION_TEXTURECUBEARRAY,
} D3D10_SB_RESOURCE_DIMENSION;

typedef enum D3D10_SB_RESOURCE_RETURN_TYPE
{
    D3D10_SB_RETURN_TYPE_UNORM = 1,
    D3D10_SB_RETURN_TYPE_SNORM,
    D3D10_SB_RETURN_TYPE_SINT,
    D3D10_SB_RETURN_TYPE_UINT,
    D3D10_SB_RETURN_TYPE_FLOAT,
    D3D10_SB_RETURN_TYPE_MIXED,
} D3D10_SB_RESOURCE_RETURN_TYPE;

#define D3D10_SB_TOKENIZED_PROGRAM_TYPE_MASK 0xffff0000u
#define D3D10_SB_TOKENIZED_PROGRAM_TYPE_SHIFT 16
#define D3D10_SB_TOKENIZED_PROGRAM_MAJOR_VERSION_MASK 0x000000f0u
#define D3D10_SB_TOKENIZED_PROGRAM_MAJOR_VERSION_SHIFT 4
#define D3D10_SB_TOKENIZED_PROGRAM_MINOR_VERSION_MASK 0x0000000fu
#define DECODE_D3D10_SB_TOKENIZED_PROGRAM_TYPE(t) ((D3D10_SB_TOKENIZED_PROGRAM_TYPE)(((t) & D3D10_SB_TOKENIZED_PROGRAM_TYPE_MASK) >> D3D10_SB_TOKENIZED_PROGRAM_TYPE_SHIFT))
#define DECODE_D3D10_SB_TOKENIZED_PROGRAM_MAJOR_VERSION(t) (((t) & D3D10_SB_TOKENIZED_PROGRAM_MAJOR_VERSION_MASK) >> D3D10_SB_TOKENIZED_PROGRAM_MAJOR_VERSION_SHIFT)
#define DECODE_D3D10_SB_TOKENIZED_PROGRAM_MINOR_VERSION(t) ((t) & D3D10_SB_TOKENIZED_PROGRAM_MINOR_VERSION_MASK)
#define DECODE_D3D10_SB_TOKENIZED_PROGRAM_LENGTH(t) (t)

#define D3D10_SB_OPCODE_TYPE_MASK 0x000007ffu
#define DECODE_D3D10_SB_OPCODE_TYPE(t) ((D3D10_SB_OPCODE_TYPE)((t) & D3D10_SB_OPCODE_TYPE_MASK))
#define D3D10_SB_TOKENIZED_INSTRUCTION_LENGTH_MASK 0x7f000000u
#define D3D10_SB_TOKENIZED_INSTRUCTION_LENGTH_SHIFT 24
#define DECODE_D3D10_SB_TOKENIZED_INSTRUCTION_LENGTH(t) (((t) & D3D10_SB_TOKENIZED_INSTRUCTION_LENGTH_MASK) >> D3D10_SB_TOKENIZED_INSTRUCTION_LENGTH_SHIFT)

#define D3D10_SB_INSTRUCTION_SATURATE_MASK 0x00002000u
#define DECODE_IS_D3D10_SB_INSTRUCTION_SATURATE_ENABLED(t) ((t) & D3D10_SB_INSTRUCTION_SATURATE_MASK)
#define D3D10_SB_INSTRUCTION_TEST_BOOLEAN_MASK 0x00040000u
#define D3D10_SB_INSTRUCTION_TEST_BOOLEAN_SHIFT 18
#define DECODE_D3D10_SB_INSTRUCTION_TEST_BOOLEAN(t) ((D3D10_SB_INSTRUCTION_TEST_BOOLEAN)(((t) & D3D10_SB_INSTRUCTION_TEST_BOOLEAN_MASK) >> D3D10_SB_INSTRUCTION_TEST_BOOLEAN_SHIFT))
#define D3D10_SB_RESINFO_INSTRUCTION_RETURN_TYPE_MASK 0x00001800u
#define D3D10_SB_RESINFO_INSTRUCTION_RETURN_TYPE_SHIFT 11
#define DECODE_D3D10_SB_RESINFO_INSTRUCTION_RETURN_TYPE(t) ((D3D10_SB_RESINFO_INSTRUCTION_RETURN_TYPE)(((t) & D3D10_SB_RESINFO_INSTRUCTION_RETURN_TYPE_MASK) >> D3D10_SB_RESINFO_INSTRUCTION_RETURN_TYPE_SHIFT))

#define D3D10_SB_OPCODE_EXTENDED_MASK 0x80000000u
#define D3D10_SB_OPCODE_EXTENDED_SHIFT 31
#define DECODE_IS_D3D10_SB_OPCODE_EXTENDED(t) (((t) & D3D10_SB_OPCODE_EXTENDED_MASK) >> D3D10_SB_OPCODE_EXTENDED_SHIFT)
#define D3D10_SB_EXTENDED_OPCODE_TYPE_MASK 0x0000003fu
#define DECODE_D3D10_SB_EXTENDED_OPCODE_TYPE(t) ((D3D10_SB_EXTENDED_OPCODE_TYPE)((t) & D3D10_SB_EXTENDED_OPCODE_TYPE_MASK))

#define D3D10_SB_IMMEDIATE_ADDRESS_OFFSET_COORD_MASK 3u
#define D3D10_SB_IMMEDIATE_ADDRESS_OFFSET_SHIFT(c) (9u + 4u * ((c) & D3D10_SB_IMMEDIATE_ADDRESS_OFFSET_COORD_MASK))
#define D3D10_SB_IMMEDIATE_ADDRESS_OFFSET_MASK(c) (0x0fu << D3D10_SB_IMMEDIATE_ADDRESS_OFFSET_SHIFT(c))
#define DECODE_IMMEDIATE_D3D10_SB_ADDRESS_OFFSET(c, t) (((t) & D3D10_SB_IMMEDIATE_ADDRESS_OFFSET_MASK(c)) >> D3D10_SB_IMMEDIATE_ADDRESS_OFFSET_SHIFT(c))

#define D3D10_SB_CUSTOMDATA_CLASS_MASK 0xfffff800u
#define D3D10_SB_CUSTOMDATA_CLASS_SHIFT 11
#define DECODE_D3D10_SB_CUSTOMDATA_CLASS(t) ((D3D10_SB_CUSTOMDATA_CLASS)(((t) & D3D10_SB_CUSTOMDATA_CLASS_MASK) >> D3D10_SB_CUSTOMDATA_CLASS_SHIFT))

#define D3D10_SB_OPERAND_NUM_COMPONENTS_MASK 0x00000003u
#define DECODE_D3D10_SB_OPERAND_NUM_COMPONENTS(t) ((D3D10_SB_OPERAND_NUM_COMPONENTS)((t) & D3D10_SB_OPERAND_NUM_COMPONENTS_MASK))
#define D3D10_SB_OPERAND_4_COMPONENT_SELECTION_MODE_MASK 0x0000000cu
#define D3D10_SB_OPERAND_4_COMPONENT_SELECTION_MODE_SHIFT 2
#define DECODE_D3D10_SB_OPERAND_4_COMPONENT_SELECTION_MODE(t) ((D3D10_SB_OPERAND_4_COMPONENT_SELECTION_MODE)(((t) & D3D10_SB_OPERAND_4_COMPONENT_SELECTION_MODE_MASK) >> D3D10_SB_OPERAND_4_COMPONENT_SELECTION_MODE_SHIFT))

#define D3D10_SB_4_COMPONENT_NAME_MASK 3u
#define D3D10_SB_OPERAND_4_COMPONENT_MASK_MASK 0x000000f0u
#define D3D10_SB_OPERAND_4_COMPONENT_MASK_SHIFT 4
#define D3D10_SB_OPERAND_4_COMPONENT_MASK_X 0x00000010u
#define D3D10_SB_OPERAND_4_COMPONENT_MASK_Y 0x00000020u
#define D3D10_SB_OPERAND_4_COMPONENT_MASK_Z 0x00000040u
#define D3D10_SB_OPERAND_4_COMPONENT_MASK_W 0x00000080u
#define DECODE_D3D10_SB_OPERAND_4_COMPONENT_MASK(t) ((t) & D3D10_SB_OPERAND_4_COMPONENT_MASK_MASK)
#define D3D10_SB_OPERAND_4_COMPONENT_SWIZZLE_SHIFT 4
#define DECODE_D3D10_SB_OPERAND_4_COMPONENT_SWIZZLE_SOURCE(t, c) ((D3D10_SB_4_COMPONENT_NAME)(((t) >> (D3D10_SB_OPERAND_4_COMPONENT_SWIZZLE_SHIFT + 2u * ((c) & D3D10_SB_4_COMPONENT_NAME_MASK))) & D3D10_SB_4_COMPONENT_NAME_MASK))
#define D3D10_SB_OPERAND_4_COMPONENT_SELECT_1_MASK 0x00000030u
#define D3D10_SB_OPERAND_4_COMPONENT_SELECT_1_SHIFT 4
#define DECODE_D3D10_SB_OPERAND_4_COMPONENT_SELECT_1(t) ((D3D10_SB_4_COMPONENT_NAME)(((t) & D3D10_SB_OPERAND_4_COMPONENT_SELECT_1_MASK) >> D3D10_SB_OPERAND_4_COMPONENT_SELECT_1_SHIFT))

#define D3D10_SB_OPERAND_TYPE_MASK 0x000ff000u
#define D3D10_SB_OPERAND_TYPE_SHIFT 12
#define DECODE_D3D10_SB_OPERAND_TYPE(t) ((D3D10_SB_OPERAND_TYPE)(((t) & D3D10_SB_OPERAND_TYPE_MASK) >> D3D10_SB_OPERAND_TYPE_SHIFT))
#define D3D10_SB_OPERAND_INDEX_DIMENSION_MASK 0x00300000u
#define D3D10_SB_OPERAND_INDEX_DIMENSION_SHIFT 20
#define DECODE_D3D10_SB_OPERAND_INDEX_DIMENSION(t) ((D3D10_SB_OPERAND_INDEX_DIMENSION)(((t) & D3D10_SB_OPERAND_INDEX_DIMENSION_MASK) >> D3D10_SB_OPERAND_INDEX_DIMENSION_SHIFT))
#define D3D10_SB_OPERAND_INDEX_REPRESENTATION_SHIFT(d) (22u + 3u * ((d) & 3u))
#define D3D10_SB_OPERAND_INDEX_REPRESENTATION_MASK(d) (0x3u << D3D10_SB_OPERAND_INDEX_REPRESENTATION_SHIFT(d))
#define DECODE_D3D10_SB_OPERAND_INDEX_REPRESENTATION(d, t) ((D3D10_SB_OPERAND_INDEX_REPRESENTATION)(((t) & D3D10_SB_OPERAND_INDEX_REPRESENTATION_MASK(d)) >> D3D10_SB_OPERAND_INDEX_REPRESENTATION_SHIFT(d)))

#define D3D10_SB_OPERAND_EXTENDED_MASK 0x80000000u
#define D3D10_SB_OPERAND_EXTENDED_SHIFT 31
#define DECODE_IS_D3D10_SB_OPERAND_EXTENDED(t) (((t) & D3D10_SB_OPERAND_EXTENDED_MASK) >> D3D10_SB_OPERAND_EXTENDED_SHIFT)
#define D3D10_SB_EXTENDED_OPERAND_TYPE_MASK 0x0000003fu
#define DECODE_D3D10_SB_EXTENDED_OPERAND_TYPE(t) ((D3D10_SB_EXTENDED_OPERAND_TYPE)((t) & D3D10_SB_EXTENDED_OPERAND_TYPE_MASK))
#define D3D10_SB_OPERAND_MODIFIER_MASK 0x00003fc0u
#define D3D10_SB_OPERAND_MODIFIER_SHIFT 6
#define DECODE_D3D10_SB_OPERAND_MODIFIER(t) ((D3D10_SB_OPERAND_MODIFIER)(((t) & D3D10_SB_OPERAND_MODIFIER_MASK) >> D3D10_SB_OPERAND_MODIFIER_SHIFT))
#define D3D10_SB_OPERAND_DOUBLE_EXTENDED_MASK 0x80000000u
#define D3D10_SB_OPERAND_DOUBLE_EXTENDED_SHIFT 31
#define DECODE_IS_D3D10_SB_OPERAND_DOUBLE_EXTENDED(t) (((t) & D3D10_SB_OPERAND_DOUBLE_EXTENDED_MASK) >> D3D10_SB_OPERAND_DOUBLE_EXTENDED_SHIFT)

#define D3D10_SB_NAME_MASK 0x0000ffffu
#define DECODE_D3D10_SB_NAME(t) ((D3D10_SB_NAME)((t) & D3D10_SB_NAME_MASK))
#define D3D10_SB_GLOBAL_FLAGS_MASK 0x00fff800u
#define DECODE_D3D10_SB_GLOBAL_FLAGS(t) ((t) & D3D10_SB_GLOBAL_FLAGS_MASK)
#define D3D10_SB_RESOURCE_DIMENSION_MASK 0x0000f800u
#define D3D10_SB_RESOURCE_DIMENSION_SHIFT 11
#define DECODE_D3D10_SB_RESOURCE_DIMENSION(t) ((D3D10_SB_RESOURCE_DIMENSION)(((t) & D3D10_SB_RESOURCE_DIMENSION_MASK) >> D3D10_SB_RESOURCE_DIMENSION_SHIFT))
#define D3D10_SB_RESOURCE_RETURN_TYPE_MASK 0x0000000fu
#define D3D10_SB_RESOURCE_RETURN_TYPE_NUMBITS 4
#define DECODE_D3D10_SB_RESOURCE_RETURN_TYPE(t, c) ((D3D10_SB_RESOURCE_RETURN_TYPE)(((t) >> ((c) * D3D10_SB_RESOURCE_RETURN_TYPE_NUMBITS)) & D3D10_SB_RESOURCE_RETURN_TYPE_MASK))
#define D3D10_SB_SAMPLER_MODE_MASK 0x00007800u
#define D3D10_SB_SAMPLER_MODE_SHIFT 11
#define DECODE_D3D10_SB_SAMPLER_MODE(t) ((D3D10_SB_SAMPLER_MODE)(((t) & D3D10_SB_SAMPLER_MODE_MASK) >> D3D10_SB_SAMPLER_MODE_SHIFT))
#define D3D10_SB_INPUT_INTERPOLATION_MODE_MASK 0x00007800u
#define D3D10_SB_INPUT_INTERPOLATION_MODE_SHIFT 11
#define DECODE_D3D10_SB_INPUT_INTERPOLATION_MODE(t) ((D3D10_SB_INTERPOLATION_MODE)(((t) & D3D10_SB_INPUT_INTERPOLATION_MODE_MASK) >> D3D10_SB_INPUT_INTERPOLATION_MODE_SHIFT))
#define D3D10_SB_CONSTANT_BUFFER_ACCESS_PATTERN_MASK 0x00000800u
#define D3D10_SB_CONSTANT_BUFFER_ACCESS_PATTERN_SHIFT 11
#define DECODE_D3D10_SB_CONSTANT_BUFFER_ACCESS_PATTERN(t) ((D3D10_SB_CONSTANT_BUFFER_ACCESS_PATTERN)(((t) & D3D10_SB_CONSTANT_BUFFER_ACCESS_PATTERN_MASK) >> D3D10_SB_CONSTANT_BUFFER_ACCESS_PATTERN_SHIFT))
#define D3D10_SB_GS_INPUT_PRIMITIVE_MASK 0x0001f800u
#define D3D10_SB_GS_INPUT_PRIMITIVE_SHIFT 11
#define DECODE_D3D10_SB_GS_INPUT_PRIMITIVE(t) ((D3D10_SB_PRIMITIVE)(((t) & D3D10_SB_GS_INPUT_PRIMITIVE_MASK) >> D3D10_SB_GS_INPUT_PRIMITIVE_SHIFT))
#define D3D10_SB_GS_OUTPUT_PRIMITIVE_TOPOLOGY_MASK 0x0001f800u
#define D3D10_SB_GS_OUTPUT_PRIMITIVE_TOPOLOGY_SHIFT 11
#define DECODE_D3D10_SB_GS_OUTPUT_PRIMITIVE_TOPOLOGY(t) ((D3D10_SB_PRIMITIVE_TOPOLOGY)(((t) & D3D10_SB_GS_OUTPUT_PRIMITIVE_TOPOLOGY_MASK) >> D3D10_SB_GS_OUTPUT_PRIMITIVE_TOPOLOGY_SHIFT))
