/*
 * PROJECT:     ReactOS SDK
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Direct3D user-mode display driver interface (UMD DDI)
 * COPYRIGHT:   Copyright 2026 ReactOS WDDM Team
 *
 * A WDDM graphics driver is two halves.  This tree has the kernel half; this
 * header is the ABI the *user* half is loaded through, and without it a UMD
 * cannot be built at all -- which is why the roadmap's gate 1.3 was blocked on
 * its absence rather than on any missing implementation.
 *
 * What is frozen here is the entry surface and the two tables that cross it:
 * the runtime calls OpenAdapter10_2, receives D3DDDI_ADAPTERFUNCS, calls
 * pfnCreateDevice, and receives D3DDDI_DEVICEFUNCS while handing the driver
 * D3DDDI_DEVICECALLBACKS to call back through.  Member order and count are the
 * ABI: a table entry in the wrong slot dispatches the runtime into the wrong
 * driver function, so both tables are reproduced in their exact published
 * order, including the version guards that decide their length.
 *
 * The per-entry argument structures are forward-declared.  A driver defines
 * each as it implements that entry; declaring them here without definitions
 * keeps every table slot at its correct offset while leaving the payloads to
 * be filled in one at a time, which is how a UMD gets written incrementally.
 *
 * Note this is *not* the interface a Mesa winsys needs -- that one talks
 * D3DKMT directly.  This header is for the D3D-runtime-loaded UMD route.
 */

#ifndef _D3DUMDDI_H_
#define _D3DUMDDI_H_

#include <d3dkmthk.h>

/*
 * The D3D_UMD_INTERFACE_VERSION_* constants and the compiled-against value
 * already live in <d3dukmdt.h>, which d3dkmthk.h pulls in.  They are not
 * repeated here: two definitions of a version constant is exactly how a table
 * guard ends up evaluating against the wrong number.
 */
#ifndef D3D_UMD_INTERFACE_VERSION
#error <d3dukmdt.h> must be included before this header
#endif

/* The exported entry point the D3D runtime resolves by name. */
#define D3DDDI_OPENADAPTER_PROCNAME "OpenAdapter10_2"

/* ------------------------------------------------------------------------ *
 * Argument structures.  Forward declarations only -- see the header comment.
 * ------------------------------------------------------------------------ */
struct _D3DDDIARG_GETCAPS;
struct _D3DDDICB_QUERYADAPTERINFO;
struct _D3DDDICB_GETMULTISAMPLEMETHODLIST;

/* ------------------------------------------------------------------------ *
 * Device function table -- the driver's entries, called by the runtime.
 * ------------------------------------------------------------------------ */
typedef HRESULT (APIENTRY *PFND3DDDI_SETRENDERSTATE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETRENDERSTATE*);
typedef HRESULT (APIENTRY *PFND3DDDI_UPDATEWINFO)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_UPDATEWINFO*);
typedef HRESULT (APIENTRY *PFND3DDDI_VALIDATEDEVICE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_VALIDATEDEVICE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETTEXTURESTAGESTATE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETTEXTURESTAGESTATE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETTEXTURE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETTEXTURE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETPIXELSHADER)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETPIXELSHADER*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETPIXELSHADERCONST)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETPIXELSHADERCONST*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETSTREAMSOURCEUM)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETSTREAMSOURCEUM*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETINDICES)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETINDICES*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETINDICESUM)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETINDICESUM*);
typedef HRESULT (APIENTRY *PFND3DDDI_DRAWPRIMITIVE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DRAWPRIMITIVE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DRAWINDEXEDPRIMITIVE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DRAWINDEXEDPRIMITIVE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DRAWRECTPATCH)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DRAWRECTPATCH*);
typedef HRESULT (APIENTRY *PFND3DDDI_DRAWTRIPATCH)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DRAWTRIPATCH*);
typedef HRESULT (APIENTRY *PFND3DDDI_DRAWPRIMITIVE2)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DRAWPRIMITIVE2*);
typedef HRESULT (APIENTRY *PFND3DDDI_DRAWINDEXEDPRIMITIVE2)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DRAWINDEXEDPRIMITIVE2*);
typedef HRESULT (APIENTRY *PFND3DDDI_VOLBLT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_VOLBLT*);
typedef HRESULT (APIENTRY *PFND3DDDI_BUFBLT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_BUFBLT*);
typedef HRESULT (APIENTRY *PFND3DDDI_TEXBLT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_TEXBLT*);
typedef HRESULT (APIENTRY *PFND3DDDI_STATESET)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_STATESET*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETPRIORITY)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETPRIORITY*);
typedef HRESULT (APIENTRY *PFND3DDDI_CLEAR)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CLEAR*);
typedef HRESULT (APIENTRY *PFND3DDDI_UPDATEPALETTE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_UPDATEPALETTE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETPALETTE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETPALETTE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETVERTEXSHADERCONST)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETVERTEXSHADERCONST*);
typedef HRESULT (APIENTRY *PFND3DDDI_MULTIPLYTRANSFORM)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_MULTIPLYTRANSFORM*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETTRANSFORM)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETTRANSFORM*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETVIEWPORT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETVIEWPORT*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETZRANGE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETZRANGE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETMATERIAL)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETMATERIAL*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETLIGHT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETLIGHT*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATELIGHT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATELIGHT*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYLIGHT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DESTROYLIGHT*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETCLIPPLANE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETCLIPPLANE*);
typedef HRESULT (APIENTRY *PFND3DDDI_GETINFO)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_GETINFO*);
typedef HRESULT (APIENTRY *PFND3DDDI_LOCK)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_LOCK*);
typedef HRESULT (APIENTRY *PFND3DDDI_UNLOCK)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_UNLOCK*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATERESOURCE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATERESOURCE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYRESOURCE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DESTROYRESOURCE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETDISPLAYMODE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETDISPLAYMODE*);
typedef HRESULT (APIENTRY *PFND3DDDI_PRESENT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_PRESENT*);
typedef HRESULT (APIENTRY *PFND3DDDI_FLUSH)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_FLUSH*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEVERTEXSHADERFUNC)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATEVERTEXSHADERFUNC*);
typedef HRESULT (APIENTRY *PFND3DDDI_DELETEVERTEXSHADERFUNC)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DELETEVERTEXSHADERFUNC*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETVERTEXSHADERFUNC)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETVERTEXSHADERFUNC*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEVERTEXSHADERDECL)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATEVERTEXSHADERDECL*);
typedef HRESULT (APIENTRY *PFND3DDDI_DELETEVERTEXSHADERDECL)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DELETEVERTEXSHADERDECL*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETVERTEXSHADERDECL)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETVERTEXSHADERDECL*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETVERTEXSHADERCONSTI)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETVERTEXSHADERCONSTI*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETVERTEXSHADERCONSTB)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETVERTEXSHADERCONSTB*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETSCISSORRECT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETSCISSORRECT*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETSTREAMSOURCE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETSTREAMSOURCE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETSTREAMSOURCEFREQ)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETSTREAMSOURCEFREQ*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETCONVOLUTIONKERNELMONO)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETCONVOLUTIONKERNELMONO*);
typedef HRESULT (APIENTRY *PFND3DDDI_COMPOSERECTS)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_COMPOSERECTS*);
typedef HRESULT (APIENTRY *PFND3DDDI_BLT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_BLT*);
typedef HRESULT (APIENTRY *PFND3DDDI_COLORFILL)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_COLORFILL*);
typedef HRESULT (APIENTRY *PFND3DDDI_DEPTHFILL)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DEPTHFILL*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEQUERY)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATEQUERY*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYQUERY)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DESTROYQUERY*);
typedef HRESULT (APIENTRY *PFND3DDDI_ISSUEQUERY)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_ISSUEQUERY*);
typedef HRESULT (APIENTRY *PFND3DDDI_GETQUERYDATA)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_GETQUERYDATA*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETRENDERTARGET)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETRENDERTARGET*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETDEPTHSTENCIL)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETDEPTHSTENCIL*);
typedef HRESULT (APIENTRY *PFND3DDDI_GENERATEMIPSUBLEVELS)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_GENERATEMIPSUBLEVELS*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETPIXELSHADERCONSTI)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETPIXELSHADERCONSTI*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETPIXELSHADERCONSTB)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETPIXELSHADERCONSTB*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEPIXELSHADER)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATEPIXELSHADER*);
typedef HRESULT (APIENTRY *PFND3DDDI_DELETEPIXELSHADER)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DELETEPIXELSHADER*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEDECODEDEVICE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATEDECODEDEVICE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYDECODEDEVICE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DESTROYDECODEDEVICE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETDECODERENDERTARGET)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETDECODERENDERTARGET*);
typedef HRESULT (APIENTRY *PFND3DDDI_DECODEBEGINFRAME)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DECODEBEGINFRAME*);
typedef HRESULT (APIENTRY *PFND3DDDI_DECODEENDFRAME)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DECODEENDFRAME*);
typedef HRESULT (APIENTRY *PFND3DDDI_DECODEEXECUTE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DECODEEXECUTE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DECODEEXTENSIONEXECUTE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DECODEEXTENSIONEXECUTE*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEVIDEOPROCESSDEVICE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATEVIDEOPROCESSDEVICE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYVIDEOPROCESSDEVICE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DESTROYVIDEOPROCESSDEVICE*);
typedef HRESULT (APIENTRY *PFND3DDDI_VIDEOPROCESSBEGINFRAME)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_VIDEOPROCESSBEGINFRAME*);
typedef HRESULT (APIENTRY *PFND3DDDI_VIDEOPROCESSENDFRAME)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_VIDEOPROCESSENDFRAME*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETVIDEOPROCESSRENDERTARGET)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETVIDEOPROCESSRENDERTARGET*);
typedef HRESULT (APIENTRY *PFND3DDDI_VIDEOPROCESSBLT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_VIDEOPROCESSBLT*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEEXTENSIONDEVICE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATEEXTENSIONDEVICE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYEXTENSIONDEVICE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DESTROYEXTENSIONDEVICE*);
typedef HRESULT (APIENTRY *PFND3DDDI_EXTENSIONEXECUTE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_EXTENSIONEXECUTE*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEOVERLAY)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATEOVERLAY*);
typedef HRESULT (APIENTRY *PFND3DDDI_UPDATEOVERLAY)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_UPDATEOVERLAY*);
typedef HRESULT (APIENTRY *PFND3DDDI_FLIPOVERLAY)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_FLIPOVERLAY*);
typedef HRESULT (APIENTRY *PFND3DDDI_GETOVERLAYCOLORCONTROLS)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_GETOVERLAYCOLORCONTROLS*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETOVERLAYCOLORCONTROLS)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETOVERLAYCOLORCONTROLS*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYOVERLAY)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DESTROYOVERLAY*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYDEVICE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DESTROYDEVICE*);
typedef HRESULT (APIENTRY *PFND3DDDI_QUERYRESOURCERESIDENCY)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_QUERYRESOURCERESIDENCY*);
typedef HRESULT (APIENTRY *PFND3DDDI_OPENRESOURCE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_OPENRESOURCE*);
typedef HRESULT (APIENTRY *PFND3DDDI_GETCAPTUREALLOCATIONHANDLE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_GETCAPTUREALLOCATIONHANDLE*);
typedef HRESULT (APIENTRY *PFND3DDDI_CAPTURETOSYSMEM)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CAPTURETOSYSMEM*);
typedef HRESULT (APIENTRY *PFND3DDDI_LOCKASYNC)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_LOCKASYNC*);
typedef HRESULT (APIENTRY *PFND3DDDI_UNLOCKASYNC)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_UNLOCKASYNC*);
typedef HRESULT (APIENTRY *PFND3DDDI_RENAME)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_RENAME*);
typedef HRESULT (APIENTRY *PFND3DDDI_DXVAHD_CREATEVIDEOPROCESSOR)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DXVAHD_CREATEVIDEOPROCESSOR*);
typedef HRESULT (APIENTRY *PFND3DDDI_DXVAHD_SETVIDEOPROCESSBLTSTATE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DXVAHD_SETVIDEOPROCESSBLTSTATE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DXVAHD_GETVIDEOPROCESSBLTSTATEPRIVATE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DXVAHD_GETVIDEOPROCESSBLTSTATEPRIVATE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DXVAHD_SETVIDEOPROCESSSTREAMSTATE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DXVAHD_SETVIDEOPROCESSSTREAMSTATE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DXVAHD_GETVIDEOPROCESSSTREAMSTATEPRIVATE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DXVAHD_GETVIDEOPROCESSSTREAMSTATEPRIVATE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DXVAHD_VIDEOPROCESSBLTHD)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DXVAHD_VIDEOPROCESSBLTHD*);
typedef HRESULT (APIENTRY *PFND3DDDI_DXVAHD_DESTROYVIDEOPROCESSOR)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DXVAHD_DESTROYVIDEOPROCESSOR*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEAUTHENTICATEDCHANNEL)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATEAUTHENTICATEDCHANNEL*);
typedef HRESULT (APIENTRY *PFND3DDDI_AUTHENTICATEDCHANNELKEYEXCHANGE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_AUTHENTICATEDCHANNELKEYEXCHANGE*);
typedef HRESULT (APIENTRY *PFND3DDDI_QUERYAUTHENTICATEDCHANNEL)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_QUERYAUTHENTICATEDCHANNEL*);
typedef HRESULT (APIENTRY *PFND3DDDI_CONFIGUREAUTHENICATEDCHANNEL)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CONFIGUREAUTHENICATEDCHANNEL*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYAUTHENTICATEDCHANNEL)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DESTROYAUTHENTICATEDCHANNEL*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATECRYPTOSESSION)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATECRYPTOSESSION*);
typedef HRESULT (APIENTRY *PFND3DDDI_CRYPTOSESSIONKEYEXCHANGE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CRYPTOSESSIONKEYEXCHANGE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYCRYPTOSESSION)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DESTROYCRYPTOSESSION*);
typedef HRESULT (APIENTRY *PFND3DDDI_ENCRYPTIONBLT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_ENCRYPTIONBLT*);
typedef HRESULT (APIENTRY *PFND3DDDI_GETPITCH)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_GETPITCH*);
typedef HRESULT (APIENTRY *PFND3DDDI_STARTSESSIONKEYREFRESH)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_STARTSESSIONKEYREFRESH*);
typedef HRESULT (APIENTRY *PFND3DDDI_FINISHSESSIONKEYREFRESH)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_FINISHSESSIONKEYREFRESH*);
typedef HRESULT (APIENTRY *PFND3DDDI_GETENCRYPTIONBLTKEY)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_GETENCRYPTIONBLTKEY*);
typedef HRESULT (APIENTRY *PFND3DDDI_DECRYPTIONBLT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DECRYPTIONBLT*);
typedef HRESULT (APIENTRY *PFND3DDDI_RESOLVESHAREDRESOURCE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_RESOLVESHAREDRESOURCE*);
typedef HRESULT (APIENTRY *PFND3DDDI_VOLBLT1)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_VOLBLT1*);
typedef HRESULT (APIENTRY *PFND3DDDI_BUFBLT1)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_BUFBLT1*);
typedef HRESULT (APIENTRY *PFND3DDDI_TEXBLT1)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_TEXBLT1*);
typedef HRESULT (APIENTRY *PFND3DDDI_DISCARD)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_DISCARD*);
typedef HRESULT (APIENTRY *PFND3DDDI_OFFERRESOURCES)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_OFFERRESOURCES*);
typedef HRESULT (APIENTRY *PFND3DDDI_RECLAIMRESOURCES)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_RECLAIMRESOURCES*);
typedef HRESULT (APIENTRY *PFND3DDDI_CHECKDIRECTFLIPSUPPORT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CHECKDIRECTFLIPSUPPORT*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATERESOURCE2)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CREATERESOURCE2*);
typedef HRESULT (APIENTRY *PFND3DDDI_CHECKMULTIPLANEOVERLAYSUPPORT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CHECKMULTIPLANEOVERLAYSUPPORT*);
typedef HRESULT (APIENTRY *PFND3DDDI_PRESENTMULTIPLANEOVERLAY)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_PRESENTMULTIPLANEOVERLAY*);
typedef HRESULT (APIENTRY *PFND3DDDI_FLUSH1)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_FLUSH1*);
typedef HRESULT (APIENTRY *PFND3DDDI_CHECKCOUNTERINFO)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CHECKCOUNTERINFO*);
typedef HRESULT (APIENTRY *PFND3DDDI_CHECKCOUNTER)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CHECKCOUNTER*);
typedef HRESULT (APIENTRY *PFND3DDDI_UPDATESUBRESOURCEUP)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_UPDATESUBRESOURCEUP*);
typedef HRESULT (APIENTRY *PFND3DDDI_PRESENT1)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_PRESENT1*);
typedef HRESULT (APIENTRY *PFND3DDDI_CHECKPRESENTDURATIONSUPPORT)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_CHECKPRESENTDURATIONSUPPORT*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETMARKER)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETMARKER*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETMARKERMODE)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SETMARKERMODE*);
typedef HRESULT (APIENTRY *PFND3DDDI_TRIMRESIDENCYSET)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_TRIMRESIDENCYSET*);
typedef HRESULT (APIENTRY *PFND3DDDI_SYNCTOKEN)(_In_ HANDLE, _Inout_ struct _D3DDDIARG_SYNCTOKEN*);

typedef struct _D3DDDI_DEVICEFUNCS
{
    PFND3DDDI_SETRENDERSTATE                            pfnSetRenderState;
    PFND3DDDI_UPDATEWINFO                               pfnUpdateWInfo;
    PFND3DDDI_VALIDATEDEVICE                            pfnValidateDevice;
    PFND3DDDI_SETTEXTURESTAGESTATE                      pfnSetTextureStageState;
    PFND3DDDI_SETTEXTURE                                pfnSetTexture;
    PFND3DDDI_SETPIXELSHADER                            pfnSetPixelShader;
    PFND3DDDI_SETPIXELSHADERCONST                       pfnSetPixelShaderConst;
    PFND3DDDI_SETSTREAMSOURCEUM                         pfnSetStreamSourceUm;
    PFND3DDDI_SETINDICES                                pfnSetIndices;
    PFND3DDDI_SETINDICESUM                              pfnSetIndicesUm;
    PFND3DDDI_DRAWPRIMITIVE                             pfnDrawPrimitive;
    PFND3DDDI_DRAWINDEXEDPRIMITIVE                      pfnDrawIndexedPrimitive;
    PFND3DDDI_DRAWRECTPATCH                             pfnDrawRectPatch;
    PFND3DDDI_DRAWTRIPATCH                              pfnDrawTriPatch;
    PFND3DDDI_DRAWPRIMITIVE2                            pfnDrawPrimitive2;
    PFND3DDDI_DRAWINDEXEDPRIMITIVE2                     pfnDrawIndexedPrimitive2;
    PFND3DDDI_VOLBLT                                    pfnVolBlt;
    PFND3DDDI_BUFBLT                                    pfnBufBlt;
    PFND3DDDI_TEXBLT                                    pfnTexBlt;
    PFND3DDDI_STATESET                                  pfnStateSet;
    PFND3DDDI_SETPRIORITY                               pfnSetPriority;
    PFND3DDDI_CLEAR                                     pfnClear;
    PFND3DDDI_UPDATEPALETTE                             pfnUpdatePalette;
    PFND3DDDI_SETPALETTE                                pfnSetPalette;
    PFND3DDDI_SETVERTEXSHADERCONST                      pfnSetVertexShaderConst;
    PFND3DDDI_MULTIPLYTRANSFORM                         pfnMultiplyTransform;
    PFND3DDDI_SETTRANSFORM                              pfnSetTransform;
    PFND3DDDI_SETVIEWPORT                               pfnSetViewport;
    PFND3DDDI_SETZRANGE                                 pfnSetZRange;
    PFND3DDDI_SETMATERIAL                               pfnSetMaterial;
    PFND3DDDI_SETLIGHT                                  pfnSetLight;
    PFND3DDDI_CREATELIGHT                               pfnCreateLight;
    PFND3DDDI_DESTROYLIGHT                              pfnDestroyLight;
    PFND3DDDI_SETCLIPPLANE                              pfnSetClipPlane;
    PFND3DDDI_GETINFO                                   pfnGetInfo;
    PFND3DDDI_LOCK                                      pfnLock;
    PFND3DDDI_UNLOCK                                    pfnUnlock;
    PFND3DDDI_CREATERESOURCE                            pfnCreateResource;
    PFND3DDDI_DESTROYRESOURCE                           pfnDestroyResource;
    PFND3DDDI_SETDISPLAYMODE                            pfnSetDisplayMode;
    PFND3DDDI_PRESENT                                   pfnPresent;
    PFND3DDDI_FLUSH                                     pfnFlush;
    PFND3DDDI_CREATEVERTEXSHADERFUNC                    pfnCreateVertexShaderFunc;
    PFND3DDDI_DELETEVERTEXSHADERFUNC                    pfnDeleteVertexShaderFunc;
    PFND3DDDI_SETVERTEXSHADERFUNC                       pfnSetVertexShaderFunc;
    PFND3DDDI_CREATEVERTEXSHADERDECL                    pfnCreateVertexShaderDecl;
    PFND3DDDI_DELETEVERTEXSHADERDECL                    pfnDeleteVertexShaderDecl;
    PFND3DDDI_SETVERTEXSHADERDECL                       pfnSetVertexShaderDecl;
    PFND3DDDI_SETVERTEXSHADERCONSTI                     pfnSetVertexShaderConstI;
    PFND3DDDI_SETVERTEXSHADERCONSTB                     pfnSetVertexShaderConstB;
    PFND3DDDI_SETSCISSORRECT                            pfnSetScissorRect;
    PFND3DDDI_SETSTREAMSOURCE                           pfnSetStreamSource;
    PFND3DDDI_SETSTREAMSOURCEFREQ                       pfnSetStreamSourceFreq;
    PFND3DDDI_SETCONVOLUTIONKERNELMONO                  pfnSetConvolutionKernelMono;
    PFND3DDDI_COMPOSERECTS                              pfnComposeRects;
    PFND3DDDI_BLT                                       pfnBlt;
    PFND3DDDI_COLORFILL                                 pfnColorFill;
    PFND3DDDI_DEPTHFILL                                 pfnDepthFill;
    PFND3DDDI_CREATEQUERY                               pfnCreateQuery;
    PFND3DDDI_DESTROYQUERY                              pfnDestroyQuery;
    PFND3DDDI_ISSUEQUERY                                pfnIssueQuery;
    PFND3DDDI_GETQUERYDATA                              pfnGetQueryData;
    PFND3DDDI_SETRENDERTARGET                           pfnSetRenderTarget;
    PFND3DDDI_SETDEPTHSTENCIL                           pfnSetDepthStencil;
    PFND3DDDI_GENERATEMIPSUBLEVELS                      pfnGenerateMipSubLevels;
    PFND3DDDI_SETPIXELSHADERCONSTI                      pfnSetPixelShaderConstI;
    PFND3DDDI_SETPIXELSHADERCONSTB                      pfnSetPixelShaderConstB;
    PFND3DDDI_CREATEPIXELSHADER                         pfnCreatePixelShader;
    PFND3DDDI_DELETEPIXELSHADER                         pfnDeletePixelShader;
    PFND3DDDI_CREATEDECODEDEVICE                        pfnCreateDecodeDevice;
    PFND3DDDI_DESTROYDECODEDEVICE                       pfnDestroyDecodeDevice;
    PFND3DDDI_SETDECODERENDERTARGET                     pfnSetDecodeRenderTarget;
    PFND3DDDI_DECODEBEGINFRAME                          pfnDecodeBeginFrame;
    PFND3DDDI_DECODEENDFRAME                            pfnDecodeEndFrame;
    PFND3DDDI_DECODEEXECUTE                             pfnDecodeExecute;
    PFND3DDDI_DECODEEXTENSIONEXECUTE                    pfnDecodeExtensionExecute;
    PFND3DDDI_CREATEVIDEOPROCESSDEVICE                  pfnCreateVideoProcessDevice;
    PFND3DDDI_DESTROYVIDEOPROCESSDEVICE                 pfnDestroyVideoProcessDevice;
    PFND3DDDI_VIDEOPROCESSBEGINFRAME                    pfnVideoProcessBeginFrame;
    PFND3DDDI_VIDEOPROCESSENDFRAME                      pfnVideoProcessEndFrame;
    PFND3DDDI_SETVIDEOPROCESSRENDERTARGET               pfnSetVideoProcessRenderTarget;
    PFND3DDDI_VIDEOPROCESSBLT                           pfnVideoProcessBlt;
    PFND3DDDI_CREATEEXTENSIONDEVICE                     pfnCreateExtensionDevice;
    PFND3DDDI_DESTROYEXTENSIONDEVICE                    pfnDestroyExtensionDevice;
    PFND3DDDI_EXTENSIONEXECUTE                          pfnExtensionExecute;
    PFND3DDDI_CREATEOVERLAY                             pfnCreateOverlay;
    PFND3DDDI_UPDATEOVERLAY                             pfnUpdateOverlay;
    PFND3DDDI_FLIPOVERLAY                               pfnFlipOverlay;
    PFND3DDDI_GETOVERLAYCOLORCONTROLS                   pfnGetOverlayColorControls;
    PFND3DDDI_SETOVERLAYCOLORCONTROLS                   pfnSetOverlayColorControls;
    PFND3DDDI_DESTROYOVERLAY                            pfnDestroyOverlay;
    PFND3DDDI_DESTROYDEVICE                             pfnDestroyDevice;
    PFND3DDDI_QUERYRESOURCERESIDENCY                    pfnQueryResourceResidency;
    PFND3DDDI_OPENRESOURCE                              pfnOpenResource;
    PFND3DDDI_GETCAPTUREALLOCATIONHANDLE                pfnGetCaptureAllocationHandle;
    PFND3DDDI_CAPTURETOSYSMEM                           pfnCaptureToSysMem;
    PFND3DDDI_LOCKASYNC                                 pfnLockAsync;
    PFND3DDDI_UNLOCKASYNC                               pfnUnlockAsync;
    PFND3DDDI_RENAME                                    pfnRename;
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WIN7)
    PFND3DDDI_DXVAHD_CREATEVIDEOPROCESSOR               pfnCreateVideoProcessor;
    PFND3DDDI_DXVAHD_SETVIDEOPROCESSBLTSTATE            pfnSetVideoProcessBltState;
    PFND3DDDI_DXVAHD_GETVIDEOPROCESSBLTSTATEPRIVATE     pfnGetVideoProcessBltStatePrivate;
    PFND3DDDI_DXVAHD_SETVIDEOPROCESSSTREAMSTATE         pfnSetVideoProcessStreamState;
    PFND3DDDI_DXVAHD_GETVIDEOPROCESSSTREAMSTATEPRIVATE  pfnGetVideoProcessStreamStatePrivate;
    PFND3DDDI_DXVAHD_VIDEOPROCESSBLTHD                  pfnVideoProcessBltHD;
    PFND3DDDI_DXVAHD_DESTROYVIDEOPROCESSOR              pfnDestroyVideoProcessor;
    PFND3DDDI_CREATEAUTHENTICATEDCHANNEL                pfnCreateAuthenticatedChannel;
    PFND3DDDI_AUTHENTICATEDCHANNELKEYEXCHANGE           pfnAuthenticatedChannelKeyExchange;
    PFND3DDDI_QUERYAUTHENTICATEDCHANNEL                 pfnQueryAuthenticatedChannel;
    PFND3DDDI_CONFIGUREAUTHENICATEDCHANNEL              pfnConfigureAuthenticatedChannel;
    PFND3DDDI_DESTROYAUTHENTICATEDCHANNEL               pfnDestroyAuthenticatedChannel;
    PFND3DDDI_CREATECRYPTOSESSION                       pfnCreateCryptoSession;
    PFND3DDDI_CRYPTOSESSIONKEYEXCHANGE                  pfnCryptoSessionKeyExchange;
    PFND3DDDI_DESTROYCRYPTOSESSION                      pfnDestroyCryptoSession;
    PFND3DDDI_ENCRYPTIONBLT                             pfnEncryptionBlt;
    PFND3DDDI_GETPITCH                                  pfnGetPitch;
    PFND3DDDI_STARTSESSIONKEYREFRESH                    pfnStartSessionKeyRefresh;
    PFND3DDDI_FINISHSESSIONKEYREFRESH                   pfnFinishSessionKeyRefresh;
    PFND3DDDI_GETENCRYPTIONBLTKEY                       pfnGetEncryptionBltKey;
    PFND3DDDI_DECRYPTIONBLT                             pfnDecryptionBlt;
    PFND3DDDI_RESOLVESHAREDRESOURCE                     pfnResolveSharedResource;
#endif // D3D_UMD_INTERFACE_VERSION
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WIN8)
    PFND3DDDI_VOLBLT1                                   pfnVolBlt1;
    PFND3DDDI_BUFBLT1                                   pfnBufBlt1;
    PFND3DDDI_TEXBLT1                                   pfnTexBlt1;
    PFND3DDDI_DISCARD                                   pfnDiscard;
    PFND3DDDI_OFFERRESOURCES                            pfnOfferResources;
    PFND3DDDI_RECLAIMRESOURCES                          pfnReclaimResources;
    PFND3DDDI_CHECKDIRECTFLIPSUPPORT                    pfnCheckDirectFlipSupport;
    PFND3DDDI_CREATERESOURCE2                           pfnCreateResource2;
    PFND3DDDI_CHECKMULTIPLANEOVERLAYSUPPORT             pfnCheckMultiPlaneOverlaySupport;
    PFND3DDDI_PRESENTMULTIPLANEOVERLAY                  pfnPresentMultiPlaneOverlay;
#endif // D3D_UMD_INTERFACE_VERSION
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WDDM1_3) // M1
    PFND3DDDI_FLUSH1                                    pfnFlush1;
    PFND3DDDI_CHECKCOUNTERINFO                          pfnCheckCounterInfo;
    PFND3DDDI_CHECKCOUNTER                              pfnCheckCounter;
    PFND3DDDI_UPDATESUBRESOURCEUP                       pfnUpdateSubresourceUP;
    PFND3DDDI_PRESENT1                                  pfnPresent1;
    PFND3DDDI_CHECKPRESENTDURATIONSUPPORT               pfnCheckPresentDurationSupport;
#endif
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WDDM1_3) // MP
    PFND3DDDI_SETMARKER                                 pfnSetMarker;
    PFND3DDDI_SETMARKERMODE                             pfnSetMarkerMode;
#endif
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WDDM2_0)
    PFND3DDDI_TRIMRESIDENCYSET                          pfnTrimResidencySet;
#endif
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WDDM2_1_2)
    PFND3DDDI_SYNCTOKEN                                 pfnAcquireResource;
    PFND3DDDI_SYNCTOKEN                                 pfnReleaseResource;
#endif
} D3DDDI_DEVICEFUNCS;

/* ------------------------------------------------------------------------ *
 * Device callback table -- the runtime's entries, called by the driver.
 * ------------------------------------------------------------------------ */
typedef HRESULT (APIENTRY *PFND3DDDI_ALLOCATECB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_ALLOCATE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DEALLOCATECB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_DEALLOCATE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETPRIORITYCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SETPRIORITY*);
typedef HRESULT (APIENTRY *PFND3DDDI_QUERYRESIDENCYCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_QUERYRESIDENCY*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETDISPLAYMODECB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SETDISPLAYMODE*);
typedef HRESULT (APIENTRY *PFND3DDDI_PRESENTCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_PRESENT*);
typedef HRESULT (APIENTRY *PFND3DDDI_RENDERCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_RENDER*);
typedef HRESULT (APIENTRY *PFND3DDDI_LOCKCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_LOCK*);
typedef HRESULT (APIENTRY *PFND3DDDI_UNLOCKCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_UNLOCK*);
typedef HRESULT (APIENTRY *PFND3DDDI_ESCAPECB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_ESCAPE*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEOVERLAYCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_CREATEOVERLAY*);
typedef HRESULT (APIENTRY *PFND3DDDI_UPDATEOVERLAYCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_UPDATEOVERLAY*);
typedef HRESULT (APIENTRY *PFND3DDDI_FLIPOVERLAYCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_FLIPOVERLAY*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYOVERLAYCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_DESTROYOVERLAY*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATECONTEXTCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_CREATECONTEXT*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYCONTEXTCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_DESTROYCONTEXT*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATESYNCHRONIZATIONOBJECTCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_CREATESYNCHRONIZATIONOBJECT*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYSYNCHRONIZATIONOBJECTCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_DESTROYSYNCHRONIZATIONOBJECT*);
typedef HRESULT (APIENTRY *PFND3DDDI_WAITFORSYNCHRONIZATIONOBJECTCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_WAITFORSYNCHRONIZATIONOBJECT*);
typedef HRESULT (APIENTRY *PFND3DDDI_SIGNALSYNCHRONIZATIONOBJECTCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SIGNALSYNCHRONIZATIONOBJECT*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETASYNCCALLBACKSCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SETASYNCCALLBACKS*);
typedef HRESULT (APIENTRY *PFND3DDDI_SETDISPLAYPRIVATEDRIVERFORMATCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SETDISPLAYPRIVATEDRIVERFORMAT*);
typedef HRESULT (APIENTRY *PFND3DDDI_OFFERALLOCATIONSCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_OFFERALLOCATIONS*);
typedef HRESULT (APIENTRY *PFND3DDDI_RECLAIMALLOCATIONSCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_RECLAIMALLOCATIONS*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATESYNCHRONIZATIONOBJECT2CB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_CREATESYNCHRONIZATIONOBJECT2*);
typedef HRESULT (APIENTRY *PFND3DDDI_WAITFORSYNCHRONIZATIONOBJECT2CB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_WAITFORSYNCHRONIZATIONOBJECT2*);
typedef HRESULT (APIENTRY *PFND3DDDI_SIGNALSYNCHRONIZATIONOBJECT2CB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SIGNALSYNCHRONIZATIONOBJECT2*);
typedef HRESULT (APIENTRY *PFND3DDDI_PRESENTMULTIPLANEOVERLAYCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_PRESENTMULTIPLANEOVERLAY*);
typedef HRESULT (APIENTRY *PFND3DDDI_LOGUMDMARKERCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_LOGUMDMARKER*);
typedef HRESULT (APIENTRY *PFND3DDDI_MAKERESIDENTCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_MAKERESIDENT*);
typedef HRESULT (APIENTRY *PFND3DDDI_EVICTCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_EVICT*);
typedef HRESULT (APIENTRY *PFND3DDDI_WAITFORSYNCHRONIZATIONOBJECTFROMCPUCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_WAITFORSYNCHRONIZATIONOBJECTFROMCPU*);
typedef HRESULT (APIENTRY *PFND3DDDI_SIGNALSYNCHRONIZATIONOBJECTFROMCPUCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SIGNALSYNCHRONIZATIONOBJECTFROMCPU*);
typedef HRESULT (APIENTRY *PFND3DDDI_WAITFORSYNCHRONIZATIONOBJECTFROMGPUCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_WAITFORSYNCHRONIZATIONOBJECTFROMGPU*);
typedef HRESULT (APIENTRY *PFND3DDDI_SIGNALSYNCHRONIZATIONOBJECTFROMGPUCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SIGNALSYNCHRONIZATIONOBJECTFROMGPU*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEPAGINGQUEUECB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_CREATEPAGINGQUEUE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYPAGINGQUEUECB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_DESTROYPAGINGQUEUE*);
typedef HRESULT (APIENTRY *PFND3DDDI_LOCK2CB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_LOCK2*);
typedef HRESULT (APIENTRY *PFND3DDDI_UNLOCK2CB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_UNLOCK2*);
typedef HRESULT (APIENTRY *PFND3DDDI_INVALIDATECACHECB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_INVALIDATECACHE*);
typedef HRESULT (APIENTRY *PFND3DDDI_RESERVEGPUVIRTUALADDRESSCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_RESERVEGPUVIRTUALADDRESS*);
typedef HRESULT (APIENTRY *PFND3DDDI_MAPGPUVIRTUALADDRESSCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_MAPGPUVIRTUALADDRESS*);
typedef HRESULT (APIENTRY *PFND3DDDI_FREEGPUVIRTUALADDRESSCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_FREEGPUVIRTUALADDRESS*);
typedef HRESULT (APIENTRY *PFND3DDDI_UPDATEGPUVIRTUALADDRESSCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_UPDATEGPUVIRTUALADDRESS*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATECONTEXTVIRTUALCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_CREATECONTEXTVIRTUAL*);
typedef HRESULT (APIENTRY *PFND3DDDI_SUBMITCOMMANDCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SUBMITCOMMAND*);
typedef HRESULT (APIENTRY *PFND3DDDI_DEALLOCATE2CB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_DEALLOCATE2*);
typedef HRESULT (APIENTRY *PFND3DDDI_SIGNALSYNCHRONIZATIONOBJECTFROMGPU2CB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SIGNALSYNCHRONIZATIONOBJECTFROMGPU2*);
typedef HRESULT (APIENTRY *PFND3DDDI_RECLAIMALLOCATIONS2CB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_RECLAIMALLOCATIONS2*);
typedef HRESULT (APIENTRY *PFND3DDDI_GETRESOURCEPRESENTPRIVATEDRIVERDATACB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_GETRESOURCEPRESENTPRIVATEDRIVERDATA*);
typedef HRESULT (APIENTRY *PFND3DDDI_UPDATEALLOCATIONPROPERTYCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_UPDATEALLOCATIONPROPERTY*);
typedef HRESULT (APIENTRY *PFND3DDDI_OFFERALLOCATIONS2CB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_OFFERALLOCATIONS2*);
typedef HRESULT (APIENTRY *PFND3DDDI_RECLAIMALLOCATIONS3CB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_RECLAIMALLOCATIONS3*);
typedef HRESULT (APIENTRY *PFND3DDDI_SYNCTOKENCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SYNCTOKEN*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEHWCONTEXTCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_CREATEHWCONTEXT*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYHWCONTEXTCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_DESTROYHWCONTEXT*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEHWQUEUECB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_CREATEHWQUEUE*);
typedef HRESULT (APIENTRY *PFND3DDDI_DESTROYHWQUEUECB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_DESTROYHWQUEUE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SUBMITCOMMANDTOHWQUEUECB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SUBMITCOMMANDTOHWQUEUE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SUBMITWAITFORSYNCOBJECTSTOHWQUEUECB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SUBMITWAITFORSYNCOBJECTSTOHWQUEUE*);
typedef HRESULT (APIENTRY *PFND3DDDI_SUBMITSIGNALSYNCOBJECTSTOHWQUEUECB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_SUBMITSIGNALSYNCOBJECTSTOHWQUEUE*);

typedef struct _D3DDDI_DEVICECALLBACKS
{
    PFND3DDDI_ALLOCATECB                                pfnAllocateCb;
    PFND3DDDI_DEALLOCATECB                              pfnDeallocateCb;
    PFND3DDDI_SETPRIORITYCB                             pfnSetPriorityCb;
    PFND3DDDI_QUERYRESIDENCYCB                          pfnQueryResidencyCb;
    PFND3DDDI_SETDISPLAYMODECB                          pfnSetDisplayModeCb;
    PFND3DDDI_PRESENTCB                                 pfnPresentCb;
    PFND3DDDI_RENDERCB                                  pfnRenderCb;
    PFND3DDDI_LOCKCB                                    pfnLockCb;
    PFND3DDDI_UNLOCKCB                                  pfnUnlockCb;
    PFND3DDDI_ESCAPECB                                  pfnEscapeCb;
    PFND3DDDI_CREATEOVERLAYCB                           pfnCreateOverlayCb;
    PFND3DDDI_UPDATEOVERLAYCB                           pfnUpdateOverlayCb;
    PFND3DDDI_FLIPOVERLAYCB                             pfnFlipOverlayCb;
    PFND3DDDI_DESTROYOVERLAYCB                          pfnDestroyOverlayCb;
    PFND3DDDI_CREATECONTEXTCB                           pfnCreateContextCb;
    PFND3DDDI_DESTROYCONTEXTCB                          pfnDestroyContextCb;
    PFND3DDDI_CREATESYNCHRONIZATIONOBJECTCB             pfnCreateSynchronizationObjectCb;
    PFND3DDDI_DESTROYSYNCHRONIZATIONOBJECTCB            pfnDestroySynchronizationObjectCb;
    PFND3DDDI_WAITFORSYNCHRONIZATIONOBJECTCB            pfnWaitForSynchronizationObjectCb;
    PFND3DDDI_SIGNALSYNCHRONIZATIONOBJECTCB             pfnSignalSynchronizationObjectCb;
    PFND3DDDI_SETASYNCCALLBACKSCB                       pfnSetAsyncCallbacksCb;
    PFND3DDDI_SETDISPLAYPRIVATEDRIVERFORMATCB           pfnSetDisplayPrivateDriverFormatCb;
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WIN8)
    PFND3DDDI_OFFERALLOCATIONSCB                        pfnOfferAllocationsCb;
    PFND3DDDI_RECLAIMALLOCATIONSCB                      pfnReclaimAllocationsCb;
    PFND3DDDI_CREATESYNCHRONIZATIONOBJECT2CB            pfnCreateSynchronizationObject2Cb;
    PFND3DDDI_WAITFORSYNCHRONIZATIONOBJECT2CB           pfnWaitForSynchronizationObject2Cb;
    PFND3DDDI_SIGNALSYNCHRONIZATIONOBJECT2CB            pfnSignalSynchronizationObject2Cb;
    PFND3DDDI_PRESENTMULTIPLANEOVERLAYCB                pfnPresentMultiPlaneOverlayCb;
#endif // (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WIN8)
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WDDM1_3) // MP
    PFND3DDDI_LOGUMDMARKERCB                            pfnLogUMDMarkerCb;
#endif // D3D_UMD_INTERFACE_VERSION
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WDDM2_0)
    PFND3DDDI_MAKERESIDENTCB                            pfnMakeResidentCb;
    PFND3DDDI_EVICTCB                                   pfnEvictCb;
    PFND3DDDI_WAITFORSYNCHRONIZATIONOBJECTFROMCPUCB     pfnWaitForSynchronizationObjectFromCpuCb;
    PFND3DDDI_SIGNALSYNCHRONIZATIONOBJECTFROMCPUCB      pfnSignalSynchronizationObjectFromCpuCb;
    PFND3DDDI_WAITFORSYNCHRONIZATIONOBJECTFROMGPUCB     pfnWaitForSynchronizationObjectFromGpuCb;
    PFND3DDDI_SIGNALSYNCHRONIZATIONOBJECTFROMGPUCB      pfnSignalSynchronizationObjectFromGpuCb;
    PFND3DDDI_CREATEPAGINGQUEUECB                       pfnCreatePagingQueueCb;
    PFND3DDDI_DESTROYPAGINGQUEUECB                      pfnDestroyPagingQueueCb;
    PFND3DDDI_LOCK2CB                                   pfnLock2Cb;
    PFND3DDDI_UNLOCK2CB                                 pfnUnlock2Cb;
    PFND3DDDI_INVALIDATECACHECB                         pfnInvalidateCacheCb;
    PFND3DDDI_RESERVEGPUVIRTUALADDRESSCB                pfnReserveGpuVirtualAddressCb;
    PFND3DDDI_MAPGPUVIRTUALADDRESSCB                    pfnMapGpuVirtualAddressCb;
    PFND3DDDI_FREEGPUVIRTUALADDRESSCB                   pfnFreeGpuVirtualAddressCb;
    PFND3DDDI_UPDATEGPUVIRTUALADDRESSCB                 pfnUpdateGpuVirtualAddressCb;
    PFND3DDDI_CREATECONTEXTVIRTUALCB                    pfnCreateContextVirtualCb;
    PFND3DDDI_SUBMITCOMMANDCB                           pfnSubmitCommandCb;
    PFND3DDDI_DEALLOCATE2CB                             pfnDeallocate2Cb;
    PFND3DDDI_SIGNALSYNCHRONIZATIONOBJECTFROMGPU2CB     pfnSignalSynchronizationObjectFromGpu2Cb;
    PFND3DDDI_RECLAIMALLOCATIONS2CB                     pfnReclaimAllocations2Cb;
    PFND3DDDI_GETRESOURCEPRESENTPRIVATEDRIVERDATACB     pfnGetResourcePresentPrivateDriverDataCb;
#endif // D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WDDM2_0
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WDDM2_1_1)
    PFND3DDDI_UPDATEALLOCATIONPROPERTYCB                pfnUpdateAllocationPropertyCb;
    PFND3DDDI_OFFERALLOCATIONS2CB                       pfnOfferAllocations2Cb;
#endif // D3D_UMD_INTERFACE_VERSION
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WDDM2_1_2)
    PFND3DDDI_RECLAIMALLOCATIONS3CB                     pfnReclaimAllocations3Cb;
    PFND3DDDI_SYNCTOKENCB                               pfnAcquireResourceCb;
#endif // D3D_UMD_INTERFACE_VERSION
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WDDM2_1_3)
    PFND3DDDI_SYNCTOKENCB                               pfnReleaseResourceCb;
#endif // D3D_UMD_INTERFACE_VERSION
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WDDM2_2_1)
    PFND3DDDI_CREATEHWCONTEXTCB                         pfnCreateHwContextCb;
    PFND3DDDI_DESTROYHWCONTEXTCB                        pfnDestroyHwContextCb;
    PFND3DDDI_CREATEHWQUEUECB                           pfnCreateHwQueueCb;
    PFND3DDDI_DESTROYHWQUEUECB                          pfnDestroyHwQueueCb;
    PFND3DDDI_SUBMITCOMMANDTOHWQUEUECB                  pfnSubmitCommandToHwQueueCb;
    PFND3DDDI_SUBMITWAITFORSYNCOBJECTSTOHWQUEUECB       pfnSubmitWaitForSyncObjectsToHwQueueCb;
    PFND3DDDI_SUBMITSIGNALSYNCOBJECTSTOHWQUEUECB        pfnSubmitSignalSyncObjectsToHwQueueCb;
#endif // D3D_UMD_INTERFACE_VERSION
} D3DDDI_DEVICECALLBACKS;

/* ------------------------------------------------------------------------ *
 * Device creation
 * ------------------------------------------------------------------------ */
typedef struct _D3DDDI_CREATEDEVICEFLAGS
{
    union
    {
        struct
        {
            UINT AllowMultithreading : 1;
            UINT AllowFlipBatching   : 1;
            UINT Reserved            : 30;
        };
        UINT Value;
    };
} D3DDDI_CREATEDEVICEFLAGS;

typedef struct _D3DDDIARG_CREATEDEVICE
{
    HANDLE                          hDevice;                /* in: runtime handle / out: driver handle */
    UINT                            Interface;
    UINT                            Version;
    CONST D3DDDI_DEVICECALLBACKS   *pCallbacks;             /* in:  runtime callbacks */
    VOID                           *pCommandBuffer;         /* in:  first command buffer */
    UINT                            CommandBufferSize;
    D3DDDI_ALLOCATIONLIST          *pAllocationList;        /* out: first allocation list */
    UINT                            AllocationListSize;
    D3DDDI_PATCHLOCATIONLIST       *pPatchLocationList;     /* out: first patch location list */
    UINT                            PatchLocationListSize;
    D3DDDI_DEVICEFUNCS             *pDeviceFuncs;           /* out: driver function table */
    D3DDDI_CREATEDEVICEFLAGS        Flags;
#if (D3D_UMD_INTERFACE_VERSION >= D3D_UMD_INTERFACE_VERSION_WIN7)
    D3DGPU_VIRTUAL_ADDRESS          CommandBuffer;          /* out: GPU VA of the command buffer */
#endif
} D3DDDIARG_CREATEDEVICE;

/* ------------------------------------------------------------------------ *
 * Adapter entry surface -- what OpenAdapter10_2 exchanges.
 * ------------------------------------------------------------------------ */
typedef HRESULT (APIENTRY *PFND3DDDI_QUERYADAPTERINFOCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_QUERYADAPTERINFO*);
typedef HRESULT (APIENTRY *PFND3DDDI_GETMULTISAMPLEMETHODLISTCB)(_In_ HANDLE, _Inout_ struct _D3DDDICB_GETMULTISAMPLEMETHODLIST*);

typedef struct _D3DDDI_ADAPTERCALLBACKS
{
    PFND3DDDI_QUERYADAPTERINFOCB         pfnQueryAdapterInfoCb;
    PFND3DDDI_GETMULTISAMPLEMETHODLISTCB pfnGetMultisampleMethodListCb;
} D3DDDI_ADAPTERCALLBACKS;

typedef HRESULT (APIENTRY *PFND3DDDI_GETCAPS)(_In_ HANDLE, _Inout_ CONST struct _D3DDDIARG_GETCAPS*);
typedef HRESULT (APIENTRY *PFND3DDDI_CREATEDEVICE)(_In_ HANDLE, _Inout_ D3DDDIARG_CREATEDEVICE*);
typedef HRESULT (APIENTRY *PFND3DDDI_CLOSEADAPTER)(_In_ HANDLE);

typedef struct _D3DDDI_ADAPTERFUNCS
{
    PFND3DDDI_GETCAPS      pfnGetCaps;
    PFND3DDDI_CREATEDEVICE pfnCreateDevice;
    PFND3DDDI_CLOSEADAPTER pfnCloseAdapter;
} D3DDDI_ADAPTERFUNCS;

typedef struct _D3DDDIARG_OPENADAPTER
{
    HANDLE                         hAdapter;           /* in: runtime handle / out: driver handle */
    UINT                           Interface;
    UINT                           Version;
    CONST D3DDDI_ADAPTERCALLBACKS *pAdapterCallbacks;  /* in:  runtime callbacks */
    D3DDDI_ADAPTERFUNCS           *pAdapterFuncs;      /* out: driver function table */
    UINT                           DriverVersion;      /* out: D3D_UMD_INTERFACE_VERSION */
} D3DDDIARG_OPENADAPTER;

typedef HRESULT (APIENTRY *PFND3DDDI_OPENADAPTER)(_Inout_ D3DDDIARG_OPENADAPTER*);

#endif /* _D3DUMDDI_H_ */
