/*
 * PROJECT:     ReactOS DDK
 * LICENSE:     GPL-2.0-or-later
 * PURPOSE:     Public WDI miniport control interface declarations.
 */
#ifndef _DOT11WDI_H_
#define _DOT11WDI_H_

#include <ndis.h>

#ifdef __cplusplus
extern "C" {
#endif

#define NDIS_OBJECT_TYPE_MINIPORT_WDI_CHARACTERISTICS 0xc0
#define NDIS_MINIPORT_DRIVER_WDI_CHARACTERISTICS_REVISION_1 1
#define NDIS_OBJECT_TYPE_WDI_INIT_PARAMETERS 0xc3
#define NDIS_OBJECT_TYPE_WDI_INIT_PARAMETERS_REVISION_1 1
#define WDI_VERSION_1_0 0x00010000
#define WDI_VERSION_1_1_12 0x0001010c
#define WDI_VERSION_LATEST WDI_VERSION_1_1_12

typedef struct _NDIS_WDI_DATA_API NDIS_WDI_DATA_API, *PNDIS_WDI_DATA_API;
typedef struct _NDIS_MINIPORT_WDI_DATA_HANDLERS NDIS_MINIPORT_WDI_DATA_HANDLERS, *PNDIS_MINIPORT_WDI_DATA_HANDLERS;
typedef NDIS_HANDLE TAL_TXRX_HANDLE, *PTAL_TXRX_HANDLE;

typedef VOID NDIS_WDI_OPEN_ADAPTER_COMPLETE(NDIS_HANDLE, NDIS_STATUS);
typedef VOID NDIS_WDI_CLOSE_ADAPTER_COMPLETE(NDIS_HANDLE, NDIS_STATUS);
typedef VOID NDIS_WDI_IDLE_NOTIFICATION_CONFIRM(NDIS_HANDLE, NDIS_DEVICE_POWER_STATE);
typedef VOID NDIS_WDI_IDLE_NOTIFICATION_COMPLETE(NDIS_HANDLE);
typedef NDIS_WDI_OPEN_ADAPTER_COMPLETE *NDIS_WDI_OPEN_ADAPTER_COMPLETE_HANDLER;
typedef NDIS_WDI_CLOSE_ADAPTER_COMPLETE *NDIS_WDI_CLOSE_ADAPTER_COMPLETE_HANDLER;
typedef NDIS_WDI_IDLE_NOTIFICATION_CONFIRM *NDIS_WDI_IDLE_NOTIFICATION_CONFIRM_HANDLER;
typedef NDIS_WDI_IDLE_NOTIFICATION_COMPLETE *NDIS_WDI_IDLE_NOTIFICATION_COMPLETE_HANDLER;

typedef struct _NDIS_WDI_INIT_PARAMETERS
{
    NDIS_OBJECT_HEADER Header;
    ULONG WdiVersion;
    NDIS_WDI_OPEN_ADAPTER_COMPLETE_HANDLER OpenAdapterCompleteHandler;
    NDIS_WDI_CLOSE_ADAPTER_COMPLETE_HANDLER CloseAdapterCompleteHandler;
    NDIS_WDI_IDLE_NOTIFICATION_CONFIRM_HANDLER UeIdleNotificationConfirm;
    NDIS_WDI_IDLE_NOTIFICATION_COMPLETE_HANDLER UeIdleNotificationComplete;
} NDIS_WDI_INIT_PARAMETERS, *PNDIS_WDI_INIT_PARAMETERS;

#define NDIS_SIZEOF_WDI_INIT_PARAMETERS_REVISION_1 RTL_SIZEOF_THROUGH_FIELD(NDIS_WDI_INIT_PARAMETERS, UeIdleNotificationComplete)

typedef enum {
    DiagnoseLevelNone,
    DiagnoseLevelHardwareRegisters,
    DiagnoseLevelFirmwareImageDump,
    DiagnoseLevelDriverStateDump
} eDiagnoseLevel;

typedef NDIS_STATUS MINIPORT_WDI_ALLOCATE_ADAPTER(NDIS_HANDLE, NDIS_HANDLE, PNDIS_MINIPORT_INIT_PARAMETERS, PNDIS_WDI_INIT_PARAMETERS, PNDIS_MINIPORT_ADAPTER_REGISTRATION_ATTRIBUTES);
typedef VOID MINIPORT_WDI_FREE_ADAPTER(NDIS_HANDLE);
typedef NDIS_STATUS MINIPORT_WDI_OPEN_ADAPTER(NDIS_HANDLE, PNDIS_MINIPORT_INIT_PARAMETERS);
typedef NDIS_STATUS MINIPORT_WDI_CLOSE_ADAPTER(NDIS_HANDLE);
typedef NDIS_STATUS MINIPORT_WDI_START_ADAPTER_OPERATION(NDIS_HANDLE);
typedef VOID MINIPORT_WDI_STOP_ADAPTER_OPERATION(NDIS_HANDLE);
typedef NDIS_STATUS MINIPORT_WDI_POST_ADAPTER_PAUSE(NDIS_HANDLE, PNDIS_MINIPORT_PAUSE_PARAMETERS);
typedef NDIS_STATUS MINIPORT_WDI_POST_ADAPTER_RESTART(NDIS_HANDLE, PNDIS_MINIPORT_RESTART_PARAMETERS);
typedef NDIS_STATUS MINIPORT_WDI_ADAPTER_HANG_DIAGNOSE(NDIS_HANDLE, eDiagnoseLevel, UINT32, UINT8 *, UINT32 *);
typedef NDIS_STATUS MINIPORT_WDI_TAL_TXRX_INITIALIZE(NDIS_HANDLE, NDIS_HANDLE, PNDIS_WDI_DATA_API, PTAL_TXRX_HANDLE, PNDIS_MINIPORT_WDI_DATA_HANDLERS, UINT32 *);
typedef VOID MINIPORT_WDI_TAL_TXRX_DEINITIALIZE(TAL_TXRX_HANDLE);
typedef NDIS_STATUS MINIPORT_WDI_IDLE_NOTIFICATION(NDIS_HANDLE, BOOLEAN);
typedef VOID MINIPORT_WDI_CANCEL_IDLE_NOTIFICATION(NDIS_HANDLE);

typedef MINIPORT_WDI_ALLOCATE_ADAPTER *MINIPORT_WDI_ALLOCATE_ADAPTER_HANDLER;
typedef MINIPORT_WDI_FREE_ADAPTER *MINIPORT_WDI_FREE_ADAPTER_HANDLER;
typedef MINIPORT_WDI_OPEN_ADAPTER *MINIPORT_WDI_OPEN_ADAPTER_HANDLER;
typedef MINIPORT_WDI_CLOSE_ADAPTER *MINIPORT_WDI_CLOSE_ADAPTER_HANDLER;
typedef MINIPORT_WDI_START_ADAPTER_OPERATION *MINIPORT_WDI_START_OPERATION_HANDLER;
typedef MINIPORT_WDI_STOP_ADAPTER_OPERATION *MINIPORT_WDI_STOP_OPERATION_HANDLER;
typedef MINIPORT_WDI_POST_ADAPTER_PAUSE *MINIPORT_WDI_POST_PAUSE_HANDLER;
typedef MINIPORT_WDI_POST_ADAPTER_RESTART *MINIPORT_WDI_POST_RESTART_HANDLER;
typedef MINIPORT_WDI_ADAPTER_HANG_DIAGNOSE *MINIPORT_WDI_HANG_DIAGNOSE_HANDLER;
typedef MINIPORT_WDI_TAL_TXRX_INITIALIZE *MINIPORT_WDI_TAL_TXRX_INITIALIZE_HANDLER;
typedef MINIPORT_WDI_TAL_TXRX_DEINITIALIZE *MINIPORT_WDI_TAL_TXRX_DEINITIALIZE_HANDLER;
typedef MINIPORT_WDI_IDLE_NOTIFICATION *MINIPORT_WDI_IDLE_NOTIFICATION_HANDLER;
typedef MINIPORT_WDI_CANCEL_IDLE_NOTIFICATION *MINIPORT_WDI_CANCEL_IDLE_NOTIFICATION_HANDLER;

typedef struct _NDIS_MINIPORT_DRIVER_WDI_CHARACTERISTICS
{
    NDIS_OBJECT_HEADER Header;
    ULONG WdiVersion;
    MINIPORT_WDI_ALLOCATE_ADAPTER_HANDLER AllocateAdapterHandler;
    MINIPORT_WDI_FREE_ADAPTER_HANDLER FreeAdapterHandler;
    MINIPORT_WDI_OPEN_ADAPTER_HANDLER OpenAdapterHandler;
    MINIPORT_WDI_CLOSE_ADAPTER_HANDLER CloseAdapterHandler;
    MINIPORT_WDI_START_OPERATION_HANDLER StartOperationHandler;
    MINIPORT_WDI_STOP_OPERATION_HANDLER StopOperationHandler;
    MINIPORT_WDI_POST_PAUSE_HANDLER PostPauseHandler;
    MINIPORT_WDI_POST_RESTART_HANDLER PostRestartHandler;
    MINIPORT_WDI_HANG_DIAGNOSE_HANDLER HangDiagnoseHandler;
    MINIPORT_WDI_TAL_TXRX_INITIALIZE_HANDLER TalTxRxInitializeHandler;
    MINIPORT_WDI_TAL_TXRX_DEINITIALIZE_HANDLER TalTxRxDeinitializeHandler;
    MINIPORT_WDI_IDLE_NOTIFICATION_HANDLER LeIdleNotificationHandler;
    MINIPORT_WDI_CANCEL_IDLE_NOTIFICATION_HANDLER LeCancelIdleNotificationHandler;
} NDIS_MINIPORT_DRIVER_WDI_CHARACTERISTICS, *PNDIS_MINIPORT_DRIVER_WDI_CHARACTERISTICS;

#define NDIS_SIZEOF_MINIPORT_WDI_CHARACTERISTICS_REVISION_1 RTL_SIZEOF_THROUGH_FIELD(NDIS_MINIPORT_DRIVER_WDI_CHARACTERISTICS, LeCancelIdleNotificationHandler)

NDIS_STATUS NdisMRegisterWdiMiniportDriver(PDRIVER_OBJECT, PCUNICODE_STRING, NDIS_HANDLE, PNDIS_MINIPORT_DRIVER_CHARACTERISTICS, PNDIS_MINIPORT_DRIVER_WDI_CHARACTERISTICS, PNDIS_HANDLE);
VOID NdisMDeregisterWdiMiniportDriver(NDIS_HANDLE);

#ifdef __cplusplus
}
#endif
#endif
