/*
 * PROJECT:     ReactOS GPIO class extension
 * LICENSE:     GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later)
 * PURPOSE:     Public GPIO client interface version 3
 * COPYRIGHT:   Copyright 2026 Ahmed Arif <arif193@gmail.com>
 */

#pragma once

#ifndef WDFAPI
#error Include wdf.h before gpioclx.h
#endif

WDF_EXTERN_C_START

#define GPIO_CLIENT_VERSION 3
#define GPIO_CONTROLLER_BASIC_INFORMATION_VERSION 1
#define GPIO_CLIENT_REGISTRATION_FLAGS_NONE 0

typedef USHORT PIN_NUMBER, *PPIN_NUMBER;
typedef USHORT BANK_ID, *PBANK_ID;

#define INVALID_PIN_NUMBER ((PIN_NUMBER)-1)
#define MAXIMUM_PIN_NUMBER ((PIN_NUMBER)-1)
#define INVALID_BANK_ID ((BANK_ID)-1)

#define GPIO_PIN_PULL_CONFIGURATION_DEFAULT 0
#define GPIO_PIN_PULL_CONFIGURATION_PULLUP 1
#define GPIO_PIN_PULL_CONFIGURATION_PULLDOWN 2
#define GPIO_PIN_PULL_CONFIGURATION_NONE 3

typedef union _CONTROLLER_ATTRIBUTE_FLAGS
{
    struct
    {
        ULONG MemoryMappedController : 1;
        ULONG ActiveInterruptsAutoClearOnRead : 1;
        ULONG FormatIoRequestsAsMasks : 1;
        ULONG DeviceIdlePowerMgmtSupported : 1;
        ULONG BankIdlePowerMgmtSupported : 1;
        ULONG EmulateDebouncing : 1;
        ULONG EmulateActiveBoth : 1;
        ULONG IndependentIoHwSupported : 1;
        ULONG Reserved : 24;
    };
    ULONG AsULONG;
} CONTROLLER_ATTRIBUTE_FLAGS, *PCONTROLLER_ATTRIBUTE_FLAGS;

typedef struct _CLIENT_CONTROLLER_BASIC_INFORMATION
{
    USHORT Version;
    USHORT Size;
    USHORT TotalPins;
    UCHAR NumberOfPinsPerBank;
    ULONG DeviceIdleTimeout;
    CONTROLLER_ATTRIBUTE_FLAGS Flags;
} CLIENT_CONTROLLER_BASIC_INFORMATION, *PCLIENT_CONTROLLER_BASIC_INFORMATION;

typedef union _GPIO_ENABLE_INTERRUPT_FLAGS { ULONG AsULONG; } GPIO_ENABLE_INTERRUPT_FLAGS;
typedef struct _GPIO_ENABLE_INTERRUPT_PARAMETERS
{
    BANK_ID BankId;
    PIN_NUMBER PinNumber;
    GPIO_ENABLE_INTERRUPT_FLAGS Flags;
    KINTERRUPT_MODE InterruptMode;
    KINTERRUPT_POLARITY Polarity;
    UCHAR PullConfiguration;
    USHORT DebounceTimeout;
    PVOID VendorData;
    ULONG VendorDataLength;
} GPIO_ENABLE_INTERRUPT_PARAMETERS, *PGPIO_ENABLE_INTERRUPT_PARAMETERS;

typedef union _GPIO_DISABLE_INTERRUPT_FLAGS
{
    struct { ULONG RetryDisableOnFailure : 1; ULONG Reserved : 31; };
    ULONG AsULONG;
} GPIO_DISABLE_INTERRUPT_FLAGS;
typedef struct _GPIO_DISABLE_INTERRUPT_PARAMETERS
{
    BANK_ID BankId;
    PIN_NUMBER PinNumber;
    GPIO_DISABLE_INTERRUPT_FLAGS Flags;
} GPIO_DISABLE_INTERRUPT_PARAMETERS, *PGPIO_DISABLE_INTERRUPT_PARAMETERS;

typedef struct _GPIO_QUERY_ENABLED_INTERRUPTS_PARAMETERS
{
    BANK_ID BankId;
    ULONG64 EnabledMask;
} GPIO_QUERY_ENABLED_INTERRUPTS_PARAMETERS, *PGPIO_QUERY_ENABLED_INTERRUPTS_PARAMETERS;

typedef struct _GPIO_MASK_INTERRUPT_PARAMETERS
{
    BANK_ID BankId;
    ULONG64 PinMask;
    ULONG64 FailedMask;
} GPIO_MASK_INTERRUPT_PARAMETERS, *PGPIO_MASK_INTERRUPT_PARAMETERS;

typedef struct _GPIO_QUERY_ACTIVE_INTERRUPTS_PARAMETERS
{
    BANK_ID BankId;
    ULONG64 EnabledMask;
    ULONG64 ActiveMask;
} GPIO_QUERY_ACTIVE_INTERRUPTS_PARAMETERS, *PGPIO_QUERY_ACTIVE_INTERRUPTS_PARAMETERS;

typedef struct _GPIO_CLEAR_ACTIVE_INTERRUPTS_PARAMETERS
{
    BANK_ID BankId;
    ULONG64 ClearActiveMask;
    ULONG64 FailedClearMask;
} GPIO_CLEAR_ACTIVE_INTERRUPTS_PARAMETERS, *PGPIO_CLEAR_ACTIVE_INTERRUPTS_PARAMETERS;

typedef union _GPIO_RECONFIGURE_INTERRUPT_FLAGS { ULONG AsULONG; } GPIO_RECONFIGURE_INTERRUPT_FLAGS;
typedef struct _GPIO_RECONFIGURE_INTERRUPTS_PARAMETERS
{
    BANK_ID BankId;
    PIN_NUMBER PinNumber;
    KINTERRUPT_MODE InterruptMode;
    KINTERRUPT_POLARITY Polarity;
    GPIO_RECONFIGURE_INTERRUPT_FLAGS Flags;
} GPIO_RECONFIGURE_INTERRUPTS_PARAMETERS, *PGPIO_RECONFIGURE_INTERRUPTS_PARAMETERS;

typedef union _GPIO_CONNECT_FUNCTION_CONFIG_PINS_FLAGS { ULONG AsULONG; }
    GPIO_CONNECT_FUNCTION_CONFIG_PINS_FLAGS;
typedef struct _GPIO_CONNECT_FUNCTION_CONFIG_PINS_PARAMETERS
{
    BANK_ID BankId;
    PPIN_NUMBER PinNumberTable;
    USHORT PinCount;
    ULONG FunctionNumber;
    UCHAR PullConfiguration;
    PVOID VendorData;
    ULONG VendorDataLength;
    GPIO_CONNECT_FUNCTION_CONFIG_PINS_FLAGS ConnectFlags;
} GPIO_CONNECT_FUNCTION_CONFIG_PINS_PARAMETERS, *PGPIO_CONNECT_FUNCTION_CONFIG_PINS_PARAMETERS;

typedef union _GPIO_DISCONNECT_FUNCTION_CONFIG_PINS_FLAGS { ULONG AsULONG; }
    GPIO_DISCONNECT_FUNCTION_CONFIG_PINS_FLAGS;
typedef struct _GPIO_DISCONNECT_FUNCTION_CONFIG_PINS_PARAMETERS
{
    BANK_ID BankId;
    PPIN_NUMBER PinNumberTable;
    ULONG PinCount;
    GPIO_DISCONNECT_FUNCTION_CONFIG_PINS_FLAGS DisconnectFlags;
} GPIO_DISCONNECT_FUNCTION_CONFIG_PINS_PARAMETERS, *PGPIO_DISCONNECT_FUNCTION_CONFIG_PINS_PARAMETERS;

typedef enum _GPIO_CONNECT_IO_PINS_MODE
{
    ConnectModeInvalid,
    ConnectModeInput,
    ConnectModeOutput,
    ConnectModeMaximum = ConnectModeOutput
} GPIO_CONNECT_IO_PINS_MODE, *PGPIO_CONNECT_IO_PINS_MODE;

typedef union _GPIO_CONNECT_IO_PINS_FLAGS { ULONG AsULONG; } GPIO_CONNECT_IO_PINS_FLAGS;
typedef struct _GPIO_CONNECT_IO_PINS_PARAMETERS
{
    BANK_ID BankId;
    PPIN_NUMBER PinNumberTable;
    USHORT PinCount;
    GPIO_CONNECT_IO_PINS_MODE ConnectMode;
    UCHAR PullConfiguration;
    USHORT DebounceTimeout;
    USHORT DriveStrength;
    PVOID VendorData;
    ULONG VendorDataLength;
    GPIO_CONNECT_IO_PINS_FLAGS ConnectFlags;
} GPIO_CONNECT_IO_PINS_PARAMETERS, *PGPIO_CONNECT_IO_PINS_PARAMETERS;

typedef union _GPIO_DISCONNECT_IO_PINS_FLAGS
{
    struct { ULONG PreserveConfiguration : 1; ULONG Reserved : 31; };
    ULONG AsULONG;
} GPIO_DISCONNECT_IO_PINS_FLAGS;
typedef struct _GPIO_DISCONNECT_IO_PINS_PARAMETERS
{
    BANK_ID BankId;
    PPIN_NUMBER PinNumberTable;
    ULONG PinCount;
    GPIO_CONNECT_IO_PINS_MODE DisconnectMode;
    GPIO_DISCONNECT_IO_PINS_FLAGS DisconnectFlags;
} GPIO_DISCONNECT_IO_PINS_PARAMETERS, *PGPIO_DISCONNECT_IO_PINS_PARAMETERS;

typedef union _GPIO_READ_PINS_FLAGS
{
    struct { ULONG WriteConfiguredPins : 1; ULONG Reserved : 31; };
    ULONG AsULONG;
} GPIO_READ_PINS_FLAGS;
typedef struct _GPIO_READ_PINS_MASK_PARAMETERS
{
    BANK_ID BankId;
    PULONG64 PinValues;
    GPIO_READ_PINS_FLAGS Flags;
    PVOID Reserved;
} GPIO_READ_PINS_MASK_PARAMETERS, *PGPIO_READ_PINS_MASK_PARAMETERS;

typedef union _GPIO_WRITE_PINS_FLAGS { ULONG AsULONG; } GPIO_WRITE_PINS_FLAGS;
typedef struct _GPIO_WRITE_PINS_MASK_PARAMETERS
{
    BANK_ID BankId;
    ULONG64 SetMask;
    ULONG64 ClearMask;
    GPIO_WRITE_PINS_FLAGS Flags;
    PVOID Reserved;
} GPIO_WRITE_PINS_MASK_PARAMETERS, *PGPIO_WRITE_PINS_MASK_PARAMETERS;

typedef NTSTATUS (NTAPI GPIO_CLIENT_PREPARE_CONTROLLER)(WDFDEVICE, PVOID, WDFCMRESLIST, WDFCMRESLIST);
typedef GPIO_CLIENT_PREPARE_CONTROLLER *PGPIO_CLIENT_PREPARE_CONTROLLER;
typedef NTSTATUS (NTAPI GPIO_CLIENT_RELEASE_CONTROLLER)(WDFDEVICE, PVOID);
typedef GPIO_CLIENT_RELEASE_CONTROLLER *PGPIO_CLIENT_RELEASE_CONTROLLER;
typedef NTSTATUS (NTAPI GPIO_CLIENT_START_CONTROLLER)(PVOID, BOOLEAN, WDF_POWER_DEVICE_STATE);
typedef GPIO_CLIENT_START_CONTROLLER *PGPIO_CLIENT_START_CONTROLLER;
typedef NTSTATUS (NTAPI GPIO_CLIENT_STOP_CONTROLLER)(PVOID, BOOLEAN, WDF_POWER_DEVICE_STATE);
typedef GPIO_CLIENT_STOP_CONTROLLER *PGPIO_CLIENT_STOP_CONTROLLER;
typedef NTSTATUS (NTAPI GPIO_CLIENT_QUERY_CONTROLLER_BASIC_INFORMATION)(PVOID, PCLIENT_CONTROLLER_BASIC_INFORMATION);
typedef GPIO_CLIENT_QUERY_CONTROLLER_BASIC_INFORMATION *PGPIO_CLIENT_QUERY_CONTROLLER_BASIC_INFORMATION;
typedef NTSTATUS (NTAPI GPIO_CLIENT_ENABLE_INTERRUPT)(PVOID, PGPIO_ENABLE_INTERRUPT_PARAMETERS);
typedef GPIO_CLIENT_ENABLE_INTERRUPT *PGPIO_CLIENT_ENABLE_INTERRUPT;
typedef NTSTATUS (NTAPI GPIO_CLIENT_DISABLE_INTERRUPT)(PVOID, PGPIO_DISABLE_INTERRUPT_PARAMETERS);
typedef GPIO_CLIENT_DISABLE_INTERRUPT *PGPIO_CLIENT_DISABLE_INTERRUPT;
typedef NTSTATUS (NTAPI GPIO_CLIENT_UNMASK_INTERRUPT)(PVOID, PGPIO_ENABLE_INTERRUPT_PARAMETERS);
typedef GPIO_CLIENT_UNMASK_INTERRUPT *PGPIO_CLIENT_UNMASK_INTERRUPT;
typedef NTSTATUS (NTAPI GPIO_CLIENT_MASK_INTERRUPTS)(PVOID, PGPIO_MASK_INTERRUPT_PARAMETERS);
typedef GPIO_CLIENT_MASK_INTERRUPTS *PGPIO_CLIENT_MASK_INTERRUPTS;
typedef NTSTATUS (NTAPI GPIO_CLIENT_QUERY_ACTIVE_INTERRUPTS)(PVOID, PGPIO_QUERY_ACTIVE_INTERRUPTS_PARAMETERS);
typedef GPIO_CLIENT_QUERY_ACTIVE_INTERRUPTS *PGPIO_CLIENT_QUERY_ACTIVE_INTERRUPTS;
typedef NTSTATUS (NTAPI GPIO_CLIENT_CLEAR_ACTIVE_INTERRUPTS)(PVOID, PGPIO_CLEAR_ACTIVE_INTERRUPTS_PARAMETERS);
typedef GPIO_CLIENT_CLEAR_ACTIVE_INTERRUPTS *PGPIO_CLIENT_CLEAR_ACTIVE_INTERRUPTS;
typedef NTSTATUS (NTAPI GPIO_CLIENT_PRE_PROCESS_CONTROLLER_INTERRUPT)(PVOID, BANK_ID, ULONG64);
typedef GPIO_CLIENT_PRE_PROCESS_CONTROLLER_INTERRUPT *PGPIO_CLIENT_PRE_PROCESS_CONTROLLER_INTERRUPT;
typedef NTSTATUS (NTAPI GPIO_CLIENT_RECONFIGURE_INTERRUPT)(PVOID, PGPIO_RECONFIGURE_INTERRUPTS_PARAMETERS);
typedef GPIO_CLIENT_RECONFIGURE_INTERRUPT *PGPIO_CLIENT_RECONFIGURE_INTERRUPT;
typedef NTSTATUS (NTAPI GPIO_CLIENT_QUERY_ENABLED_INTERRUPTS)(PVOID, PGPIO_QUERY_ENABLED_INTERRUPTS_PARAMETERS);
typedef GPIO_CLIENT_QUERY_ENABLED_INTERRUPTS *PGPIO_CLIENT_QUERY_ENABLED_INTERRUPTS;
typedef NTSTATUS (NTAPI GPIO_CLIENT_CONNECT_FUNCTION_CONFIG_PINS)(PVOID, PGPIO_CONNECT_FUNCTION_CONFIG_PINS_PARAMETERS);
typedef GPIO_CLIENT_CONNECT_FUNCTION_CONFIG_PINS *PGPIO_CLIENT_CONNECT_FUNCTION_CONFIG_PINS;
typedef NTSTATUS (NTAPI GPIO_CLIENT_DISCONNECT_FUNCTION_CONFIG_PINS)(PVOID, PGPIO_DISCONNECT_FUNCTION_CONFIG_PINS_PARAMETERS);
typedef GPIO_CLIENT_DISCONNECT_FUNCTION_CONFIG_PINS *PGPIO_CLIENT_DISCONNECT_FUNCTION_CONFIG_PINS;
typedef NTSTATUS (NTAPI GPIO_CLIENT_CONNECT_IO_PINS)(PVOID, PGPIO_CONNECT_IO_PINS_PARAMETERS);
typedef GPIO_CLIENT_CONNECT_IO_PINS *PGPIO_CLIENT_CONNECT_IO_PINS;
typedef NTSTATUS (NTAPI GPIO_CLIENT_DISCONNECT_IO_PINS)(PVOID, PGPIO_DISCONNECT_IO_PINS_PARAMETERS);
typedef GPIO_CLIENT_DISCONNECT_IO_PINS *PGPIO_CLIENT_DISCONNECT_IO_PINS;
typedef NTSTATUS (NTAPI GPIO_CLIENT_READ_PINS_MASK)(PVOID, PGPIO_READ_PINS_MASK_PARAMETERS);
typedef GPIO_CLIENT_READ_PINS_MASK *PGPIO_CLIENT_READ_PINS_MASK;
typedef NTSTATUS (NTAPI GPIO_CLIENT_WRITE_PINS_MASK)(PVOID, PGPIO_WRITE_PINS_MASK_PARAMETERS);
typedef GPIO_CLIENT_WRITE_PINS_MASK *PGPIO_CLIENT_WRITE_PINS_MASK;

typedef struct _GPIO_CLIENT_REGISTRATION_PACKET
{
    USHORT Version;
    USHORT Size;
    ULONG Flags;
    ULONG ControllerContextSize;
    ULONG64 Reserved;
    PGPIO_CLIENT_PREPARE_CONTROLLER CLIENT_PrepareController;
    PGPIO_CLIENT_RELEASE_CONTROLLER CLIENT_ReleaseController;
    PGPIO_CLIENT_START_CONTROLLER CLIENT_StartController;
    PGPIO_CLIENT_STOP_CONTROLLER CLIENT_StopController;
    PGPIO_CLIENT_QUERY_CONTROLLER_BASIC_INFORMATION CLIENT_QueryControllerBasicInformation;
    PVOID CLIENT_QuerySetControllerInformation;
    PGPIO_CLIENT_ENABLE_INTERRUPT CLIENT_EnableInterrupt;
    PGPIO_CLIENT_DISABLE_INTERRUPT CLIENT_DisableInterrupt;
    PGPIO_CLIENT_UNMASK_INTERRUPT CLIENT_UnmaskInterrupt;
    PGPIO_CLIENT_MASK_INTERRUPTS CLIENT_MaskInterrupts;
    PGPIO_CLIENT_QUERY_ACTIVE_INTERRUPTS CLIENT_QueryActiveInterrupts;
    PGPIO_CLIENT_CLEAR_ACTIVE_INTERRUPTS CLIENT_ClearActiveInterrupts;
    PGPIO_CLIENT_CONNECT_IO_PINS CLIENT_ConnectIoPins;
    PGPIO_CLIENT_DISCONNECT_IO_PINS CLIENT_DisconnectIoPins;
    union { PVOID CLIENT_ReadGpioPins; PGPIO_CLIENT_READ_PINS_MASK CLIENT_ReadGpioPinsUsingMask; };
    union { PVOID CLIENT_WriteGpioPins; PGPIO_CLIENT_WRITE_PINS_MASK CLIENT_WriteGpioPinsUsingMask; };
    PVOID CLIENT_SaveBankHardwareContext;
    PVOID CLIENT_RestoreBankHardwareContext;
    PGPIO_CLIENT_PRE_PROCESS_CONTROLLER_INTERRUPT CLIENT_PreProcessControllerInterrupt;
    PVOID CLIENT_ControllerSpecificFunction;
    PGPIO_CLIENT_RECONFIGURE_INTERRUPT CLIENT_ReconfigureInterrupt;
    PGPIO_CLIENT_QUERY_ENABLED_INTERRUPTS CLIENT_QueryEnabledInterrupts;
    PGPIO_CLIENT_CONNECT_FUNCTION_CONFIG_PINS CLIENT_ConnectFunctionConfigPins;
    PGPIO_CLIENT_DISCONNECT_FUNCTION_CONFIG_PINS CLIENT_DisconnectFunctionConfigPins;
} GPIO_CLIENT_REGISTRATION_PACKET, *PGPIO_CLIENT_REGISTRATION_PACKET;

typedef NTSTATUS (NTAPI GPIO_CLX_REGISTER_CLIENT)(WDFDRIVER, PGPIO_CLIENT_REGISTRATION_PACKET, PUNICODE_STRING);
typedef NTSTATUS (NTAPI GPIO_CLX_UNREGISTER_CLIENT)(WDFDRIVER);
typedef NTSTATUS (NTAPI GPIO_CLX_PROCESS_ADD_DEVICE_PRE_DEVICE_CREATE)(WDFDRIVER, PWDFDEVICE_INIT, PWDF_OBJECT_ATTRIBUTES);
typedef NTSTATUS (NTAPI GPIO_CLX_PROCESS_ADD_DEVICE_POST_DEVICE_CREATE)(WDFDRIVER, WDFDEVICE);
typedef VOID (NTAPI GPIO_CLX_ACQUIRE_INTERRUPT_LOCK)(PVOID, BANK_ID);
typedef VOID (NTAPI GPIO_CLX_RELEASE_INTERRUPT_LOCK)(PVOID, BANK_ID);

typedef enum _GPIO_CLX_EXPORT_INDEX
{
    RegisterClientIndex,
    UnregisterClientIndex,
    AddDevicePreDeviceCreateIndex,
    AddDevicePostDeviceCreateIndex,
    AcquireInterruptLockIndex,
    ReleaseInterruptLockIndex,
    GpioExportLastExportIndex
} GPIO_CLX_EXPORT_INDEX;

typedef VOID (*PGPIO_CLX_EXPORTED_INTERFACES)(VOID);
extern PGPIO_CLX_EXPORTED_INTERFACES GpioClxExportedInterfaces[GpioExportLastExportIndex];

FORCEINLINE NTSTATUS GPIO_CLX_RegisterClient(WDFDRIVER Driver, PGPIO_CLIENT_REGISTRATION_PACKET Packet,
                                             PUNICODE_STRING RegistryPath)
{
    return ((GPIO_CLX_REGISTER_CLIENT *)GpioClxExportedInterfaces[RegisterClientIndex])(
        Driver, Packet, RegistryPath);
}
FORCEINLINE NTSTATUS GPIO_CLX_UnregisterClient(WDFDRIVER Driver)
{
    return ((GPIO_CLX_UNREGISTER_CLIENT *)GpioClxExportedInterfaces[UnregisterClientIndex])(Driver);
}
FORCEINLINE NTSTATUS GPIO_CLX_ProcessAddDevicePreDeviceCreate(WDFDRIVER Driver, PWDFDEVICE_INIT DeviceInit,
                                                              PWDF_OBJECT_ATTRIBUTES Attributes)
{
    return ((GPIO_CLX_PROCESS_ADD_DEVICE_PRE_DEVICE_CREATE *)
        GpioClxExportedInterfaces[AddDevicePreDeviceCreateIndex])(Driver, DeviceInit, Attributes);
}
FORCEINLINE NTSTATUS GPIO_CLX_ProcessAddDevicePostDeviceCreate(WDFDRIVER Driver, WDFDEVICE Device)
{
    return ((GPIO_CLX_PROCESS_ADD_DEVICE_POST_DEVICE_CREATE *)
        GpioClxExportedInterfaces[AddDevicePostDeviceCreateIndex])(Driver, Device);
}
FORCEINLINE VOID GPIO_CLX_AcquireInterruptLock(PVOID Context, BANK_ID BankId)
{
    ((GPIO_CLX_ACQUIRE_INTERRUPT_LOCK *)GpioClxExportedInterfaces[AcquireInterruptLockIndex])(Context, BankId);
}
FORCEINLINE VOID GPIO_CLX_ReleaseInterruptLock(PVOID Context, BANK_ID BankId)
{
    ((GPIO_CLX_RELEASE_INTERRUPT_LOCK *)GpioClxExportedInterfaces[ReleaseInterruptLockIndex])(Context, BankId);
}

WDF_EXTERN_C_END
