/*
 * PROJECT:     ReactOS serial class extension
 * LICENSE:     GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later)
 * PURPOSE:     Public SerCx2 client interface
 * COPYRIGHT:   Copyright 2026 Ahmed Arif <arif193@gmail.com>
 */

#pragma once

#ifndef WDFAPI
#error Include wdf.h before SerCx.h
#endif

WDF_EXTERN_C_START

DECLARE_HANDLE(SERCX2SYSTEMDMATRANSMIT);
DECLARE_HANDLE(SERCX2SYSTEMDMARECEIVE);
DECLARE_HANDLE(SERCX2PIOTRANSMIT);
DECLARE_HANDLE(SERCX2PIORECEIVE);
DECLARE_HANDLE(SERCX2CUSTOMTRANSMIT);
DECLARE_HANDLE(SERCX2CUSTOMRECEIVE);
DECLARE_HANDLE(SERCX2CUSTOMTRANSMITTRANSACTION);
DECLARE_HANDLE(SERCX2CUSTOMRECEIVETRANSACTION);

typedef enum _SERCX2_TRANSACTION_TYPE
{
    SerCx2TransactionTypeInvalid = 0,
    SerCx2TransactionTypePio,
    SerCx2TransactionTypeSystemDma,
    SerCx2TransactionTypeCustom,
    SerCx2TransactionTypeMax
} SERCX2_TRANSACTION_TYPE, *PSERCX2_TRANSACTION_TYPE;

typedef enum _SERCX2_CUSTOM_RECEIVE_TRANSACTION_PROGRESS
{
    SerCx2CustomReceiveTransactionNoProgress = 0,
    SerCx2CustomReceiveTransactionBytesTransferred
} SERCX2_CUSTOM_RECEIVE_TRANSACTION_PROGRESS, *PSERCX2_CUSTOM_RECEIVE_TRANSACTION_PROGRESS;

typedef VOID (*SERCXFUNC)(VOID);
extern SERCXFUNC SercxFunctions[];
typedef struct _WDF_DRIVER_GLOBALS SERCX_DRIVER_GLOBALS, *PSERCX_DRIVER_GLOBALS;
extern PSERCX_DRIVER_GLOBALS SercxDriverGlobals;

typedef enum _SERCXFUNCENUM
{
    SerCx2InitializeDeviceInitTableIndex = 0,
    SerCx2InitializeDeviceTableIndex,
    SerCx2CompleteWaitTableIndex,
    SerCx2PioTransmitCreateTableIndex,
    SerCx2PioReceiveCreateTableIndex,
    SerCx2SystemDmaTransmitCreateTableIndex,
    SerCx2SystemDmaReceiveCreateTableIndex,
    SerCx2SystemDmaTransmitGetDmaEnablerTableIndex,
    SerCx2SystemDmaReceiveGetDmaEnablerTableIndex,
    SerCx2SystemDmaTransmitInitializeTransactionCompleteTableIndex,
    SerCx2SystemDmaReceiveInitializeTransactionCompleteTableIndex,
    SerCx2SystemDmaTransmitCleanupTransactionCompleteTableIndex,
    SerCx2SystemDmaReceiveCleanupTransactionCompleteTableIndex,
    SerCx2SystemDmaReceiveNewDataNotificationTableIndex,
    SerCx2PioTransmitInitializeTransactionCompleteTableIndex,
    SerCx2PioReceiveInitializeTransactionCompleteTableIndex,
    SerCx2PioTransmitCleanupTransactionCompleteTableIndex,
    SerCx2PioReceiveCleanupTransactionCompleteTableIndex,
    SerCx2PioTransmitReadyTableIndex,
    SerCx2PioReceiveReadyTableIndex,
    SerCx2SaveReceiveFifoOnD0ExitTableIndex,
    SerCx2PioTransmitDrainFifoCompleteTableIndex,
    SerCx2PioTransmitPurgeFifoCompleteTableIndex,
    SerCx2SystemDmaTransmitDrainFifoCompleteTableIndex,
    SerCx2SystemDmaTransmitPurgeFifoCompleteTableIndex,
    SerCx2CustomTransmitCreateTableIndex,
    SerCx2CustomReceiveCreateTableIndex,
    SerCx2CustomTransmitTransactionCreateTableIndex,
    SerCx2CustomReceiveTransactionCreateTableIndex,
    SerCx2CustomTransmitTransactionInitializeCompleteTableIndex,
    SerCx2CustomReceiveTransactionInitializeCompleteTableIndex,
    SerCx2CustomTransmitTransactionCleanupCompleteTableIndex,
    SerCx2CustomReceiveTransactionCleanupCompleteTableIndex,
    SerCx2CustomReceiveTransactionNewDataNotificationTableIndex,
    SerCx2CustomReceiveTransactionReportProgressTableIndex,
    SercxFunctionTableNumEntries
} SERCXFUNCENUM;

typedef NTSTATUS EVT_SERCX2_FILEOPEN(WDFDEVICE Device);
typedef EVT_SERCX2_FILEOPEN *PFN_SERCX2_FILEOPEN;
typedef VOID EVT_SERCX2_FILECLOSE(WDFDEVICE Device);
typedef EVT_SERCX2_FILECLOSE *PFN_SERCX2_FILECLOSE;
typedef VOID EVT_SERCX2_SET_WAIT_MASK(WDFDEVICE Device, WDFREQUEST Request, ULONG WaitMask);
typedef EVT_SERCX2_SET_WAIT_MASK *PFN_SERCX2_SET_WAIT_MASK;
typedef VOID EVT_SERCX2_PURGE_FIFOS(WDFDEVICE Device, BOOLEAN PurgeRxFifo, BOOLEAN PurgeTxFifo);
typedef EVT_SERCX2_PURGE_FIFOS *PFN_SERCX2_PURGE_FIFOS;
typedef NTSTATUS EVT_SERCX2_CONTROL(WDFDEVICE Device, WDFREQUEST Request, size_t OutputBufferLength,
                                    size_t InputBufferLength, ULONG IoControlCode);
typedef EVT_SERCX2_CONTROL *PFN_SERCX2_CONTROL;
typedef NTSTATUS EVT_SERCX2_APPLY_CONFIG(WDFDEVICE Device, PVOID ConnectionParameters);
typedef EVT_SERCX2_APPLY_CONFIG *PFN_SERCX2_APPLY_CONFIG;

typedef ULONG EVT_SERCX2_PIO_TRANSMIT_WRITE_BUFFER(SERCX2PIOTRANSMIT, PUCHAR, ULONG);
typedef EVT_SERCX2_PIO_TRANSMIT_WRITE_BUFFER *PFN_SERCX2_PIO_TRANSMIT_WRITE_BUFFER;
typedef ULONG EVT_SERCX2_PIO_RECEIVE_READ_BUFFER(SERCX2PIORECEIVE, PUCHAR, ULONG);
typedef EVT_SERCX2_PIO_RECEIVE_READ_BUFFER *PFN_SERCX2_PIO_RECEIVE_READ_BUFFER;
typedef VOID EVT_SERCX2_PIO_TRANSMIT_ENABLE_READY_NOTIFICATION(SERCX2PIOTRANSMIT);
typedef EVT_SERCX2_PIO_TRANSMIT_ENABLE_READY_NOTIFICATION *PFN_SERCX2_PIO_TRANSMIT_ENABLE_READY_NOTIFICATION;
typedef VOID EVT_SERCX2_PIO_RECEIVE_ENABLE_READY_NOTIFICATION(SERCX2PIORECEIVE);
typedef EVT_SERCX2_PIO_RECEIVE_ENABLE_READY_NOTIFICATION *PFN_SERCX2_PIO_RECEIVE_ENABLE_READY_NOTIFICATION;
typedef BOOLEAN EVT_SERCX2_PIO_TRANSMIT_CANCEL_READY_NOTIFICATION(SERCX2PIOTRANSMIT);
typedef EVT_SERCX2_PIO_TRANSMIT_CANCEL_READY_NOTIFICATION *PFN_SERCX2_PIO_TRANSMIT_CANCEL_READY_NOTIFICATION;
typedef BOOLEAN EVT_SERCX2_PIO_RECEIVE_CANCEL_READY_NOTIFICATION(SERCX2PIORECEIVE);
typedef EVT_SERCX2_PIO_RECEIVE_CANCEL_READY_NOTIFICATION *PFN_SERCX2_PIO_RECEIVE_CANCEL_READY_NOTIFICATION;
typedef VOID EVT_SERCX2_PIO_TRANSMIT_DRAIN_FIFO(SERCX2PIOTRANSMIT);
typedef EVT_SERCX2_PIO_TRANSMIT_DRAIN_FIFO *PFN_SERCX2_PIO_TRANSMIT_DRAIN_FIFO;
typedef BOOLEAN EVT_SERCX2_PIO_TRANSMIT_CANCEL_DRAIN_FIFO(SERCX2PIOTRANSMIT);
typedef EVT_SERCX2_PIO_TRANSMIT_CANCEL_DRAIN_FIFO *PFN_SERCX2_PIO_TRANSMIT_CANCEL_DRAIN_FIFO;
typedef VOID EVT_SERCX2_PIO_TRANSMIT_PURGE_FIFO(SERCX2PIOTRANSMIT, ULONG);
typedef EVT_SERCX2_PIO_TRANSMIT_PURGE_FIFO *PFN_SERCX2_PIO_TRANSMIT_PURGE_FIFO;

typedef VOID EVT_SERCX2_PIO_TRANSMIT_INITIALIZE_TRANSACTION(SERCX2PIOTRANSMIT, ULONG);
typedef EVT_SERCX2_PIO_TRANSMIT_INITIALIZE_TRANSACTION *PFN_SERCX2_PIO_TRANSMIT_INITIALIZE_TRANSACTION;
typedef VOID EVT_SERCX2_PIO_RECEIVE_INITIALIZE_TRANSACTION(SERCX2PIORECEIVE, ULONG);
typedef EVT_SERCX2_PIO_RECEIVE_INITIALIZE_TRANSACTION *PFN_SERCX2_PIO_RECEIVE_INITIALIZE_TRANSACTION;
typedef VOID EVT_SERCX2_PIO_TRANSMIT_CLEANUP_TRANSACTION(SERCX2PIOTRANSMIT);
typedef EVT_SERCX2_PIO_TRANSMIT_CLEANUP_TRANSACTION *PFN_SERCX2_PIO_TRANSMIT_CLEANUP_TRANSACTION;
typedef VOID EVT_SERCX2_PIO_RECEIVE_CLEANUP_TRANSACTION(SERCX2PIORECEIVE);
typedef EVT_SERCX2_PIO_RECEIVE_CLEANUP_TRANSACTION *PFN_SERCX2_PIO_RECEIVE_CLEANUP_TRANSACTION;

typedef VOID EVT_SERCX2_SYSTEM_DMA_RECEIVE_ENABLE_NEW_DATA_NOTIFICATION(SERCX2SYSTEMDMARECEIVE);
typedef EVT_SERCX2_SYSTEM_DMA_RECEIVE_ENABLE_NEW_DATA_NOTIFICATION
    *PFN_SERCX2_SYSTEM_DMA_RECEIVE_ENABLE_NEW_DATA_NOTIFICATION;
typedef BOOLEAN EVT_SERCX2_SYSTEM_DMA_RECEIVE_CANCEL_NEW_DATA_NOTIFICATION(SERCX2SYSTEMDMARECEIVE);
typedef EVT_SERCX2_SYSTEM_DMA_RECEIVE_CANCEL_NEW_DATA_NOTIFICATION
    *PFN_SERCX2_SYSTEM_DMA_RECEIVE_CANCEL_NEW_DATA_NOTIFICATION;
typedef VOID EVT_SERCX2_SYSTEM_DMA_TRANSMIT_DRAIN_FIFO(SERCX2SYSTEMDMATRANSMIT);
typedef EVT_SERCX2_SYSTEM_DMA_TRANSMIT_DRAIN_FIFO *PFN_SERCX2_SYSTEM_DMA_TRANSMIT_DRAIN_FIFO;
typedef BOOLEAN EVT_SERCX2_SYSTEM_DMA_TRANSMIT_CANCEL_DRAIN_FIFO(SERCX2SYSTEMDMATRANSMIT);
typedef EVT_SERCX2_SYSTEM_DMA_TRANSMIT_CANCEL_DRAIN_FIFO *PFN_SERCX2_SYSTEM_DMA_TRANSMIT_CANCEL_DRAIN_FIFO;
typedef VOID EVT_SERCX2_SYSTEM_DMA_TRANSMIT_PURGE_FIFO(SERCX2SYSTEMDMATRANSMIT, ULONG);
typedef EVT_SERCX2_SYSTEM_DMA_TRANSMIT_PURGE_FIFO *PFN_SERCX2_SYSTEM_DMA_TRANSMIT_PURGE_FIFO;
typedef VOID EVT_SERCX2_SELECT_NEXT_TRANSMIT_TRANSACTION_TYPE(WDFDEVICE, WDFREQUEST, ULONG, PSERCX2_TRANSACTION_TYPE);
typedef EVT_SERCX2_SELECT_NEXT_TRANSMIT_TRANSACTION_TYPE *PFN_SERCX2_SELECT_NEXT_TRANSMIT_TRANSACTION_TYPE;
typedef VOID EVT_SERCX2_SELECT_NEXT_RECEIVE_TRANSACTION_TYPE(WDFDEVICE, WDFREQUEST, ULONG, PSERCX2_TRANSACTION_TYPE);
typedef EVT_SERCX2_SELECT_NEXT_RECEIVE_TRANSACTION_TYPE *PFN_SERCX2_SELECT_NEXT_RECEIVE_TRANSACTION_TYPE;
typedef VOID EVT_SERCX2_SYSTEM_DMA_TRANSMIT_INITIALIZE_TRANSACTION(SERCX2SYSTEMDMATRANSMIT, WDFREQUEST, ULONG);
typedef EVT_SERCX2_SYSTEM_DMA_TRANSMIT_INITIALIZE_TRANSACTION *PFN_SERCX2_SYSTEM_DMA_TRANSMIT_INITIALIZE_TRANSACTION;
typedef VOID EVT_SERCX2_SYSTEM_DMA_TRANSMIT_CLEANUP_TRANSACTION(SERCX2SYSTEMDMATRANSMIT);
typedef EVT_SERCX2_SYSTEM_DMA_TRANSMIT_CLEANUP_TRANSACTION *PFN_SERCX2_SYSTEM_DMA_TRANSMIT_CLEANUP_TRANSACTION;
typedef VOID EVT_SERCX2_SYSTEM_DMA_TRANSMIT_CONFIGURE_DMA(SERCX2SYSTEMDMATRANSMIT, WDFREQUEST, ULONG, WDFDMATRANSACTION);
typedef EVT_SERCX2_SYSTEM_DMA_TRANSMIT_CONFIGURE_DMA *PFN_SERCX2_SYSTEM_DMA_TRANSMIT_CONFIGURE_DMA;
typedef VOID EVT_SERCX2_SYSTEM_DMA_RECEIVE_INITIALIZE_TRANSACTION(SERCX2SYSTEMDMARECEIVE, WDFREQUEST, ULONG);
typedef EVT_SERCX2_SYSTEM_DMA_RECEIVE_INITIALIZE_TRANSACTION *PFN_SERCX2_SYSTEM_DMA_RECEIVE_INITIALIZE_TRANSACTION;
typedef VOID EVT_SERCX2_SYSTEM_DMA_RECEIVE_CLEANUP_TRANSACTION(SERCX2SYSTEMDMARECEIVE);
typedef EVT_SERCX2_SYSTEM_DMA_RECEIVE_CLEANUP_TRANSACTION *PFN_SERCX2_SYSTEM_DMA_RECEIVE_CLEANUP_TRANSACTION;
typedef VOID EVT_SERCX2_SYSTEM_DMA_RECEIVE_CONFIGURE_DMA(SERCX2SYSTEMDMARECEIVE, WDFREQUEST, ULONG, WDFDMATRANSACTION);
typedef EVT_SERCX2_SYSTEM_DMA_RECEIVE_CONFIGURE_DMA *PFN_SERCX2_SYSTEM_DMA_RECEIVE_CONFIGURE_DMA;
typedef VOID EVT_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_INITIALIZE(SERCX2CUSTOMTRANSMITTRANSACTION, WDFREQUEST, ULONG);
typedef EVT_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_INITIALIZE *PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_INITIALIZE;
typedef VOID EVT_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CLEANUP(SERCX2CUSTOMTRANSMITTRANSACTION);
typedef EVT_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CLEANUP *PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CLEANUP;
typedef VOID EVT_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_START(SERCX2CUSTOMTRANSMITTRANSACTION, WDFREQUEST, ULONG);
typedef EVT_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_START *PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_START;
typedef VOID EVT_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CANCEL(SERCX2CUSTOMTRANSMITTRANSACTION);
typedef EVT_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CANCEL *PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CANCEL;
typedef VOID EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_INITIALIZE(SERCX2CUSTOMRECEIVETRANSACTION, WDFREQUEST, ULONG);
typedef EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_INITIALIZE *PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_INITIALIZE;
typedef VOID EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CLEANUP(SERCX2CUSTOMRECEIVETRANSACTION);
typedef EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CLEANUP *PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CLEANUP;
typedef VOID EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_START(SERCX2CUSTOMRECEIVETRANSACTION, WDFREQUEST, ULONG);
typedef EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_START *PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_START;
typedef VOID EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CANCEL(SERCX2CUSTOMRECEIVETRANSACTION);
typedef EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CANCEL *PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CANCEL;
typedef VOID EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_ENABLE_NEW_DATA_NOTIFICATION(SERCX2CUSTOMRECEIVETRANSACTION);
typedef EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_ENABLE_NEW_DATA_NOTIFICATION
    *PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_ENABLE_NEW_DATA_NOTIFICATION;
typedef BOOLEAN EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CANCEL_NEW_DATA_NOTIFICATION(SERCX2CUSTOMRECEIVETRANSACTION);
typedef EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CANCEL_NEW_DATA_NOTIFICATION
    *PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CANCEL_NEW_DATA_NOTIFICATION;
typedef SERCX2_CUSTOM_RECEIVE_TRANSACTION_PROGRESS
    EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_QUERY_PROGRESS(SERCX2CUSTOMRECEIVETRANSACTION);
typedef EVT_SERCX2_CUSTOM_RECEIVE_TRANSACTION_QUERY_PROGRESS *PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_QUERY_PROGRESS;

typedef struct _SERCX2_SYSTEM_DMA_TRANSMIT_CONFIG
{
    ULONG Size;
    BOOLEAN Exclusive;
    ULONG MinimumTransactionLength;
    ULONG MaximumTransactionLength;
    ULONG MinimumTransferUnit;
    PFN_SERCX2_SYSTEM_DMA_TRANSMIT_INITIALIZE_TRANSACTION EvtSerCx2SystemDmaTransmitInitializeTransaction;
    PFN_SERCX2_SYSTEM_DMA_TRANSMIT_CLEANUP_TRANSACTION EvtSerCx2SystemDmaTransmitCleanupTransaction;
    PFN_SERCX2_SYSTEM_DMA_TRANSMIT_CONFIGURE_DMA EvtSerCx2SystemDmaTransmitConfigureDma;
    PFN_SERCX2_SYSTEM_DMA_TRANSMIT_DRAIN_FIFO EvtSerCx2SystemDmaTransmitDrainFifo;
    PFN_SERCX2_SYSTEM_DMA_TRANSMIT_CANCEL_DRAIN_FIFO EvtSerCx2SystemDmaTransmitCancelDrainFifo;
    PFN_SERCX2_SYSTEM_DMA_TRANSMIT_PURGE_FIFO EvtSerCx2SystemDmaTransmitPurgeFifo;
} SERCX2_SYSTEM_DMA_TRANSMIT_CONFIG, *PSERCX2_SYSTEM_DMA_TRANSMIT_CONFIG;
FORCEINLINE VOID SERCX2_SYSTEM_DMA_TRANSMIT_CONFIG_INIT(PSERCX2_SYSTEM_DMA_TRANSMIT_CONFIG Config,
                                                        ULONG MinimumTransactionLength,
                                                        ULONG MaximumTransactionLength)
{
    RtlZeroMemory(Config, sizeof(*Config));
    Config->Size = sizeof(*Config);
    Config->MinimumTransactionLength = MinimumTransactionLength;
    Config->MaximumTransactionLength = MaximumTransactionLength;
}
typedef struct _SERCX2_SYSTEM_DMA_RECEIVE_CONFIG
{
    ULONG Size;
    BOOLEAN Exclusive;
    ULONG MinimumTransactionLength;
    ULONG MaximumTransactionLength;
    ULONG MinimumTransferUnit;
    PFN_SERCX2_SYSTEM_DMA_RECEIVE_INITIALIZE_TRANSACTION EvtSerCx2SystemDmaReceiveInitializeTransaction;
    PFN_SERCX2_SYSTEM_DMA_RECEIVE_CLEANUP_TRANSACTION EvtSerCx2SystemDmaReceiveCleanupTransaction;
    PFN_SERCX2_SYSTEM_DMA_RECEIVE_CONFIGURE_DMA EvtSerCx2SystemDmaReceiveConfigureDma;
    PFN_SERCX2_SYSTEM_DMA_RECEIVE_ENABLE_NEW_DATA_NOTIFICATION EvtSerCx2SystemDmaReceiveEnableNewDataNotification;
    PFN_SERCX2_SYSTEM_DMA_RECEIVE_CANCEL_NEW_DATA_NOTIFICATION EvtSerCx2SystemDmaReceiveCancelNewDataNotification;
} SERCX2_SYSTEM_DMA_RECEIVE_CONFIG, *PSERCX2_SYSTEM_DMA_RECEIVE_CONFIG;
FORCEINLINE VOID SERCX2_SYSTEM_DMA_RECEIVE_CONFIG_INIT(PSERCX2_SYSTEM_DMA_RECEIVE_CONFIG Config,
                                                       ULONG MinimumTransactionLength,
                                                       ULONG MaximumTransactionLength)
{
    RtlZeroMemory(Config, sizeof(*Config));
    Config->Size = sizeof(*Config);
    Config->MinimumTransactionLength = MinimumTransactionLength;
    Config->MaximumTransactionLength = MaximumTransactionLength;
}
typedef struct _SERCX2_CUSTOM_TRANSMIT_CONFIG
{
    ULONG Size;
    BOOLEAN Exclusive;
    ULONG MinimumTransactionLength;
    ULONG MaximumTransactionLength;
    ULONG MinimumTransferUnit;
} SERCX2_CUSTOM_TRANSMIT_CONFIG, *PSERCX2_CUSTOM_TRANSMIT_CONFIG;
FORCEINLINE VOID SERCX2_CUSTOM_TRANSMIT_CONFIG_INIT(PSERCX2_CUSTOM_TRANSMIT_CONFIG Config,
                                                    ULONG MinimumTransactionLength,
                                                    ULONG MaximumTransactionLength)
{
    RtlZeroMemory(Config, sizeof(*Config));
    Config->Size = sizeof(*Config);
    Config->MinimumTransactionLength = MinimumTransactionLength;
    Config->MaximumTransactionLength = MaximumTransactionLength;
}
typedef struct _SERCX2_CUSTOM_RECEIVE_CONFIG
{
    ULONG Size;
    BOOLEAN Exclusive;
    ULONG MinimumTransactionLength;
    ULONG MaximumTransactionLength;
    ULONG MinimumTransferUnit;
} SERCX2_CUSTOM_RECEIVE_CONFIG, *PSERCX2_CUSTOM_RECEIVE_CONFIG;
FORCEINLINE VOID SERCX2_CUSTOM_RECEIVE_CONFIG_INIT(PSERCX2_CUSTOM_RECEIVE_CONFIG Config,
                                                   ULONG MinimumTransactionLength,
                                                   ULONG MaximumTransactionLength)
{
    RtlZeroMemory(Config, sizeof(*Config));
    Config->Size = sizeof(*Config);
    Config->MinimumTransactionLength = MinimumTransactionLength;
    Config->MaximumTransactionLength = MaximumTransactionLength;
}
typedef struct _SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CONFIG
{
    ULONG Size;
    PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_INITIALIZE EvtSerCx2CustomTransmitTransactionInitialize;
    PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CLEANUP EvtSerCx2CustomTransmitTransactionCleanup;
    PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_START EvtSerCx2CustomTransmitTransactionStart;
    PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CANCEL EvtSerCx2CustomTransmitTransactionCancel;
} SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CONFIG, *PSERCX2_CUSTOM_TRANSMIT_TRANSACTION_CONFIG;
FORCEINLINE VOID SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CONFIG_INIT(PSERCX2_CUSTOM_TRANSMIT_TRANSACTION_CONFIG Config,
    PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_START Start)
{
    RtlZeroMemory(Config, sizeof(*Config));
    Config->Size = sizeof(*Config);
    Config->EvtSerCx2CustomTransmitTransactionStart = Start;
}
typedef struct _SERCX2_CUSTOM_RECEIVE_TRANSACTION_CONFIG
{
    ULONG Size;
    PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_INITIALIZE EvtSerCx2CustomReceiveTransactionInitialize;
    PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CLEANUP EvtSerCx2CustomReceiveTransactionCleanup;
    PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_START EvtSerCx2CustomReceiveTransactionStart;
    PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CANCEL EvtSerCx2CustomReceiveTransactionCancel;
    PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_ENABLE_NEW_DATA_NOTIFICATION EvtSerCx2CustomReceiveTransactionEnableNewDataNotification;
    PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CANCEL_NEW_DATA_NOTIFICATION EvtSerCx2CustomReceiveTransactionCancelNewDataNotification;
    PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_QUERY_PROGRESS EvtSerCx2CustomReceiveTransactionQueryProgress;
} SERCX2_CUSTOM_RECEIVE_TRANSACTION_CONFIG, *PSERCX2_CUSTOM_RECEIVE_TRANSACTION_CONFIG;
FORCEINLINE VOID SERCX2_CUSTOM_RECEIVE_TRANSACTION_CONFIG_INIT(PSERCX2_CUSTOM_RECEIVE_TRANSACTION_CONFIG Config,
    PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_START Start,
    PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_ENABLE_NEW_DATA_NOTIFICATION EnableNewData,
    PFN_SERCX2_CUSTOM_RECEIVE_TRANSACTION_CANCEL_NEW_DATA_NOTIFICATION CancelNewData)
{
    RtlZeroMemory(Config, sizeof(*Config));
    Config->Size = sizeof(*Config);
    Config->EvtSerCx2CustomReceiveTransactionStart = Start;
    Config->EvtSerCx2CustomReceiveTransactionEnableNewDataNotification = EnableNewData;
    Config->EvtSerCx2CustomReceiveTransactionCancelNewDataNotification = CancelNewData;
}
typedef EVT_SERCX2_SYSTEM_DMA_TRANSMIT_PURGE_FIFO *PFN_SERCX2_SYSTEM_DMA_TRANSMIT_PURGE_FIFO;

typedef struct _SERCX2_CONFIG
{
    ULONG Size;
    PFN_SERCX2_FILEOPEN EvtSerCx2FileOpen;
    PFN_SERCX2_FILECLOSE EvtSerCx2FileClose;
    PFN_SERCX2_SET_WAIT_MASK EvtSerCx2SetWaitMask;
    PFN_SERCX2_PURGE_FIFOS EvtSerCx2PurgeFifos;
    PFN_SERCX2_CONTROL EvtSerCx2Control;
    PFN_SERCX2_APPLY_CONFIG EvtSerCx2ApplyConfig;
    PFN_SERCX2_SELECT_NEXT_RECEIVE_TRANSACTION_TYPE EvtSerCx2SelectNextReceiveTransactionType;
    PFN_SERCX2_SELECT_NEXT_TRANSMIT_TRANSACTION_TYPE EvtSerCx2SelectNextTransmitTransactionType;
    PWDF_OBJECT_ATTRIBUTES RequestAttributes;
} SERCX2_CONFIG, *PSERCX2_CONFIG;

FORCEINLINE VOID SERCX2_CONFIG_INIT(PSERCX2_CONFIG Config, PFN_SERCX2_APPLY_CONFIG ApplyConfig,
                                    PFN_SERCX2_CONTROL Control, PFN_SERCX2_PURGE_FIFOS PurgeFifos)
{
    RtlZeroMemory(Config, sizeof(*Config));
    Config->Size = sizeof(*Config);
    Config->EvtSerCx2ApplyConfig = ApplyConfig;
    Config->EvtSerCx2Control = Control;
    Config->EvtSerCx2PurgeFifos = PurgeFifos;
    Config->RequestAttributes = WDF_NO_OBJECT_ATTRIBUTES;
}

typedef struct _SERCX2_PIO_TRANSMIT_CONFIG
{
    ULONG Size;
    PFN_SERCX2_PIO_TRANSMIT_INITIALIZE_TRANSACTION EvtSerCx2PioTransmitInitializeTransaction;
    PFN_SERCX2_PIO_TRANSMIT_CLEANUP_TRANSACTION EvtSerCx2PioTransmitCleanupTransaction;
    PFN_SERCX2_PIO_TRANSMIT_WRITE_BUFFER EvtSerCx2PioTransmitWriteBuffer;
    PFN_SERCX2_PIO_TRANSMIT_ENABLE_READY_NOTIFICATION EvtSerCx2PioTransmitEnableReadyNotification;
    PFN_SERCX2_PIO_TRANSMIT_CANCEL_READY_NOTIFICATION EvtSerCx2PioTransmitCancelReadyNotification;
    PFN_SERCX2_PIO_TRANSMIT_DRAIN_FIFO EvtSerCx2PioTransmitDrainFifo;
    PFN_SERCX2_PIO_TRANSMIT_CANCEL_DRAIN_FIFO EvtSerCx2PioTransmitCancelDrainFifo;
    PFN_SERCX2_PIO_TRANSMIT_PURGE_FIFO EvtSerCx2PioTransmitPurgeFifo;
} SERCX2_PIO_TRANSMIT_CONFIG, *PSERCX2_PIO_TRANSMIT_CONFIG;

FORCEINLINE VOID SERCX2_PIO_TRANSMIT_CONFIG_INIT(PSERCX2_PIO_TRANSMIT_CONFIG Config,
    PFN_SERCX2_PIO_TRANSMIT_WRITE_BUFFER WriteBuffer,
    PFN_SERCX2_PIO_TRANSMIT_ENABLE_READY_NOTIFICATION EnableReady,
    PFN_SERCX2_PIO_TRANSMIT_CANCEL_READY_NOTIFICATION CancelReady)
{
    RtlZeroMemory(Config, sizeof(*Config));
    Config->Size = sizeof(*Config);
    Config->EvtSerCx2PioTransmitWriteBuffer = WriteBuffer;
    Config->EvtSerCx2PioTransmitEnableReadyNotification = EnableReady;
    Config->EvtSerCx2PioTransmitCancelReadyNotification = CancelReady;
}

typedef struct _SERCX2_PIO_RECEIVE_CONFIG
{
    ULONG Size;
    PFN_SERCX2_PIO_RECEIVE_INITIALIZE_TRANSACTION EvtSerCx2PioReceiveInitializeTransaction;
    PFN_SERCX2_PIO_RECEIVE_CLEANUP_TRANSACTION EvtSerCx2PioReceiveCleanupTransaction;
    PFN_SERCX2_PIO_RECEIVE_READ_BUFFER EvtSerCx2PioReceiveReadBuffer;
    PFN_SERCX2_PIO_RECEIVE_ENABLE_READY_NOTIFICATION EvtSerCx2PioReceiveEnableReadyNotification;
    PFN_SERCX2_PIO_RECEIVE_CANCEL_READY_NOTIFICATION EvtSerCx2PioReceiveCancelReadyNotification;
} SERCX2_PIO_RECEIVE_CONFIG, *PSERCX2_PIO_RECEIVE_CONFIG;

FORCEINLINE VOID SERCX2_PIO_RECEIVE_CONFIG_INIT(PSERCX2_PIO_RECEIVE_CONFIG Config,
    PFN_SERCX2_PIO_RECEIVE_READ_BUFFER ReadBuffer,
    PFN_SERCX2_PIO_RECEIVE_ENABLE_READY_NOTIFICATION EnableReady,
    PFN_SERCX2_PIO_RECEIVE_CANCEL_READY_NOTIFICATION CancelReady)
{
    RtlZeroMemory(Config, sizeof(*Config));
    Config->Size = sizeof(*Config);
    Config->EvtSerCx2PioReceiveReadBuffer = ReadBuffer;
    Config->EvtSerCx2PioReceiveEnableReadyNotification = EnableReady;
    Config->EvtSerCx2PioReceiveCancelReadyNotification = CancelReady;
}

typedef NTSTATUS (WDFAPI *PFN_SERCX2INITIALIZEDEVICEINIT)(PSERCX_DRIVER_GLOBALS, PWDFDEVICE_INIT);
typedef NTSTATUS (WDFAPI *PFN_SERCX2INITIALIZEDEVICE)(PSERCX_DRIVER_GLOBALS, WDFDEVICE, PSERCX2_CONFIG);
typedef VOID (WDFAPI *PFN_SERCX2COMPLETEWAIT)(PSERCX_DRIVER_GLOBALS, WDFDEVICE, ULONG);
typedef NTSTATUS (WDFAPI *PFN_SERCX2PIOTRANSMITCREATE)(PSERCX_DRIVER_GLOBALS, WDFDEVICE,
                                                       PSERCX2_PIO_TRANSMIT_CONFIG,
                                                       PWDF_OBJECT_ATTRIBUTES, SERCX2PIOTRANSMIT *);
typedef NTSTATUS (WDFAPI *PFN_SERCX2PIORECEIVECREATE)(PSERCX_DRIVER_GLOBALS, WDFDEVICE,
                                                      PSERCX2_PIO_RECEIVE_CONFIG,
                                                      PWDF_OBJECT_ATTRIBUTES, SERCX2PIORECEIVE *);
typedef VOID (WDFAPI *PFN_SERCX2PIOTRANSMITREADY)(PSERCX_DRIVER_GLOBALS, SERCX2PIOTRANSMIT);
typedef VOID (WDFAPI *PFN_SERCX2PIORECEIVEREADY)(PSERCX_DRIVER_GLOBALS, SERCX2PIORECEIVE);
typedef VOID (WDFAPI *PFN_SERCX2PIOTRANSMITDRAINFIFOCOMPLETE)(PSERCX_DRIVER_GLOBALS, SERCX2PIOTRANSMIT);
typedef VOID (WDFAPI *PFN_SERCX2PIOTRANSMITPURGEFIFOCOMPLETE)(PSERCX_DRIVER_GLOBALS, SERCX2PIOTRANSMIT, ULONG);
typedef NTSTATUS (WDFAPI *PFN_SERCX2SYSTEMDMATRANSMITCREATE)(PSERCX_DRIVER_GLOBALS, WDFDEVICE,
                                                             PSERCX2_SYSTEM_DMA_TRANSMIT_CONFIG,
                                                             PWDF_OBJECT_ATTRIBUTES, SERCX2SYSTEMDMATRANSMIT *);
typedef NTSTATUS (WDFAPI *PFN_SERCX2SYSTEMDMARECEIVECREATE)(PSERCX_DRIVER_GLOBALS, WDFDEVICE,
                                                            PSERCX2_SYSTEM_DMA_RECEIVE_CONFIG,
                                                            PWDF_OBJECT_ATTRIBUTES, SERCX2SYSTEMDMARECEIVE *);
typedef WDFDMAENABLER (WDFAPI *PFN_SERCX2SYSTEMDMATRANSMITGETDMAENABLER)(PSERCX_DRIVER_GLOBALS, SERCX2SYSTEMDMATRANSMIT);
typedef WDFDMAENABLER (WDFAPI *PFN_SERCX2SYSTEMDMARECEIVEGETDMAENABLER)(PSERCX_DRIVER_GLOBALS, SERCX2SYSTEMDMARECEIVE);
typedef VOID (WDFAPI *PFN_SERCX2SYSTEMDMATRANSMITINITIALIZETRANSACTIONCOMPLETE)(PSERCX_DRIVER_GLOBALS, SERCX2SYSTEMDMATRANSMIT, NTSTATUS);
typedef VOID (WDFAPI *PFN_SERCX2SYSTEMDMARECEIVEINITIALIZETRANSACTIONCOMPLETE)(PSERCX_DRIVER_GLOBALS, SERCX2SYSTEMDMARECEIVE, NTSTATUS);
typedef VOID (WDFAPI *PFN_SERCX2SYSTEMDMATRANSMITCLEANUPTRANSACTIONCOMPLETE)(PSERCX_DRIVER_GLOBALS, SERCX2SYSTEMDMATRANSMIT);
typedef VOID (WDFAPI *PFN_SERCX2SYSTEMDMARECEIVECLEANUPTRANSACTIONCOMPLETE)(PSERCX_DRIVER_GLOBALS, SERCX2SYSTEMDMARECEIVE);
typedef VOID (WDFAPI *PFN_SERCX2SYSTEMDMARECEIVENEWDATANOTIFICATION)(PSERCX_DRIVER_GLOBALS, SERCX2SYSTEMDMARECEIVE);
typedef VOID (WDFAPI *PFN_SERCX2SYSTEMDMATRANSMITDRAINFIFOCOMPLETE)(PSERCX_DRIVER_GLOBALS, SERCX2SYSTEMDMATRANSMIT);
typedef VOID (WDFAPI *PFN_SERCX2SYSTEMDMATRANSMITPURGEFIFOCOMPLETE)(PSERCX_DRIVER_GLOBALS, SERCX2SYSTEMDMATRANSMIT, ULONG);
typedef NTSTATUS (WDFAPI *PFN_SERCX2CUSTOMTRANSMITCREATE)(PSERCX_DRIVER_GLOBALS, WDFDEVICE, PSERCX2_CUSTOM_TRANSMIT_CONFIG,
                                                          PWDF_OBJECT_ATTRIBUTES, SERCX2CUSTOMTRANSMIT *);
typedef NTSTATUS (WDFAPI *PFN_SERCX2CUSTOMRECEIVECREATE)(PSERCX_DRIVER_GLOBALS, WDFDEVICE, PSERCX2_CUSTOM_RECEIVE_CONFIG,
                                                         PWDF_OBJECT_ATTRIBUTES, SERCX2CUSTOMRECEIVE *);
typedef NTSTATUS (WDFAPI *PFN_SERCX2CUSTOMTRANSMITTRANSACTIONCREATE)(PSERCX_DRIVER_GLOBALS, SERCX2CUSTOMTRANSMIT,
                                                                     PSERCX2_CUSTOM_TRANSMIT_TRANSACTION_CONFIG,
                                                                     PWDF_OBJECT_ATTRIBUTES, SERCX2CUSTOMTRANSMITTRANSACTION *);
typedef NTSTATUS (WDFAPI *PFN_SERCX2CUSTOMRECEIVETRANSACTIONCREATE)(PSERCX_DRIVER_GLOBALS, SERCX2CUSTOMRECEIVE,
                                                                    PSERCX2_CUSTOM_RECEIVE_TRANSACTION_CONFIG,
                                                                    PWDF_OBJECT_ATTRIBUTES, SERCX2CUSTOMRECEIVETRANSACTION *);
typedef VOID (WDFAPI *PFN_SERCX2CUSTOMTRANSMITTRANSACTIONINITIALIZECOMPLETE)(PSERCX_DRIVER_GLOBALS, SERCX2CUSTOMTRANSMITTRANSACTION, NTSTATUS);
typedef VOID (WDFAPI *PFN_SERCX2CUSTOMRECEIVETRANSACTIONINITIALIZECOMPLETE)(PSERCX_DRIVER_GLOBALS, SERCX2CUSTOMRECEIVETRANSACTION, NTSTATUS);
typedef VOID (WDFAPI *PFN_SERCX2CUSTOMTRANSMITTRANSACTIONCLEANUPCOMPLETE)(PSERCX_DRIVER_GLOBALS, SERCX2CUSTOMTRANSMITTRANSACTION);
typedef VOID (WDFAPI *PFN_SERCX2CUSTOMRECEIVETRANSACTIONCLEANUPCOMPLETE)(PSERCX_DRIVER_GLOBALS, SERCX2CUSTOMRECEIVETRANSACTION);
typedef VOID (WDFAPI *PFN_SERCX2CUSTOMRECEIVETRANSACTIONNEWDATANOTIFICATION)(PSERCX_DRIVER_GLOBALS, SERCX2CUSTOMRECEIVETRANSACTION);
typedef VOID (WDFAPI *PFN_SERCX2CUSTOMRECEIVETRANSACTIONREPORTPROGRESS)(PSERCX_DRIVER_GLOBALS, SERCX2CUSTOMRECEIVETRANSACTION,
                                                                        SERCX2_CUSTOM_RECEIVE_TRANSACTION_PROGRESS);

FORCEINLINE NTSTATUS SerCx2InitializeDeviceInit(PWDFDEVICE_INIT DeviceInit)
{
    return ((PFN_SERCX2INITIALIZEDEVICEINIT)SercxFunctions[SerCx2InitializeDeviceInitTableIndex])(
        SercxDriverGlobals, DeviceInit);
}
FORCEINLINE NTSTATUS SerCx2InitializeDevice(WDFDEVICE Device, PSERCX2_CONFIG Config)
{
    return ((PFN_SERCX2INITIALIZEDEVICE)SercxFunctions[SerCx2InitializeDeviceTableIndex])(
        SercxDriverGlobals, Device, Config);
}
FORCEINLINE VOID SerCx2CompleteWait(WDFDEVICE Device, ULONG Event)
{
    ((PFN_SERCX2COMPLETEWAIT)SercxFunctions[SerCx2CompleteWaitTableIndex])(SercxDriverGlobals, Device, Event);
}
FORCEINLINE NTSTATUS SerCx2PioTransmitCreate(WDFDEVICE Device, PSERCX2_PIO_TRANSMIT_CONFIG Config,
                                             PWDF_OBJECT_ATTRIBUTES Attributes, SERCX2PIOTRANSMIT *Object)
{
    return ((PFN_SERCX2PIOTRANSMITCREATE)SercxFunctions[SerCx2PioTransmitCreateTableIndex])(
        SercxDriverGlobals, Device, Config, Attributes, Object);
}
FORCEINLINE NTSTATUS SerCx2PioReceiveCreate(WDFDEVICE Device, PSERCX2_PIO_RECEIVE_CONFIG Config,
                                            PWDF_OBJECT_ATTRIBUTES Attributes, SERCX2PIORECEIVE *Object)
{
    return ((PFN_SERCX2PIORECEIVECREATE)SercxFunctions[SerCx2PioReceiveCreateTableIndex])(
        SercxDriverGlobals, Device, Config, Attributes, Object);
}
FORCEINLINE VOID SerCx2PioTransmitReady(SERCX2PIOTRANSMIT Object)
{
    ((PFN_SERCX2PIOTRANSMITREADY)SercxFunctions[SerCx2PioTransmitReadyTableIndex])(SercxDriverGlobals, Object);
}
FORCEINLINE VOID SerCx2PioReceiveReady(SERCX2PIORECEIVE Object)
{
    ((PFN_SERCX2PIORECEIVEREADY)SercxFunctions[SerCx2PioReceiveReadyTableIndex])(SercxDriverGlobals, Object);
}
FORCEINLINE VOID SerCx2PioTransmitDrainFifoComplete(SERCX2PIOTRANSMIT Object)
{
    ((PFN_SERCX2PIOTRANSMITDRAINFIFOCOMPLETE)SercxFunctions[SerCx2PioTransmitDrainFifoCompleteTableIndex])(
        SercxDriverGlobals, Object);
}
FORCEINLINE VOID SerCx2PioTransmitPurgeFifoComplete(SERCX2PIOTRANSMIT Object, ULONG BytesPurged)
{
    ((PFN_SERCX2PIOTRANSMITPURGEFIFOCOMPLETE)SercxFunctions[SerCx2PioTransmitPurgeFifoCompleteTableIndex])(
        SercxDriverGlobals, Object, BytesPurged);
}

#define SERCX2_DDI0(Name, Pfn, Ret, ArgT) \
FORCEINLINE Ret Name(ArgT Object) \
{ return ((Pfn)SercxFunctions[Name##TableIndex])(SercxDriverGlobals, Object); }
#define SERCX2_DDI0V(Name, Pfn, ArgT) \
FORCEINLINE VOID Name(ArgT Object) \
{ ((Pfn)SercxFunctions[Name##TableIndex])(SercxDriverGlobals, Object); }
#define SERCX2_DDI1V(Name, Pfn, ArgT, Arg2T) \
FORCEINLINE VOID Name(ArgT Object, Arg2T Arg) \
{ ((Pfn)SercxFunctions[Name##TableIndex])(SercxDriverGlobals, Object, Arg); }
#define SERCX2_DDICREATE(Name, Pfn, ParentT, ConfigT, ObjT) \
FORCEINLINE NTSTATUS Name(ParentT Parent, ConfigT Config, PWDF_OBJECT_ATTRIBUTES Attributes, ObjT *Object) \
{ return ((Pfn)SercxFunctions[Name##TableIndex])(SercxDriverGlobals, Parent, Config, Attributes, Object); }

SERCX2_DDICREATE(SerCx2SystemDmaTransmitCreate, PFN_SERCX2SYSTEMDMATRANSMITCREATE, WDFDEVICE, PSERCX2_SYSTEM_DMA_TRANSMIT_CONFIG, SERCX2SYSTEMDMATRANSMIT)
SERCX2_DDICREATE(SerCx2SystemDmaReceiveCreate, PFN_SERCX2SYSTEMDMARECEIVECREATE, WDFDEVICE, PSERCX2_SYSTEM_DMA_RECEIVE_CONFIG, SERCX2SYSTEMDMARECEIVE)
SERCX2_DDI0(SerCx2SystemDmaTransmitGetDmaEnabler, PFN_SERCX2SYSTEMDMATRANSMITGETDMAENABLER, WDFDMAENABLER, SERCX2SYSTEMDMATRANSMIT)
SERCX2_DDI0(SerCx2SystemDmaReceiveGetDmaEnabler, PFN_SERCX2SYSTEMDMARECEIVEGETDMAENABLER, WDFDMAENABLER, SERCX2SYSTEMDMARECEIVE)
SERCX2_DDI1V(SerCx2SystemDmaTransmitInitializeTransactionComplete, PFN_SERCX2SYSTEMDMATRANSMITINITIALIZETRANSACTIONCOMPLETE, SERCX2SYSTEMDMATRANSMIT, NTSTATUS)
SERCX2_DDI1V(SerCx2SystemDmaReceiveInitializeTransactionComplete, PFN_SERCX2SYSTEMDMARECEIVEINITIALIZETRANSACTIONCOMPLETE, SERCX2SYSTEMDMARECEIVE, NTSTATUS)
SERCX2_DDI0V(SerCx2SystemDmaTransmitCleanupTransactionComplete, PFN_SERCX2SYSTEMDMATRANSMITCLEANUPTRANSACTIONCOMPLETE, SERCX2SYSTEMDMATRANSMIT)
SERCX2_DDI0V(SerCx2SystemDmaReceiveCleanupTransactionComplete, PFN_SERCX2SYSTEMDMARECEIVECLEANUPTRANSACTIONCOMPLETE, SERCX2SYSTEMDMARECEIVE)
SERCX2_DDI0V(SerCx2SystemDmaReceiveNewDataNotification, PFN_SERCX2SYSTEMDMARECEIVENEWDATANOTIFICATION, SERCX2SYSTEMDMARECEIVE)
SERCX2_DDI0V(SerCx2SystemDmaTransmitDrainFifoComplete, PFN_SERCX2SYSTEMDMATRANSMITDRAINFIFOCOMPLETE, SERCX2SYSTEMDMATRANSMIT)
SERCX2_DDI1V(SerCx2SystemDmaTransmitPurgeFifoComplete, PFN_SERCX2SYSTEMDMATRANSMITPURGEFIFOCOMPLETE, SERCX2SYSTEMDMATRANSMIT, ULONG)
SERCX2_DDICREATE(SerCx2CustomTransmitCreate, PFN_SERCX2CUSTOMTRANSMITCREATE, WDFDEVICE, PSERCX2_CUSTOM_TRANSMIT_CONFIG, SERCX2CUSTOMTRANSMIT)
SERCX2_DDICREATE(SerCx2CustomReceiveCreate, PFN_SERCX2CUSTOMRECEIVECREATE, WDFDEVICE, PSERCX2_CUSTOM_RECEIVE_CONFIG, SERCX2CUSTOMRECEIVE)
SERCX2_DDICREATE(SerCx2CustomTransmitTransactionCreate, PFN_SERCX2CUSTOMTRANSMITTRANSACTIONCREATE, SERCX2CUSTOMTRANSMIT, PSERCX2_CUSTOM_TRANSMIT_TRANSACTION_CONFIG, SERCX2CUSTOMTRANSMITTRANSACTION)
SERCX2_DDICREATE(SerCx2CustomReceiveTransactionCreate, PFN_SERCX2CUSTOMRECEIVETRANSACTIONCREATE, SERCX2CUSTOMRECEIVE, PSERCX2_CUSTOM_RECEIVE_TRANSACTION_CONFIG, SERCX2CUSTOMRECEIVETRANSACTION)
SERCX2_DDI1V(SerCx2CustomTransmitTransactionInitializeComplete, PFN_SERCX2CUSTOMTRANSMITTRANSACTIONINITIALIZECOMPLETE, SERCX2CUSTOMTRANSMITTRANSACTION, NTSTATUS)
SERCX2_DDI1V(SerCx2CustomReceiveTransactionInitializeComplete, PFN_SERCX2CUSTOMRECEIVETRANSACTIONINITIALIZECOMPLETE, SERCX2CUSTOMRECEIVETRANSACTION, NTSTATUS)
SERCX2_DDI0V(SerCx2CustomTransmitTransactionCleanupComplete, PFN_SERCX2CUSTOMTRANSMITTRANSACTIONCLEANUPCOMPLETE, SERCX2CUSTOMTRANSMITTRANSACTION)
SERCX2_DDI0V(SerCx2CustomReceiveTransactionCleanupComplete, PFN_SERCX2CUSTOMRECEIVETRANSACTIONCLEANUPCOMPLETE, SERCX2CUSTOMRECEIVETRANSACTION)
SERCX2_DDI0V(SerCx2CustomReceiveTransactionNewDataNotification, PFN_SERCX2CUSTOMRECEIVETRANSACTIONNEWDATANOTIFICATION, SERCX2CUSTOMRECEIVETRANSACTION)
SERCX2_DDI1V(SerCx2CustomReceiveTransactionReportProgress, PFN_SERCX2CUSTOMRECEIVETRANSACTIONREPORTPROGRESS, SERCX2CUSTOMRECEIVETRANSACTION, SERCX2_CUSTOM_RECEIVE_TRANSACTION_PROGRESS)

WDF_EXTERN_C_END
