@ stub FormatTagFromWfx
@ stub MFCreateGuid
@ stub MFGetIoPortHandle
@ stub MFGetPlatformVersion
@ stub MFGetRandomNumber
@ stub MFIsFeatureEnabled
@ stub MFIsQueueThread
@ stub MFPlatformBigEndian
@ stub MFPlatformLittleEndian
@ stub ValidateWaveFormat
@ stub CopyPropVariant
@ stub CreatePropVariant
@ stub CreatePropertyStore
@ stub DestroyPropVariant
@ stub GetAMSubtypeFromD3DFormat
@ stub GetD3DFormatFromMFSubtype
@ stub LFGetGlobalPool
@ stub MFAddPeriodicCallback
@ stub MFAllocateSerialWorkQueue
@ stub MFAllocateWorkQueue
@ stub MFAllocateWorkQueueEx
@ stub MFAppendCollection
@ stub MFAverageTimePerFrameToFrameRate
@ stub MFBeginCreateFile
@ stub MFBeginGetHostByName
@ stub MFBeginRegisterWorkQueueWithMMCSS
@ stub MFBeginRegisterWorkQueueWithMMCSSEx
@ stub MFBeginUnregisterWorkQueueWithMMCSS
@ stub MFBlockThread
@ stub MFCalculateBitmapImageSize
@ stub MFCalculateImageSize
@ stub MFCancelCreateFile
@ stub MFCancelWorkItem
@ stub MFCompareFullToPartialMediaType
@ stub MFCompareSockaddrAddresses
@ stub MFConvertColorInfoFromDXVA
@ stub MFConvertColorInfoToDXVA
@ stub MFConvertFromFP16Array
@ stub MFConvertToFP16Array
@ stub MFCopyImage
@ stub MFCreate2DMediaBuffer
@ stub MFCreateAMMediaTypeFromMFMediaType
@ stub MFCreateAlignedMemoryBuffer
@ stub MFCreateAsyncResult
@ stub MFCreateAttributes
@ stub MFCreateAudioMediaType
@ stub MFCreateCollection
@ stub MFCreateDXGIDeviceManager
@ stub MFCreateDXGISurfaceBuffer
@ stub MFCreateDXSurfaceBuffer
@ stub MFCreateEventQueue
@ stub MFCreateFile
@ stub MFCreateLegacyMediaBufferOnMFMediaBuffer
@ stub MFCreateMFByteStreamOnStream
@ stub MFCreateMFByteStreamOnStreamEx
@ stub MFCreateMFByteStreamWrapper
@ stub MFCreateMFVideoFormatFromMFMediaType
@ stub MFCreateMediaBufferFromMediaType
@ stub MFCreateMediaBufferWrapper
@ stub MFCreateMediaEvent
@ stub MFCreateMediaType
@ stub MFCreateMediaTypeFromRepresentation
@ stub MFCreateMemoryBuffer
@ stub MFCreateMemoryStream
@ stub MFCreatePathFromURL
@ stub MFCreatePresentationDescriptor
@ stub MFCreateSample
@ stub MFCreateSocket
@ stub MFCreateSocketListener
@ stub MFCreateSourceResolver
@ stub MFCreateStreamDescriptor
@ stub MFCreateSystemTimeSource
@ stub MFCreateSystemUnderlyingClock
@ stub MFCreateTempFile
@ stub MFCreateTrackedSample
@ stub MFCreateTransformActivate
@ stub MFCreateURLFromPath
@ stub MFCreateUdpSockets
@ stub MFCreateVideoMediaType
@ stub MFCreateVideoMediaTypeFromBitMapInfoHeader
@ stub MFCreateVideoMediaTypeFromBitMapInfoHeaderEx
@ stub MFCreateVideoMediaTypeFromSubtype
@ stub MFCreateVideoMediaTypeFromVideoInfoHeader2
@ stub MFCreateVideoMediaTypeFromVideoInfoHeader
@ stub MFCreateVideoSampleAllocatorEx
@ stub MFCreateWaveFormatExFromMFMediaType
@ stub MFDeserializeAttributesFromStream
@ stub MFDeserializeEvent
@ stub MFDeserializeMediaTypeFromStream
@ stub MFDeserializePresentationDescriptor
@ stub MFEndCreateFile
@ stub MFEndGetHostByName
@ stub MFEndRegisterWorkQueueWithMMCSS
@ stub MFEndUnregisterWorkQueueWithMMCSS
@ stub MFFrameRateToAverageTimePerFrame
@ stub MFFreeAdaptersAddresses
@ stub MFGetAdaptersAddresses
@ stub MFGetAttributesAsBlob
@ stub MFGetAttributesAsBlobSize
@ stub MFGetConfigurationDWORD
@ stub MFGetConfigurationPolicy
@ stub MFGetConfigurationStore
@ stub MFGetConfigurationString
@ stub MFGetMFTMerit
@ stub MFGetNumericNameFromSockaddr
@ stub MFGetPlaneSize
@ stub MFGetPlatform
@ stub MFGetPluginControl
@ stub MFGetPrivateWorkqueues
@ stub MFGetSockaddrFromNumericName
@ stub MFGetStrideForBitmapInfoHeader
@ stub MFGetSystemTime
@ stub MFGetTimerPeriodicity
@ stub MFGetUncompressedVideoFormat
@ stub MFGetWorkQueueMMCSSClass
@ stub MFGetWorkQueueMMCSSTaskId
@ stub MFGetWorkQueueMMCSSPriority
@ stub MFHeapAlloc
@ stub MFHeapFree
@ stub MFInitAMMediaTypeFromMFMediaType
@ stub MFInitAttributesFromBlob
@ stub MFInitMediaTypeFromAMMediaType
@ stub MFInitMediaTypeFromMFVideoFormat
@ stub MFInitMediaTypeFromMPEG1VideoInfo
@ stub MFInitMediaTypeFromMPEG2VideoInfo
@ stub MFInitMediaTypeFromVideoInfoHeader2
@ stub MFInitMediaTypeFromVideoInfoHeader
@ stub MFInitMediaTypeFromWaveFormatEx
@ stub MFInitVideoFormat
@ stub MFInitVideoFormat_RGB
@ stub MFInvokeCallback
@ stub MFJoinIoPort
@ stub MFJoinWorkQueue
@ stub MFLockDXGIDeviceManager
@ stub MFLockPlatform
@ stub MFLockSharedWorkQueue
@ stub MFLockWorkQueue
@ stub MFMapDX9FormatToDXGIFormat
@ stub MFMapDXGIFormatToDX9Format
@ stub MFPutWaitingWorkItem
@ stub MFPutWorkItem
@ stub MFPutWorkItem2
@ stub MFPutWorkItemEx
@ stub MFPutWorkItemEx2
@ stub MFRecordError
@ stub MFRegisterLocalByteStreamHandler
@ stub MFRegisterLocalSchemeHandler
@ stub MFRegisterPlatformWithMMCSS
@ stub MFRemovePeriodicCallback
@ stub MFScheduleWorkItem
@ stub MFScheduleWorkItemEx
@ stub MFSerializeAttributesToStream
@ stub MFSerializeEvent
@ stub MFSerializeMediaTypeToStream
@ stub MFSerializePresentationDescriptor
@ stub MFSetSockaddrAny
@ stub MFShutdown
@ stub MFStartup
@ stub MFStreamDescriptorProtectMediaType
@ stub MFTEnum
@ stub MFTEnum2
@ stub MFTEnumEx
@ stub MFTGetInfo
@ stub MFTRegister
@ stub MFTRegisterLocal
@ stub MFTRegisterLocalByCLSID
@ stub MFTUnregister
@ stub MFTUnregisterLocal
@ stub MFTUnregisterLocalByCLSID
@ stub MFUnregisterPlatformFromMMCSS
@ stub MFTraceError
@ stub MFTraceFuncEnter
@ stub MFUnblockThread
@ stub MFUnjoinWorkQueue
@ stub MFUnlockDXGIDeviceManager
@ stub MFUnlockPlatform
@ stub MFUnlockWorkQueue
@ stub MFUnwrapMediaType
@ stub MFValidateMediaTypeSize
@ stub MFWrapMediaType
@ stub MFllMulDiv
@ stub PropVariantFromStream
@ stub PropVariantToStream
