if(ARCH STREQUAL "i386" OR ARCH STREQUAL "amd64")
    add_subdirectory(intelgpio)
    add_subdirectory(intelpmc)
    add_subdirectory(intelocwdt)
    if(LATTEPANDAMU_SUPPORT)
        add_subdirectory(it8613sensor)
    endif()
endif()
if((ARCH STREQUAL "arm64") AND RPI3_SUPPORT)
    include(rpi3winsync.cmake)
    add_subdirectory(rpi3winsync/drivers/mailbox/bcm2836)
    add_subdirectory(rpi3winsync/drivers/pwm/bcm2836)
    add_subdirectory(rpi3winsync/drivers/gpio/bcm2836)
    add_subdirectory(rpi3winsync/drivers/i2c/bcm2836)
    add_subdirectory(rpi3winsync/drivers/sd/bcm2836/bcm2836sdhc)
    add_subdirectory(rpi3winsync/drivers/sd/bcm2836/rpisdhc)
    add_subdirectory(rpi3winsync/drivers/spi/bcm2836)
    add_subdirectory(rpi3winsync/drivers/spi/bcmauxspi)
    add_subdirectory(rpi3winsync/drivers/uart/bcm2836/miniUart)
    add_subdirectory(rpi3winsync/drivers/uart/bcm2836/serPL011)
    add_subdirectory(rpi3winsync/drivers/misc/userland/interface/vcos/generic)
    add_subdirectory(rpi3winsync/drivers/misc/userland/interface/vcos/win32)
    add_subdirectory(rpi3winsync/drivers/misc/userland/interface/vchiq_arm)
    add_subdirectory(rpi3winsync/drivers/misc/vchiq)
endif()
add_subdirectory(tpm2)
