use std::env;
use std::error::Error;
use std::fs;
use std::io::{BufRead, BufReader, Write};
use std::path::Path;

#[derive(Debug)]
struct SyscallEntry {
    name: String,
    arg_count: u32,
}

fn parse_sysfuncs_lst(path: &Path) -> Result<Vec<SyscallEntry>, Box<dyn Error>> {
    let file = fs::File::open(path)?;
    let reader = BufReader::new(file);

    let mut entries = Vec::new();
    for (lineno, line_res) in reader.lines().enumerate() {
        let line = line_res?;
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        if line.starts_with('#') || line.starts_with("//") || line.starts_with(';') {
            continue;
        }

        let mut parts = line.split_whitespace();
        let fullname = match parts.next() {
            Some(s) => s,
            None => continue,
        };
        let arg_str = match parts.next() {
            Some(s) => s,
            None => {
                return Err(format!("{}:{}: missing argument count", path.display(), lineno + 1).into());
            }
        };
        let arg_count: u32 = arg_str.parse().map_err(|e| {
            format!(
                "{}:{}: invalid argument count '{}': {}",
                path.display(),
                lineno + 1,
                arg_str,
                e
            )
        })?;

        if !fullname.starts_with("Nt") {
            return Err(format!(
                "{}:{}: syscall name '{}' does not start with 'Nt'",
                path.display(),
                lineno + 1,
                fullname
            )
            .into());
        }

        let short_name = &fullname["Nt".len()..];
        if short_name.is_empty() {
            return Err(format!(
                "{}:{}: invalid syscall name '{}'",
                path.display(),
                lineno + 1,
                fullname
            )
            .into());
        }

        entries.push(SyscallEntry {
            name: short_name.to_string(),
            arg_count,
        });
    }

    Ok(entries)
}

fn write_syscall_table_header(path: &Path, entries: &[SyscallEntry]) -> Result<(), Box<dyn Error>> {
    let mut file = fs::File::create(path)?;
    let wow64_count = entries.iter().filter(|e| e.name.starts_with("Wow64")).count();
    let non_amd64_total = entries.len() - wow64_count;

    writeln!(
        file,
        "/* Auto-generated by gen_syscalls; do not edit manually. */"
    )?;
    writeln!(file, "#pragma once")?;
    writeln!(file)?;
    writeln!(file, "/*")?;
    writeln!(
        file,
        " * This header provides a single source of truth for the"
    )?;
    writeln!(
        file,
        " * number of syscalls. The order and names are defined in"
    )?;
    writeln!(file, " * ntoskrnl/sysfuncs.lst.")?;
    writeln!(file, " */")?;
    writeln!(file)?;
    writeln!(file, "#ifdef _M_AMD64")?;
    writeln!(file, "#define NUMBER_OF_SYSCALLS {}", entries.len())?;
    writeln!(file, "#else")?;
    writeln!(file, "#define NUMBER_OF_SYSCALLS {}", non_amd64_total)?;
    writeln!(file, "#endif")?;

    Ok(())
}

fn write_syscalls_body_header(path: &Path, entries: &[SyscallEntry]) -> Result<(), Box<dyn Error>> {
    let mut file = fs::File::create(path)?;

    writeln!(
        file,
        "/* Auto-generated by gen_syscalls; do not edit manually. */"
    )?;
    writeln!(file)?;

    let mut in_amd64_only_block = false;
    for entry in entries {
        let is_wow64 = entry.name.starts_with("Wow64");
        if is_wow64 && !in_amd64_only_block {
            writeln!(file, "#ifdef _M_AMD64")?;
            in_amd64_only_block = true;
        } else if !is_wow64 && in_amd64_only_block {
            writeln!(file, "#endif")?;
            in_amd64_only_block = false;
        }
        writeln!(file, "    SVC_({}, {})", entry.name, entry.arg_count)?;
    }
    if in_amd64_only_block {
        writeln!(file, "#endif")?;
    }

    Ok(())
}

fn write_ntdll_syscalls_asm(path: &Path, entries: &[SyscallEntry]) -> Result<(), Box<dyn Error>> {
    let mut file = fs::File::create(path)?;

    writeln!(
        file,
        "/* Auto-generated by gen_syscalls; do not edit manually. */"
    )?;
    writeln!(file, "#include <asm.inc>")?;
    writeln!(file, "#include <ksamd64.inc>")?;
    writeln!(file)?;
    writeln!(file, ".code")?;
    writeln!(file)?;

    for (index, entry) in entries.iter().enumerate() {
        let sys_index = index as u32;
        let base_name = &entry.name;

        // Zw<Name> stub
        writeln!(file, "PUBLIC Zw{0}", base_name)?;
        writeln!(file, ".PROC Zw{0}", base_name)?;
        writeln!(file, "    .endprolog")?;
        writeln!(file, "    mov eax, {}", sys_index)?;
        writeln!(file, "    mov r10, rcx")?;
        writeln!(file, "    syscall")?;
        writeln!(file, "    ret")?;
        writeln!(file, ".ENDP")?;
        writeln!(file)?;

        // Nt<Name> alias to Zw<Name>
        writeln!(file, "PUBLIC Nt{0}", base_name)?;
        writeln!(file, ".PROC Nt{0}", base_name)?;
        writeln!(file, "    .endprolog")?;
        writeln!(file, "    jmp Zw{0}", base_name)?;
        writeln!(file, ".ENDP")?;
        writeln!(file)?;
    }

    writeln!(file, "END")?;

    Ok(())
}

fn write_syscall_ids_header(path: &Path, entries: &[SyscallEntry]) -> Result<(), Box<dyn Error>> {
    let mut file = fs::File::create(path)?;

    writeln!(
        file,
        "/* Auto-generated by gen_syscalls; do not edit manually. */"
    )?;
    writeln!(file, "#pragma once")?;
    writeln!(file)?;
    writeln!(file, "#ifdef _M_AMD64")?;
    for (index, entry) in entries.iter().enumerate() {
        writeln!(file, "#define SYSCALL_ID_{} {}", entry.name, index)?;
    }
    writeln!(file, "#else")?;
    let mut index = 0;
    for entry in entries.iter() {
        if entry.name.starts_with("Wow64") {
            continue;
        }
        writeln!(file, "#define SYSCALL_ID_{} {}", entry.name, index)?;
        index += 1;
    }
    writeln!(file, "#endif")?;

    Ok(())
}

fn main() -> Result<(), Box<dyn Error>> {
    let args: Vec<String> = env::args().collect();
    if args.len() < 4 || args.len() > 6 {
        eprintln!(
            "Usage: {} <sysfuncs.lst> <syscall_table.h> <ntdll_syscalls.S> [syscalls_body.h [syscall_ids.h]]",
            args.get(0).map(String::as_str).unwrap_or("gen_syscalls")
        );
        std::process::exit(1);
    }

    let sysfuncs_lst = Path::new(&args[1]);
    let header_out = Path::new(&args[2]);
    let asm_out = Path::new(&args[3]);
    let body_out = if args.len() >= 5 {
        Some(Path::new(&args[4]))
    } else {
        None
    };
    let ids_out = if args.len() >= 6 {
        Some(Path::new(&args[5]))
    } else {
        None
    };

    let entries = parse_sysfuncs_lst(sysfuncs_lst)?;

    if let Some(parent) = header_out.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)?;
        }
    }
    if let Some(parent) = asm_out.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)?;
        }
    }
    if let Some(body_path) = &body_out {
        if let Some(parent) = body_path.parent() {
            if !parent.as_os_str().is_empty() {
                fs::create_dir_all(parent)?;
            }
        }
    }
    if let Some(ids_path) = &ids_out {
        if let Some(parent) = ids_path.parent() {
            if !parent.as_os_str().is_empty() {
                fs::create_dir_all(parent)?;
            }
        }
    }

    write_syscall_table_header(header_out, &entries)?;
    write_ntdll_syscalls_asm(asm_out, &entries)?;
    if let Some(body_path) = body_out {
        write_syscalls_body_header(body_path, &entries)?;
    }
    if let Some(ids_path) = ids_out {
        write_syscall_ids_header(ids_path, &entries)?;
    }

    Ok(())
}
