/*
 * PROJECT:         ReactOS HAL
 * LICENSE:         BSD - See COPYING.ARM in the top level directory
 * FILE:            hal/arch/common/acpi/halpnpdd.c
 * PURPOSE:         HAL Plug and Play Device Driver shared by the ACPI HALs
 * PROGRAMMERS:     ReactOS Portable Systems Group
 */

/* INCLUDES *******************************************************************/

#include <hal.h>
#include <halpnp.h>

#include <initguid.h>
#include <wdmguid.h>

#include <ntstrsafe.h>

#define NDEBUG
#include <debug.h>

typedef enum _EXTENSION_TYPE
{
    PdoExtensionType = 0xC0,
    FdoExtensionType
} EXTENSION_TYPE;

typedef enum _PDO_TYPE
{
    AcpiPdo = 0x80,
    WdPdo,
    PlatformPdo
} PDO_TYPE;

typedef enum _HALP_PNP_STATE
{
    HalpPnpStateNotStarted = 0,
    HalpPnpStateStarted,
    HalpPnpStateStopPending,
    HalpPnpStateStopped,
    HalpPnpStateRemovePending,
    HalpPnpStateSurpriseRemoved
} HALP_PNP_STATE;

typedef struct _FDO_EXTENSION
{
    EXTENSION_TYPE ExtensionType;
    struct _PDO_EXTENSION* ChildPdoList;
    FAST_MUTEX ChildPdoLock;
    LONG InterfaceReferenceCount;
    PDEVICE_OBJECT PhysicalDeviceObject;
    PDEVICE_OBJECT FunctionalDeviceObject;
    PDEVICE_OBJECT AttachedDeviceObject;
} FDO_EXTENSION, *PFDO_EXTENSION;

typedef struct _PDO_EXTENSION
{
    EXTENSION_TYPE ExtensionType;
    struct _PDO_EXTENSION* Next;
    PDEVICE_OBJECT PhysicalDeviceObject;
    PFDO_EXTENSION ParentFdoExtension;
    PDEVICE_OBJECT ParentFdoDeviceObject;
    PDO_TYPE PdoType;
    const HAL_PLATFORM_DEVICE *PlatformDevice;
    FAST_MUTEX PnpStateLock;
    HALP_PNP_STATE PnpState;
    HALP_PNP_STATE PreviousPnpState;
    DEVICE_POWER_STATE CurrentDevicePowerState;
    SYSTEM_POWER_STATE CurrentSystemPowerState;
    LONG InterfaceReferenceCount;
} PDO_EXTENSION, *PPDO_EXTENSION;

/* GLOBALS ********************************************************************/

PDRIVER_OBJECT HalpDriverObject;

/* PRIVATE FUNCTIONS **********************************************************/

static
PLONG
HalpGetInterfaceReferenceCount(
    _In_ PDEVICE_OBJECT DeviceObject)
{
    PFDO_EXTENSION DeviceExtension = DeviceObject->DeviceExtension;

    if (DeviceExtension->ExtensionType == FdoExtensionType)
        return &DeviceExtension->InterfaceReferenceCount;

    ASSERT(DeviceExtension->ExtensionType == PdoExtensionType);
    return &((PPDO_EXTENSION)DeviceExtension)->InterfaceReferenceCount;
}

VOID
NTAPI
HalpPnpInterfaceReference(
    _In_opt_ PVOID Context)
{
    PDEVICE_OBJECT DeviceObject = Context;

    if (!DeviceObject) return;

    /* The interface keeps the device object alive */
    ObReferenceObject(DeviceObject);
    InterlockedIncrement(HalpGetInterfaceReferenceCount(DeviceObject));
}

VOID
NTAPI
HalpPnpInterfaceDereference(
    _In_opt_ PVOID Context)
{
    PDEVICE_OBJECT DeviceObject = Context;

    if (!DeviceObject) return;

    InterlockedDecrement(HalpGetInterfaceReferenceCount(DeviceObject));
    ObDereferenceObject(DeviceObject);
}

static
NTSTATUS
HalpCreatePdo(
    _In_ PDRIVER_OBJECT DriverObject,
    _In_ PFDO_EXTENSION FdoExtension,
    _In_ PDO_TYPE PdoType,
    _In_opt_ const HAL_PLATFORM_DEVICE *PlatformDevice)
{
    NTSTATUS Status;
    PDEVICE_OBJECT PdoDeviceObject;
    PPDO_EXTENSION PdoExtension;

    /* Create the PDO */
    Status = IoCreateDevice(DriverObject,
                            sizeof(PDO_EXTENSION),
                            NULL,
                            FILE_DEVICE_BUS_EXTENDER,
                            FILE_AUTOGENERATED_DEVICE_NAME,
                            FALSE,
                            &PdoDeviceObject);
    if (!NT_SUCCESS(Status)) return Status;

    /* Setup the PDO device extension; the PDO keeps its parent alive */
    PdoExtension = PdoDeviceObject->DeviceExtension;
    PdoExtension->ExtensionType = PdoExtensionType;
    PdoExtension->PhysicalDeviceObject = PdoDeviceObject;
    PdoExtension->ParentFdoExtension = FdoExtension;
    PdoExtension->ParentFdoDeviceObject = FdoExtension->FunctionalDeviceObject;
    ObReferenceObject(PdoExtension->ParentFdoDeviceObject);
    PdoExtension->PdoType = PdoType;
    PdoExtension->PlatformDevice = PlatformDevice;
    ExInitializeFastMutex(&PdoExtension->PnpStateLock);
    PdoExtension->PnpState = HalpPnpStateNotStarted;
    PdoExtension->PreviousPnpState = HalpPnpStateNotStarted;
    PdoExtension->CurrentDevicePowerState = PowerDeviceD3;
    PdoExtension->CurrentSystemPowerState = PowerSystemWorking;

    /* Add the PDO to the head of the list */
    ExAcquireFastMutex(&FdoExtension->ChildPdoLock);
    PdoExtension->Next = FdoExtension->ChildPdoList;
    FdoExtension->ChildPdoList = PdoExtension;
    ExReleaseFastMutex(&FdoExtension->ChildPdoLock);

    /* Initialization is finished */
    PdoDeviceObject->Flags &= ~DO_DEVICE_INITIALIZING;
    return STATUS_SUCCESS;
}

static
VOID
HalpDeletePdo(
    _In_ PPDO_EXTENSION PdoExtension)
{
    PDEVICE_OBJECT ParentFdoDeviceObject = PdoExtension->ParentFdoDeviceObject;

    PdoExtension->ParentFdoDeviceObject = NULL;
    IoDeleteDevice(PdoExtension->PhysicalDeviceObject);
    ObDereferenceObject(ParentFdoDeviceObject);
}

NTSTATUS
NTAPI
HalpAddDevice(IN PDRIVER_OBJECT DriverObject,
              IN PDEVICE_OBJECT TargetDevice)
{
    NTSTATUS Status;
    PFDO_EXTENSION FdoExtension;
    PDEVICE_OBJECT DeviceObject, AttachedDevice;
    PDESCRIPTION_HEADER Wdrt;
    const HAL_PLATFORM_DEVICE *PlatformDevice;
    ULONG Index;

    DPRINT("HAL: PnP Driver ADD!\n");

    /* Create the FDO */
    Status = IoCreateDevice(DriverObject,
                            sizeof(FDO_EXTENSION),
                            NULL,
                            FILE_DEVICE_BUS_EXTENDER,
                            0,
                            FALSE,
                            &DeviceObject);
    if (!NT_SUCCESS(Status))
    {
        /* Should not happen */
        DbgBreakPoint();
        return Status;
    }

    /* Setup the FDO extension */
    FdoExtension = DeviceObject->DeviceExtension;
    FdoExtension->ExtensionType = FdoExtensionType;
    FdoExtension->PhysicalDeviceObject = TargetDevice;
    FdoExtension->FunctionalDeviceObject = DeviceObject;
    FdoExtension->ChildPdoList = NULL;
    ExInitializeFastMutex(&FdoExtension->ChildPdoLock);

    /* Attach to the physical device object (the bus) */
    AttachedDevice = IoAttachDeviceToDeviceStack(DeviceObject, TargetDevice);
    if (!AttachedDevice)
    {
        /* Failed, undo everything */
        IoDeleteDevice(DeviceObject);
        return STATUS_NO_SUCH_DEVICE;
    }

    /* Save the attachment */
    FdoExtension->AttachedDeviceObject = AttachedDevice;

    /* Create the ACPI PDO */
    Status = HalpCreatePdo(DriverObject, FdoExtension, AcpiPdo, NULL);
    if (!NT_SUCCESS(Status))
    {
        /* Fail */
        DPRINT1("HAL: Could not create ACPI device object status=0x%08x\n", Status);
        IoDetachDevice(AttachedDevice);
        IoDeleteDevice(DeviceObject);
        return Status;
    }

    /* Report the devices the firmware tables do not describe */
    for (Index = 0; (PlatformDevice = HalpGetPlatformDevice(Index)) != NULL; Index++)
    {
        /* A missing platform device must not fail the HAL bus */
        if (!NT_SUCCESS(HalpCreatePdo(DriverObject, FdoExtension, PlatformPdo, PlatformDevice)))
        {
            DPRINT1("HAL: Could not create platform PDO for %S\n", PlatformDevice->DeviceId);
        }
    }

    /* Find the ACPI watchdog table */
    Wdrt = HalAcpiGetTable(0, 'TRDW');
    if (Wdrt)
    {
        /* FIXME: TODO */
        DPRINT1("You have an ACPI Watchdog. That's great! You should be proud ;-)\n");
    }

    /* FDO is done initializing */
    DeviceObject->Flags &= ~DO_DEVICE_INITIALIZING;

    /* Return status */
    DPRINT("Device added %lx\n", Status);
    return Status;
}

NTSTATUS
NTAPI
HalpQueryInterface(IN PDEVICE_OBJECT DeviceObject,
                   IN CONST GUID* InterfaceType,
                   IN USHORT Version,
                   IN PVOID InterfaceSpecificData,
                   IN ULONG InterfaceBufferSize,
                   IN PINTERFACE Interface,
                   OUT PULONG Length)
{
    NTSTATUS Status;

    UNREFERENCED_PARAMETER(InterfaceSpecificData);

    Status = HalpQueryBusInterface(DeviceObject,
                                   InterfaceType,
                                   Version,
                                   InterfaceBufferSize,
                                   Interface,
                                   Length);
    if (Status == STATUS_NOT_SUPPORTED)
    {
        DPRINT1("HalpQueryInterface({%08X-%04X-%04X-%02X%02X-%02X%02X%02X%02X%02X%02X}) is UNIMPLEMENTED\n",
                InterfaceType->Data1, InterfaceType->Data2, InterfaceType->Data3,
                InterfaceType->Data4[0], InterfaceType->Data4[1],
                InterfaceType->Data4[2], InterfaceType->Data4[3],
                InterfaceType->Data4[4], InterfaceType->Data4[5],
                InterfaceType->Data4[6], InterfaceType->Data4[7]);
    }

    return Status;
}

NTSTATUS
NTAPI
HalpQueryDeviceRelations(IN PDEVICE_OBJECT DeviceObject,
                         IN DEVICE_RELATION_TYPE RelationType,
                         OUT PDEVICE_RELATIONS* DeviceRelations)
{
    EXTENSION_TYPE ExtensionType;
    PPDO_EXTENSION PdoExtension;
    PFDO_EXTENSION FdoExtension;
    PDEVICE_RELATIONS PdoRelations, FdoRelations;
    PDEVICE_OBJECT* ObjectEntry;
    ULONG i = 0, PdoCount = 0;

    /* Get FDO device extension and PDO count */
    FdoExtension = DeviceObject->DeviceExtension;
    ExtensionType = FdoExtension->ExtensionType;

    /* What do they want? */
    if (RelationType == BusRelations)
    {
        /* This better be an FDO */
        if (ExtensionType == FdoExtensionType)
        {
            ExAcquireFastMutex(&FdoExtension->ChildPdoLock);

            /* Count how many PDOs we have */
            PdoExtension = FdoExtension->ChildPdoList;
            while (PdoExtension)
            {
                /* Next one */
                PdoExtension = PdoExtension->Next;
                PdoCount++;
            }

            /* Add the PDOs that already exist in the device relations */
            if (*DeviceRelations)
            {
                PdoCount += (*DeviceRelations)->Count;
            }

            /* Allocate our structure */
            FdoRelations = ExAllocatePoolWithTag(PagedPool,
                                                 FIELD_OFFSET(DEVICE_RELATIONS,
                                                              Objects) +
                                                 sizeof(PDEVICE_OBJECT) * PdoCount,
                                                 TAG_HAL);
            if (!FdoRelations)
            {
                ExReleaseFastMutex(&FdoExtension->ChildPdoLock);
                return STATUS_INSUFFICIENT_RESOURCES;
            }

            /* Save our count */
            FdoRelations->Count = PdoCount;

            /* Query existing relations */
            ObjectEntry = FdoRelations->Objects;
            if (*DeviceRelations)
            {
                /* Check if there were any */
                if ((*DeviceRelations)->Count)
                {
                    /* Loop them all */
                    do
                    {
                        /* Copy into our structure */
                        *ObjectEntry++ = (*DeviceRelations)->Objects[i];
                    }
                    while (++i < (*DeviceRelations)->Count);
                }

                /* Free existing structure */
                ExFreePool(*DeviceRelations);
            }

            /* Now check if we have a PDO list */
            PdoExtension = FdoExtension->ChildPdoList;
            if (PdoExtension)
            {
                /* Loop the PDOs */
                do
                {
                    /* Save our own PDO and reference it */
                    *ObjectEntry++ = PdoExtension->PhysicalDeviceObject;
                    ObReferenceObject(PdoExtension->PhysicalDeviceObject);

                    /* Go to our next PDO */
                    PdoExtension = PdoExtension->Next;
                }
                while (PdoExtension);
            }

            ExReleaseFastMutex(&FdoExtension->ChildPdoLock);

            /* Return the new structure */
            *DeviceRelations = FdoRelations;
            return STATUS_SUCCESS;
        }
    }
    else
    {
        /* The only other thing we support is a target relation for the PDO */
        if ((RelationType == TargetDeviceRelation) &&
            (ExtensionType == PdoExtensionType))
        {
            /* Only one entry */
            PdoRelations = ExAllocatePoolWithTag(PagedPool,
                                                 sizeof(DEVICE_RELATIONS),
                                                 TAG_HAL);
            if (!PdoRelations) return STATUS_INSUFFICIENT_RESOURCES;

            /* Fill it out and reference us */
            PdoRelations->Count = 1;
            PdoRelations->Objects[0] = DeviceObject;
            ObReferenceObject(DeviceObject);

            /* Return it */
            *DeviceRelations = PdoRelations;
            return STATUS_SUCCESS;
        }
    }

    /* We don't support anything else */
    return STATUS_NOT_SUPPORTED;
}

NTSTATUS
NTAPI
HalpQueryCapabilities(IN PDEVICE_OBJECT DeviceObject,
                      OUT PDEVICE_CAPABILITIES Capabilities)
{
    NTSTATUS Status;
    ULONG i;
    PAGED_CODE();

    /* Check for valid version */
    ASSERT(Capabilities->Version == 1);
    if (Capabilities->Version == 1)
    {
        /* Can't lock or eject us */
        Capabilities->LockSupported = FALSE;
        Capabilities->EjectSupported = FALSE;

        /* Can't remove or dock us */
        Capabilities->Removable = FALSE;
        Capabilities->DockDevice = FALSE;

        /* Can't access us raw */
        Capabilities->RawDeviceOK = FALSE;

        /* We have a unique ID, and don't bother the user */
        Capabilities->UniqueID = TRUE;
        Capabilities->SilentInstall = TRUE;

        /* Fill out the address */
        Capabilities->Address = InterfaceTypeUndefined;
        Capabilities->UINumber = InterfaceTypeUndefined;

        /* We can't wake the system */
        Capabilities->SystemWake = PowerSystemUnspecified;
        Capabilities->DeviceWake = PowerDeviceUnspecified;

        /* Fill out latencies */
        Capabilities->D1Latency = 0;
        Capabilities->D2Latency = 0;
        Capabilities->D3Latency = 0;

        /* Fill out supported device states: on while working, off otherwise */
        for (i = PowerSystemWorking; i < PowerSystemMaximum; i++)
        {
            Capabilities->DeviceState[i] = PowerDeviceD3;
        }
        Capabilities->DeviceState[PowerSystemWorking] = PowerDeviceD0;

        /* Done */
        Status = STATUS_SUCCESS;
    }
    else
    {
        /* Fail */
        Status = STATUS_NOT_SUPPORTED;
    }

    /* Return status */
    return Status;
}

/*
 * Report a platform device's fixed memory windows and interrupt. The raw GSI
 * goes in u.Interrupt.Level; the PnP manager translates it through the HAL.
 */
static
NTSTATUS
HalpBuildPlatformDeviceResources(
    _In_ const HAL_PLATFORM_DEVICE *Device,
    _Out_ PCM_RESOURCE_LIST *Resources)
{
    PCM_RESOURCE_LIST List;
    PCM_PARTIAL_RESOURCE_DESCRIPTOR Desc;
    ULONG Count;
    ULONG Index;
    ULONG Size;

    Count = Device->MemoryCount + (Device->Gsi != 0 ? 1 : 0);
    if (Count == 0)
        return STATUS_NOT_SUPPORTED;

    /* CM_RESOURCE_LIST already covers one partial descriptor */
    Size = sizeof(CM_RESOURCE_LIST) +
           (Count - 1) * sizeof(CM_PARTIAL_RESOURCE_DESCRIPTOR);
    List = ExAllocatePoolZero(PagedPool, Size, TAG_HAL);
    if (!List)
        return STATUS_INSUFFICIENT_RESOURCES;

    List->Count = 1;
    List->List[0].InterfaceType = PNPBus;
    List->List[0].BusNumber = 0;
    List->List[0].PartialResourceList.Version = 1;
    List->List[0].PartialResourceList.Revision = 1;
    List->List[0].PartialResourceList.Count = Count;

    Desc = List->List[0].PartialResourceList.PartialDescriptors;

    for (Index = 0; Index < Device->MemoryCount; Index++, Desc++)
    {
        Desc->Type = CmResourceTypeMemory;
        Desc->ShareDisposition = CmResourceShareDeviceExclusive;
        Desc->Flags = CM_RESOURCE_MEMORY_READ_WRITE;
        Desc->u.Memory.Start.QuadPart = Device->Memory[Index].Base;
        Desc->u.Memory.Length = Device->Memory[Index].Length;
    }

    if (Device->Gsi != 0)
    {
        Desc->Type = CmResourceTypeInterrupt;
        Desc->ShareDisposition = CmResourceShareDeviceExclusive;
        Desc->Flags = Device->EdgeTriggered ? CM_RESOURCE_INTERRUPT_LATCHED
                                            : CM_RESOURCE_INTERRUPT_LEVEL_SENSITIVE;
        Desc->u.Interrupt.Level = Device->Gsi;
        Desc->u.Interrupt.Vector = Device->Gsi;
        Desc->u.Interrupt.Affinity = (KAFFINITY)-1;
    }

    *Resources = List;
    return STATUS_SUCCESS;
}

/* The matching requirements: fixed addresses and a fixed GSI */
static
NTSTATUS
HalpBuildPlatformDeviceRequirements(
    _In_ const HAL_PLATFORM_DEVICE *Device,
    _Out_ PIO_RESOURCE_REQUIREMENTS_LIST *Requirements)
{
    PIO_RESOURCE_REQUIREMENTS_LIST List;
    PIO_RESOURCE_DESCRIPTOR Desc;
    ULONG Count;
    ULONG Index;
    ULONG Size;

    Count = Device->MemoryCount + (Device->Gsi != 0 ? 1 : 0);
    if (Count == 0)
        return STATUS_NOT_SUPPORTED;

    /* One alternative list; the structure already covers one descriptor */
    Size = sizeof(IO_RESOURCE_REQUIREMENTS_LIST) +
           (Count - 1) * sizeof(IO_RESOURCE_DESCRIPTOR);
    List = ExAllocatePoolZero(PagedPool, Size, TAG_HAL);
    if (!List)
        return STATUS_INSUFFICIENT_RESOURCES;

    List->ListSize = Size;
    List->InterfaceType = PNPBus;
    List->BusNumber = 0;
    List->SlotNumber = 0;
    List->AlternativeLists = 1;
    List->List[0].Version = 1;
    List->List[0].Revision = 1;
    List->List[0].Count = Count;

    Desc = List->List[0].Descriptors;

    for (Index = 0; Index < Device->MemoryCount; Index++, Desc++)
    {
        Desc->Type = CmResourceTypeMemory;
        Desc->ShareDisposition = CmResourceShareDeviceExclusive;
        Desc->Flags = CM_RESOURCE_MEMORY_READ_WRITE;
        Desc->u.Memory.Length = Device->Memory[Index].Length;
        Desc->u.Memory.Alignment = 1;
        Desc->u.Memory.MinimumAddress.QuadPart = Device->Memory[Index].Base;
        Desc->u.Memory.MaximumAddress.QuadPart =
            Device->Memory[Index].Base + Device->Memory[Index].Length - 1;
    }

    if (Device->Gsi != 0)
    {
        Desc->Type = CmResourceTypeInterrupt;
        Desc->ShareDisposition = CmResourceShareDeviceExclusive;
        Desc->Flags = Device->EdgeTriggered ? CM_RESOURCE_INTERRUPT_LATCHED
                                            : CM_RESOURCE_INTERRUPT_LEVEL_SENSITIVE;
        Desc->u.Interrupt.MinimumVector = Device->Gsi;
        Desc->u.Interrupt.MaximumVector = Device->Gsi;
    }

    *Requirements = List;
    return STATUS_SUCCESS;
}

NTSTATUS
NTAPI
HalpQueryResources(IN PDEVICE_OBJECT DeviceObject,
                   OUT PCM_RESOURCE_LIST *Resources)
{
    PPDO_EXTENSION DeviceExtension = DeviceObject->DeviceExtension;
    NTSTATUS Status;
    PCM_RESOURCE_LIST ResourceList;
    PIO_RESOURCE_REQUIREMENTS_LIST RequirementsList;
    PIO_RESOURCE_DESCRIPTOR Descriptor;
    PCM_PARTIAL_RESOURCE_DESCRIPTOR PartialDesc;
    ULONG ReservedCount;
    ULONG i;
    PAGED_CODE();

    /* Only the ACPI PDO has requirements */
    if (DeviceExtension->PdoType == AcpiPdo)
    {
        /* Query ACPI requirements */
        Status = HalpQueryAcpiResourceRequirements(&RequirementsList);
        if (!NT_SUCCESS(Status)) return Status;

        ASSERT(RequirementsList->AlternativeLists == 1);

        /* Allocate the resource list: the SCI plus what the HAL reserves */
        ReservedCount = HalpQueryReservedResources(NULL);
        ResourceList = ExAllocatePoolWithTag(PagedPool,
                                             sizeof(CM_RESOURCE_LIST) +
                                             ReservedCount * sizeof(CM_PARTIAL_RESOURCE_DESCRIPTOR),
                                             TAG_HAL);
        if (!ResourceList)
        {
            /* Fail, no memory */
            Status = STATUS_INSUFFICIENT_RESOURCES;
            ExFreePoolWithTag(RequirementsList, TAG_HAL);
            return Status;
        }

        /* Initialize it */
        RtlZeroMemory(ResourceList, sizeof(CM_RESOURCE_LIST));
        ResourceList->Count = 1;

        /* Setup the list fields */
        ResourceList->List[0].BusNumber = -1;
        ResourceList->List[0].InterfaceType = PNPBus;
        ResourceList->List[0].PartialResourceList.Version = 1;
        ResourceList->List[0].PartialResourceList.Revision = 1;
        ResourceList->List[0].PartialResourceList.Count = 0;

        /* Setup the first descriptor */
        PartialDesc = ResourceList->List[0].PartialResourceList.PartialDescriptors;

        /* Find the requirement descriptor for the SCI */
        for (i = 0; i < RequirementsList->List[0].Count; i++)
        {
            /* Get this descriptor */
            Descriptor = &RequirementsList->List[0].Descriptors[i];
            if (Descriptor->Type == CmResourceTypeInterrupt)
            {
                /* Copy requirements descriptor into resource descriptor */
                PartialDesc->Type = CmResourceTypeInterrupt;
                PartialDesc->ShareDisposition = Descriptor->ShareDisposition;
                PartialDesc->Flags = Descriptor->Flags;
                ASSERT(Descriptor->u.Interrupt.MinimumVector ==
                       Descriptor->u.Interrupt.MaximumVector);

                /* Raw resource: the PnP manager translates the GSI */
                PartialDesc->u.Interrupt.Vector = Descriptor->u.Interrupt.MinimumVector;
                PartialDesc->u.Interrupt.Level = Descriptor->u.Interrupt.MinimumVector;
                PartialDesc->u.Interrupt.Affinity = (KAFFINITY)-1;

                ResourceList->List[0].PartialResourceList.Count++;
                PartialDesc++;

                break;
            }
        }

        /* Append the resources the HAL keeps for itself */
        ResourceList->List[0].PartialResourceList.Count += HalpQueryReservedResources(PartialDesc);

        /* Return resources and success */
        *Resources = ResourceList;

        ExFreePoolWithTag(RequirementsList, TAG_HAL);

        return STATUS_SUCCESS;
    }
    else if (DeviceExtension->PdoType == PlatformPdo)
    {
        return HalpBuildPlatformDeviceResources(DeviceExtension->PlatformDevice,
                                                Resources);
    }
    else if (DeviceExtension->PdoType == WdPdo)
    {
        /* Watchdog doesn't */
        return STATUS_NOT_SUPPORTED;
    }
    else
    {
        /* This shouldn't happen */
        return STATUS_UNSUCCESSFUL;
    }
}

NTSTATUS
NTAPI
HalpQueryResourceRequirements(IN PDEVICE_OBJECT DeviceObject,
                              OUT PIO_RESOURCE_REQUIREMENTS_LIST *Requirements)
{
    PPDO_EXTENSION DeviceExtension = DeviceObject->DeviceExtension;
    PAGED_CODE();

    /* Only the ACPI PDO has requirements */
    if (DeviceExtension->PdoType == AcpiPdo)
    {
        /* Query ACPI requirements */
        return HalpQueryAcpiResourceRequirements(Requirements);
    }
    else if (DeviceExtension->PdoType == PlatformPdo)
    {
        return HalpBuildPlatformDeviceRequirements(DeviceExtension->PlatformDevice,
                                                   Requirements);
    }
    else if (DeviceExtension->PdoType == WdPdo)
    {
        /* Watchdog doesn't */
        return STATUS_NOT_SUPPORTED;
    }
    else
    {
        /* This shouldn't happen */
        return STATUS_UNSUCCESSFUL;
    }
}

NTSTATUS
NTAPI
HalpQueryIdPdo(IN PDEVICE_OBJECT DeviceObject,
               IN BUS_QUERY_ID_TYPE IdType,
               OUT PUSHORT *BusQueryId)
{
    PPDO_EXTENSION PdoExtension;
    PCWSTR DeviceId, CompatibleId;
    PCWSTR Ids[2];
    ULONG IdCount, i;
    BOOLEAN MultiSz;
    PWCHAR Buffer, Current;
    SIZE_T TotalChars;

    /* Get the PDO type */
    PdoExtension = DeviceObject->DeviceExtension;
    switch (PdoExtension->PdoType)
    {
        case AcpiPdo:
            DeviceId = L"ACPI_HAL\\PNP0C08";
            CompatibleId = L"*PNP0C08";
            break;

        case WdPdo:
            DeviceId = L"ACPI_HAL\\PNP0C18";
            CompatibleId = L"*PNP0C18";
            break;

        case PlatformPdo:
            /* A compatible ID (such as a PCI class) can select the driver */
            DeviceId = PdoExtension->PlatformDevice->DeviceId;
            CompatibleId = PdoExtension->PlatformDevice->CompatibleId;
            break;

        default:
            return STATUS_NOT_SUPPORTED;
    }

    /* What kind of ID is being requested? */
    DPRINT("ID: %d\n", IdType);
    switch (IdType)
    {
        case BusQueryDeviceID:

            /* The device ID is a single string */
            MultiSz = FALSE;
            IdCount = 1;
            Ids[0] = DeviceId;
            break;

        case BusQueryHardwareIDs:

            /* Hardware IDs are a multi-string */
            MultiSz = TRUE;
            IdCount = CompatibleId ? 2 : 1;
            Ids[0] = DeviceId;
            Ids[1] = CompatibleId;
            break;

        case BusQueryInstanceID:

            /* Instance ID */
            MultiSz = FALSE;
            IdCount = 1;
            Ids[0] = L"0";
            break;

        case BusQueryCompatibleIDs:
        default:

            /* We don't support anything else */
            return STATUS_NOT_SUPPORTED;
    }

    /* Each string is terminated; a multi-string has one more terminator */
    TotalChars = MultiSz ? 1 : 0;
    for (i = 0; i < IdCount; i++)
    {
        TotalChars += wcslen(Ids[i]) + 1;
    }

    /* Allocate the buffer */
    Buffer = ExAllocatePoolZero(PagedPool, TotalChars * sizeof(WCHAR), TAG_HAL);
    if (!Buffer) return STATUS_INSUFFICIENT_RESOURCES;

    /* Copy the strings; the zeroed buffer provides the terminators */
    Current = Buffer;
    for (i = 0; i < IdCount; i++)
    {
        RtlCopyMemory(Current, Ids[i], wcslen(Ids[i]) * sizeof(WCHAR));
        Current += wcslen(Ids[i]) + 1;
    }

    /* Return string */
    *BusQueryId = Buffer;
    DPRINT("Returning: %S\n", *BusQueryId);
    return STATUS_SUCCESS;
}

NTSTATUS
NTAPI
HalpQueryIdFdo(IN PDEVICE_OBJECT DeviceObject,
               IN BUS_QUERY_ID_TYPE IdType,
               OUT PUSHORT *BusQueryId)
{
    NTSTATUS Status;
    SIZE_T Length;
    PWCHAR Id;
    PWCHAR Buffer;

    /* What kind of ID is being requested? */
    DPRINT("ID: %d\n", IdType);
    switch (IdType)
    {
        case BusQueryDeviceID:
        case BusQueryHardwareIDs:

            /* This is our hardware ID */
            Id = HalHardwareIdString;
            break;

        case BusQueryInstanceID:

            /* And our instance ID */
            Id = L"0";
            break;

        default:

            /* We don't support anything else */
            return STATUS_NOT_SUPPORTED;
    }

    /* Calculate the length */
    Length = (wcslen(Id) * sizeof(WCHAR)) + sizeof(UNICODE_NULL);

    /* Allocate the buffer */
    Buffer = ExAllocatePoolWithTag(PagedPool,
                                   Length + sizeof(UNICODE_NULL),
                                   TAG_HAL);
    if (Buffer)
    {
        /* Copy the string and null-terminate it */
        RtlCopyMemory(Buffer, Id, Length);
        Buffer[Length / sizeof(WCHAR)] = UNICODE_NULL;

        /* Return string */
        *BusQueryId = Buffer;
        Status = STATUS_SUCCESS;
        DPRINT("Returning: %S\n", *BusQueryId);
    }
    else
    {
        /* Fail */
        Status = STATUS_INSUFFICIENT_RESOURCES;
    }

    /* Return status */
    return Status;
}

/* A device can stop or go away only once nobody holds its interfaces */
static
BOOLEAN
HalpIsDeviceQuiesced(
    _In_ PDEVICE_OBJECT DeviceObject)
{
    return InterlockedCompareExchange(HalpGetInterfaceReferenceCount(DeviceObject), 0, 0) == 0;
}

static
NTSTATUS
HalpDispatchPnpFdo(
    _In_ PDEVICE_OBJECT DeviceObject,
    _In_ PIRP Irp)
{
    PIO_STACK_LOCATION IoStackLocation = IoGetCurrentIrpStackLocation(Irp);
    PFDO_EXTENSION FdoExtension = DeviceObject->DeviceExtension;
    PPDO_EXTENSION PdoExtension, NextPdo;
    NTSTATUS Status;

    /* Query the IRP type */
    switch (IoStackLocation->MinorFunction)
    {
        case IRP_MN_REMOVE_DEVICE:

            DPRINT("Remove device received for FDO\n");

            /* The children were removed first: delete them with the bus */
            ExAcquireFastMutex(&FdoExtension->ChildPdoLock);
            PdoExtension = FdoExtension->ChildPdoList;
            FdoExtension->ChildPdoList = NULL;
            ExReleaseFastMutex(&FdoExtension->ChildPdoLock);

            while (PdoExtension)
            {
                BOOLEAN RemovedLater;

                NextPdo = PdoExtension->Next;

                /* A surprise-removed child goes away with its own remove IRP */
                ExAcquireFastMutex(&PdoExtension->PnpStateLock);
                PdoExtension->ParentFdoExtension = NULL;
                RemovedLater = (PdoExtension->PnpState == HalpPnpStateSurpriseRemoved);
                ExReleaseFastMutex(&PdoExtension->PnpStateLock);
                if (!RemovedLater) HalpDeletePdo(PdoExtension);

                PdoExtension = NextPdo;
            }

            Irp->IoStatus.Status = STATUS_SUCCESS;
            IoSkipCurrentIrpStackLocation(Irp);
            Status = IoCallDriver(FdoExtension->AttachedDeviceObject, Irp);
            IoDetachDevice(FdoExtension->AttachedDeviceObject);
            IoDeleteDevice(DeviceObject);
            return Status;

        case IRP_MN_QUERY_DEVICE_RELATIONS:

            /* Call the worker */
            DPRINT("Querying device relations for FDO\n");
            Status = HalpQueryDeviceRelations(DeviceObject,
                                              IoStackLocation->Parameters.QueryDeviceRelations.Type,
                                              (PVOID)&Irp->IoStatus.Information);
            break;

        case IRP_MN_QUERY_INTERFACE:

            /* Call the worker */
            DPRINT("Querying interface for FDO\n");
            Status = HalpQueryInterface(DeviceObject,
                                        IoStackLocation->Parameters.QueryInterface.InterfaceType,
                                        IoStackLocation->Parameters.QueryInterface.Size,
                                        IoStackLocation->Parameters.QueryInterface.InterfaceSpecificData,
                                        IoStackLocation->Parameters.QueryInterface.Version,
                                        IoStackLocation->Parameters.QueryInterface.Interface,
                                        (PVOID)&Irp->IoStatus.Information);
            break;

        case IRP_MN_QUERY_ID:

            /* Call the worker */
            DPRINT("Querying ID for FDO\n");
            Status = HalpQueryIdFdo(DeviceObject,
                                    IoStackLocation->Parameters.QueryId.IdType,
                                    (PVOID)&Irp->IoStatus.Information);
            break;

        default:

            DPRINT("Other IRP: %lx\n", IoStackLocation->MinorFunction);
            Status = STATUS_NOT_SUPPORTED;
            break;
    }

    /* What happpened? */
    if ((NT_SUCCESS(Status)) || (Status == STATUS_NOT_SUPPORTED))
    {
        /* Set the IRP status, unless this isn't understood */
        if (Status != STATUS_NOT_SUPPORTED)
        {
            Irp->IoStatus.Status = Status;
        }

        /* Pass it on */
        IoSkipCurrentIrpStackLocation(Irp);
        return IoCallDriver(FdoExtension->AttachedDeviceObject, Irp);
    }

    /* Otherwise, we failed, so set the status and complete the request */
    DPRINT1("IRP failed with status: %lx\n", Status);
    Irp->IoStatus.Status = Status;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    return Status;
}

static
NTSTATUS
HalpDispatchPnpPdo(
    _In_ PDEVICE_OBJECT DeviceObject,
    _In_ PIRP Irp)
{
    PIO_STACK_LOCATION IoStackLocation = IoGetCurrentIrpStackLocation(Irp);
    PPDO_EXTENSION PdoExtension = DeviceObject->DeviceExtension;
    UCHAR Minor = IoStackLocation->MinorFunction;
    BOOLEAN DeletePdo = FALSE;
    NTSTATUS Status;

    /* Query the IRP type */
    switch (Minor)
    {
        case IRP_MN_START_DEVICE:

            DPRINT1("Start device received\n");
            ExAcquireFastMutex(&PdoExtension->PnpStateLock);
            PdoExtension->PreviousPnpState = PdoExtension->PnpState;
            PdoExtension->PnpState = HalpPnpStateStarted;
            PdoExtension->CurrentDevicePowerState = PowerDeviceD0;
            ExReleaseFastMutex(&PdoExtension->PnpStateLock);
            Status = STATUS_SUCCESS;
            break;

        case IRP_MN_REMOVE_DEVICE:

            /* The device is still present unless the bus itself went away */
            DPRINT1("Remove device received\n");
            ExAcquireFastMutex(&PdoExtension->PnpStateLock);
            PdoExtension->PreviousPnpState = PdoExtension->PnpState;
            PdoExtension->PnpState = HalpPnpStateNotStarted;
            PdoExtension->CurrentDevicePowerState = PowerDeviceD3;
            DeletePdo = (PdoExtension->ParentFdoExtension == NULL);
            ExReleaseFastMutex(&PdoExtension->PnpStateLock);
            Status = STATUS_SUCCESS;
            break;

        case IRP_MN_QUERY_STOP_DEVICE:
        case IRP_MN_QUERY_REMOVE_DEVICE:

            /* Refuse while a consumer still holds one of our interfaces */
            DPRINT1("Query stop/remove received\n");
            ExAcquireFastMutex(&PdoExtension->PnpStateLock);
            if (!HalpIsDeviceQuiesced(DeviceObject))
            {
                Status = STATUS_DEVICE_BUSY;
            }
            else
            {
                PdoExtension->PreviousPnpState = PdoExtension->PnpState;
                PdoExtension->PnpState = (Minor == IRP_MN_QUERY_STOP_DEVICE) ?
                                         HalpPnpStateStopPending : HalpPnpStateRemovePending;
                Status = STATUS_SUCCESS;
            }
            ExReleaseFastMutex(&PdoExtension->PnpStateLock);
            break;

        case IRP_MN_CANCEL_STOP_DEVICE:
        case IRP_MN_CANCEL_REMOVE_DEVICE:

            DPRINT1("Cancel stop/remove received\n");
            ExAcquireFastMutex(&PdoExtension->PnpStateLock);
            if (((Minor == IRP_MN_CANCEL_STOP_DEVICE) &&
                 (PdoExtension->PnpState == HalpPnpStateStopPending)) ||
                ((Minor == IRP_MN_CANCEL_REMOVE_DEVICE) &&
                 (PdoExtension->PnpState == HalpPnpStateRemovePending)))
            {
                PdoExtension->PnpState = PdoExtension->PreviousPnpState;
            }
            ExReleaseFastMutex(&PdoExtension->PnpStateLock);
            Status = STATUS_SUCCESS;
            break;

        case IRP_MN_STOP_DEVICE:

            DPRINT1("Stop device received\n");
            ExAcquireFastMutex(&PdoExtension->PnpStateLock);
            PdoExtension->PreviousPnpState = PdoExtension->PnpState;
            PdoExtension->PnpState = HalpPnpStateStopped;
            PdoExtension->CurrentDevicePowerState = PowerDeviceD3;
            ExReleaseFastMutex(&PdoExtension->PnpStateLock);
            Status = STATUS_SUCCESS;
            break;

        case IRP_MN_SURPRISE_REMOVAL:

            DPRINT1("Surprise removal IRP\n");
            ExAcquireFastMutex(&PdoExtension->PnpStateLock);
            PdoExtension->PreviousPnpState = PdoExtension->PnpState;
            PdoExtension->PnpState = HalpPnpStateSurpriseRemoved;
            ExReleaseFastMutex(&PdoExtension->PnpStateLock);
            Status = STATUS_SUCCESS;
            break;

        case IRP_MN_QUERY_DEVICE_RELATIONS:

            /* Query the device relations */
            DPRINT("Querying PDO relations\n");
            Status = HalpQueryDeviceRelations(DeviceObject,
                                              IoStackLocation->Parameters.QueryDeviceRelations.Type,
                                              (PVOID)&Irp->IoStatus.Information);
            break;

        case IRP_MN_QUERY_INTERFACE:

            /* Call the worker */
            DPRINT("Querying interface for PDO\n");
            Status = HalpQueryInterface(DeviceObject,
                                        IoStackLocation->Parameters.QueryInterface.InterfaceType,
                                        IoStackLocation->Parameters.QueryInterface.Size,
                                        IoStackLocation->Parameters.QueryInterface.InterfaceSpecificData,
                                        IoStackLocation->Parameters.QueryInterface.Version,
                                        IoStackLocation->Parameters.QueryInterface.Interface,
                                        (PVOID)&Irp->IoStatus.Information);
            break;

        case IRP_MN_QUERY_CAPABILITIES:

            /* Call the worker */
            DPRINT("Querying the capabilities for the PDO\n");
            Status = HalpQueryCapabilities(DeviceObject,
                                           IoStackLocation->Parameters.DeviceCapabilities.Capabilities);
            break;

        case IRP_MN_QUERY_RESOURCES:

            /* Call the worker */
            DPRINT("Querying the resources for the PDO\n");
            Status = HalpQueryResources(DeviceObject, (PVOID)&Irp->IoStatus.Information);
            break;

        case IRP_MN_QUERY_RESOURCE_REQUIREMENTS:

            /* Call the worker */
            DPRINT("Querying the resource requirements for the PDO\n");
            Status = HalpQueryResourceRequirements(DeviceObject,
                                                   (PVOID)&Irp->IoStatus.Information);
            break;

        case IRP_MN_QUERY_ID:

            /* Call the worker */
            DPRINT("Query the ID for the PDO\n");
            Status = HalpQueryIdPdo(DeviceObject,
                                    IoStackLocation->Parameters.QueryId.IdType,
                                    (PVOID)&Irp->IoStatus.Information);
            break;

        default:

            /* We don't handle anything else, so inherit the old state */
            DPRINT("Illegal IRP: %lx\n", Minor);
            Status = Irp->IoStatus.Status;
            break;
    }

    /* If it's not supported, inherit the old status */
    if (Status == STATUS_NOT_SUPPORTED) Status = Irp->IoStatus.Status;

    /* Complete the IRP */
    DPRINT("IRP completed with status: %lx\n", Status);
    Irp->IoStatus.Status = Status;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);

    /* A child of a removed bus goes away with its last remove IRP */
    if (DeletePdo) HalpDeletePdo(PdoExtension);

    return Status;
}

NTSTATUS
NTAPI
HalpDispatchPnp(IN PDEVICE_OBJECT DeviceObject,
                IN PIRP Irp)
{
    PFDO_EXTENSION FdoExtension = DeviceObject->DeviceExtension;

    /* FDO? */
    if (FdoExtension->ExtensionType == FdoExtensionType)
        return HalpDispatchPnpFdo(DeviceObject, Irp);

    /* This is a PDO instead */
    ASSERT(FdoExtension->ExtensionType == PdoExtensionType);
    return HalpDispatchPnpPdo(DeviceObject, Irp);
}

NTSTATUS
NTAPI
HalpDispatchWmi(IN PDEVICE_OBJECT DeviceObject,
                IN PIRP Irp)
{
    PFDO_EXTENSION FdoExtension = DeviceObject->DeviceExtension;
    NTSTATUS Status;

    DPRINT("HAL: PnP Driver WMI!\n");

    /* We are no WMI provider: pass it down, or leave the status as it is */
    if (FdoExtension->ExtensionType == FdoExtensionType)
    {
        IoSkipCurrentIrpStackLocation(Irp);
        return IoCallDriver(FdoExtension->AttachedDeviceObject, Irp);
    }

    Status = Irp->IoStatus.Status;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    return Status;
}

NTSTATUS
NTAPI
HalpDispatchPower(IN PDEVICE_OBJECT DeviceObject,
                  IN PIRP Irp)
{
    PFDO_EXTENSION FdoExtension = DeviceObject->DeviceExtension;
    PIO_STACK_LOCATION IoStackLocation = IoGetCurrentIrpStackLocation(Irp);
    PPDO_EXTENSION PdoExtension;
    POWER_STATE PowerState;
    NTSTATUS Status;

    DPRINT("HAL: PnP Driver Power!\n");
    PoStartNextPowerIrp(Irp);

    if (FdoExtension->ExtensionType == FdoExtensionType)
    {
        IoSkipCurrentIrpStackLocation(Irp);
        return PoCallDriver(FdoExtension->AttachedDeviceObject, Irp);
    }

    ASSERT(FdoExtension->ExtensionType == PdoExtensionType);
    PdoExtension = (PPDO_EXTENSION)FdoExtension;

    switch (IoStackLocation->MinorFunction)
    {
        case IRP_MN_SET_POWER:

            /* Track the state; there is no hardware to program */
            PowerState = IoStackLocation->Parameters.Power.State;
            if (IoStackLocation->Parameters.Power.Type == DevicePowerState)
            {
                PdoExtension->CurrentDevicePowerState = PowerState.DeviceState;
                PoSetPowerState(DeviceObject, DevicePowerState, PowerState);
            }
            else
            {
                PdoExtension->CurrentSystemPowerState = PowerState.SystemState;
            }
            Status = STATUS_SUCCESS;
            break;

        case IRP_MN_QUERY_POWER:

            Status = STATUS_SUCCESS;
            break;

        default:

            /* We can't wake the system: leave anything else as it is */
            Status = Irp->IoStatus.Status;
            break;
    }

    Irp->IoStatus.Status = Status;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    return Status;
}

NTSTATUS
NTAPI
HalpDriverEntry(IN PDRIVER_OBJECT DriverObject,
                IN PUNICODE_STRING RegistryPath)
{
    NTSTATUS Status;
    PDEVICE_OBJECT TargetDevice = NULL;

    DPRINT("HAL: PnP Driver ENTRY!\n");

    /* This is us */
    HalpDriverObject = DriverObject;

    /* Set up add device */
    DriverObject->DriverExtension->AddDevice = HalpAddDevice;

    /* Set up the callouts */
    DriverObject->MajorFunction[IRP_MJ_PNP] = HalpDispatchPnp;
    DriverObject->MajorFunction[IRP_MJ_POWER] = HalpDispatchPower;
    DriverObject->MajorFunction[IRP_MJ_SYSTEM_CONTROL] = HalpDispatchWmi;

    /* Create the PDO and tell the PnP manager about us*/
    Status = IoReportDetectedDevice(DriverObject,
                                    InterfaceTypeUndefined,
                                    -1,
                                    -1,
                                    NULL,
                                    NULL,
                                    FALSE,
                                    &TargetDevice);
    if (!NT_SUCCESS(Status))
        return Status;

    TargetDevice->Flags &= ~DO_DEVICE_INITIALIZING;

    /* Set up the device stack */
    Status = HalpAddDevice(DriverObject, TargetDevice);
    if (!NT_SUCCESS(Status))
    {
        IoDeleteDevice(TargetDevice);
        return Status;
    }

    /* Return to kernel */
    return Status;
}

NTSTATUS
NTAPI
HaliInitPnpDriver(VOID)
{
    NTSTATUS Status;
    UNICODE_STRING DriverString;
    PAGED_CODE();

    /* Create the driver */
    RtlInitUnicodeString(&DriverString, L"\\Driver\\ACPI_HAL");
    Status = IoCreateDriver(&DriverString, HalpDriverEntry);

    /* Return status */
    return Status;
}

/* EOF */
