/* SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: 2026 Ahmed ARIF <arif193@gmail.com>
 */

/* Coordinates and shared textures use top-down D3D window space. */
static const char DwmD3dShaderSource[] =
    "cbuffer State : register(b0) {\n"
    "  float4 rectangle, targetSize, sourceSize, clientRect, captureRect;\n"
    "  float4 brush, colorization, colorKey, flags, extra, shadow, filter;\n"
    "  float4 taps[33];\n"
    "};\n"
    "Texture2D source : register(t0);\n"
    "Texture2D backdrop : register(t1);\n"
    "SamplerState linearClamp : register(s0);\n"
    "struct Vertex { float4 position : SV_Position; float2 uv : TEXCOORD0; };\n"
    "Vertex QuadVS(uint index : SV_VertexID) {\n"
    "  Vertex v; v.uv = float2(index & 1, index >> 1);\n"
    "  float2 p = lerp(rectangle.xy, rectangle.zw, v.uv) / targetSize.xy;\n"
    "  v.position = float4(p * float2(2,-2) + float2(-1,1), 0, 1); return v;\n"
    "}\n"
    "float4 SolidPS(Vertex v) : SV_Target { return brush; }\n"
    "float4 CopyPS(Vertex v) : SV_Target { return float4(source.Sample(linearClamp, v.uv).rgb, sourceSize.z); }\n"
    "float distanceRGB(float3 a, float3 b) { float3 d = abs(a-b); return max(d.r,max(d.g,d.b)); }\n"
    "float materialBump(float t, float center, float halfWidth, float peak) {\n"
    "  float q=saturate(1-abs((t-center)/halfWidth)); return peak*q*q*(3-2*q);\n"
    "}\n"
    "float materialReflection(float2 screen) {\n"
    "  float t=(screen.x+screen.y*1.2)/(targetSize.x+targetSize.y*1.2+2);\n"
    "  return min(1,materialBump(t,0.30,0.14,1)+materialBump(t,0.60,0.05,0.55)+materialBump(t,0.80,0.11,0.40));\n"
    "}\n"
    "float4 WindowPS(Vertex v) : SV_Target {\n"
    "  float4 s = source.Sample(linearClamp, v.uv);\n"
    "  if (flags.w != 0 && distanceRGB(s.rgb,colorKey.rgb) < 0.5/255.0) discard;\n"
    "  float2 p = v.uv * sourceSize.xy; float coverage = 1;\n"
    "  if (sourceSize.w > 0) {\n"
    "    float2 q = abs(p-sourceSize.xy*0.5) - (sourceSize.xy*0.5-sourceSize.ww);\n"
    "    float d = length(max(q,0)) + min(max(q.x,q.y),0)-sourceSize.w;\n"
    "    coverage = saturate(0.5-d);\n"
    "  }\n"
    "  if (flags.x != 0 && (flags.y != 0 || p.x < clientRect.x || p.y < clientRect.y ||\n"
    "      p.x >= clientRect.z || p.y >= clientRect.w)) {\n"
    "    float a = distanceRGB(s.rgb,brush.rgb), b = distanceRGB(s.rgb,colorization.rgb);\n"
    "    float3 key = b < a ? colorization.rgb : brush.rgb;\n"
    "    float weight = saturate((96-min(a,b)*255)/48);\n"
    "    float3 base = backdrop.Sample(linearClamp,(v.position.xy-captureRect.xy)/captureRect.zw).rgb;\n"
    "    float luma=dot(base,float3(77,151,28)/256);\n"
    "    base=saturate(luma+(base-luma)*extra.y);\n"
    "    s.rgb = saturate(s.rgb+(base-key)*(1-extra.x)*weight+\n"
    "      extra.z*materialReflection(v.position.xy)*weight);\n"
    "  }\n"
    "  float outputAlpha=sourceSize.z*coverage*(flags.z != 0 ? s.a : 1);\n"
    "  return float4(extra.w != 0 ? s.rgb*sourceSize.z*coverage : s.rgb,outputAlpha);\n"
    "}\n"
    "float4 FilterPS(Vertex v) : SV_Target {\n"
    "  float4 color = source.Sample(linearClamp,v.uv)*taps[0].x;\n"
    "  for (int i=1; i<(int)filter.z; ++i) {\n"
    "    float2 step = filter.xy*taps[i].y;\n"
    "    color += (source.Sample(linearClamp,v.uv+step)+source.Sample(linearClamp,v.uv-step))*taps[i].x;\n"
    "  }\n"
    "  return color;\n"
    "}\n"
    "float cdf(float x) {\n"
    "  float z=abs(x), t=1/(1+0.2316419*z);\n"
    "  float p=0.39894228*exp(-0.5*z*z)*t*(0.319381530+t*(-0.356563782+t*(1.781477937+t*(-1.821255978+t*1.330274429))));\n"
    "  return x<0 ? p : 1-p;\n"
    "}\n"
    "float coverage(float p, float n, float sigma) { return saturate(cdf((p+0.5)/sigma)-cdf((p-n+0.5)/sigma)); }\n"
    "float4 ShadowPS(Vertex v) : SV_Target {\n"
    "  float2 p=v.position.xy-0.5-captureRect.xy;\n"
    "  float wx=floor(coverage(p.x,sourceSize.x,shadow.x)*256+0.5);\n"
    "  float tx=floor(coverage(p.x,sourceSize.x,shadow.y)*256+0.5);\n"
    "  float wy=floor(coverage(p.y-extra.y,sourceSize.y,shadow.x)*shadow.z*extra.z/1000);\n"
    "  float ty=floor(coverage(p.y-extra.y,sourceSize.y,shadow.y)*shadow.w*extra.z/1000);\n"
    "  float wa=floor(wx*wy/256), ta=floor(tx*ty/256);\n"
    "  return float4(0,0,0,min(wa+ta-floor(wa*ta/256),255)/256);\n"
    "}\n";
