/* Automatically generated by make depend; DO NOT EDIT!! */

#define STANDALONE
#include <wine/test.h>

extern void func_d3dxof(void);

const struct test winetest_testlist[] =
{
    { "d3dxof", func_d3dxof },
    { 0, 0 }
};
