spec2def(windows.security.credentials.ui.userconsentverifier.dll windows.security.credentials.ui.userconsentverifier.spec)
add_idl_headers(windows_security_credentials_ui_userconsentverifier_private_idl async_private.idl)

list(APPEND SOURCE
    async.c
    main.c)

add_library(windows_security_credentials_ui_userconsentverifier MODULE ${SOURCE} ${CMAKE_CURRENT_BINARY_DIR}/windows.security.credentials.ui.userconsentverifier.def ${CMAKE_CURRENT_BINARY_DIR}/windows.security.credentials.ui.userconsentverifier_stubs.c)
set_target_properties(windows_security_credentials_ui_userconsentverifier PROPERTIES OUTPUT_NAME "windows.security.credentials.ui.userconsentverifier")
add_idl_reg_scripts(windows_security_credentials_ui_userconsentverifier winrt classes.idl)
add_dependencies(windows_security_credentials_ui_userconsentverifier windows_security_credentials_ui_userconsentverifier_private_idl)
set_module_type(windows_security_credentials_ui_userconsentverifier win32dll)
target_compile_definitions(windows_security_credentials_ui_userconsentverifier PRIVATE __WINESRC__)
target_link_libraries(windows_security_credentials_ui_userconsentverifier uuid wine wine_dll_canunload wine_dll_register)
add_importlibs(windows_security_credentials_ui_userconsentverifier combase msvcrt kernel32 ntdll)
add_cd_file(TARGET windows_security_credentials_ui_userconsentverifier DESTINATION reactos/system32 FOR all)
set_wine_module_FIXME(windows_security_credentials_ui_userconsentverifier)
