/*
 * PROJECT:     ReactOS Raspberry Pi 5 WDDM display-only miniport
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Shared declarations for the RPi5 (BCM2712) WDDM2 KMDOD.
 * COPYRIGHT:   Copyright 2026 Ahmed Arif <arif193@gmail.com>
 *
 * WDDM2 display-only rework of the former XPDM videoport miniport
 * (win32ss/drivers/miniport/rpi5vc4).  The driver registers through
 * DxgkInitializeDisplayOnlyDriver, takes over the firmware GOP framebuffer
 * via DxgkCbAcquirePostDisplayOwnership, owns the HVS scanout display list
 * and composites the hardware cursor as a second HVS plane.
 */

#ifndef _RPI5VC4_PCH_
#define _RPI5VC4_PCH_

/* Mirror dxgkrnl/softgpu: the WDDM2 structures in dispmprt.h are gated on
 * NTDDI_WIN7 and DXGKDDI_INTERFACE_VERSION (see CMakeLists.txt). */
#undef  _WIN32_WINNT
#define _WIN32_WINNT  0x0601
#undef  WINVER
#define WINVER        0x0601
#undef  NTDDI_VERSION
#define NTDDI_VERSION 0x06010000

#ifndef DXGKDDI_INTERFACE_VERSION
#define DXGKDDI_INTERFACE_VERSION 0x5023 /* DXGKDDI_INTERFACE_VERSION_WDDM2_0 */
#endif

#include <ntddk.h>
#include <wdm.h>
#include <windef.h>
#include <dispmprt.h>
#include <reactos/rpi5vc4_umd.h>

#ifndef DXGKDDI_INTERFACE_VERSION_WDDM2_0
#define DXGKDDI_INTERFACE_VERSION_WDDM2_0 0x5023
#endif

/* Physical HDMI connectors on the BCM2712 (HDMI0 = boot display). */
#define RPI5VC4_CHILD_COUNT   2

#define RPI5VC4_CURSOR_WIDTH  64
#define RPI5VC4_CURSOR_HEIGHT 64

#define RPI5VC4_POOL_TAG '4cVR'

/* Local VRAM segment: a contiguous write-combined slab the HVS can scan
 * out of and the V3D can DMA to/from.  Sized best-effort at StartDevice. */
#define RPI5VC4_SEGMENT_ID          1
#define RPI5VC4_VRAM_SIZE_PREFERRED (64 * 1024 * 1024)
#define RPI5VC4_VRAM_SIZE_MIN       (16 * 1024 * 1024)

/* In-order submission tracking ("the GPU pipeline"). */
#define RPI5VC4_MAX_PENDING         64
#define RPI5VC4_DMA_MAPPING_COUNT   256

/* GPU nodes exposed via GpuEngineTopology: 0 = CLE (3D bin/render),
 * 1 = TFU (conversion/blit), 2 = CSD (compute).  One shared hardware
 * ring serialises execution, so completions stay in global fence order;
 * fences are tracked and reported per node for the scheduler. */
#define RPI5VC4_GPU_NODE_COUNT      3
#define RPI5VC4_NODE_3D             0
#define RPI5VC4_NODE_TFU            1
#define RPI5VC4_NODE_CSD            2
/* Gears-scale CLs retire in <20ms; the vertex-pipe wedge is unrecoverable
 * below core reset, so a long timeout only stretches every park.  Revisit
 * per-job-class when heavier workloads land. */
#define RPI5VC4_V3D_JOB_TIMEOUT_100NS (300 * 10 * 1000) /* 300 ms */
#define RPI5VC4_V3D_BIN_FLUSH_TIMEOUT_100NS (50 * 10 * 1000) /* 50 ms */

typedef struct _RPI5VC4_PENDING_SUBMIT
{
    ULONG Fence;
    ULONG NodeOrdinal;
    ULONG ReportNode;
    UCHAR RenderKicks;
    UCHAR RenderKickRfc;              /* RFC&0xff snapshot at render kick   */
    UCHAR BinKickBfc;                 /* BFC&0xff snapshot at bin kick      */
    ULONGLONG BinDeferStart100ns;     /* first pass the pre-bin gate deferred */
    BOOLEAN IsV3dJob;
    BOOLEAN IsTfuJob;
    BOOLEAN IsCsdJob;
    BOOLEAN IsWarmup;
    BOOLEAN BinSubmitted;             /* BCL queued to CLE thread 0        */
    BOOLEAN BinDone;                  /* FLDONE consumed for this job      */
    BOOLEAN RenderSubmitted;          /* RCL/TFU/CSD kicked                */
    ULONG BclStart;
    ULONG BclEnd;
    ULONG RclStart;
    ULONG RclEnd;
    ULONG Qma;
    ULONG Qms;
    ULONG Qts;
    ULONG TfuRegs[12];
    ULONG CsdCfg[8];
    ULONGLONG QueuedTime100ns;
} RPI5VC4_PENDING_SUBMIT, *PRPI5VC4_PENDING_SUBMIT;

/* ========================================================================
 * DMA packet stream
 *
 * The command/DMA buffer contents exchanged with the (future) user-mode
 * driver and generated by DxgkDdiPresent.  DxgkDdiRender validates and
 * copies this stream; DxgkDdiSubmitCommand executes it: V3D job packets
 * are queued to the CLE, everything else completes with the fence.
 * ====================================================================== */

#define RPI5VC4_DMA_PACKET_MAGIC    0x52355644u  /* 'DV5R' */

#define RPI5VC4_DMA_OP_NOP          0
#define RPI5VC4_DMA_OP_PRESENT      1
#define RPI5VC4_DMA_OP_V3D_JOB      2
#define RPI5VC4_DMA_OP_TFU_JOB      3
#define RPI5VC4_DMA_OP_CSD_JOB      4

typedef struct _RPI5VC4_DMA_PACKET
{
    ULONG Magic;
    ULONG Op;
    ULONG Length;                    /* total packet bytes incl. header */
    ULONG Reserved;
    union
    {
        struct
        {
            /* GPU virtual addresses (see RPI5VC4_V3D_SLAB_GPUVA) — OR,
             * when *AllocIndexPlusOne is nonzero, byte offsets within
             * that allocation (index-1 into the submission's allocation
             * list): DxgkDdiRender then emits patch locations and
             * DxgkDdiPatch relocates the dwords to real GPU VAs.  A
             * zeroed field keeps absolute-address behaviour. */
            ULONG BclStart;          /* binning list; Start==End = none  */
            ULONG BclEnd;
            ULONG RclStart;          /* render list                      */
            ULONG RclEnd;
            ULONG BclAllocIndexPlusOne;
            ULONG RclAllocIndexPlusOne;
            /* Per-job tile allocation (absolute GPU VAs).  Qms==0 means
             * "use the device-global binner overflow pool" (legacy smoke
             * path); a real v3dv job supplies all three. */
            ULONG Qma;               /* tile allocation memory address    */
            ULONG Qms;               /* tile allocation memory size       */
            ULONG Qts;               /* tile state data array address     */
        } V3dJob;
        struct
        {
            RECT DstRect;
            ULONG Color;
            ULONG Flags;             /* DXGK_PRESENTFLAGS.Value          */
        } Present;
        struct
        {
            /* UMD-encoded TFU register image:
             * [Icfg Iia Ica Iis Iua Ioc Ioa Ios Coef0..Coef3]. */
            UINT Regs[12];
        } TfuJob;
        struct
        {
            /* UMD-encoded compute dispatch: QUEUED_CFG0..CFG7. */
            ULONG Cfg[8];
        } CsdJob;
    };
} RPI5VC4_DMA_PACKET, *PRPI5VC4_DMA_PACKET;

/* Per-object magics. */
#define RPI5VC4_DEVICE_MAGIC        0x52564430u  /* per-D3D-device        */
#define RPI5VC4_CONTEXT_MAGIC       0x52564431u
#define RPI5VC4_ALLOCATION_MAGIC    0x52564432u
#define RPI5VC4_OPENALLOC_MAGIC     0x52564433u

typedef struct _RPI5VC4_DEVICE_EXTENSION RPI5VC4_DEVICE_EXTENSION,
    *PRPI5VC4_DEVICE_EXTENSION;

typedef struct _RPI5VC4_WDDM_DEVICE
{
    ULONG Magic;
    PRPI5VC4_DEVICE_EXTENSION Adapter;
} RPI5VC4_WDDM_DEVICE, *PRPI5VC4_WDDM_DEVICE;

typedef struct _RPI5VC4_CONTEXT
{
    ULONG Magic;
    PRPI5VC4_WDDM_DEVICE Device;
} RPI5VC4_CONTEXT, *PRPI5VC4_CONTEXT;

typedef struct _RPI5VC4_ALLOCATION
{
    ULONG Magic;
    SIZE_T Size;
} RPI5VC4_ALLOCATION, *PRPI5VC4_ALLOCATION;

typedef struct _RPI5VC4_OPENALLOCATION
{
    ULONG Magic;
    D3DKMT_HANDLE hVidMmAllocation;
} RPI5VC4_OPENALLOCATION, *PRPI5VC4_OPENALLOCATION;

typedef struct _RPI5VC4_DMA_MAPPING
{
    UINT             SegmentId;
    PHYSICAL_ADDRESS PhysicalAddress;
    PVOID            VirtualAddress;
    ULONG            Size;
} RPI5VC4_DMA_MAPPING, *PRPI5VC4_DMA_MAPPING;

struct _RPI5VC4_DEVICE_EXTENSION
{
    /* dxgkrnl callback vtable captured at StartDevice. */
    DXGK_INTERFACE DxgkInterface;
    PDEVICE_OBJECT PhysicalDeviceObject;
    BOOLEAN Started;

    /* No firmware display (headless boot): the driver owns a RAM scanout
     * and reports a phantom monitor; HVS/PV stay untouched. */
    BOOLEAN Headless;
    PVOID HeadlessFbVa;
    PIO_WORKITEM HpdWorkItem;
    LONG HpdCheckQueued;
    KTIMER HpdTimer;
    KDPC HpdDpc;
    UCHAR Edid[128];
    BOOLEAN EdidValid;

    /* Firmware GOP scanout geometry (from DxgkCbAcquirePostDisplayOwnership). */
    PHYSICAL_ADDRESS FirmwareFrameBufferPhysical;
    PHYSICAL_ADDRESS FrameBufferPhysical;
    PVOID FrameBufferVa;              /* write-combined kernel mapping        */
    ULONG FrameBufferSize;
    ULONG ScreenWidth;
    ULONG ScreenHeight;
    ULONG PixelsPerScanLine;
    ULONG BitsPerPixel;
    ULONG BytesPerScanLine;
    D3DDDIFORMAT ColorFormat;

    /* Committed VidPN state. */
    BOOLEAN VidPnCommitted;
    BOOLEAN SourceVisible;

    /* Cached MMIO mapping of the HVS register block (mapped once, reused). */
    PVOID HvsBase;

    /* Cached MMIO mapping of the active PixelValve (mapped once, reused). */
    PVOID PixelValveBase;

    /* Validated cursor-plane location for the low-MMIO cursor move fast path. */
    ULONG HvsLptrsReg;
    ULONG HvsLptrsVal;
    ULONG HvsCursorHead;
    BOOLEAN HvsCursorFastValid;

    /* Active private display-list slot (0 = scanning the firmware head). */
    ULONG HvsActivePrivateSlot;

    /* Silicon bring-up state: consecutive flip failures latch the flip
     * path off (stops per-present vblank spins swamping the work queue);
     * a vblank-wait timeout latches the tear-avoidance wait off. */
    ULONG HvsFlipFailCount;
    BOOLEAN HvsFlipBroken;
    BOOLEAN PvVBlankBroken;
    LONG HvsDiagPrints;              /* budget for first-N diagnostics  */

    BOOLEAN PixelValveValid;
    ULONG PixelValveIndex;
    PHYSICAL_ADDRESS PixelValvePhysical;
    ULONG PixelValveControl;
    ULONG PixelValveVControl;
    ULONG PixelValveVsyncEven;
    ULONG PixelValveHorzA;
    ULONG PixelValveHorzB;
    ULONG PixelValveVertA;
    ULONG PixelValveVertB;
    ULONG PixelValveHactAct;

    /* Hardware cursor composited by the HVS as a second display-list plane. */
    PVOID CursorVa;                   /* CPU mapping of the cursor surface      */
    PHYSICAL_ADDRESS CursorPhys;      /* physical base the HVS scans the cursor */
    ULONG CursorWidth;
    ULONG CursorHeight;
    LONG CursorX;                     /* top-left, screen coordinates          */
    LONG CursorY;
    LONG CursorHotX;
    LONG CursorHotY;
    BOOLEAN CursorVisible;
    BOOLEAN CursorShapeValid;

    /* ---- Wayland-style flip presents ------------------------------------
     * Display-only presents compose into an off-screen buffer of a private
     * triple-buffer ring and page-flip the HVS plane (pointer words latch at
     * frame start = atomic, tear-free). Per-buffer stale rects catch each
     * buffer up from pSource (always the complete frame). 0 count = fall
     * back to the classic blit-into-live-scanout path. */
    PVOID FlipBufVa;                  /* one WC region holding the ring     */
    PHYSICAL_ADDRESS FlipBufPhys;
    ULONG FlipBufSize;                /* bytes of ONE buffer                */
    ULONG FlipBufCount;               /* ring depth (3/2) or 0 = disabled   */
    ULONG FlipBufIndex;               /* buffer the HVS currently scans     */
    ULONG FlipsSinceVBlank;           /* pending unlatched flips            */
    BOOLEAN FlipPresentBroken;
    RECT FlipStale[3];                /* per-buffer catch-up bounding box   */

    /* ---- Local VRAM segment (segment 1) -------------------------------- */
    PVOID VramVa;                     /* write-combined kernel mapping     */
    PHYSICAL_ADDRESS VramPhysical;
    ULONG VramSize;

    /* ---- In-order submission/fence pipeline ---------------------------- */
    KSPIN_LOCK DmaLock;
    RPI5VC4_DMA_MAPPING DmaMappings[RPI5VC4_DMA_MAPPING_COUNT];
    ULONG DmaMappingNext;
    LONG V3dKickPrints;
    /* One in-order queue per GPU node; the engines run in parallel. */
    struct
    {
        RPI5VC4_PENDING_SUBMIT Pending[RPI5VC4_MAX_PENDING];
        ULONG Head;                   /* index of oldest pending submit    */
        ULONG Count;
    } NodeQueue[RPI5VC4_GPU_NODE_COUNT];
    ULONG LastCompletedFence;
    ULONG LastCompletedFencePerNode[RPI5VC4_GPU_NODE_COUNT];
    ULONG LastReportedFencePerNode[RPI5VC4_GPU_NODE_COUNT];
    KDPC FenceDpc;                    /* notifies dxgkrnl of completions   */
    KTIMER V3dPollTimer;              /* drives V3D job completion polling */
    KDPC V3dPollDpc;
    BOOLEAN StopAccepting;            /* set during StopDevice             */
    BOOLEAN DmaPipelineInitialized;

    /* Vsync source: refresh-rate timer polling the PixelValve VFP latch
     * (the root-enumerated devnode has no interrupt resource). */
    KTIMER VsyncTimer;
    KDPC VsyncDpc;
    BOOLEAN VsyncEnabled;

    /* ---- V3D 7.1 (3D engine) state -------------------------------------- */
    BOOLEAN V3dReady;
    BOOLEAN V3dNeedsSmsPulse;
    ULONG V3dVersion;
    ULONG V3dHubIdent[4];
    ULONG V3dCoreIdent[3];
    PVOID V3dSmsBase;
    PVOID V3dHubBase;
    PVOID V3dCoreBase;
    PULONG V3dPageTable;
    PHYSICAL_ADDRESS V3dPageTablePhys;
    PVOID V3dScratchPage;
    PHYSICAL_ADDRESS V3dScratchPagePhys;
    PVOID V3dOverflowVa;              /* binner overflow memory pool       */
    PHYSICAL_ADDRESS V3dOverflowPhys;
    ULONG V3dOverflowGpuVa;

    /* ---- VideoCore firmware property mailbox ---------------------------- */
    PVOID MboxBase;
    PVOID MboxBufferVa;               /* <4 GB contiguous property buffer  */
    PHYSICAL_ADDRESS MboxBufferPhys;
    ULONG FirmwareRevision;

    /* ---- V3D interrupt (SPI 250, DTB) — poll timer remains the backstop
     * because the ARM64 root IRQ arbiter may not grant the SPI. ---------- */
    PKINTERRUPT V3dInterrupt;
    PKINTERRUPT V3dInterrupt2;
    BOOLEAN V3dIrqConnected;
    volatile LONG V3dIsrCount;
    volatile LONG V3dIsrMasked;
    LONG V3dTdrPrints;
    LONG V3dQmaPrints;
    UCHAR HvsLptrsDead[2];
    LONG V3dOomPrints;
    ULONG V3dResetCount;
    volatile LONG V3dDpcFromIsr;
    ULONG V3dLastBfc;
    ULONG V3dLastRfc;
};

/* rpi5vc4.c — lifecycle / child / adapter-info / pointer DDIs */

NTSTATUS APIENTRY Rpi5Vc4DdiAddDevice(
    _In_  PDEVICE_OBJECT PhysicalDeviceObject,
    _Out_ PVOID *MiniportDeviceContext);

NTSTATUS APIENTRY Rpi5Vc4DdiStartDevice(
    _In_  PVOID MiniportDeviceContext,
    _In_  PDXGK_START_INFO DxgkStartInfo,
    _In_  PDXGK_INTERFACE DxgkInterface,
    _Out_ PULONG NumberOfVideoPresentSources,
    _Out_ PULONG NumberOfChildren);

NTSTATUS APIENTRY Rpi5Vc4DdiStopDevice(
    _In_ PVOID MiniportDeviceContext);

NTSTATUS APIENTRY Rpi5Vc4DdiRemoveDevice(
    _In_ PVOID MiniportDeviceContext);

NTSTATUS APIENTRY Rpi5Vc4DdiQueryChildRelations(
    _In_  PVOID MiniportDeviceContext,
    _Out_ PDXGK_CHILD_DESCRIPTOR ChildRelations,
    _In_  ULONG ChildRelationsSize);

NTSTATUS APIENTRY Rpi5Vc4DdiQueryChildStatus(
    _In_    PVOID MiniportDeviceContext,
    _Inout_ PDXGK_CHILD_STATUS ChildStatus,
    _In_    BOOLEAN NonDestructiveOnly);

NTSTATUS APIENTRY Rpi5Vc4DdiQueryDeviceDescriptor(
    _In_    PVOID MiniportDeviceContext,
    _In_    ULONG ChildUid,
    _Inout_ PDXGK_DEVICE_DESCRIPTOR DeviceDescriptor);

NTSTATUS APIENTRY Rpi5Vc4DdiQueryAdapterInfo(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_QUERYADAPTERINFO *QueryAdapterInfo);

NTSTATUS APIENTRY Rpi5Vc4DdiSetPowerState(
    _In_ PVOID MiniportDeviceContext,
    _In_ ULONG DeviceUid,
    _In_ DEVICE_POWER_STATE DevicePowerState,
    _In_ POWER_ACTION ActionType);

VOID APIENTRY Rpi5Vc4DdiResetDevice(
    _In_ PVOID MiniportDeviceContext);

VOID APIENTRY Rpi5Vc4DdiUnload(VOID);

NTSTATUS APIENTRY Rpi5Vc4DdiSetPointerPosition(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_SETPOINTERPOSITION *SetPointerPosition);

NTSTATUS APIENTRY Rpi5Vc4DdiSetPointerShape(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_SETPOINTERSHAPE *SetPointerShape);

/* rpi5vc4_wddm.c — full-WDDM render/memory/scheduling DDIs */

NTSTATUS APIENTRY Rpi5Vc4DdiCreateDevice(
    _In_    PVOID MiniportDeviceContext,
    _Inout_ PDXGKARG_CREATEDEVICE CreateDevice);

NTSTATUS APIENTRY Rpi5Vc4DdiDestroyDevice(
    _In_ PVOID MiniportDeviceContext);

NTSTATUS APIENTRY Rpi5Vc4DdiCreateContext(
    _In_    PVOID MiniportDeviceContext,
    _Inout_ PDXGKARG_CREATECONTEXT CreateContext);

NTSTATUS APIENTRY Rpi5Vc4DdiDestroyContext(
    _In_ PVOID MiniportDeviceContext);

NTSTATUS APIENTRY Rpi5Vc4DdiCreateAllocation(
    _In_    PVOID MiniportDeviceContext,
    _Inout_ PDXGKARG_CREATEALLOCATION CreateAllocation);

NTSTATUS APIENTRY Rpi5Vc4DdiDestroyAllocation(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_DESTROYALLOCATION *DestroyAllocation);

NTSTATUS APIENTRY Rpi5Vc4DdiOpenAllocation(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_OPENALLOCATION *OpenAllocation);

NTSTATUS APIENTRY Rpi5Vc4DdiCloseAllocation(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_CLOSEALLOCATION *CloseAllocation);

NTSTATUS APIENTRY Rpi5Vc4DdiGetStandardAllocationDriverData(
    _In_    PVOID MiniportDeviceContext,
    _Inout_ PDXGKARG_GETSTANDARDALLOCATIONDRIVERDATA GetStandardAllocationDriverData);

NTSTATUS APIENTRY Rpi5Vc4DdiRender(
    _In_    PVOID MiniportDeviceContext,
    _Inout_ PDXGKARG_RENDER Render);

NTSTATUS APIENTRY Rpi5Vc4DdiPresent(
    _In_    PVOID MiniportDeviceContext,
    _Inout_ PDXGKARG_PRESENT Present);

NTSTATUS APIENTRY Rpi5Vc4DdiPatch(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_PATCH *Patch);

NTSTATUS APIENTRY Rpi5Vc4DdiSubmitCommand(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_SUBMITCOMMAND *SubmitCommand);

NTSTATUS APIENTRY Rpi5Vc4DdiPreemptCommand(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_PREEMPTCOMMAND *PreemptCommand);

NTSTATUS APIENTRY Rpi5Vc4DdiQueryCurrentFence(
    _In_    PVOID MiniportDeviceContext,
    _Inout_ PDXGKARG_QUERYCURRENTFENCE CurrentFence);

NTSTATUS APIENTRY Rpi5Vc4DdiGetNodeMetadata(
    _In_ PVOID MiniportDeviceContext,
    _In_ UINT NodeOrdinalAndAdapterIndex,
    _Out_ DXGKARG_GETNODEMETADATA *GetNodeMetadata);

NTSTATUS APIENTRY Rpi5Vc4DdiBuildPagingBuffer(
    _In_    PVOID MiniportDeviceContext,
    _Inout_ PDXGKARG_BUILDPAGINGBUFFER BuildPagingBuffer);

NTSTATUS APIENTRY Rpi5Vc4DdiResetFromTimeout(
    _In_ PVOID MiniportDeviceContext);

NTSTATUS APIENTRY Rpi5Vc4DdiRestartFromTimeout(
    _In_ PVOID MiniportDeviceContext);

NTSTATUS APIENTRY Rpi5Vc4DdiControlInterrupt(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGK_INTERRUPT_TYPE InterruptType,
    _In_ BOOLEAN EnableInterrupt);

NTSTATUS APIENTRY Rpi5Vc4DdiEscape(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_ESCAPE *Escape);

BOOLEAN APIENTRY Rpi5Vc4DdiInterruptRoutine(
    _In_ PVOID MiniportDeviceContext,
    _In_ ULONG MessageNumber);

VOID APIENTRY Rpi5Vc4DdiDpcRoutine(
    _In_ PVOID MiniportDeviceContext);

/* Fence pipeline (rpi5vc4_wddm.c), shared with rpi5vc4.c lifecycle. */
VOID Rpi5Vc4QueueWarmupV3dJob(
    _Inout_ struct _RPI5VC4_DEVICE_EXTENSION *DeviceExtension);
/* Headless hotplug poll timer (armed by StartDevice once started + headless). */
VOID Rpi5Vc4ArmHpdTimer(
    _Inout_ struct _RPI5VC4_DEVICE_EXTENSION *DeviceExtension);
VOID Rpi5Vc4DmaPipelineInit(
    _Inout_ PRPI5VC4_DEVICE_EXTENSION DeviceExtension);
VOID Rpi5Vc4DmaPipelineDrain(
    _Inout_ PRPI5VC4_DEVICE_EXTENSION DeviceExtension);

/* rpi5vc4_vidpn.c — VidPN DDIs */

NTSTATUS APIENTRY Rpi5Vc4DdiSetVidPnSourceAddress(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_SETVIDPNSOURCEADDRESS *SetVidPnSourceAddress);


NTSTATUS APIENTRY Rpi5Vc4DdiIsSupportedVidPn(
    _In_    PVOID MiniportDeviceContext,
    _Inout_ PDXGKARG_ISSUPPORTEDVIDPN IsSupportedVidPn);

NTSTATUS APIENTRY Rpi5Vc4DdiRecommendFunctionalVidPn(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_RECOMMENDFUNCTIONALVIDPN *RecommendFunctionalVidPn);

NTSTATUS APIENTRY Rpi5Vc4DdiEnumVidPnCofuncModality(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_ENUMVIDPNCOFUNCMODALITY *EnumCofuncModality);

NTSTATUS APIENTRY Rpi5Vc4DdiSetVidPnSourceVisibility(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_SETVIDPNSOURCEVISIBILITY *SetVidPnSourceVisibility);

NTSTATUS APIENTRY Rpi5Vc4DdiCommitVidPn(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_COMMITVIDPN *CommitVidPn);

NTSTATUS APIENTRY Rpi5Vc4DdiCheckMultiPlaneOverlaySupport(
    _In_    PVOID MiniportDeviceContext,
    _Inout_ PDXGKARG_CHECKMULTIPLANEOVERLAYSUPPORT CheckMultiPlaneOverlaySupport);

NTSTATUS APIENTRY Rpi5Vc4DdiSetVidPnSourceAddressWithMultiPlaneOverlay(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_SETVIDPNSOURCEADDRESSWITHMULTIPLANEOVERLAY *SetMpo);

NTSTATUS APIENTRY Rpi5Vc4DdiUpdateActiveVidPnPresentPath(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_UPDATEACTIVEVIDPNPRESENTPATH *UpdateActiveVidPnPresentPath);

NTSTATUS APIENTRY Rpi5Vc4DdiRecommendMonitorModes(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_RECOMMENDMONITORMODES *RecommendMonitorModes);

/* rpi5vc4_present.c — present / system display / POST handoff */

/* Kernel VA of the surface the HVS is currently scanning out. */
PVOID Rpi5Vc4CurrentScanoutVa(
    _In_ PRPI5VC4_DEVICE_EXTENSION DeviceExtension);

/* Release the flip-present ring (StopDevice). */
VOID Rpi5Vc4FreeFlipRing(
    _Inout_ PRPI5VC4_DEVICE_EXTENSION DeviceExtension);

NTSTATUS APIENTRY Rpi5Vc4DdiPresentDisplayOnly(
    _In_ PVOID MiniportDeviceContext,
    _In_ CONST DXGKARG_PRESENT_DISPLAYONLY *PresentDisplayOnly);

NTSTATUS APIENTRY Rpi5Vc4DdiStopDeviceAndReleasePostDisplayOwnership(
    _In_  PVOID MiniportDeviceContext,
    _In_  D3DDDI_VIDEO_PRESENT_TARGET_ID TargetId,
    _Out_ PDXGK_DISPLAY_INFORMATION DisplayInfo);

NTSTATUS APIENTRY Rpi5Vc4DdiSystemDisplayEnable(
    _In_  PVOID MiniportDeviceContext,
    _In_  D3DDDI_VIDEO_PRESENT_TARGET_ID TargetId,
    _In_  PDXGKARG_SYSTEM_DISPLAY_ENABLE_FLAGS Flags,
    _Out_ PUINT Width,
    _Out_ PUINT Height,
    _Out_ D3DDDIFORMAT *ColorFormat);

VOID APIENTRY Rpi5Vc4DdiSystemDisplayWrite(
    _In_ PVOID MiniportDeviceContext,
    _In_ PVOID Source,
    _In_ UINT SourceWidth,
    _In_ UINT SourceHeight,
    _In_ UINT SourceStride,
    _In_ UINT PositionX,
    _In_ UINT PositionY);

#endif /* _RPI5VC4_PCH_ */
