# ReactOS, UEFI and assembly-offset generator modules are native PE/COFF targets.
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ARCH REACTOS_CLANG_LLVM_MINGW_ROOT)
if(NOT REACTOS_CLANG_LLVM_MINGW_ROOT)
    set(REACTOS_CLANG_LLVM_MINGW_ROOT "$ENV{HOME}/.local/opt/rosbe/llvm-mingw-riscv24")
endif()
set(CMAKE_C_COMPILER "${REACTOS_CLANG_LLVM_MINGW_ROOT}/bin/clang")
set(CMAKE_CXX_COMPILER "${REACTOS_CLANG_LLVM_MINGW_ROOT}/bin/clang++")
set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
set(CMAKE_C_COMPILER_TARGET riscv64-w64-windows-gnu)
set(CMAKE_CXX_COMPILER_TARGET riscv64-w64-windows-gnu)
set(CMAKE_ASM_COMPILER_TARGET riscv64-w64-windows-gnu)
set(CMAKE_AR "${REACTOS_CLANG_LLVM_MINGW_ROOT}/bin/llvm-ar")
set(CMAKE_RANLIB "${REACTOS_CLANG_LLVM_MINGW_ROOT}/bin/llvm-ranlib")
set(CMAKE_LINKER "${REACTOS_CLANG_LLVM_MINGW_ROOT}/bin/ld.lld")
set(CMAKE_DLLTOOL "${REACTOS_CLANG_LLVM_MINGW_ROOT}/bin/llvm-dlltool")
set(CMAKE_RC_COMPILER "${REACTOS_CLANG_LLVM_MINGW_ROOT}/bin/llvm-windres")
set(CMAKE_RC_FLAGS_INIT "--target=riscv64-w64-windows-gnu")
set(CMAKE_NM "${REACTOS_CLANG_LLVM_MINGW_ROOT}/bin/llvm-nm")
set(CMAKE_OBJCOPY "${REACTOS_CLANG_LLVM_MINGW_ROOT}/bin/llvm-objcopy")
set(CMAKE_OBJDUMP "${REACTOS_CLANG_LLVM_MINGW_ROOT}/bin/llvm-objdump")
set(CMAKE_STRIP "${REACTOS_CLANG_LLVM_MINGW_ROOT}/bin/llvm-strip")
set(CMAKE_C_FLAGS_INIT "-march=rv64gc -mabi=lp64 -mcmodel=medany -mno-relax")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")
set(CMAKE_ASM_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")

# ReactOS provides every runtime and import library explicitly. Do not let
# CMake's Windows platform defaults pull a MinGW CRT or system SDK into links.
set(CMAKE_C_STANDARD_LIBRARIES "" CACHE STRING "Standard C libraries" FORCE)
set(CMAKE_CXX_STANDARD_LIBRARIES "" CACHE STRING "Standard C++ libraries" FORCE)
set(REACTOS_CLANG_BASE_LINKER_FLAGS "-nostdlib -fuse-ld=lld -Wl,--enable-auto-image-base,--disable-auto-import")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${REACTOS_CLANG_BASE_LINKER_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${REACTOS_CLANG_BASE_LINKER_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${REACTOS_CLANG_BASE_LINKER_FLAGS}")
