/* Automatically generated by make depend; DO NOT EDIT!! */

#define STANDALONE
#include <wine/test.h>

extern void func_iccvid(void);

const struct test winetest_testlist[] =
{
    { "iccvid", func_iccvid },
    { 0, 0 }
};
