#pragma once

#define IOCTL_FILTER_LOAD           CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x01, METHOD_BUFFERED, FILE_WRITE_DATA) //88004
#define IOCTL_FILTER_UNLOAD         CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x02, METHOD_BUFFERED, FILE_WRITE_DATA) //88008
#define IOCTL_FILTER_CREATE         CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x03, METHOD_BUFFERED, FILE_READ_DATA)  //8400C
#define IOCTL_FILTER_ATTATCH        CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x04, METHOD_BUFFERED, FILE_WRITE_DATA) //88010
#define IOCTL_FILTER_DETATCH        CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x05, METHOD_BUFFERED, FILE_WRITE_DATA) //88014
#define IOCTL_FILTER_SEND_MESSAGE   CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x06, METHOD_NEITHER,  FILE_WRITE_DATA) //8801B
#define IOCTL_FILTER_GET_MESSAGE    CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x07, METHOD_NEITHER,  FILE_READ_DATA)  //8401F
#define IOCTL_FILTER_REPLY_MESSAGE  CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x08, METHOD_NEITHER,  FILE_WRITE_DATA) //88023
#define IOCTL_FILTER_FIND_FIRST     CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x09, METHOD_BUFFERED, FILE_READ_DATA)  //84024
#define IOCTL_FILTER_FIND_NEXT      CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x0A, METHOD_BUFFERED, FILE_READ_DATA)  //84028
#define IOCTL_FILTER_GET_INFO       CTL_CODE(FILE_DEVICE_DISK_FILE_SYSTEM, 0x0B, METHOD_BUFFERED, FILE_READ_DATA)  //8402C

#define FLT_PORT_EA_NAME            "FLTPORT"
#define FLT_PORT_EA_NAME_LENGTH     7
#define FLT_PORT_VALID_OPTIONS      0x00000001

typedef struct _FILTER_NAME
{
    USHORT Length;
    WCHAR FilterName[1];

} FILTER_NAME, *PFILTER_NAME;



typedef struct _FILTER_PORT_DATA
{
    PUNICODE_STRING PortName;
    PUNICODE_STRING64 PortName64;
    USHORT ContextSize;
    UCHAR Reserved[6];

} FILTER_PORT_DATA, *PFILTER_PORT_DATA;

typedef struct _FILTER_PORT_DATA32
{
    ULONG PortName;
    ULONG PortName64;
    USHORT ContextSize;
    UCHAR Reserved[6];

} FILTER_PORT_DATA32, *PFILTER_PORT_DATA32;
