/*
 * PROJECT:     ReactOS API tests
 * LICENSE:     LGPL-2.1-or-later (https://spdx.org/licenses/LGPL-2.1-or-later)
 * PURPOSE:     Validate the Windows 11 HID haptics usage ABI
 * COPYRIGHT:   Copyright 2026 Ahmed ARIF <arif.ing@outlook.com>
 */

#define STANDALONE
#include <apitest.h>
#include <hidusage.h>

/* Public ABI from Microsoft.Windows.SDK.CPP 10.0.26100.8249. */
C_ASSERT(HID_USAGE_PAGE_HAPTICS == 0x000E);
C_ASSERT(HID_USAGE_HAPTICS_SIMPLE_CONTROLLER == 0x0001);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_LIST == 0x0010);
C_ASSERT(HID_USAGE_HAPTICS_DURATION_LIST == 0x0011);
C_ASSERT(HID_USAGE_HAPTICS_AUTO_TRIGGER == 0x0020);
C_ASSERT(HID_USAGE_HAPTICS_MANUAL_TRIGGER == 0x0021);
C_ASSERT(HID_USAGE_HAPTICS_AUTO_ASSOCIATED_CONTROL == 0x0022);
C_ASSERT(HID_USAGE_HAPTICS_INTENSITY == 0x0023);
C_ASSERT(HID_USAGE_HAPTICS_REPEAT_COUNT == 0x0024);
C_ASSERT(HID_USAGE_HAPTICS_RETRIGGER_PERIOD == 0x0025);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_VENDOR_PAGE == 0x0026);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_VENDOR_ID == 0x0027);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_CUTOFF_TIME == 0x0028);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_NONE == 0x1001);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_STOP == 0x1002);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_CLICK == 0x1003);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_BUZZ == 0x1004);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_RUMBLE == 0x1005);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_PRESS == 0x1006);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_RELEASE == 0x1007);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_HOVER == 0x1008);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_SUCCESS == 0x1009);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_ERROR == 0x100A);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_INK_CONTINUOUS == 0x100B);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_PENCIL_CONTINUOUS == 0x100C);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_MARKER_CONTINUOUS == 0x100D);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_CHISEL_MARKER_CONTINUOUS == 0x100E);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_BRUSH_CONTINUOUS == 0x100F);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_ERASER_CONTINUOUS == 0x1010);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_SPARKLE_CONTINUOUS == 0x1011);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_COLLIDE == 0x1012);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_ALIGN == 0x1013);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_STEP == 0x1014);
C_ASSERT(HID_USAGE_HAPTICS_WAVEFORM_GROW == 0x1015);

START_TEST(hidusage_haptics)
{
    ok(HID_USAGE_HAPTICS_WAVEFORM_GROW - HID_USAGE_HAPTICS_WAVEFORM_NONE == 20,
       "Unexpected Windows 11 haptics waveform range\n");
}
