/*
 * PROJECT:     ReactOS API tests
 * LICENSE:     LGPL-2.1-or-later (https://spdx.org/licenses/LGPL-2.1-or-later)
 * PURPOSE:     Validate the Windows 11 Resource Hub data ABI
 * COPYRIGHT:   Copyright 2026 Ahmed ARIF <arif.ing@outlook.com>
 */

#define STANDALONE
#include <apitest.h>
#include <reshub.h>

/* Public ABI from Microsoft.Windows.SDK.CPP 10.0.26100.8249. */
C_ASSERT(RH_UPDATE_CONNECTIONAL_MASK_ALL == 0xFFFF);
C_ASSERT(INVALID_PIN_NUMBER == 0xFFFF);
C_ASSERT(PNP_FUNCTION_CONFIG_DESCRIPTOR_REVISION == 0x1);
C_ASSERT(PNP_FUNCTION_CONFIG_DESCRIPTOR_REVISION_MINIMUM == 0x1);
C_ASSERT(PNP_GPIO_IRQ_DESCRIPTOR_REVISION == 0x1);
C_ASSERT(PNP_GPIO_IRQ_DESCRIPTOR_REVISION_MINIMUM == 0x1);
C_ASSERT(PNP_GPIO_IRQ_DESCRIPTOR_TYPE_INTERRUPT == 0x0);
C_ASSERT(PNP_GPIO_IRQ_DESCRIPTOR_TYPE_IO == 0x1);
C_ASSERT(PNP_GPIO_IRQ_RESOURCE_CONSUMER_ONLY == 0x01);
C_ASSERT(PNP_GPIO_IRQ_MODE == 0x01);
C_ASSERT(PNP_GPIO_IRQ_POLARITY == 0x06);
C_ASSERT(PNP_GPIO_IRQ_SHARED == 0x08);
C_ASSERT(PNP_GPIO_IRQ_WAKE_HINT == 0x10);
C_ASSERT(PNP_GPIO_IRQ_MODE_EDGE == 0x01);
C_ASSERT(PNP_GPIO_IRQ_MODE_LEVEL == 0x00);
C_ASSERT(PNP_GPIO_IRQ_POLARITY_LOW == 0x02);
C_ASSERT(PNP_GPIO_IRQ_POLARITY_HIGH == 0x00);
C_ASSERT(PNP_GPIO_IRQ_POLARITY_BOTH == 0x04);

C_ASSERT(sizeof(RH_GPIO_IO_CONNECTION_PARAMETERS) == 16);
C_ASSERT(FIELD_OFFSET(RH_GPIO_IO_CONNECTION_PARAMETERS, UpdateMask) == 8);
C_ASSERT(FIELD_OFFSET(RH_GPIO_IO_CONNECTION_PARAMETERS, PinConfiguration) == 10);
C_ASSERT(FIELD_OFFSET(RH_GPIO_IO_CONNECTION_PARAMETERS, DebounceTimeout) == 12);
C_ASSERT(FIELD_OFFSET(RH_GPIO_IO_CONNECTION_PARAMETERS, DriveStrength) == 14);

C_ASSERT(sizeof(RH_GPIO_INTERRUPT_CONNECTION_PARAMETERS) == 12);
C_ASSERT(FIELD_OFFSET(RH_GPIO_INTERRUPT_CONNECTION_PARAMETERS, UpdateMask) == 4);
C_ASSERT(FIELD_OFFSET(RH_GPIO_INTERRUPT_CONNECTION_PARAMETERS, InterruptMode) == 6);
C_ASSERT(FIELD_OFFSET(RH_GPIO_INTERRUPT_CONNECTION_PARAMETERS, InterruptPolarity) == 7);
C_ASSERT(FIELD_OFFSET(RH_GPIO_INTERRUPT_CONNECTION_PARAMETERS, PinConfiguration) == 8);
C_ASSERT(FIELD_OFFSET(RH_GPIO_INTERRUPT_CONNECTION_PARAMETERS, DebounceTimeout) == 10);

C_ASSERT(sizeof(RH_SPI_CONNECTION_PARAMETERS) == 24);
C_ASSERT(FIELD_OFFSET(RH_SPI_CONNECTION_PARAMETERS, DeviceSelection) == 10);
C_ASSERT(FIELD_OFFSET(RH_SPI_CONNECTION_PARAMETERS, ConnectionSpeed) == 12);
C_ASSERT(FIELD_OFFSET(RH_SPI_CONNECTION_PARAMETERS, DataBitLength) == 19);

C_ASSERT(sizeof(RH_I2C_CONNECTION_PARAMETERS) == 24);
C_ASSERT(FIELD_OFFSET(RH_I2C_CONNECTION_PARAMETERS, TypeSpecificFlags) == 10);
C_ASSERT(FIELD_OFFSET(RH_I2C_CONNECTION_PARAMETERS, ConnectionSpeed) == 12);
C_ASSERT(FIELD_OFFSET(RH_I2C_CONNECTION_PARAMETERS, SlaveAddress) == 16);

C_ASSERT(sizeof(RH_UART_CONNECTION_PARAMETERS) == 24);
C_ASSERT(FIELD_OFFSET(RH_UART_CONNECTION_PARAMETERS, BaudRate) == 12);
C_ASSERT(FIELD_OFFSET(RH_UART_CONNECTION_PARAMETERS, TypeSpecificFlags) == 16);
C_ASSERT(FIELD_OFFSET(RH_UART_CONNECTION_PARAMETERS, Parity) == 22);

C_ASSERT(sizeof(RH_ALLOCATE_UPDATE_CONNECTION_INPUT_BUFFER) == 32);
C_ASSERT(FIELD_OFFSET(RH_ALLOCATE_UPDATE_CONNECTION_INPUT_BUFFER, u) == 8);
C_ASSERT(sizeof(RH_ALLOCATE_CONNECTION_OUTPUT_BUFFER) == 16);
C_ASSERT(FIELD_OFFSET(RH_ALLOCATE_CONNECTION_OUTPUT_BUFFER, ConnectionId) == 8);
C_ASSERT(sizeof(RH_UPDATE_CONNECTION_PROPERTIES_OUTPUT_BUFFER) == 4);

C_ASSERT(sizeof(RH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_BUFFER) == 8);
C_ASSERT(sizeof(RH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_BUFFER) == 8);
C_ASSERT(FIELD_OFFSET(RH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_BUFFER, InitialPolarity) == 4);
C_ASSERT(sizeof(RH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_BUFFER) == 12);
C_ASSERT(FIELD_OFFSET(RH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_BUFFER, InitialPolarity) == 8);
C_ASSERT(sizeof(RH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_BUFFER) == 4);

C_ASSERT(sizeof(PNP_GPIO_INTERRUPT_IO_DESCRIPTOR) == 23);
C_ASSERT(sizeof(PNP_LARGE_VENDOR_DESCRIPTOR) == 21);
C_ASSERT(sizeof(PNP_FUNCTION_CONFIG_DESCRIPTOR) == 18);
C_ASSERT(sizeof(PNP_SERIAL_BUS_DESCRIPTOR) == 12);

START_TEST(reshub)
{
    ok(RH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_VERSION == 1,
       "Unexpected query input version\n");
    ok(RH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_VERSION == 1,
       "Unexpected query output version\n");
    ok(RH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_VERSION == 1,
       "Unexpected update input version\n");
    ok(RH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_VERSION == 1,
       "Unexpected update output version\n");
}
