/*
 * PROJECT:     ReactOS API tests
 * LICENSE:     LGPL-2.1-or-later (https://spdx.org/licenses/LGPL-2.1-or-later)
 * PURPOSE:     Validate the Windows 11 input data ABI
 * COPYRIGHT:   Copyright 2026 Ahmed ARIF <arif.ing@outlook.com>
 */

#define STANDALONE
#include <apitest.h>
#include <winuser.h>

/* Public ABI from Microsoft.Windows.SDK.CPP 10.0.26100.8249. */
C_ASSERT(WM_GESTURE == 0x0119);
C_ASSERT(WM_GESTURENOTIFY == 0x011A);
C_ASSERT(WM_TOUCH == 0x0240);
C_ASSERT(SM_DIGITIZER == 94);
C_ASSERT(SM_MAXIMUMTOUCHES == 95);
C_ASSERT(SM_CMETRICS == 97);

C_ASSERT(TOUCH_COORD_TO_PIXEL(1234) == 12);
C_ASSERT(TOUCHEVENTF_MOVE == 0x0001);
C_ASSERT(TOUCHEVENTF_DOWN == 0x0002);
C_ASSERT(TOUCHEVENTF_UP == 0x0004);
C_ASSERT(TOUCHEVENTF_INRANGE == 0x0008);
C_ASSERT(TOUCHEVENTF_PRIMARY == 0x0010);
C_ASSERT(TOUCHEVENTF_NOCOALESCE == 0x0020);
C_ASSERT(TOUCHEVENTF_PEN == 0x0040);
C_ASSERT(TOUCHEVENTF_PALM == 0x0080);
C_ASSERT(TOUCHINPUTMASKF_TIMEFROMSYSTEM == 0x0001);
C_ASSERT(TOUCHINPUTMASKF_EXTRAINFO == 0x0002);
C_ASSERT(TOUCHINPUTMASKF_CONTACTAREA == 0x0004);
C_ASSERT(TWF_FINETOUCH == 0x00000001);
C_ASSERT(TWF_WANTPALM == 0x00000002);

C_ASSERT(GF_BEGIN == 0x00000001);
C_ASSERT(GF_INERTIA == 0x00000002);
C_ASSERT(GF_END == 0x00000004);
C_ASSERT(GID_BEGIN == 1);
C_ASSERT(GID_END == 2);
C_ASSERT(GID_ZOOM == 3);
C_ASSERT(GID_PAN == 4);
C_ASSERT(GID_ROTATE == 5);
C_ASSERT(GID_TWOFINGERTAP == 6);
C_ASSERT(GID_PRESSANDTAP == 7);
C_ASSERT(GID_ROLLOVER == GID_PRESSANDTAP);
C_ASSERT(GC_ALLGESTURES == 0x00000001);
C_ASSERT(GC_ZOOM == 0x00000001);
C_ASSERT(GC_PAN == 0x00000001);
C_ASSERT(GC_PAN_WITH_SINGLE_FINGER_VERTICALLY == 0x00000002);
C_ASSERT(GC_PAN_WITH_SINGLE_FINGER_HORIZONTALLY == 0x00000004);
C_ASSERT(GC_PAN_WITH_GUTTER == 0x00000008);
C_ASSERT(GC_PAN_WITH_INERTIA == 0x00000010);
C_ASSERT(GC_ROTATE == 0x00000001);
C_ASSERT(GC_TWOFINGERTAP == 0x00000001);
C_ASSERT(GC_PRESSANDTAP == 0x00000001);
C_ASSERT(GC_ROLLOVER == GC_PRESSANDTAP);
C_ASSERT(GESTURECONFIGMAXCOUNT == 256);
C_ASSERT(GCF_INCLUDE_ANCESTORS == 0x00000001);

C_ASSERT(NID_INTEGRATED_TOUCH == 0x00000001);
C_ASSERT(NID_EXTERNAL_TOUCH == 0x00000002);
C_ASSERT(NID_INTEGRATED_PEN == 0x00000004);
C_ASSERT(NID_EXTERNAL_PEN == 0x00000008);
C_ASSERT(NID_MULTI_INPUT == 0x00000040);
C_ASSERT(NID_READY == 0x00000080);

C_ASSERT(SPI_GETTOUCHPADPARAMETERS == 0x00AE);
C_ASSERT(SPI_SETTOUCHPADPARAMETERS == 0x00AF);

C_ASSERT(PT_POINTER == 1);
C_ASSERT(PT_TOUCH == 2);
C_ASSERT(PT_PEN == 3);
C_ASSERT(PT_MOUSE == 4);
C_ASSERT(PT_TOUCHPAD == 5);

C_ASSERT(POINTER_FLAG_NONE == 0x00000000);
C_ASSERT(POINTER_FLAG_NEW == 0x00000001);
C_ASSERT(POINTER_FLAG_INRANGE == 0x00000002);
C_ASSERT(POINTER_FLAG_INCONTACT == 0x00000004);
C_ASSERT(POINTER_FLAG_FIRSTBUTTON == 0x00000010);
C_ASSERT(POINTER_FLAG_SECONDBUTTON == 0x00000020);
C_ASSERT(POINTER_FLAG_THIRDBUTTON == 0x00000040);
C_ASSERT(POINTER_FLAG_FOURTHBUTTON == 0x00000080);
C_ASSERT(POINTER_FLAG_FIFTHBUTTON == 0x00000100);
C_ASSERT(POINTER_FLAG_PRIMARY == 0x00002000);
C_ASSERT(POINTER_FLAG_CONFIDENCE == 0x00004000);
C_ASSERT(POINTER_FLAG_CANCELED == 0x00008000);
C_ASSERT(POINTER_FLAG_DOWN == 0x00010000);
C_ASSERT(POINTER_FLAG_UPDATE == 0x00020000);
C_ASSERT(POINTER_FLAG_UP == 0x00040000);
C_ASSERT(POINTER_FLAG_WHEEL == 0x00080000);
C_ASSERT(POINTER_FLAG_HWHEEL == 0x00100000);
C_ASSERT(POINTER_FLAG_CAPTURECHANGED == 0x00200000);
C_ASSERT(POINTER_FLAG_HASTRANSFORM == 0x00400000);
C_ASSERT(POINTER_MOD_SHIFT == 0x0004);
C_ASSERT(POINTER_MOD_CTRL == 0x0008);

C_ASSERT(TOUCH_FLAG_NONE == 0x00000000);
C_ASSERT(TOUCH_MASK_NONE == 0x00000000);
C_ASSERT(TOUCH_MASK_CONTACTAREA == 0x00000001);
C_ASSERT(TOUCH_MASK_ORIENTATION == 0x00000002);
C_ASSERT(TOUCH_MASK_PRESSURE == 0x00000004);
C_ASSERT(PEN_FLAG_NONE == 0x00000000);
C_ASSERT(PEN_FLAG_BARREL == 0x00000001);
C_ASSERT(PEN_FLAG_INVERTED == 0x00000002);
C_ASSERT(PEN_FLAG_ERASER == 0x00000004);
C_ASSERT(PEN_MASK_NONE == 0x00000000);
C_ASSERT(PEN_MASK_PRESSURE == 0x00000001);
C_ASSERT(PEN_MASK_ROTATION == 0x00000002);
C_ASSERT(PEN_MASK_TILT_X == 0x00000004);
C_ASSERT(PEN_MASK_TILT_Y == 0x00000008);

C_ASSERT(GET_POINTERID_WPARAM((WPARAM)0x12345678) == 0x5678);
C_ASSERT(IS_POINTER_NEW_WPARAM((WPARAM)POINTER_MESSAGE_FLAG_NEW << 16));
C_ASSERT(IS_POINTER_INRANGE_WPARAM((WPARAM)POINTER_MESSAGE_FLAG_INRANGE << 16));
C_ASSERT(IS_POINTER_INCONTACT_WPARAM((WPARAM)POINTER_MESSAGE_FLAG_INCONTACT << 16));
C_ASSERT(IS_POINTER_FIRSTBUTTON_WPARAM((WPARAM)POINTER_MESSAGE_FLAG_FIRSTBUTTON << 16));
C_ASSERT(IS_POINTER_SECONDBUTTON_WPARAM((WPARAM)POINTER_MESSAGE_FLAG_SECONDBUTTON << 16));
C_ASSERT(IS_POINTER_THIRDBUTTON_WPARAM((WPARAM)POINTER_MESSAGE_FLAG_THIRDBUTTON << 16));
C_ASSERT(IS_POINTER_FOURTHBUTTON_WPARAM((WPARAM)POINTER_MESSAGE_FLAG_FOURTHBUTTON << 16));
C_ASSERT(IS_POINTER_FIFTHBUTTON_WPARAM((WPARAM)POINTER_MESSAGE_FLAG_FIFTHBUTTON << 16));
C_ASSERT(IS_POINTER_PRIMARY_WPARAM((WPARAM)POINTER_MESSAGE_FLAG_PRIMARY << 16));
C_ASSERT(HAS_POINTER_CONFIDENCE_WPARAM((WPARAM)POINTER_MESSAGE_FLAG_CONFIDENCE << 16));
C_ASSERT(IS_POINTER_CANCELED_WPARAM((WPARAM)POINTER_MESSAGE_FLAG_CANCELED << 16));

C_ASSERT(PA_ACTIVATE == MA_ACTIVATE);
C_ASSERT(PA_NOACTIVATE == MA_NOACTIVATE);
C_ASSERT(MAX_TOUCH_COUNT == 256);
C_ASSERT(TOUCH_FEEDBACK_DEFAULT == 1);
C_ASSERT(TOUCH_FEEDBACK_INDIRECT == 2);
C_ASSERT(TOUCH_FEEDBACK_NONE == 3);
C_ASSERT(POINTER_FEEDBACK_DEFAULT == 1);
C_ASSERT(POINTER_FEEDBACK_INDIRECT == 2);
C_ASSERT(POINTER_FEEDBACK_NONE == 3);

C_ASSERT(TOUCH_HIT_TESTING_DEFAULT == 0);
C_ASSERT(TOUCH_HIT_TESTING_CLIENT == 1);
C_ASSERT(TOUCH_HIT_TESTING_NONE == 2);
C_ASSERT(TOUCH_HIT_TESTING_PROXIMITY_CLOSEST == 0);
C_ASSERT(TOUCH_HIT_TESTING_PROXIMITY_FARTHEST == 0xFFF);
C_ASSERT(GWFS_INCLUDE_ANCESTORS == 0x00000001);

C_ASSERT(FEEDBACK_TOUCH_CONTACTVISUALIZATION == 1);
C_ASSERT(FEEDBACK_PEN_BARRELVISUALIZATION == 2);
C_ASSERT(FEEDBACK_PEN_TAP == 3);
C_ASSERT(FEEDBACK_PEN_DOUBLETAP == 4);
C_ASSERT(FEEDBACK_PEN_PRESSANDHOLD == 5);
C_ASSERT(FEEDBACK_PEN_RIGHTTAP == 6);
C_ASSERT(FEEDBACK_TOUCH_TAP == 7);
C_ASSERT(FEEDBACK_TOUCH_DOUBLETAP == 8);
C_ASSERT(FEEDBACK_TOUCH_PRESSANDHOLD == 9);
C_ASSERT(FEEDBACK_TOUCH_RIGHTTAP == 10);
C_ASSERT(FEEDBACK_GESTURE_PRESSANDTAP == 11);
C_ASSERT(FEEDBACK_MAX == 0xFFFFFFFF);

C_ASSERT(PDC_ARRIVAL == 0x001);
C_ASSERT(PDC_REMOVAL == 0x002);
C_ASSERT(PDC_ORIENTATION_0 == 0x004);
C_ASSERT(PDC_ORIENTATION_90 == 0x008);
C_ASSERT(PDC_ORIENTATION_180 == 0x010);
C_ASSERT(PDC_ORIENTATION_270 == 0x020);
C_ASSERT(PDC_MODE_DEFAULT == 0x040);
C_ASSERT(PDC_MODE_CENTERED == 0x080);
C_ASSERT(PDC_MAPPING_CHANGE == 0x100);
C_ASSERT(PDC_RESOLUTION == 0x200);
C_ASSERT(PDC_ORIGIN == 0x400);
C_ASSERT(PDC_MODE_ASPECTRATIOPRESERVED == 0x800);

C_ASSERT(POINTER_DEVICE_TYPE_INTEGRATED_PEN == 1);
C_ASSERT(POINTER_DEVICE_TYPE_EXTERNAL_PEN == 2);
C_ASSERT(POINTER_DEVICE_TYPE_TOUCH == 3);
C_ASSERT(POINTER_DEVICE_TYPE_TOUCH_PAD == 4);
C_ASSERT(POINTER_DEVICE_TYPE_MAX == 0xFFFFFFFF);
C_ASSERT(POINTER_DEVICE_CURSOR_TYPE_UNKNOWN == 0);
C_ASSERT(POINTER_DEVICE_CURSOR_TYPE_TIP == 1);
C_ASSERT(POINTER_DEVICE_CURSOR_TYPE_ERASER == 2);
C_ASSERT(POINTER_DEVICE_CURSOR_TYPE_MAX == 0xFFFFFFFF);

C_ASSERT(LEGACY_TOUCHPAD_FEATURE_NONE == 0x00000000);
C_ASSERT(LEGACY_TOUCHPAD_FEATURE_ENABLE_DISABLE == 0x00000001);
C_ASSERT(LEGACY_TOUCHPAD_FEATURE_REVERSE_SCROLL_DIRECTION == 0x00000004);
C_ASSERT(TOUCHPAD_SENSITIVITY_LEVEL_MOST_SENSITIVE == 0);
C_ASSERT(TOUCHPAD_SENSITIVITY_LEVEL_HIGH_SENSITIVITY == 1);
C_ASSERT(TOUCHPAD_SENSITIVITY_LEVEL_MEDIUM_SENSITIVITY == 2);
C_ASSERT(TOUCHPAD_SENSITIVITY_LEVEL_LOW_SENSITIVITY == 3);
C_ASSERT(TOUCHPAD_SENSITIVITY_LEVEL_LEAST_SENSITIVE == 4);
C_ASSERT(TOUCHPAD_PARAMETERS_VERSION_1 == 1);
C_ASSERT(TOUCHPAD_PARAMETERS_VERSION_2 == 2);

#ifdef _WIN64
C_ASSERT(sizeof(TOUCHINPUT) == 48);
C_ASSERT(FIELD_OFFSET(TOUCHINPUT, dwExtraInfo) == 32);
C_ASSERT(sizeof(GESTUREINFO) == 56);
C_ASSERT(FIELD_OFFSET(GESTUREINFO, hwndTarget) == 16);
C_ASSERT(FIELD_OFFSET(GESTUREINFO, ullArguments) == 40);
C_ASSERT(FIELD_OFFSET(GESTUREINFO, cbExtraArgs) == 48);
C_ASSERT(sizeof(GESTURENOTIFYSTRUCT) == 24);
C_ASSERT(sizeof(POINTER_INFO) == 96);
C_ASSERT(FIELD_OFFSET(POINTER_INFO, hwndTarget) == 24);
C_ASSERT(FIELD_OFFSET(POINTER_INFO, PerformanceCount) == 80);
C_ASSERT(FIELD_OFFSET(POINTER_INFO, ButtonChangeType) == 88);
C_ASSERT(sizeof(POINTER_TOUCH_INFO) == 144);
C_ASSERT(FIELD_OFFSET(POINTER_TOUCH_INFO, touchFlags) == 96);
C_ASSERT(sizeof(POINTER_PEN_INFO) == 120);
C_ASSERT(FIELD_OFFSET(POINTER_PEN_INFO, penFlags) == 96);
C_ASSERT(sizeof(POINTER_TYPE_INFO) == 152);
C_ASSERT(FIELD_OFFSET(POINTER_TYPE_INFO, pointerInfo) == 8);
C_ASSERT(sizeof(POINTER_DEVICE_INFO) == 1080);
C_ASSERT(FIELD_OFFSET(POINTER_DEVICE_INFO, device) == 8);
C_ASSERT(FIELD_OFFSET(POINTER_DEVICE_INFO, pointerDeviceType) == 16);
C_ASSERT(FIELD_OFFSET(POINTER_DEVICE_INFO, monitor) == 24);
C_ASSERT(FIELD_OFFSET(POINTER_DEVICE_INFO, productString) == 38);
#else
C_ASSERT(sizeof(TOUCHINPUT) == 40);
C_ASSERT(FIELD_OFFSET(TOUCHINPUT, dwExtraInfo) == 28);
C_ASSERT(sizeof(GESTUREINFO) == 48);
C_ASSERT(FIELD_OFFSET(GESTUREINFO, hwndTarget) == 12);
C_ASSERT(FIELD_OFFSET(GESTUREINFO, ullArguments) == 32);
C_ASSERT(FIELD_OFFSET(GESTUREINFO, cbExtraArgs) == 40);
C_ASSERT(sizeof(GESTURENOTIFYSTRUCT) == 20);
C_ASSERT(sizeof(POINTER_INFO) == 88);
C_ASSERT(FIELD_OFFSET(POINTER_INFO, hwndTarget) == 20);
C_ASSERT(FIELD_OFFSET(POINTER_INFO, PerformanceCount) == 72);
C_ASSERT(FIELD_OFFSET(POINTER_INFO, ButtonChangeType) == 80);
C_ASSERT(sizeof(POINTER_TOUCH_INFO) == 136);
C_ASSERT(FIELD_OFFSET(POINTER_TOUCH_INFO, touchFlags) == 88);
C_ASSERT(sizeof(POINTER_PEN_INFO) == 112);
C_ASSERT(FIELD_OFFSET(POINTER_PEN_INFO, penFlags) == 88);
C_ASSERT(sizeof(POINTER_TYPE_INFO) == 144);
C_ASSERT(FIELD_OFFSET(POINTER_TYPE_INFO, pointerInfo) == 8);
C_ASSERT(sizeof(POINTER_DEVICE_INFO) == 1064);
C_ASSERT(FIELD_OFFSET(POINTER_DEVICE_INFO, device) == 4);
C_ASSERT(FIELD_OFFSET(POINTER_DEVICE_INFO, pointerDeviceType) == 8);
C_ASSERT(FIELD_OFFSET(POINTER_DEVICE_INFO, monitor) == 12);
C_ASSERT(FIELD_OFFSET(POINTER_DEVICE_INFO, productString) == 22);
#endif

C_ASSERT(FIELD_OFFSET(TOUCHINPUT, hSource) == 8);
C_ASSERT(FIELD_OFFSET(GESTURENOTIFYSTRUCT, hwndTarget) == 8);
C_ASSERT(sizeof(GESTURECONFIG) == 12);
C_ASSERT(FIELD_OFFSET(GESTURECONFIG, dwWant) == 4);
C_ASSERT(FIELD_OFFSET(GESTURECONFIG, dwBlock) == 8);
C_ASSERT(FIELD_OFFSET(POINTER_INFO, sourceDevice) == 16);
C_ASSERT(sizeof(USAGE_PROPERTIES) == 32);
C_ASSERT(FIELD_OFFSET(USAGE_PROPERTIES, logicalMinimum) == 8);
C_ASSERT(FIELD_OFFSET(USAGE_PROPERTIES, physicalMinimum) == 24);
C_ASSERT(sizeof(INPUT_INJECTION_VALUE) == 12);
C_ASSERT(FIELD_OFFSET(INPUT_INJECTION_VALUE, value) == 4);
C_ASSERT(sizeof(TOUCH_HIT_TESTING_PROXIMITY_EVALUATION) == 12);
C_ASSERT(FIELD_OFFSET(TOUCH_HIT_TESTING_PROXIMITY_EVALUATION, adjustedPoint) == 4);
C_ASSERT(sizeof(TOUCH_HIT_TESTING_INPUT) == 48);
C_ASSERT(FIELD_OFFSET(TOUCH_HIT_TESTING_INPUT, boundingBox) == 12);
C_ASSERT(sizeof(POINTER_DEVICE_PROPERTY) == 28);
C_ASSERT(FIELD_OFFSET(POINTER_DEVICE_PROPERTY, usagePageId) == 24);
C_ASSERT(sizeof(POINTER_DEVICE_CURSOR_INFO) == 8);
C_ASSERT(sizeof(INPUT_TRANSFORM) == 64);
C_ASSERT(FIELD_OFFSET(INPUT_TRANSFORM, m[3][3]) == 60);
C_ASSERT(sizeof(TOUCHPAD_PARAMETERS_V1) == 44);
C_ASSERT(FIELD_OFFSET(TOUCHPAD_PARAMETERS_V1, sensitivityLevel) == 20);
C_ASSERT(FIELD_OFFSET(TOUCHPAD_PARAMETERS_V1, cursorSpeed) == 24);
C_ASSERT(FIELD_OFFSET(TOUCHPAD_PARAMETERS_V1, rightClickZoneHeight) == 40);
C_ASSERT(sizeof(TOUCHPAD_PARAMETERS_V2) == 48);

#define VERIFY_FUNCTION_SIGNATURE(Name, ReturnType, Parameters) \
    typedef ReturnType (WINAPI Name##_ABI) Parameters; \
    extern Name##_ABI Name

VERIFY_FUNCTION_SIGNATURE(InitializeTouchInjection, BOOL, (UINT32, DWORD));
VERIFY_FUNCTION_SIGNATURE(InjectTouchInput, BOOL, (UINT32, CONST POINTER_TOUCH_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerType, BOOL, (UINT32, POINTER_INPUT_TYPE *));
VERIFY_FUNCTION_SIGNATURE(GetPointerCursorId, BOOL, (UINT32, UINT32 *));
VERIFY_FUNCTION_SIGNATURE(GetPointerInfo, BOOL, (UINT32, POINTER_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerInfoHistory, BOOL, (UINT32, UINT32 *, POINTER_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerFrameInfo, BOOL, (UINT32, UINT32 *, POINTER_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerFrameInfoHistory, BOOL, (UINT32, UINT32 *, UINT32 *, POINTER_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerTouchInfo, BOOL, (UINT32, POINTER_TOUCH_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerTouchInfoHistory, BOOL, (UINT32, UINT32 *, POINTER_TOUCH_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerFrameTouchInfo, BOOL, (UINT32, UINT32 *, POINTER_TOUCH_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerFrameTouchInfoHistory, BOOL, (UINT32, UINT32 *, UINT32 *, POINTER_TOUCH_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerPenInfo, BOOL, (UINT32, POINTER_PEN_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerPenInfoHistory, BOOL, (UINT32, UINT32 *, POINTER_PEN_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerFramePenInfo, BOOL, (UINT32, UINT32 *, POINTER_PEN_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerFramePenInfoHistory, BOOL, (UINT32, UINT32 *, UINT32 *, POINTER_PEN_INFO *));
VERIFY_FUNCTION_SIGNATURE(SkipPointerFrameMessages, BOOL, (UINT32));
VERIFY_FUNCTION_SIGNATURE(RegisterPointerInputTarget, BOOL, (HWND, POINTER_INPUT_TYPE));
VERIFY_FUNCTION_SIGNATURE(UnregisterPointerInputTarget, BOOL, (HWND, POINTER_INPUT_TYPE));
VERIFY_FUNCTION_SIGNATURE(RegisterPointerInputTargetEx, BOOL, (HWND, POINTER_INPUT_TYPE, BOOL));
VERIFY_FUNCTION_SIGNATURE(UnregisterPointerInputTargetEx, BOOL, (HWND, POINTER_INPUT_TYPE));
VERIFY_FUNCTION_SIGNATURE(CreateSyntheticPointerDevice, HSYNTHETICPOINTERDEVICE, (POINTER_INPUT_TYPE, ULONG, POINTER_FEEDBACK_MODE));
VERIFY_FUNCTION_SIGNATURE(InjectSyntheticPointerInput, BOOL, (HSYNTHETICPOINTERDEVICE, CONST POINTER_TYPE_INFO *, UINT32));
VERIFY_FUNCTION_SIGNATURE(DestroySyntheticPointerDevice, VOID, (HSYNTHETICPOINTERDEVICE));
VERIFY_FUNCTION_SIGNATURE(EnableMouseInPointer, BOOL, (BOOL));
VERIFY_FUNCTION_SIGNATURE(IsMouseInPointerEnabled, BOOL, (VOID));
VERIFY_FUNCTION_SIGNATURE(EnableMouseInPointerForThread, BOOL, (VOID));
VERIFY_FUNCTION_SIGNATURE(RegisterTouchHitTestingWindow, BOOL, (HWND, ULONG));
VERIFY_FUNCTION_SIGNATURE(EvaluateProximityToRect, BOOL, (const RECT *, const TOUCH_HIT_TESTING_INPUT *, TOUCH_HIT_TESTING_PROXIMITY_EVALUATION *));
VERIFY_FUNCTION_SIGNATURE(EvaluateProximityToPolygon, BOOL, (UINT32, const POINT *, const TOUCH_HIT_TESTING_INPUT *, TOUCH_HIT_TESTING_PROXIMITY_EVALUATION *));
VERIFY_FUNCTION_SIGNATURE(PackTouchHitTestingProximityEvaluation, LRESULT, (const TOUCH_HIT_TESTING_INPUT *, const TOUCH_HIT_TESTING_PROXIMITY_EVALUATION *));
VERIFY_FUNCTION_SIGNATURE(GetWindowFeedbackSetting, BOOL, (HWND, FEEDBACK_TYPE, DWORD, UINT32 *, VOID *));
VERIFY_FUNCTION_SIGNATURE(SetWindowFeedbackSetting, BOOL, (HWND, FEEDBACK_TYPE, DWORD, UINT32, CONST VOID *));
VERIFY_FUNCTION_SIGNATURE(GetPointerInputTransform, BOOL, (UINT32, UINT32, INPUT_TRANSFORM *));
VERIFY_FUNCTION_SIGNATURE(GetPointerDevices, BOOL, (UINT32 *, POINTER_DEVICE_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerDevice, BOOL, (HANDLE, POINTER_DEVICE_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetPointerDeviceProperties, BOOL, (HANDLE, UINT32 *, POINTER_DEVICE_PROPERTY *));
VERIFY_FUNCTION_SIGNATURE(RegisterPointerDeviceNotifications, BOOL, (HWND, BOOL));
VERIFY_FUNCTION_SIGNATURE(GetPointerDeviceRects, BOOL, (HANDLE, RECT *, RECT *));
VERIFY_FUNCTION_SIGNATURE(GetPointerDeviceCursors, BOOL, (HANDLE, UINT32 *, POINTER_DEVICE_CURSOR_INFO *));
VERIFY_FUNCTION_SIGNATURE(GetRawPointerDeviceData, BOOL, (UINT32, UINT32, UINT32, POINTER_DEVICE_PROPERTY *, LONG *));

#undef VERIFY_FUNCTION_SIGNATURE

typedef BOOL (WINAPI *PGET_TOUCH_INPUT_INFO)(HTOUCHINPUT, UINT, PTOUCHINPUT, int);
typedef BOOL (WINAPI *PCLOSE_TOUCH_INPUT_HANDLE)(HTOUCHINPUT);
typedef BOOL (WINAPI *PREGISTER_TOUCH_WINDOW)(HWND, ULONG);
typedef BOOL (WINAPI *PUNREGISTER_TOUCH_WINDOW)(HWND);
typedef BOOL (WINAPI *PIS_TOUCH_WINDOW)(HWND, PULONG);
typedef BOOL (WINAPI *PGET_GESTURE_INFO)(HGESTUREINFO, PGESTUREINFO);
typedef BOOL (WINAPI *PGET_GESTURE_EXTRA_ARGS)(HGESTUREINFO, UINT, PBYTE);
typedef BOOL (WINAPI *PCLOSE_GESTURE_INFO_HANDLE)(HGESTUREINFO);
typedef BOOL (WINAPI *PSET_GESTURE_CONFIG)(HWND, DWORD, UINT, PGESTURECONFIG, UINT);
typedef BOOL (WINAPI *PGET_GESTURE_CONFIG)(HWND, DWORD, DWORD, PUINT, PGESTURECONFIG, UINT);

static const PGET_TOUCH_INPUT_INFO GetTouchInputInfoSignature = GetTouchInputInfo;
static const PCLOSE_TOUCH_INPUT_HANDLE CloseTouchInputHandleSignature = CloseTouchInputHandle;
static const PREGISTER_TOUCH_WINDOW RegisterTouchWindowSignature = RegisterTouchWindow;
static const PUNREGISTER_TOUCH_WINDOW UnregisterTouchWindowSignature = UnregisterTouchWindow;
static const PIS_TOUCH_WINDOW IsTouchWindowSignature = IsTouchWindow;
static const PGET_GESTURE_INFO GetGestureInfoSignature = GetGestureInfo;
static const PGET_GESTURE_EXTRA_ARGS GetGestureExtraArgsSignature = GetGestureExtraArgs;
static const PCLOSE_GESTURE_INFO_HANDLE CloseGestureInfoHandleSignature = CloseGestureInfoHandle;
static const PSET_GESTURE_CONFIG SetGestureConfigSignature = SetGestureConfig;
static const PGET_GESTURE_CONFIG GetGestureConfigSignature = GetGestureConfig;
static GetPointerType_ABI * const GetPointerTypeImport = GetPointerType;
static GetPointerInfo_ABI * const GetPointerInfoImport = GetPointerInfo;
static GetPointerTouchInfo_ABI * const GetPointerTouchInfoImport = GetPointerTouchInfo;
static GetPointerTouchInfoHistory_ABI * const GetPointerTouchInfoHistoryImport = GetPointerTouchInfoHistory;
static GetPointerDevices_ABI * const GetPointerDevicesImport = GetPointerDevices;
static RegisterPointerDeviceNotifications_ABI * const RegisterPointerDeviceNotificationsImport = RegisterPointerDeviceNotifications;
static RegisterTouchHitTestingWindow_ABI * const RegisterTouchHitTestingWindowImport = RegisterTouchHitTestingWindow;
static EvaluateProximityToRect_ABI * const EvaluateProximityToRectImport = EvaluateProximityToRect;
static PackTouchHitTestingProximityEvaluation_ABI * const PackTouchHitTestingProximityEvaluationImport = PackTouchHitTestingProximityEvaluation;
static CreateSyntheticPointerDevice_ABI * const CreateSyntheticPointerDeviceImport = CreateSyntheticPointerDevice;

START_TEST(winuser_input)
{
    ok(GetTouchInputInfoSignature != NULL, "GetTouchInputInfo is not linked\n");
    ok(CloseTouchInputHandleSignature != NULL, "CloseTouchInputHandle is not linked\n");
    ok(RegisterTouchWindowSignature != NULL, "RegisterTouchWindow is not linked\n");
    ok(UnregisterTouchWindowSignature != NULL, "UnregisterTouchWindow is not linked\n");
    ok(IsTouchWindowSignature != NULL, "IsTouchWindow is not linked\n");
    ok(GetGestureInfoSignature != NULL, "GetGestureInfo is not linked\n");
    ok(GetGestureExtraArgsSignature != NULL, "GetGestureExtraArgs is not linked\n");
    ok(CloseGestureInfoHandleSignature != NULL, "CloseGestureInfoHandle is not linked\n");
    ok(SetGestureConfigSignature != NULL, "SetGestureConfig is not linked\n");
    ok(GetGestureConfigSignature != NULL, "GetGestureConfig is not linked\n");
    ok(GetPointerTypeImport != NULL, "GetPointerType is not linked\n");
    ok(GetPointerInfoImport != NULL, "GetPointerInfo is not linked\n");
    ok(GetPointerTouchInfoImport != NULL, "GetPointerTouchInfo is not linked\n");
    ok(GetPointerTouchInfoHistoryImport != NULL, "GetPointerTouchInfoHistory is not linked\n");
    ok(GetPointerDevicesImport != NULL, "GetPointerDevices is not linked\n");
    ok(RegisterPointerDeviceNotificationsImport != NULL, "RegisterPointerDeviceNotifications is not linked\n");
    ok(RegisterTouchHitTestingWindowImport != NULL, "RegisterTouchHitTestingWindow is not linked\n");
    ok(EvaluateProximityToRectImport != NULL, "EvaluateProximityToRect is not linked\n");
    ok(PackTouchHitTestingProximityEvaluationImport != NULL, "PackTouchHitTestingProximityEvaluation is not linked\n");
    ok(CreateSyntheticPointerDeviceImport != NULL, "CreateSyntheticPointerDevice is not linked\n");
}
