add_subdirectory(acpitimectl)
add_subdirectory(at)
add_subdirectory(attrib)
add_subdirectory(certutil)
add_subdirectory(chcp)
add_subdirectory(clip)
add_subdirectory(comp)
add_subdirectory(cscript)
add_subdirectory(dbgprint)
add_subdirectory(diskbench)
add_subdirectory(doskey)
add_subdirectory(eventcreate)
add_subdirectory(fanctl)
add_subdirectory(fc)
add_subdirectory(find)
add_subdirectory(fsutil)
add_subdirectory(help)
add_subdirectory(hostname)
add_subdirectory(label)
add_subdirectory(livedump)
add_subdirectory(lodctr)
add_subdirectory(mode)
add_subdirectory(mofcomp)
add_subdirectory(more)
if(ARCH STREQUAL "i386" OR ARCH STREQUAL "amd64")
    add_subdirectory(pmcctl)
endif()
add_subdirectory(reg)
add_subdirectory(replace)
add_subdirectory(schtasks)
add_subdirectory(sort)
add_subdirectory(taskkill)
add_subdirectory(tasklist)
add_subdirectory(timeout)
add_subdirectory(tpm2diag)
add_subdirectory(tree)
add_subdirectory(where)
add_subdirectory(whoami)
add_subdirectory(wmic)
add_subdirectory(wscript)
add_subdirectory(xcopy)
