
@ stdcall InitOnceBeginInitialize(ptr long ptr ptr)
@ stdcall InitOnceComplete(ptr long ptr)
@ stdcall InitOnceExecuteOnce(ptr ptr ptr ptr)
@ stdcall InitOnceInitialize(ptr) NTDLL.RtlRunOnceInitialize

@ stdcall GetFileInformationByHandleEx(long long ptr long)
@ stdcall -ret64 GetTickCount64()

@ stdcall InitializeSRWLock(ptr)
@ stdcall AcquireSRWLockExclusive(ptr)
@ stdcall AcquireSRWLockShared(ptr)
@ stdcall ReleaseSRWLockExclusive(ptr)
@ stdcall ReleaseSRWLockShared(ptr)

@ stdcall InitializeConditionVariable(ptr)
@ stdcall SleepConditionVariableCS(ptr ptr long)
@ stdcall SleepConditionVariableSRW(ptr ptr long long)
@ stdcall WakeAllConditionVariable(ptr)
@ stdcall WakeConditionVariable(ptr)

@ stdcall InitializeCriticalSectionEx(ptr long long)

@ stdcall GetFirmwareEnvironmentVariableExA(str str ptr long long)
@ stdcall GetFirmwareEnvironmentVariableExW(wstr wstr ptr long long)
@ stdcall GetFirmwareType(ptr)
@ stdcall SetFirmwareEnvironmentVariableExA(str str ptr long long)
@ stdcall SetFirmwareEnvironmentVariableExW(str str ptr long long)

@ stdcall ApplicationRecoveryFinished(long)
@ stdcall ApplicationRecoveryInProgress(ptr)
@ stdcall CancelIoEx(long ptr)
@ stdcall CancelSynchronousIo(long)
@ stdcall CreateSymbolicLinkA(str str long)
@ stdcall CreateSymbolicLinkW(wstr wstr long)
@ stdcall CreateEventExA(ptr str long long)
@ stdcall CreateEventExW(ptr wstr long long)
@ stdcall CreateMutexExA(ptr str long long)
@ stdcall CreateMutexExW(ptr wstr long long)
@ stdcall CreateWaitableTimerExA(ptr str long long)
@ stdcall CreateWaitableTimerExW(ptr wstr long long)
@ stdcall FlushProcessWriteBuffers()
@ stdcall DeleteProcThreadAttributeList(ptr)
@ stdcall EnumSystemLocalesEx(ptr long long ptr)
@ stdcall GetApplicationRecoveryCallback(ptr ptr ptr ptr ptr)
@ stdcall GetApplicationRestart(ptr wstr ptr ptr)
@ stdcall GetFileBandwidthReservation(ptr ptr ptr ptr ptr ptr)
@ stdcall CreateFileMappingNumaA(ptr ptr long long long str long)
@ stdcall CreateFileMappingNumaW(ptr ptr long long long wstr long)
@ stdcall GetFileMUIInfo(long wstr ptr ptr)
@ stdcall GetFileMUIPath(long wstr wstr ptr wstr ptr ptr)
@ stdcall GetFinalPathNameByHandleA(ptr str long long)
@ stdcall GetFinalPathNameByHandleW(ptr wstr long long)
@ stdcall GetPhysicallyInstalledSystemMemory(ptr)
@ stdcall GetQueuedCompletionStatusEx(ptr ptr long ptr long long)
@ stdcall GetProcessDEPPolicy(long ptr ptr)
@ stdcall GetSystemDEPPolicy()
@ stdcall GetLocaleInfoEx(wstr long ptr long)
@ stdcall GetSystemPreferredUILanguages(long ptr wstr ptr)
@ stdcall GetThreadPreferredUILanguages(long ptr wstr ptr)
@ stdcall GetThreadUILanguage()
@ stdcall GetUILanguageInfo(long wstr wstr ptr ptr)
@ stdcall GetUserDefaultLocaleName(wstr long)
@ stdcall GetUserPreferredUILanguages(long ptr wstr ptr)
@ stdcall IsValidLocaleName(wstr)
@ stdcall LCIDToLocaleName(long wstr long long)
@ stdcall LocaleNameToLCID(wstr long)
@ stdcall GetThreadErrorMode()
@ stdcall InitializeProcThreadAttributeList(ptr long long ptr)
@ stdcall OpenFileById(ptr ptr long long ptr long)
@ stdcall QueryFullProcessImageNameA(ptr long ptr ptr)
@ stdcall QueryFullProcessImageNameW(ptr long ptr ptr)
@ stdcall RegisterApplicationRecoveryCallback(ptr ptr long long)
@ stdcall RegisterApplicationRestart(wstr long)
@ stdcall SetThreadErrorMode(long ptr)
@ stdcall SetFileBandwidthReservation(ptr long long long ptr ptr)
@ stdcall SetProcessDEPPolicy(long)
@ stdcall SetFileInformationByHandle(ptr long ptr long)
@ stdcall SetThreadPreferredUILanguages(long wstr ptr)
@ stdcall UpdateProcThreadAttribute(ptr long ptr ptr ptr ptr ptr)
@ stdcall MapViewOfFileExNuma(long long long long long ptr long)
@ stdcall VirtualAllocExNuma(long ptr long long long long)
