1  stdcall D3D10CompileEffectFromMemory(ptr long str ptr ptr long ptr ptr)
2  stdcall D3D10CompileShader(ptr long str ptr ptr str str long ptr ptr)
3  stdcall D3D10CreateBlob(long ptr)
4  stdcall D3D10CreateDevice1(ptr long ptr long long long ptr)
5  stdcall D3D10CreateDeviceAndSwapChain1(ptr long ptr long long long ptr ptr ptr)
6  stdcall D3D10CreateEffectFromMemory(ptr long long ptr ptr ptr)
7  stdcall D3D10CreateEffectPoolFromMemory(ptr long long ptr ptr)
8  stdcall D3D10CreateStateBlock(ptr ptr ptr)
9  stdcall D3D10DisassembleEffect(ptr long ptr)
10 stdcall D3D10DisassembleShader(ptr long long ptr ptr)
11 stdcall D3D10GetGeometryShaderProfile(ptr)
12 stdcall D3D10GetInputAndOutputSignatureBlob(ptr long ptr)
13 stdcall D3D10GetInputSignatureBlob(ptr long ptr)
14 stdcall D3D10GetOutputSignatureBlob(ptr long ptr)
15 stdcall D3D10GetPixelShaderProfile(ptr)
16 stdcall D3D10GetShaderDebugInfo(ptr long ptr)
17 stdcall D3D10GetVersion()
18 stdcall D3D10GetVertexShaderProfile(ptr)
19 stdcall D3D10PreprocessShader(ptr long str ptr ptr ptr ptr)
20 stdcall D3D10ReflectShader(ptr long ptr)
21 stdcall D3D10RegisterLayers()
22 stdcall D3D10StateBlockMaskDifference(ptr ptr ptr)
23 stdcall D3D10StateBlockMaskDisableAll(ptr)
24 stdcall D3D10StateBlockMaskDisableCapture(ptr long long long)
25 stdcall D3D10StateBlockMaskEnableAll(ptr)
26 stdcall D3D10StateBlockMaskEnableCapture(ptr long long long)
27 stdcall D3D10StateBlockMaskGetSetting(ptr long long)
28 stdcall D3D10StateBlockMaskIntersect(ptr ptr ptr)
29 stdcall D3D10StateBlockMaskUnion(ptr ptr ptr)
