@ stdcall SmartcardAcquireRemoveLock(ptr)
@ stdcall SmartcardAcquireRemoveLockWithTag(ptr long)
@ stdcall SmartcardCreateLink(ptr ptr)
@ stdcall SmartcardDeviceControl(ptr ptr)
@ stdcall SmartcardExit(ptr)
@ stdcall SmartcardGetDebugLevel()
@ stdcall SmartcardInitialize(ptr)
@ stdcall SmartcardInitializeCardCapabilities(ptr)
@ stdcall SmartcardInvertData(ptr long)
@ stdcall SmartcardLogError(ptr long ptr long)
@ stdcall SmartcardRawReply(ptr)
@ stdcall SmartcardRawRequest(ptr)
@ stdcall SmartcardReleaseRemoveLock(ptr)
@ stdcall SmartcardReleaseRemoveLockAndWait(ptr)
@ stdcall SmartcardReleaseRemoveLockWithTag(ptr long)
@ stdcall SmartcardSetDebugLevel(long)
@ stdcall SmartcardT0Reply(ptr)
@ stdcall SmartcardT0Request(ptr)
@ stdcall SmartcardT1Reply(ptr)
@ stdcall SmartcardT1Request(ptr)
@ stdcall SmartcardUpdateCardCapabilities(ptr)
