/* Automatically generated by make depend; DO NOT EDIT!! */

#define STANDALONE
#include <wine/test.h>

extern void func_wintypes(void);

const struct test winetest_testlist[] =
{
    { "wintypes", func_wintypes },
    { 0, 0 }
};
