; dxgkrnl.sys exports
;
; The public name set is the clean-room-supported intersection with Windows 11
; 24H2 build 26100.1742. Verified Windows exports retain their native ordinals.
; Miniport initialization is resolved through the displib control-device
; protocol and is intentionally not exported.

; --- Optional telemetry admission ---
2 cdecl DxgKrnlTelemetryGlobal_LogTelemetryEvent()

; --- Display Port / Scheduler bridge ---
38 stdcall DpSynchronizeExecution(ptr ptr ptr long ptr)
39 stdcall DpiGetDriverVersion(ptr)
40 stdcall DpiGetDxgAdapter(ptr)
41 stdcall DpiGetSchedulerCallbackState(ptr)
42 stdcall DpiSetSchedulerCallbackState(ptr long)

; --- DxgCoreInterface (static callback table consumed by dxgmms2.sys) ---
43 extern DxgCoreInterface

; --- IOMMU feature-disabled boundary ---
11 cdecl SysMmMapIommuContiguousRange(ptr int64 int64 int64 long)
12 cdecl SysMmMapIommuRange(ptr int64 ptr long)
13 cdecl SysMmUnmapIommuContiguousRange(ptr int64 int64 int64 long)
14 cdecl SysMmUnmapIommuRange(ptr int64 ptr long)

; --- Layout-free TDR policy ---
23 stdcall TdrIsEnabled()
25 stdcall TdrIsTimeoutForcedFlip()

; --- dxgmms2 build, bugcheck, and timeout state ---
30 extern g_DxgMmsBugcheckExportIndex
31 extern g_IsInternalRelease
32 extern g_IsInternalReleaseOrDbg
35 extern ?g_TdrForceDodPresentTimeout@@3JC g_TdrForceDodPresentTimeout
36 extern ?g_TdrForceDodVSyncTimeout@@3JC g_TdrForceDodVSyncTimeout
37 extern g_TdrForceTimeout

; --- ETW tracing stubs ---
321 stdcall TraceDxgkBlockThread(long)
322 stdcall TraceDxgkContext(long ptr)
323 stdcall TraceDxgkDevice(long ptr)
324 stdcall TraceDxgkFunctionProfiler(long)
325 stdcall TraceDxgkPerformanceWarning(long ptr)

; --- VidMm ---
8 stdcall DxgkUnreferenceDxgAllocation(ptr)
9 stdcall DxgkUnreferenceDxgResource(ptr)
10 stdcall DxgkVidMmAllowFailOnOfferReclaimErrors()

; --- Hardware-context feature-disabled boundary ---
48 stdcall DxgkSubmitPresentBltToHwQueue(ptr)
83 stdcall NtDxgkSubmitPresentBltToHwQueue(ptr) DxgkSubmitPresentBltToHwQueue

; --- Public D3DKMT syscall entries routed through win32k capture ---
112 stdcall NtGdiDdDDIAcquireKeyedMutex(ptr) DxgkNtGdiDdDDIAcquireKeyedMutex
113 stdcall NtGdiDdDDIAcquireKeyedMutex2(ptr) DxgkNtGdiDdDDIAcquireKeyedMutex2
116 stdcall NtGdiDdDDIAdjustFullscreenGamma(ptr) DxgkNtGdiDdDDIAdjustFullscreenGamma
118 stdcall NtGdiDdDDIChangeVideoMemoryReservation(ptr) DxgkNtGdiDdDDIChangeVideoMemoryReservation
119 stdcall NtGdiDdDDICheckExclusiveOwnership() DxgkNtGdiDdDDICheckExclusiveOwnership
120 stdcall NtGdiDdDDICheckMonitorPowerState(ptr) DxgkNtGdiDdDDICheckMonitorPowerState
121 stdcall NtGdiDdDDICheckMultiPlaneOverlaySupport(ptr) DxgkNtGdiDdDDICheckMultiPlaneOverlaySupport
122 stdcall NtGdiDdDDICheckMultiPlaneOverlaySupport2(ptr) DxgkNtGdiDdDDICheckMultiPlaneOverlaySupport2
123 stdcall NtGdiDdDDICheckMultiPlaneOverlaySupport3(ptr) DxgkNtGdiDdDDICheckMultiPlaneOverlaySupport3
124 stdcall NtGdiDdDDICheckOcclusion(ptr) DxgkNtGdiDdDDICheckOcclusion
125 stdcall NtGdiDdDDICheckSharedResourceAccess(ptr) DxgkNtGdiDdDDICheckSharedResourceAccess
126 stdcall NtGdiDdDDICheckVidPnExclusiveOwnership(ptr) DxgkNtGdiDdDDICheckVidPnExclusiveOwnership
127 stdcall NtGdiDdDDICloseAdapter(ptr) DxgkNtGdiDdDDICloseAdapter
128 stdcall NtGdiDdDDIConfigureSharedResource(ptr) DxgkNtGdiDdDDIConfigureSharedResource
129 stdcall NtGdiDdDDICreateAllocation(ptr) DxgkNtGdiDdDDICreateAllocation
131 stdcall NtGdiDdDDICreateContext(ptr) DxgkNtGdiDdDDICreateContext
132 stdcall NtGdiDdDDICreateContextVirtual(ptr) DxgkNtGdiDdDDICreateContextVirtual
133 stdcall NtGdiDdDDICreateDevice(ptr) DxgkNtGdiDdDDICreateDevice
134 stdcall NtGdiDdDDICreateHwContext(ptr) DxgkNtGdiDdDDICreateHwContext
135 stdcall NtGdiDdDDICreateHwQueue(ptr) DxgkNtGdiDdDDICreateHwQueue
136 stdcall NtGdiDdDDICreateKeyedMutex(ptr) DxgkNtGdiDdDDICreateKeyedMutex
137 stdcall NtGdiDdDDICreateKeyedMutex2(ptr) DxgkNtGdiDdDDICreateKeyedMutex2
138 stdcall NtGdiDdDDICreateOutputDupl(ptr) DxgkNtGdiDdDDICreateOutputDupl
139 stdcall NtGdiDdDDICreateOverlay(ptr) DxgkNtGdiDdDDICreateOverlay
140 stdcall NtGdiDdDDICreatePagingQueue(ptr) DxgkNtGdiDdDDICreatePagingQueue
141 stdcall NtGdiDdDDICreateProtectedSession(ptr) DxgkNtGdiDdDDICreateProtectedSession
143 stdcall NtGdiDdDDICreateSynchronizationObject(ptr) DxgkNtGdiDdDDICreateSynchronizationObject
145 stdcall NtGdiDdDDIDestroyAllocation(ptr) DxgkNtGdiDdDDIDestroyAllocation
146 stdcall NtGdiDdDDIDestroyAllocation2(ptr) DxgkNtGdiDdDDIDestroyAllocation2
147 stdcall NtGdiDdDDIDestroyContext(ptr) DxgkNtGdiDdDDIDestroyContext
148 stdcall NtGdiDdDDIDestroyDevice(ptr) DxgkNtGdiDdDDIDestroyDevice
149 stdcall NtGdiDdDDIDestroyHwContext(ptr) DxgkNtGdiDdDDIDestroyHwContext
150 stdcall NtGdiDdDDIDestroyHwQueue(ptr) DxgkNtGdiDdDDIDestroyHwQueue
151 stdcall NtGdiDdDDIDestroyKeyedMutex(ptr) DxgkNtGdiDdDDIDestroyKeyedMutex
152 stdcall NtGdiDdDDIDestroyOutputDupl(ptr) DxgkNtGdiDdDDIDestroyOutputDupl
153 stdcall NtGdiDdDDIDestroyOverlay(ptr) DxgkNtGdiDdDDIDestroyOverlay
154 stdcall NtGdiDdDDIDestroyPagingQueue(ptr) DxgkNtGdiDdDDIDestroyPagingQueue
155 stdcall NtGdiDdDDIDestroyProtectedSession(ptr) DxgkNtGdiDdDDIDestroyProtectedSession
156 stdcall NtGdiDdDDIDestroySynchronizationObject(ptr) DxgkNtGdiDdDDIDestroySynchronizationObject
160 stdcall NtGdiDdDDIEnumAdapters(ptr) DxgkNtGdiDdDDIEnumAdapters
161 stdcall NtGdiDdDDIEnumAdapters2(ptr) DxgkNtGdiDdDDIEnumAdapters2
162 stdcall NtGdiDdDDIEscape(ptr) DxgkNtGdiDdDDIEscape
163 stdcall NtGdiDdDDIEvict(ptr) DxgkNtGdiDdDDIEvict
165 stdcall NtGdiDdDDIFlipOverlay(ptr) DxgkNtGdiDdDDIFlipOverlay
166 stdcall NtGdiDdDDIFlushHeapTransitions(ptr) DxgkNtGdiDdDDIFlushHeapTransitions
167 stdcall NtGdiDdDDIFreeGpuVirtualAddress(ptr) DxgkNtGdiDdDDIFreeGpuVirtualAddress
168 stdcall NtGdiDdDDIGetAllocationPriority(ptr) DxgkNtGdiDdDDIGetAllocationPriority
170 stdcall NtGdiDdDDIGetContextInProcessSchedulingPriority(ptr) DxgkNtGdiDdDDIGetContextInProcessSchedulingPriority
171 stdcall NtGdiDdDDIGetContextSchedulingPriority(ptr) DxgkNtGdiDdDDIGetContextSchedulingPriority
172 stdcall NtGdiDdDDIGetDWMVerticalBlankEvent(ptr) DxgkNtGdiDdDDIGetDWMVerticalBlankEvent
173 stdcall NtGdiDdDDIGetDeviceState(ptr) DxgkNtGdiDdDDIGetDeviceState
174 stdcall NtGdiDdDDIGetDisplayModeList(ptr) DxgkNtGdiDdDDIGetDisplayModeList
176 stdcall NtGdiDdDDIGetMultiPlaneOverlayCaps(ptr) DxgkNtGdiDdDDIGetMultiPlaneOverlayCaps
177 stdcall NtGdiDdDDIGetMultisampleMethodList(ptr) DxgkNtGdiDdDDIGetMultisampleMethodList
178 stdcall NtGdiDdDDIGetOverlayState(ptr) DxgkNtGdiDdDDIGetOverlayState
179 stdcall NtGdiDdDDIGetPostCompositionCaps(ptr) DxgkNtGdiDdDDIGetPostCompositionCaps
180 stdcall NtGdiDdDDIGetPresentHistory(ptr) DxgkNtGdiDdDDIGetPresentHistory
181 stdcall NtGdiDdDDIGetProcessDeviceRemovalSupport(ptr) DxgkNtGdiDdDDIGetProcessDeviceRemovalSupport
183 stdcall NtGdiDdDDIGetProcessSchedulingPriorityClass(ptr ptr) DxgkNtGdiDdDDIGetProcessSchedulingPriorityClass
184 stdcall NtGdiDdDDIGetResourcePresentPrivateDriverData(ptr) DxgkNtGdiDdDDIGetResourcePresentPrivateDriverData
185 stdcall NtGdiDdDDIGetRuntimeData(ptr) DxgkNtGdiDdDDIGetRuntimeData
186 stdcall NtGdiDdDDIGetScanLine(ptr) DxgkNtGdiDdDDIGetScanLine
188 stdcall NtGdiDdDDIGetSharedPrimaryHandle(ptr) DxgkNtGdiDdDDIGetSharedPrimaryHandle
189 stdcall NtGdiDdDDIGetSharedResourceAdapterLuid(ptr) DxgkNtGdiDdDDIGetSharedResourceAdapterLuid
193 stdcall NtGdiDdDDIInvalidateActiveVidPn(ptr) DxgkNtGdiDdDDIInvalidateActiveVidPn
194 stdcall NtGdiDdDDIInvalidateCache(ptr) DxgkNtGdiDdDDIInvalidateCache
195 stdcall NtGdiDdDDILock(ptr) DxgkNtGdiDdDDILock
196 stdcall NtGdiDdDDILock2(ptr) DxgkNtGdiDdDDILock2
197 stdcall NtGdiDdDDIMakeResident(ptr) DxgkNtGdiDdDDIMakeResident
198 stdcall NtGdiDdDDIMapGpuVirtualAddress(ptr) DxgkNtGdiDdDDIMapGpuVirtualAddress
199 stdcall NtGdiDdDDIMarkDeviceAsError(ptr) DxgkNtGdiDdDDIMarkDeviceAsError
205 stdcall NtGdiDdDDIOfferAllocations(ptr) DxgkNtGdiDdDDIOfferAllocations
206 stdcall NtGdiDdDDIOpenAdapterFromDeviceName(ptr) DxgkNtGdiDdDDIOpenAdapterFromDeviceName
207 stdcall NtGdiDdDDIOpenAdapterFromHdc(ptr) DxgkNtGdiDdDDIOpenAdapterFromHdc
208 stdcall NtGdiDdDDIOpenAdapterFromLuid(ptr) DxgkNtGdiDdDDIOpenAdapterFromLuid
210 stdcall NtGdiDdDDIOpenKeyedMutex(ptr) DxgkNtGdiDdDDIOpenKeyedMutex
211 stdcall NtGdiDdDDIOpenKeyedMutex2(ptr) DxgkNtGdiDdDDIOpenKeyedMutex2
212 stdcall NtGdiDdDDIOpenKeyedMutexFromNtHandle(ptr) DxgkNtGdiDdDDIOpenKeyedMutexFromNtHandle
213 stdcall NtGdiDdDDIOpenNtHandleFromName(ptr) DxgkNtGdiDdDDIOpenNtHandleFromName
214 stdcall NtGdiDdDDIOpenProtectedSessionFromNtHandle(ptr) DxgkNtGdiDdDDIOpenProtectedSessionFromNtHandle
215 stdcall NtGdiDdDDIOpenResource(ptr) DxgkNtGdiDdDDIOpenResource
216 stdcall NtGdiDdDDIOpenResourceFromNtHandle(ptr) DxgkNtGdiDdDDIOpenResourceFromNtHandle
218 stdcall NtGdiDdDDIOpenSyncObjectFromNtHandle(ptr) DxgkNtGdiDdDDIOpenSyncObjectFromNtHandle
219 stdcall NtGdiDdDDIOpenSyncObjectFromNtHandle2(ptr) DxgkNtGdiDdDDIOpenSyncObjectFromNtHandle2
220 stdcall NtGdiDdDDIOpenSyncObjectNtHandleFromName(ptr) DxgkNtGdiDdDDIOpenSyncObjectNtHandleFromName
221 stdcall NtGdiDdDDIOpenSynchronizationObject(ptr) DxgkNtGdiDdDDIOpenSynchronizationObject
222 stdcall NtGdiDdDDIOutputDuplGetFrameInfo(ptr) DxgkNtGdiDdDDIOutputDuplGetFrameInfo
223 stdcall NtGdiDdDDIOutputDuplGetMetaData(ptr) DxgkNtGdiDdDDIOutputDuplGetMetaData
224 stdcall NtGdiDdDDIOutputDuplGetPointerShapeData(ptr) DxgkNtGdiDdDDIOutputDuplGetPointerShapeData
225 stdcall NtGdiDdDDIOutputDuplPresent(ptr) DxgkNtGdiDdDDIOutputDuplPresent
226 stdcall NtGdiDdDDIOutputDuplReleaseFrame(ptr) DxgkNtGdiDdDDIOutputDuplReleaseFrame
227 stdcall NtGdiDdDDIPollDisplayChildren(ptr) DxgkNtGdiDdDDIPollDisplayChildren
228 stdcall NtGdiDdDDIPresent(ptr) DxgkNtGdiDdDDIPresent
229 stdcall NtGdiDdDDIPresentMultiPlaneOverlay(ptr) DxgkNtGdiDdDDIPresentMultiPlaneOverlay
230 stdcall NtGdiDdDDIPresentMultiPlaneOverlay2(ptr) DxgkNtGdiDdDDIPresentMultiPlaneOverlay2
231 stdcall NtGdiDdDDIPresentMultiPlaneOverlay3(ptr) DxgkNtGdiDdDDIPresentMultiPlaneOverlay3
232 stdcall NtGdiDdDDIPresentRedirected(ptr) DxgkNtGdiDdDDIPresentRedirected
233 stdcall NtGdiDdDDIQueryAdapterInfo(ptr) DxgkNtGdiDdDDIQueryAdapterInfo
234 stdcall NtGdiDdDDIQueryAllocationResidency(ptr) DxgkNtGdiDdDDIQueryAllocationResidency
235 stdcall NtGdiDdDDIQueryClockCalibration(ptr) DxgkNtGdiDdDDIQueryClockCalibration
236 stdcall NtGdiDdDDIQueryFSEBlock(ptr) DxgkNtGdiDdDDIQueryFSEBlock
237 stdcall NtGdiDdDDIQueryProcessOfferInfo(ptr) DxgkNtGdiDdDDIQueryProcessOfferInfo
238 stdcall NtGdiDdDDIQueryProtectedSessionInfoFromNtHandle(ptr) DxgkNtGdiDdDDIQueryProtectedSessionInfoFromNtHandle
239 stdcall NtGdiDdDDIQueryProtectedSessionStatus(ptr) DxgkNtGdiDdDDIQueryProtectedSessionStatus
240 stdcall NtGdiDdDDIQueryRemoteVidPnSourceFromGdiDisplayName(ptr) DxgkNtGdiDdDDIQueryRemoteVidPnSourceFromGdiDisplayName
241 stdcall NtGdiDdDDIQueryResourceInfo(ptr) DxgkNtGdiDdDDIQueryResourceInfo
242 stdcall NtGdiDdDDIQueryResourceInfoFromNtHandle(ptr) DxgkNtGdiDdDDIQueryResourceInfoFromNtHandle
243 stdcall NtGdiDdDDIQueryStatistics(ptr) DxgkNtGdiDdDDIQueryStatistics
244 stdcall NtGdiDdDDIQueryVidPnExclusiveOwnership(ptr) DxgkNtGdiDdDDIQueryVidPnExclusiveOwnership
245 stdcall NtGdiDdDDIQueryVideoMemoryInfo(ptr) DxgkNtGdiDdDDIQueryVideoMemoryInfo
246 stdcall NtGdiDdDDIReclaimAllocations(ptr) DxgkNtGdiDdDDIReclaimAllocations
247 stdcall NtGdiDdDDIReclaimAllocations2(ptr) DxgkNtGdiDdDDIReclaimAllocations2
248 stdcall NtGdiDdDDIReleaseKeyedMutex(ptr) DxgkNtGdiDdDDIReleaseKeyedMutex
249 stdcall NtGdiDdDDIReleaseKeyedMutex2(ptr) DxgkNtGdiDdDDIReleaseKeyedMutex2
250 stdcall NtGdiDdDDIReleaseProcessVidPnSourceOwners(ptr) DxgkNtGdiDdDDIReleaseProcessVidPnSourceOwners
253 stdcall NtGdiDdDDIRender(ptr) DxgkNtGdiDdDDIRender
254 stdcall NtGdiDdDDIReserveGpuVirtualAddress(ptr) DxgkNtGdiDdDDIReserveGpuVirtualAddress
255 stdcall NtGdiDdDDISetAllocationPriority(ptr) DxgkNtGdiDdDDISetAllocationPriority
256 stdcall NtGdiDdDDISetContextInProcessSchedulingPriority(ptr) DxgkNtGdiDdDDISetContextInProcessSchedulingPriority
257 stdcall NtGdiDdDDISetContextSchedulingPriority(ptr) DxgkNtGdiDdDDISetContextSchedulingPriority
258 stdcall NtGdiDdDDISetDisplayMode(ptr) DxgkNtGdiDdDDISetDisplayMode
260 stdcall NtGdiDdDDISetFSEBlock(ptr) DxgkNtGdiDdDDISetFSEBlock
261 stdcall NtGdiDdDDISetGammaRamp(ptr) DxgkNtGdiDdDDISetGammaRamp
262 stdcall NtGdiDdDDISetHwProtectionTeardownRecovery(ptr) DxgkNtGdiDdDDISetHwProtectionTeardownRecovery
264 stdcall NtGdiDdDDISetMonitorColorSpaceTransform(ptr) DxgkNtGdiDdDDISetMonitorColorSpaceTransform
267 stdcall NtGdiDdDDISetProcessSchedulingPriorityClass(ptr long) DxgkNtGdiDdDDISetProcessSchedulingPriorityClass
268 stdcall NtGdiDdDDISetQueuedLimit(ptr) DxgkNtGdiDdDDISetQueuedLimit
269 stdcall NtGdiDdDDISetStablePowerState(ptr) DxgkNtGdiDdDDISetStablePowerState
271 stdcall NtGdiDdDDISetSyncRefreshCountWaitTarget(ptr) DxgkNtGdiDdDDISetSyncRefreshCountWaitTarget
272 stdcall NtGdiDdDDISetVidPnSourceHwProtection(ptr) DxgkNtGdiDdDDISetVidPnSourceHwProtection
273 stdcall NtGdiDdDDISetVidPnSourceOwner(ptr) DxgkNtGdiDdDDISetVidPnSourceOwner
275 stdcall NtGdiDdDDIShareObjects(long ptr ptr long ptr) DxgkNtGdiDdDDIShareObjects
276 stdcall NtGdiDdDDISignalSynchronizationObject(ptr) DxgkNtGdiDdDDISignalSynchronizationObject
277 stdcall NtGdiDdDDISignalSynchronizationObjectFromCpu(ptr) DxgkNtGdiDdDDISignalSynchronizationObjectFromCpu
278 stdcall NtGdiDdDDISignalSynchronizationObjectFromGpu(ptr) DxgkNtGdiDdDDISignalSynchronizationObjectFromGpu
279 stdcall NtGdiDdDDISignalSynchronizationObjectFromGpu2(ptr) DxgkNtGdiDdDDISignalSynchronizationObjectFromGpu2
280 stdcall NtGdiDdDDISubmitCommand(ptr) DxgkNtGdiDdDDISubmitCommand
281 stdcall NtGdiDdDDISubmitCommandToHwQueue(ptr) DxgkNtGdiDdDDISubmitCommandToHwQueue
282 stdcall NtGdiDdDDISubmitSignalSyncObjectsToHwQueue(ptr) DxgkNtGdiDdDDISubmitSignalSyncObjectsToHwQueue
283 stdcall NtGdiDdDDISubmitWaitForSyncObjectsToHwQueue(ptr) DxgkNtGdiDdDDISubmitWaitForSyncObjectsToHwQueue
284 stdcall NtGdiDdDDITrimProcessCommitment(ptr) DxgkNtGdiDdDDITrimProcessCommitment
286 stdcall NtGdiDdDDIUnlock(ptr) DxgkNtGdiDdDDIUnlock
287 stdcall NtGdiDdDDIUnlock2(ptr) DxgkNtGdiDdDDIUnlock2
288 stdcall NtGdiDdDDIUpdateAllocationProperty(ptr) DxgkNtGdiDdDDIUpdateAllocationProperty
289 stdcall NtGdiDdDDIUpdateGpuVirtualAddress(ptr) DxgkNtGdiDdDDIUpdateGpuVirtualAddress
290 stdcall NtGdiDdDDIUpdateOverlay(ptr) DxgkNtGdiDdDDIUpdateOverlay
291 stdcall NtGdiDdDDIWaitForIdle(ptr) DxgkNtGdiDdDDIWaitForIdle
292 stdcall NtGdiDdDDIWaitForSynchronizationObject(ptr) DxgkNtGdiDdDDIWaitForSynchronizationObject
293 stdcall NtGdiDdDDIWaitForSynchronizationObjectFromCpu(ptr) DxgkNtGdiDdDDIWaitForSynchronizationObjectFromCpu
294 stdcall NtGdiDdDDIWaitForSynchronizationObjectFromGpu(ptr) DxgkNtGdiDdDDIWaitForSynchronizationObjectFromGpu
295 stdcall NtGdiDdDDIWaitForVerticalBlankEvent(ptr) DxgkNtGdiDdDDIWaitForVerticalBlankEvent
296 stdcall NtGdiDdDDIWaitForVerticalBlankEvent2(ptr) DxgkNtGdiDdDDIWaitForVerticalBlankEvent2
