/*
 * PROJECT:         ReactOS PCI bus driver
 * FILE:            cb.c
 * PURPOSE:         Private CardBus interface (GUID_PCI_CARDBUS_INTERFACE_PRIVATE)
 *
 * pcmcia.sys is the function driver for a CardBus controller PDO.  It
 * queries this interface from pci.sys and uses it to hand the CardBus
 * segment back to PCI: AddCardBus registers the socket's secondary bus,
 * DispatchPnp routes bus-level PnP IRPs (notably BusRelations) so that
 * 32-bit cards inserted into the socket enumerate as regular PCI\VEN_*
 * PDOs owned by pci.sys, and DeleteCardBus tears the registration down.
 *
 * The CardBus segment is represented by a "virtual FDO": a real device
 * object owned by pci.sys carrying a normal FDO_DEVICE_EXTENSION, but
 * never attached to a device stack.  That lets the existing per-bus
 * enumeration (FdoQueryBusRelations) and arbiter machinery work on the
 * CardBus bus unchanged.
 */

#include "pci.h"

#define NDEBUG
#include <debug.h>

#define PCI_CARDBUS_CONTEXT_SIGNATURE 'sbCP'

typedef struct _PCI_CARDBUS_CONTEXT
{
    ULONG Signature;
    /* The CardBus bridge PDO (owned by pci.sys) */
    PDEVICE_OBJECT BridgePdo;
    /* Unattached device object representing the CardBus segment */
    PDEVICE_OBJECT VirtualFdo;
} PCI_CARDBUS_CONTEXT, *PPCI_CARDBUS_CONTEXT;

/**
 * @brief Re-read the bridge's bus-number registers into the virtual FDO.
 *
 * pcmcia.sys or the PnP manager may (re)program the CardBus bus number
 * after AddCardBus, so refresh before every enumeration.
 */
static VOID
PciCbRefreshBusNumbers(_In_ PPCI_CARDBUS_CONTEXT Context)
{
    PPDO_DEVICE_EXTENSION BridgeExtension;
    PFDO_DEVICE_EXTENSION FdoExtension;
    UCHAR BusRegs[3];

    BridgeExtension = (PPDO_DEVICE_EXTENSION)Context->BridgePdo->DeviceExtension;
    FdoExtension = (PFDO_DEVICE_EXTENSION)Context->VirtualFdo->DeviceExtension;

    BusRegs[0] = 0;
    BusRegs[1] = 0;
    BusRegs[2] = 0;
    PciPdoGetBusDataByOffset(BridgeExtension, BusRegs, FIELD_OFFSET(PCI_COMMON_CONFIG, u.type2.PrimaryBus), 3 * sizeof(UCHAR));

    FdoExtension->BusNumber = BusRegs[1];
    FdoExtension->BusRangeStart = BusRegs[1];
    FdoExtension->BusRangeEnd = (BusRegs[2] >= BusRegs[1]) ? BusRegs[2] : BusRegs[1];

    DPRINT("PCI CB: CardBus segment primary %u secondary %u subordinate %u\n", BusRegs[0], BusRegs[1], BusRegs[2]);
}

NTSTATUS
NTAPI
PciCbAddCardBus(_In_ PDEVICE_OBJECT DeviceObject, _Inout_ PVOID *DeviceContext)
{
    PDEVICE_OBJECT BridgePdo;
    PPDO_DEVICE_EXTENSION BridgeExtension;
    PPCI_CARDBUS_CONTEXT Context;
    PFDO_DEVICE_EXTENSION FdoExtension;
    PDEVICE_OBJECT VirtualFdo;
    NTSTATUS Status;

    if (!DeviceObject || !DeviceContext)
        return STATUS_INVALID_PARAMETER;

    /* Callers may pass the bridge PDO itself or anything attached above
     * it; normalize to the bottom of the stack */
    BridgePdo = IoGetDeviceAttachmentBaseRef(DeviceObject);
    if (!BridgePdo)
        return STATUS_INVALID_PARAMETER;

    /* It must be one of our CardBus bridge PDOs */
    BridgeExtension = (PPDO_DEVICE_EXTENSION)BridgePdo->DeviceExtension;
    if (BridgePdo->DriverObject == NULL || BridgeExtension == NULL || BridgeExtension->Common.IsFDO || BridgeExtension->PciDevice == NULL || PCI_CONFIGURATION_TYPE(&BridgeExtension->PciDevice->PciConfig) != PCI_CARDBUS_BRIDGE_TYPE)
    {
        DPRINT1("PCI CB: AddCardBus on %p which is not a CardBus bridge PDO\n", DeviceObject);
        ObDereferenceObject(BridgePdo);
        return STATUS_INVALID_PARAMETER;
    }

    Context = ExAllocatePoolWithTag(NonPagedPool, sizeof(PCI_CARDBUS_CONTEXT), TAG_PCI);
    if (!Context)
    {
        ObDereferenceObject(BridgePdo);
        return STATUS_INSUFFICIENT_RESOURCES;
    }
    RtlZeroMemory(Context, sizeof(PCI_CARDBUS_CONTEXT));

    /* Create the unattached bus object for the CardBus segment */
    Status = IoCreateDevice(BridgePdo->DriverObject, sizeof(FDO_DEVICE_EXTENSION), NULL, FILE_DEVICE_BUS_EXTENDER, FILE_AUTOGENERATED_DEVICE_NAME, FALSE, &VirtualFdo);
    if (!NT_SUCCESS(Status))
    {
        DPRINT1("PCI CB: IoCreateDevice failed 0x%lx\n", Status);
        ExFreePoolWithTag(Context, TAG_PCI);
        ObDereferenceObject(BridgePdo);
        return Status;
    }

    FdoExtension = (PFDO_DEVICE_EXTENSION)VirtualFdo->DeviceExtension;
    RtlZeroMemory(FdoExtension, sizeof(FDO_DEVICE_EXTENSION));

    FdoExtension->Common.IsFDO = TRUE;
    FdoExtension->Common.DeviceObject = VirtualFdo;
    FdoExtension->Common.DevicePowerState = PowerDeviceD0;
    FdoExtension->Ldo = NULL;
    FdoExtension->State = PciStarted;
    FdoExtension->BusSegment = 0;
    IoInitializeRemoveLock(&FdoExtension->RemoveLock, TAG_PCI, 0, 0);

    PciFdoInitializeChildTracking(FdoExtension);

    Context->Signature = PCI_CARDBUS_CONTEXT_SIGNATURE;
    Context->BridgePdo = BridgePdo;
    Context->VirtualFdo = VirtualFdo;

    PciCbRefreshBusNumbers(Context);

    /* Seed the arbiters from the bridge's currently programmed windows */
    {
        CM_RESOURCE_LIST WindowResources;
        PCM_PARTIAL_RESOURCE_LIST PartialList;
        PCI_COMMON_CONFIG BridgeConfig;
        ULONG Window, Count;

        PciPdoGetBusData(BridgeExtension, &BridgeConfig, PCI_COMMON_HDR_LENGTH);

        RtlZeroMemory(&WindowResources, sizeof(WindowResources));
        WindowResources.Count = 1;
        PartialList = &WindowResources.List[0].PartialResourceList;
        PartialList->Version = 1;
        PartialList->Revision = 1;
        Count = 0;

        /* CM_RESOURCE_LIST embeds one descriptor; only the first
         * configured window fits, which is the common configuration.
         * The remaining windows are still protected by the global
         * resource map. */
        for (Window = 0; Window < 4 && Count < 1; Window++)
        {
            BOOLEAN IsMemoryWindow;
            ULONG WindowBase, WindowLimit;
            PCM_PARTIAL_RESOURCE_DESCRIPTOR Desc = &PartialList->PartialDescriptors[Count];

            if (!PciCbDecodeWindow(&BridgeConfig, Window, &WindowBase, &WindowLimit, &IsMemoryWindow))
                continue;

            if (IsMemoryWindow)
            {
                Desc->Type = CmResourceTypeMemory;
                Desc->u.Memory.Start.QuadPart = WindowBase;
                Desc->u.Memory.Length = WindowLimit - WindowBase + 1;
            }
            else
            {
                Desc->Type = CmResourceTypePort;
                Desc->u.Port.Start.QuadPart = WindowBase;
                Desc->u.Port.Length = WindowLimit - WindowBase + 1;
            }
            Count++;
        }

        PartialList->Count = Count;
        PciArbiterSeedWindows(FdoExtension, &WindowResources, TRUE);
    }

    /* Publish the segment on the driver's bus list so legacy lookups
     * (HalAssignSlotResources hook) can find devices behind the socket */
    ExInterlockedInsertTailList(&DriverExtension->BusListHead, &FdoExtension->ListEntry, &DriverExtension->BusListLock);

    VirtualFdo->Flags &= ~DO_DEVICE_INITIALIZING;

    *DeviceContext = Context;

    DPRINT1("PCI CB: Registered CardBus segment (bridge %02x:%02x.%u, secondary bus %lu)\n", (UCHAR)BridgeExtension->PciDevice->BusNumber, BridgeExtension->PciDevice->SlotNumber.u.bits.DeviceNumber, BridgeExtension->PciDevice->SlotNumber.u.bits.FunctionNumber, FdoExtension->BusNumber);

    return STATUS_SUCCESS;
}

NTSTATUS
NTAPI
PciCbDeleteCardBus(_In_ PVOID DeviceContext)
{
    PPCI_CARDBUS_CONTEXT Context = (PPCI_CARDBUS_CONTEXT)DeviceContext;
    PFDO_DEVICE_EXTENSION FdoExtension;
    KIRQL OldIrql;

    if (!Context || Context->Signature != PCI_CARDBUS_CONTEXT_SIGNATURE)
        return STATUS_INVALID_PARAMETER;

    FdoExtension = (PFDO_DEVICE_EXTENSION)Context->VirtualFdo->DeviceExtension;

    DPRINT1("PCI CB: Removing CardBus segment (secondary bus %lu)\n", FdoExtension->BusNumber);

    KeAcquireSpinLock(&DriverExtension->BusListLock, &OldIrql);
    RemoveEntryList(&FdoExtension->ListEntry);
    KeReleaseSpinLock(&DriverExtension->BusListLock, OldIrql);

    PciDestroyFdoArbiters(FdoExtension);

    IoDeleteDevice(Context->VirtualFdo);
    ObDereferenceObject(Context->BridgePdo);

    Context->Signature = 0;
    ExFreePoolWithTag(Context, TAG_PCI);

    return STATUS_SUCCESS;
}

/**
 * @brief Handle a PnP IRP forwarded by pcmcia.sys for the CardBus segment.
 *
 * The IRP still belongs to pcmcia.sys: it is neither completed nor
 * forwarded here.  Results are placed in the IRP's IoStatus and the
 * status returned, exactly as the NT contract expects.
 */
NTSTATUS
NTAPI
PciCbDispatchPnp(_In_ PVOID DeviceContext, _In_ PIRP Irp)
{
    PPCI_CARDBUS_CONTEXT Context = (PPCI_CARDBUS_CONTEXT)DeviceContext;
    PIO_STACK_LOCATION IrpSp;
    NTSTATUS Status;

    if (!Context || Context->Signature != PCI_CARDBUS_CONTEXT_SIGNATURE || !Irp)
        return STATUS_INVALID_PARAMETER;

    IrpSp = IoGetCurrentIrpStackLocation(Irp);

    switch (IrpSp->MinorFunction)
    {
        case IRP_MN_QUERY_DEVICE_RELATIONS: if (IrpSp->Parameters.QueryDeviceRelations.Type != BusRelations)
                return Irp->IoStatus.Status;

            PciCbRefreshBusNumbers(Context);

            if (((PFDO_DEVICE_EXTENSION)Context->VirtualFdo->DeviceExtension)->BusNumber == 0)
            {
                /* Socket bus not configured yet: report no children */
                PDEVICE_RELATIONS Relations;

                Relations = ExAllocatePoolWithTag(PagedPool, sizeof(DEVICE_RELATIONS), TAG_PCI);
                if (!Relations)
                    return STATUS_INSUFFICIENT_RESOURCES;

                Relations->Count = 0;
                Relations->Objects[0] = NULL;
                Irp->IoStatus.Information = (ULONG_PTR)Relations;
                return STATUS_SUCCESS;
            }

            Status = FdoQueryBusRelations(Context->VirtualFdo, Irp, IrpSp);
            DPRINT1("PCI CB: BusRelations for CardBus segment -> 0x%lx\n", Status);
            return Status;

        case IRP_MN_START_DEVICE: case IRP_MN_QUERY_STOP_DEVICE: case IRP_MN_CANCEL_STOP_DEVICE: case IRP_MN_STOP_DEVICE: case IRP_MN_QUERY_REMOVE_DEVICE: case IRP_MN_CANCEL_REMOVE_DEVICE: case IRP_MN_REMOVE_DEVICE: case IRP_MN_SURPRISE_REMOVAL: return STATUS_SUCCESS;

        default:
            /* Leave anything else untouched for pcmcia.sys to decide */
            return Irp->IoStatus.Status;
    }
}
