if(ARCH STREQUAL "i386" OR ARCH STREQUAL "amd64" OR ARCH STREQUAL "ppc")
    add_subdirectory(atapi)
    # PowerPC PReP machines wire their PATA channels to ISA legacy ports.
    if((ARCH STREQUAL "i386" AND NOT ENABLE_UNIATA) OR ARCH STREQUAL "ppc")
        add_subdirectory(legide)
    endif()
    add_subdirectory(pciide)
endif()
add_subdirectory(pciidex)
add_subdirectory(uniata)
