/*
 * PROJECT:     Kernel Mode Device Framework
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Missing headers (wdfcx.h)
 * COPYRIGHT:   2020 Victor Perevertkin (victor.perevertkin@reactos.org)
 */

#ifndef _WDFCX_H_
#define _WDFCX_H_

#include "kmdf/inc/private/wdfldr.h"

typedef BOOLEAN
(NTAPI *PFN_WDFCX_DEVICE_FILE_CREATE) (
    _In_ WDFDEVICE Device,
    _In_ WDFREQUEST Request,
    _In_opt_ WDFFILEOBJECT FileObject);

// _WDFCX_FILEOBJECT_CONFIG_V1_17

typedef struct _WDFCX_FILEOBJECT_CONFIG {
    //
    // Size of this structure in bytes
    //
    ULONG Size;

    //
    // Event callback for create requests
    //
    PFN_WDFCX_DEVICE_FILE_CREATE  EvtCxDeviceFileCreate;

    //
    // Event callback for close requests
    //
    PFN_WDF_FILE_CLOSE   EvtFileClose;

    //
    // Event callback for cleanup requests
    //
    PFN_WDF_FILE_CLEANUP EvtFileCleanup;

    //
    // If WdfTrue, create/cleanup/close file object related requests will be
    // sent down the stack.
    //
    // If WdfFalse, create/cleanup/close will be completed at this location in
    // the device stack.
    //
    // If WdfDefault, behavior depends on device type
    // FDO, PDO, Control:  use the WdfFalse behavior
    // Filter:  use the WdfTrue behavior
    //
    WDF_TRI_STATE AutoForwardCleanupClose;

    //
    // Specify whether framework should create WDFFILEOBJECT and also
    // whether it can FsContexts fields in the WDM fileobject to store
    // WDFFILEOBJECT so that it can avoid table look up and improve perf.
    //
    WDF_FILEOBJECT_CLASS FileObjectClass;

} WDFCX_FILEOBJECT_CONFIG, *PWDFCX_FILEOBJECT_CONFIG;

/*
 * KMDF 1.25+ class-extension PnP/power ABI.
 *
 * These declarations are private framework ABI, not a ReactOS driver-facing
 * API.  Keep the member order and native pointer alignment identical to the
 * Microsoft KMDF 1.33 table consumed by inbox class extensions.
 */
typedef NTSTATUS
(NTAPI *PFN_WDFCX_DEVICE_PRE_PREPARE_HARDWARE)(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesRaw,
    _In_ WDFCMRESLIST ResourcesTranslated);

typedef VOID
(NTAPI *PFN_WDFCX_DEVICE_PRE_PREPARE_HARDWARE_FAILED_CLEANUP)(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesRaw,
    _In_ WDFCMRESLIST ResourcesTranslated);

typedef PFN_WDFCX_DEVICE_PRE_PREPARE_HARDWARE
    PFN_WDFCX_DEVICE_POST_PREPARE_HARDWARE;

typedef NTSTATUS
(NTAPI *PFN_WDFCX_DEVICE_PRE_RELEASE_HARDWARE)(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesTranslated);

typedef PFN_WDFCX_DEVICE_PRE_RELEASE_HARDWARE
    PFN_WDFCX_DEVICE_POST_RELEASE_HARDWARE;

typedef NTSTATUS
(NTAPI *PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK)(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState);

typedef VOID
(NTAPI *PFN_WDFCX_DEVICE_POWER_STATE_CLEANUP_CALLBACK)(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState);

typedef PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK PFN_WDFCX_DEVICE_PRE_D0_ENTRY;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CLEANUP_CALLBACK PFN_WDFCX_DEVICE_PRE_D0_ENTRY_FAILED_CLEANUP;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK PFN_WDFCX_DEVICE_POST_D0_ENTRY;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK PFN_WDFCX_DEVICE_PRE_D0_EXIT;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK PFN_WDFCX_DEVICE_POST_D0_EXIT;

typedef VOID
(NTAPI *PFN_WDFCX_DEVICE_VOID_CALLBACK)(
    _In_ WDFDEVICE Device);

typedef NTSTATUS
(NTAPI *PFN_WDFCX_DEVICE_STATUS_CALLBACK)(
    _In_ WDFDEVICE Device);

typedef PFN_WDFCX_DEVICE_VOID_CALLBACK PFN_WDFCX_DEVICE_PRE_SURPRISE_REMOVAL;
typedef PFN_WDFCX_DEVICE_VOID_CALLBACK PFN_WDFCX_DEVICE_POST_SURPRISE_REMOVAL;
typedef PFN_WDFCX_DEVICE_STATUS_CALLBACK PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT;
typedef PFN_WDFCX_DEVICE_VOID_CALLBACK PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT_FAILED_CLEANUP;
typedef PFN_WDFCX_DEVICE_STATUS_CALLBACK PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_INIT;
typedef PFN_WDFCX_DEVICE_STATUS_CALLBACK PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART;
typedef PFN_WDFCX_DEVICE_VOID_CALLBACK PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_FAILED_CLEANUP;
typedef PFN_WDFCX_DEVICE_STATUS_CALLBACK PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART;
typedef PFN_WDFCX_DEVICE_STATUS_CALLBACK PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND;
typedef PFN_WDFCX_DEVICE_STATUS_CALLBACK PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND;
typedef PFN_WDFCX_DEVICE_VOID_CALLBACK PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_FLUSH;
typedef PFN_WDFCX_DEVICE_VOID_CALLBACK PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_FLUSH;
typedef PFN_WDFCX_DEVICE_VOID_CALLBACK PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_CLEANUP;
typedef PFN_WDFCX_DEVICE_VOID_CALLBACK PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_CLEANUP;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CLEANUP_CALLBACK PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX_FAILED_CLEANUP;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART_EX;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND_EX;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND_EX;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK PFN_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK PFN_WDFCX_DEVICE_POST_D0_ENTRY_POST_HARDWARE_ENABLED;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CLEANUP_CALLBACK PFN_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED_FAILED_CLEANUP;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK PFN_WDFCX_DEVICE_PRE_D0_EXIT_PRE_HARDWARE_DISABLED;
typedef PFN_WDFCX_DEVICE_POWER_STATE_CALLBACK PFN_WDFCX_DEVICE_POST_D0_EXIT_PRE_HARDWARE_DISABLED;

typedef struct _WDFCX_PNPPOWER_EVENT_CALLBACKS
{
    ULONG Size;
    PFN_WDFCX_DEVICE_PRE_PREPARE_HARDWARE EvtCxDevicePrePrepareHardware;
    PFN_WDFCX_DEVICE_PRE_PREPARE_HARDWARE_FAILED_CLEANUP EvtCxDevicePrePrepareHardwareFailedCleanup;
    PFN_WDFCX_DEVICE_POST_PREPARE_HARDWARE EvtCxDevicePostPrepareHardware;
    PFN_WDFCX_DEVICE_PRE_RELEASE_HARDWARE EvtCxDevicePreReleaseHardware;
    PFN_WDFCX_DEVICE_POST_RELEASE_HARDWARE EvtCxDevicePostReleaseHardware;
    PFN_WDFCX_DEVICE_PRE_D0_ENTRY EvtCxDevicePreD0Entry;
    PFN_WDFCX_DEVICE_PRE_D0_ENTRY_FAILED_CLEANUP EvtCxDevicePreD0EntryFailedCleanup;
    PFN_WDFCX_DEVICE_POST_D0_ENTRY EvtCxDevicePostD0Entry;
    PFN_WDFCX_DEVICE_PRE_D0_EXIT EvtCxDevicePreD0Exit;
    PFN_WDFCX_DEVICE_POST_D0_EXIT EvtCxDevicePostD0Exit;
    PFN_WDFCX_DEVICE_PRE_SURPRISE_REMOVAL EvtCxDevicePreSurpriseRemoval;
    PFN_WDFCX_DEVICE_POST_SURPRISE_REMOVAL EvtCxDevicePostSurpriseRemoval;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT EvtCxDevicePreSelfManagedIoInit;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_INIT_FAILED_CLEANUP EvtCxDevicePreSelfManagedIoInitFailedCleanup;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_INIT EvtCxDevicePostSelfManagedIoInit;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART EvtCxDevicePreSelfManagedIoRestart;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_FAILED_CLEANUP EvtCxDevicePreSelfManagedIoRestartFailedCleanup;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART EvtCxDevicePostSelfManagedIoRestart;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND EvtCxDevicePreSelfManagedIoSuspend;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND EvtCxDevicePostSelfManagedIoSuspend;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_FLUSH EvtCxDevicePreSelfManagedIoFlush;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_FLUSH EvtCxDevicePostSelfManagedIoFlush;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_CLEANUP EvtCxDevicePreSelfManagedIoCleanup;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_CLEANUP EvtCxDevicePostSelfManagedIoCleanup;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX EvtCxDevicePreSelfManagedIoRestartEx;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_RESTART_EX_FAILED_CLEANUP EvtCxDevicePreSelfManagedIoRestartExFailedCleanup;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_RESTART_EX EvtCxDevicePostSelfManagedIoRestartEx;
    PFN_WDFCX_DEVICE_PRE_SELF_MANAGED_IO_SUSPEND_EX EvtCxDevicePreSelfManagedIoSuspendEx;
    PFN_WDFCX_DEVICE_POST_SELF_MANAGED_IO_SUSPEND_EX EvtCxDevicePostSelfManagedIoSuspendEx;
    PFN_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED EvtCxDevicePreD0EntryPostHardwareEnabled;
    PFN_WDFCX_DEVICE_POST_D0_ENTRY_POST_HARDWARE_ENABLED EvtCxDevicePostD0EntryPostHardwareEnabled;
    PFN_WDFCX_DEVICE_PRE_D0_ENTRY_POST_HARDWARE_ENABLED_FAILED_CLEANUP EvtCxDevicePreD0EntryPostHardwareEnabledFailedCleanup;
    PFN_WDFCX_DEVICE_PRE_D0_EXIT_PRE_HARDWARE_DISABLED EvtCxDevicePreD0ExitPreHardwareDisabled;
    PFN_WDFCX_DEVICE_POST_D0_EXIT_PRE_HARDWARE_DISABLED EvtCxDevicePostD0ExitPreHardwareDisabled;
} WDFCX_PNPPOWER_EVENT_CALLBACKS, *PWDFCX_PNPPOWER_EVENT_CALLBACKS;

typedef NTSTATUS
(NTAPI *PFN_WDFCX_DEVICE_WAKE_REASON_CALLBACK)(
    _In_ WDFDEVICE Device,
    _In_ BOOLEAN ChildrenArmedForWake,
    _In_ BOOLEAN DeviceWakeEnabled);

typedef VOID
(NTAPI *PFN_WDFCX_DEVICE_WAKE_REASON_CLEANUP_CALLBACK)(
    _In_ WDFDEVICE Device,
    _In_ BOOLEAN ChildrenArmedForWake,
    _In_ BOOLEAN DeviceWakeEnabled);

typedef struct _WDFCX_POWER_POLICY_EVENT_CALLBACKS
{
    ULONG Size;
    PFN_WDFCX_DEVICE_STATUS_CALLBACK EvtCxDevicePreArmWakeFromS0;
    PFN_WDFCX_DEVICE_VOID_CALLBACK EvtCxDevicePreArmWakeFromS0FailedCleanup;
    PFN_WDFCX_DEVICE_STATUS_CALLBACK EvtCxDevicePostArmWakeFromS0;
    PFN_WDFCX_DEVICE_VOID_CALLBACK EvtCxDevicePreDisarmWakeFromS0;
    PFN_WDFCX_DEVICE_VOID_CALLBACK EvtCxDevicePostDisarmWakeFromS0;
    PFN_WDFCX_DEVICE_VOID_CALLBACK EvtCxDevicePreWakeFromS0Triggered;
    PFN_WDFCX_DEVICE_VOID_CALLBACK EvtCxDevicePostWakeFromS0Triggered;
    PFN_WDFCX_DEVICE_STATUS_CALLBACK EvtCxDevicePreArmWakeFromSx;
    PFN_WDFCX_DEVICE_VOID_CALLBACK EvtCxDevicePreArmWakeFromSxFailedCleanup;
    PFN_WDFCX_DEVICE_STATUS_CALLBACK EvtCxDevicePostArmWakeFromSx;
    PFN_WDFCX_DEVICE_WAKE_REASON_CALLBACK EvtCxDevicePreArmWakeFromSxWithReason;
    PFN_WDFCX_DEVICE_WAKE_REASON_CLEANUP_CALLBACK EvtCxDevicePreArmWakeFromSxWithReasonFailedCleanup;
    PFN_WDFCX_DEVICE_WAKE_REASON_CALLBACK EvtCxDevicePostArmWakeFromSxWithReason;
    PFN_WDFCX_DEVICE_VOID_CALLBACK EvtCxDevicePreDisarmWakeFromSx;
    PFN_WDFCX_DEVICE_VOID_CALLBACK EvtCxDevicePostDisarmWakeFromSx;
    PFN_WDFCX_DEVICE_VOID_CALLBACK EvtCxDevicePreWakeFromSxTriggered;
    PFN_WDFCX_DEVICE_VOID_CALLBACK EvtCxDevicePostWakeFromSxTriggered;
} WDFCX_POWER_POLICY_EVENT_CALLBACKS, *PWDFCX_POWER_POLICY_EVENT_CALLBACKS;

typedef NTSTATUS
(NTAPI *PFN_WDFCXDEVICE_WDM_IRP_PREPROCESS)(
    _In_ WDFDEVICE Device,
    _Inout_ PIRP Irp,
    _In_ PVOID DispatchContext);

typedef PWDFCXDEVICE_INIT
(NTAPI *PFN_WDFCXDEVICEINITALLOCATE)(
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_ PWDFDEVICE_INIT DeviceInit);

typedef NTSTATUS
(NTAPI *PFN_WDFCXDEVICEINITASSIGNWDMIRPPREPROCESSCALLBACK) (
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_ PWDFCXDEVICE_INIT CxDeviceInit,
    _In_ PFN_WDFCXDEVICE_WDM_IRP_PREPROCESS EvtCxDeviceWdmIrpPreprocess,
    _In_ UCHAR MajorFunction,
    _When_(NumMinorFunctions > 0, _In_reads_bytes_(NumMinorFunctions))
    _When_(NumMinorFunctions == 0, _In_opt_)
    PUCHAR MinorFunctions,
    _In_ ULONG NumMinorFunctions);

typedef VOID
(NTAPI *PFN_WDFCXDEVICEINITSETIOINCALLERCONTEXTCALLBACK)(
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_ PWDFCXDEVICE_INIT CxDeviceInit,
    _In_ PFN_WDF_IO_IN_CALLER_CONTEXT EvtIoInCallerContext);

typedef VOID
(NTAPI *PFN_WDFCXDEVICEINITSETREQUESTATTRIBUTES)(
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_ PWDFCXDEVICE_INIT CxDeviceInit,
    _In_ PWDF_OBJECT_ATTRIBUTES RequestAttributes);

typedef VOID
(NTAPI *PFN_WDFCXDEVICEINITSETFILEOBJECTCONFIG)(
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_ PWDFCXDEVICE_INIT CxDeviceInit,
    _In_ PWDFCX_FILEOBJECT_CONFIG CxFileObjectConfig,
    _In_opt_ PWDF_OBJECT_ATTRIBUTES FileObjectAttributes);

typedef VOID
(NTAPI *PFN_WDFCXVERIFIERKEBUGCHECK)(
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_opt_ WDFOBJECT Object,
    _In_ ULONG BugCheckCode,
    _In_ ULONG_PTR BugCheckParameter1,
    _In_ ULONG_PTR BugCheckParameter2,
    _In_ ULONG_PTR BugCheckParameter3,
    _In_ ULONG_PTR BugCheckParameter4);

typedef WDFIOTARGET
(NTAPI *PFN_WDFDEVICEGETSELFIOTARGET)(
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_ WDFDEVICE Device);

typedef VOID
(NTAPI *PFN_WDFDEVICEINITALLOWSELFIOTARGET)(
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_ PWDFDEVICE_INIT DeviceInit);

typedef NTSTATUS
(NTAPI *PFN_WDFIOTARGETSELFASSIGNDEFAULTIOQUEUE)(
    _In_ PWDF_DRIVER_GLOBALS DriverGlobals,
    _In_ WDFIOTARGET IoTarget,
    _In_ WDFQUEUE Queue);

/* Class Extension support */
typedef NTSTATUS (NTAPI *PFN_WDF_CLASS_EXTENSIONIN_BIND)(
    _In_ PWDF_CLASS_BIND_INFO ClassBindInfo,
    _In_ PWDF_COMPONENT_GLOBALS ComponentGlobals);

typedef VOID (NTAPI *PFN_WDF_CLASS_EXTENSIONIN_UNBIND)(
    _In_ PWDF_CLASS_BIND_INFO ClassBindInfo,
    _In_ PWDF_COMPONENT_GLOBALS ComponentGlobals);

typedef PVOID (NTAPI *PFN_WDF_CLASS_EXPORT)(VOID);

typedef NTSTATUS (NTAPI *PFN_WDF_CLASS_LIBRARY_INITIALIZE)(VOID);

typedef VOID (NTAPI *PFN_WDF_CLASS_LIBRARY_DEINITIALIZE)(VOID);

typedef NTSTATUS (NTAPI *PFN_WDF_CLASS_LIBRARY_BIND_CLIENT)(
    _In_ PWDF_CLASS_BIND_INFO ClassBindInfo,
    _Inout_ PWDF_COMPONENT_GLOBALS* ClientGlobals);

typedef VOID (NTAPI *PFN_WDF_CLASS_LIBRARY_UNBIND_CLIENT)(
    _In_ PWDF_CLASS_BIND_INFO ClassBindInfo,
    _Inout_ PWDF_COMPONENT_GLOBALS* ClientGlobals);

typedef NTSTATUS (NTAPI *PFN_WDF_CLIENT_BIND_CLASS)(
    _In_ PWDF_CLASS_BIND_INFO ClassBindInfo,
    _In_ PWDF_COMPONENT_GLOBALS ComponentGlobals);

typedef VOID (NTAPI *PFN_WDF_CLIENT_UNBIND_CLASS)(
    _In_ PWDF_CLASS_BIND_INFO ClassBindInfo,
    _In_ PWDF_COMPONENT_GLOBALS ComponentGlobals);

#endif // _WDFCX_H_
