@ stdcall Wow64LdrpLoadWow64Win()
@ stdcall Wow64NtUserCloseDesktop(long)
@ stdcall Wow64NtUserCreateDesktop(long long long long long)
@ stdcall Wow64NtUserCreateWindowEx(long long long long long long long long long long long long)
@ stdcall Wow64NtUserDestroyWindow(long)
@ stdcall Wow64NtUserDispatchMessage(long)
@ stdcall Wow64NtUserGetMessage(long long long long)
@ stdcall Wow64NtUserMsgWaitForMultipleObjectsEx(long long long long long)
@ stdcall Wow64NtUserOpenDesktop(long long long)
@ stdcall Wow64NtUserOpenWindowStation(long long long)
@ stdcall Wow64NtUserPeekMessage(long long long long long)
@ stdcall Wow64NtUserSetThreadDesktop(long)
@ stdcall Wow64NtUserShowWindow(long long)
@ stdcall Wow64NtUserWaitMessage()
