/*
 * ReactOS UEFIFB shared ioctl definitions
 */

#pragma once

#include <devioctl.h>

#define IOCTL_VIDEO_UEFIFB_QUERY_CAPS \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x910, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_UEFIFB_SELECT_CHILD \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x911, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_UEFIFB_QUERY_CHILD_MODES \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x912, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define UEFIFB_CAPS_VERSION      2

#define UEFIFB_CAP_LINEAR_ONLY   0x00000001
#define UEFIFB_CAP_LARGE_FB      0x00000002
#define UEFIFB_CAP_MULTI_OUTPUT  0x00000004

typedef struct _UEFIFB_SELECT_CHILD
{
    ULONG ChildIndex;
} UEFIFB_SELECT_CHILD, *PUEFIFB_SELECT_CHILD;

typedef struct _UEFIFB_CHILD_MODE_RESPONSE
{
    ULONG ChildIndex;
    ULONG ModeCount;
    ULONG ReturnedModes;
    VIDEO_MODE_INFORMATION Modes[ANYSIZE_ARRAY];
} UEFIFB_CHILD_MODE_RESPONSE, *PUEFIFB_CHILD_MODE_RESPONSE;

typedef struct _UEFIFB_CAPS
{
    ULONG Version;
    ULONG Caps;
    ULONG OutputCount;
    ULONG PrimaryChild;
    ULONGLONG FrameBufferLength;
} UEFIFB_CAPS, *PUEFIFB_CAPS;
