/*
 * PROJECT:     ReactOS Storport Driver
 * LICENSE:     GPL-2.0+ (https://spdx.org/licenses/GPL-2.0+)
 * PURPOSE:     Storport PDO code
 * COPYRIGHT:   Copyright 2017 Eric Kohl (eric.kohl@reactos.org)
 */

/* INCLUDES *******************************************************************/

#include "precomp.h"

#define NDEBUG
#include <debug.h>


/* FUNCTIONS ******************************************************************/

NTSTATUS
PortCreatePdo(
    _In_ PFDO_DEVICE_EXTENSION FdoDeviceExtension,
    _In_ ULONG Bus,
    _In_ ULONG Target,
    _In_ ULONG Lun,
    _Out_ PPDO_DEVICE_EXTENSION *PdoDeviceExtension)
{
    PPDO_DEVICE_EXTENSION DeviceExtension = NULL;
    PDEVICE_OBJECT Pdo = NULL;
    KLOCK_QUEUE_HANDLE LockHandle;
    NTSTATUS Status;

    DPRINT("PortCreatePdo(%p %p)\n",
           FdoDeviceExtension, PdoDeviceExtension);

    /* Create the port device */
    Status = IoCreateDevice(FdoDeviceExtension->Device->DriverObject,
                            sizeof(PDO_DEVICE_EXTENSION),
                            NULL,
                            FILE_DEVICE_MASS_STORAGE,
                            FILE_DEVICE_SECURE_OPEN | FILE_AUTOGENERATED_DEVICE_NAME,
                            FALSE,
                            &Pdo);
    if (!NT_SUCCESS(Status))
    {
        DPRINT1("IoCreateDevice() failed (Status 0x%lX)\n", Status);
        return Status;
    }

    /* Initialize the device */
    Pdo->Flags |= DO_DIRECT_IO;
    Pdo->Flags |= DO_POWER_PAGABLE;
    if (FdoDeviceExtension->Miniport.PortConfig.AlignmentMask > Pdo->AlignmentRequirement)
        Pdo->AlignmentRequirement = FdoDeviceExtension->Miniport.PortConfig.AlignmentMask;

    DeviceExtension = (PPDO_DEVICE_EXTENSION)Pdo->DeviceExtension;
    RtlZeroMemory(DeviceExtension, sizeof(PDO_DEVICE_EXTENSION));

    DeviceExtension->ExtensionType = PdoExtension;

    DeviceExtension->Device = Pdo;
    DeviceExtension->FdoExtension = FdoDeviceExtension;
    DeviceExtension->PnpState = dsStopped;
    DeviceExtension->Bus = Bus;
    DeviceExtension->Target = Target;
    DeviceExtension->Lun = Lun;
    DeviceExtension->QueueDepth = 1;

    /* Add the PDO to the PDO list*/
    KeAcquireInStackQueuedSpinLock(&FdoDeviceExtension->PdoListLock,
                                   &LockHandle);
    InsertHeadList(&FdoDeviceExtension->PdoListHead,
                   &DeviceExtension->PdoListEntry);
    FdoDeviceExtension->PdoCount++;
    KeReleaseInStackQueuedSpinLock(&LockHandle);

    // FIXME: More initialization


    /* The device has been initialized */
    Pdo->Flags &= ~DO_DEVICE_INITIALIZING;

    *PdoDeviceExtension = DeviceExtension;

    return STATUS_SUCCESS;
}


NTSTATUS
PortDeletePdo(
    _In_ PPDO_DEVICE_EXTENSION PdoExtension)
{
    KLOCK_QUEUE_HANDLE LockHandle;

    DPRINT("PortDeletePdo(%p)\n", PdoExtension);

    /* Remove the PDO from the PDO list*/
    KeAcquireInStackQueuedSpinLock(&PdoExtension->FdoExtension->PdoListLock,
                                   &LockHandle);
    RemoveEntryList(&PdoExtension->PdoListEntry);
    PdoExtension->FdoExtension->PdoCount--;
    KeReleaseInStackQueuedSpinLock(&LockHandle);

    if (PdoExtension->InquiryBuffer)
    {
        ExFreePoolWithTag(PdoExtension->InquiryBuffer, TAG_INQUIRY_DATA);
        PdoExtension->InquiryBuffer = NULL;
    }

    PortFreeDumpContext(PdoExtension->DumpContext);
    PdoExtension->DumpContext = NULL;

    // FIXME: More uninitialization


    /* Delete the PDO */
    IoDeleteDevice(PdoExtension->Device);

    return STATUS_SUCCESS;
}


/*
 * Build a scatter gather list describing the request buffer.
 *
 * The miniport is a bus master and asks for the list through
 * StorPortGetScatterGatherList(), so the physical layout has to be derived
 * from the MDL the I/O manager built for the transfer. Physically adjacent
 * pages are coalesced so the list stays short.
 */
typedef struct _PORT_SRBEX_REQUEST
{
    STORAGE_REQUEST_BLOCK Srb;
    STOR_ADDR_BTL8 Address;
    SRBEX_DATA_SCSI_CDB16 Scsi;
} PORT_SRBEX_REQUEST, *PPORT_SRBEX_REQUEST;

NTSTATUS PortFdoInitializeRequestPools(_In_ PFDO_DEVICE_EXTENSION FdoExtension)
{
    ULONG MaximumPages, Size, Count, Index;
    PHYSICAL_ADDRESS Address;

    if (FdoExtension->RequestPoolsReady)
        return STATUS_SUCCESS;

    /* Common buffers must be allocated at PASSIVE_LEVEL. Reserve the
     * device-visible request extensions here, before paging/interrupt I/O. */
    InitializeSListHead(&FdoExtension->FreeSrbExtensions);
    Size = FdoExtension->Miniport.PortConfig.SrbExtensionSize;
    if (Size)
    {
        if (Size > MAXULONG - (PAGE_SIZE - 1))
            return STATUS_INVALID_PARAMETER;
        Size = ROUND_TO_PAGES(Size);
        Count = FdoExtension->Miniport.PortConfig.MaxNumberOfIO;
        if (!Count || Count == SP_UNINITIALIZED_VALUE)
            Count = 256;
        if (Count > MAXULONG / Size)
            return STATUS_INVALID_PARAMETER;
        FdoExtension->SrbExtensionPool = PortAllocateDmaBuffer(
            FdoExtension, Count * Size, FALSE, &Address);
        if (!FdoExtension->SrbExtensionPool)
            return STATUS_INSUFFICIENT_RESOURCES;
        for (Index = 0; Index < Count; Index++)
            InterlockedPushEntrySList(&FdoExtension->FreeSrbExtensions,
                (PSLIST_ENTRY)((PUCHAR)FdoExtension->SrbExtensionPool + Index * Size));
    }

    MaximumPages = FdoExtension->Miniport.PortConfig.NumberOfPhysicalBreaks + 2;
    FdoExtension->SglLookasideSize = FIELD_OFFSET(STOR_SCATTER_GATHER_LIST, List) + MaximumPages * sizeof(STOR_SCATTER_GATHER_ELEMENT);

    ExInitializeNPagedLookasideList(&FdoExtension->SrbContextLookaside, NULL, NULL, 0, sizeof(STOR_SRB_CONTEXT), TAG_SRB_CONTEXT, 0);
    ExInitializeNPagedLookasideList(&FdoExtension->MiniportSrbLookaside, NULL, NULL, 0, sizeof(PORT_SRBEX_REQUEST), TAG_SRB_CONTEXT, 0);
    ExInitializeNPagedLookasideList(&FdoExtension->SglLookaside, NULL, NULL, 0, FdoExtension->SglLookasideSize, TAG_SGL, 0);
    FdoExtension->RequestPoolsReady = TRUE;
    return STATUS_SUCCESS;
}

/* The DMA adapter owns map registers until request completion. Its callback
 * may run synchronously or later, always at DISPATCH_LEVEL. */
static VOID NTAPI
PortDmaListControl(PDEVICE_OBJECT DeviceObject, PIRP UnusedIrp,
                   PSCATTER_GATHER_LIST DmaList, PVOID Context)
{
    PIRP Irp = Context;
    PSTOR_SRB_CONTEXT Request = PortGetSrbContext(Irp);
    PFDO_DEVICE_EXTENSION Fdo = Request->FdoExtension;
    PVOID Srb = Request->MiniportSrb ? (PVOID)Request->MiniportSrb : Request->LegacySrb;
    ULONG Size, Index;

    UNREFERENCED_PARAMETER(DeviceObject);
    UNREFERENCED_PARAMETER(UnusedIrp);
    Request->DmaList = DmaList;
    if (DmaList->NumberOfElements >
        (MAXULONG - FIELD_OFFSET(STOR_SCATTER_GATHER_LIST, List)) /
        sizeof(STOR_SCATTER_GATHER_ELEMENT))
        goto Fail;
    Size = FIELD_OFFSET(STOR_SCATTER_GATHER_LIST, List) +
           DmaList->NumberOfElements * sizeof(STOR_SCATTER_GATHER_ELEMENT);
    if (Fdo->RequestPoolsReady && Size <= Fdo->SglLookasideSize)
    {
        Size = Fdo->SglLookasideSize;
        Request->Sgl = ExAllocateFromNPagedLookasideList(&Fdo->SglLookaside);
    }
    else
        Request->Sgl = ExAllocatePoolWithTag(NonPagedPool, Size, TAG_SGL);
    if (!Request->Sgl)
        goto Fail;
    Request->SglAllocationSize = Size;
    RtlZeroMemory(Request->Sgl, Size);
    Request->Sgl->NumberOfElements = DmaList->NumberOfElements;
    for (Index = 0; Index < DmaList->NumberOfElements; Index++)
    {
        Request->Sgl->List[Index].PhysicalAddress = DmaList->Elements[Index].Address;
        Request->Sgl->List[Index].Length = DmaList->Elements[Index].Length;
    }
    if (MiniportBuildIo(&Fdo->Miniport, Srb))
        MiniportStartIo(&Fdo->Miniport, Srb);
    return;

Fail:
    Request->LegacySrb->SrbStatus = SRB_STATUS_ERROR;
    Request->LegacySrb->SrbExtension = NULL;
    PortFreeSrbContext(Irp);
    Irp->IoStatus.Status = STATUS_INSUFFICIENT_RESOURCES;
    Irp->IoStatus.Information = 0;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);
}


NTSTATUS PortSrbStatusToNtStatus(_In_ UCHAR SrbStatus)
{
    switch (SRB_STATUS(SrbStatus))
    {
        case SRB_STATUS_SUCCESS:
        case SRB_STATUS_DATA_OVERRUN:
            return STATUS_SUCCESS;

        case SRB_STATUS_INVALID_LUN:
        case SRB_STATUS_INVALID_TARGET_ID:
        case SRB_STATUS_NO_DEVICE:
        case SRB_STATUS_NO_HBA:
            return STATUS_DEVICE_DOES_NOT_EXIST;

        case SRB_STATUS_SELECTION_TIMEOUT:
        case SRB_STATUS_COMMAND_TIMEOUT:
        case SRB_STATUS_TIMEOUT:
            return STATUS_IO_TIMEOUT;

        case SRB_STATUS_BAD_FUNCTION:
        case SRB_STATUS_BAD_SRB_BLOCK_LENGTH:
        case SRB_STATUS_INVALID_REQUEST:
            return STATUS_INVALID_DEVICE_REQUEST;

        case SRB_STATUS_INVALID_PATH_ID:
            return STATUS_NO_SUCH_DEVICE;

        case SRB_STATUS_BUSY:
            return STATUS_DEVICE_BUSY;

        default:
            return STATUS_IO_DEVICE_ERROR;
    }
}

static NTSTATUS PortDumpSubmit(_In_ PPORT_DUMP_CONTEXT DumpContext, _In_ UCHAR Function, _In_ ULONG64 DiskByteOffset, _In_ PHYSICAL_ADDRESS Buffer, _In_ ULONG Length)
{
    PFDO_DEVICE_EXTENSION FdoExtension;
    ULONG64 BlockAddress;
    ULONG BlockCount;
    ULONG Timeout;

    FdoExtension = DumpContext->PdoExtension->FdoExtension;
    if ((Function == SRB_FUNCTION_EXECUTE_SCSI) && (((DiskByteOffset | Length) % DumpContext->BytesPerSector) != 0 || (Length == 0) || (Length > PAGE_SIZE)))
    {
        return STATUS_INVALID_PARAMETER;
    }

    RtlZeroMemory(&DumpContext->Srb, sizeof(DumpContext->Srb));
    if (DumpContext->SrbExtension != NULL)
    {
        RtlZeroMemory(DumpContext->SrbExtension, FdoExtension->Miniport.PortConfig.SrbExtensionSize);
    }

    DumpContext->Srb.Length = sizeof(SCSI_REQUEST_BLOCK);
    DumpContext->Srb.Function = Function;
    DumpContext->Srb.PathId = (UCHAR)DumpContext->PdoExtension->Bus;
    DumpContext->Srb.TargetId = (UCHAR)DumpContext->PdoExtension->Target;
    DumpContext->Srb.Lun = (UCHAR)DumpContext->PdoExtension->Lun;
    DumpContext->Srb.SrbExtension = DumpContext->SrbExtension;
    DumpContext->Srb.OriginalRequest = DumpContext->Irp;
    DumpContext->Srb.TimeOutValue = 10;

    if (Function == SRB_FUNCTION_EXECUTE_SCSI)
    {
        DumpContext->Srb.SrbFlags = SRB_FLAGS_DATA_OUT | SRB_FLAGS_DISABLE_SYNCH_TRANSFER | SRB_FLAGS_NO_QUEUE_FREEZE;
        DumpContext->Srb.DataTransferLength = Length;
        /* The dump path cannot allocate map registers. Its page-sized
         * common buffer was mapped during normal device initialization. */
        RtlCopyMemory(DumpContext->DataBuffer, MmGetVirtualForPhysical(Buffer), Length);
        KeMemoryBarrier();
        DumpContext->Srb.DataBuffer = DumpContext->DataBuffer;

        DumpContext->Sgl.NumberOfElements = 1;
        DumpContext->Sgl.List[0].PhysicalAddress = DumpContext->DataAddress;
        DumpContext->Sgl.List[0].Length = Length;

        BlockAddress = DiskByteOffset / DumpContext->BytesPerSector;
        BlockCount = Length / DumpContext->BytesPerSector;
        DumpContext->Srb.CdbLength = RosDumpBuildWriteCdb((PCDB)&DumpContext->Srb.Cdb, BlockAddress, BlockCount);
    }

    DumpContext->Status = STATUS_PENDING;
    InterlockedExchange(&DumpContext->Completed, 0);
    KeMemoryBarrier();

    if (!MiniportStartIo(&FdoExtension->Miniport, &DumpContext->Srb))
        return STATUS_DEVICE_BUSY;

    for (Timeout = 0; Timeout < ROS_DUMP_POLL_ITERATIONS; Timeout++)
    {
        MiniportHwInterrupt(&FdoExtension->Miniport);
        if (InterlockedCompareExchange(&DumpContext->Completed, 0, 0) != 0)
            return DumpContext->Status;

        KeStallExecutionProcessor(1);
    }

    return STATUS_IO_TIMEOUT;
}

static NTSTATUS NTAPI PortDumpPrepare(_In_ PVOID Context)
{
    PPORT_DUMP_CONTEXT DumpContext = Context;
    PFDO_DEVICE_EXTENSION FdoExtension;

    FdoExtension = DumpContext->PdoExtension->FdoExtension;
    FdoExtension->DumpMode = TRUE;
    KeMemoryBarrier();

    if ((FdoExtension->Miniport.InitData->HwResetBus == NULL) || !FdoExtension->Miniport.InitData->HwResetBus(&FdoExtension->Miniport.MiniportExtension->HwDeviceExtension, DumpContext->PdoExtension->Bus))
    {
        return STATUS_IO_DEVICE_ERROR;
    }

    return STATUS_SUCCESS;
}

static NTSTATUS NTAPI PortDumpWrite(_In_ PVOID Context, _In_ ULONG64 DiskByteOffset, _In_ PHYSICAL_ADDRESS Buffer, _In_ ULONG Length)
{
    return PortDumpSubmit(Context, SRB_FUNCTION_EXECUTE_SCSI, DiskByteOffset, Buffer, Length);
}

static NTSTATUS NTAPI PortDumpFlush(_In_ PVOID Context)
{
    PHYSICAL_ADDRESS Buffer = {{0}};

    return PortDumpSubmit(Context, SRB_FUNCTION_FLUSH, 0, Buffer, 0);
}

VOID PortFreeDumpContext(_In_opt_ PPORT_DUMP_CONTEXT DumpContext)
{
    if (DumpContext == NULL)
        return;

    if (DumpContext->Irp != NULL)
        IoFreeIrp(DumpContext->Irp);
    if (DumpContext->SrbExtension != NULL)
        PortFreeDmaBuffer(DumpContext->PdoExtension->FdoExtension, DumpContext->SrbExtension);
    if (DumpContext->DataBuffer != NULL)
        PortFreeDmaBuffer(DumpContext->PdoExtension->FdoExtension, DumpContext->DataBuffer);

    ExFreePoolWithTag(DumpContext, TAG_DUMP_CONTEXT);
}

NTSTATUS PortGetDumpInterface(_In_ PPDO_DEVICE_EXTENSION PdoExtension, _Out_ PROS_STORAGE_DUMP_INTERFACE Interface)
{
    PFDO_DEVICE_EXTENSION FdoExtension;
    PPORT_DUMP_CONTEXT DumpContext;
    PHYSICAL_ADDRESS LogicalAddress;
    ULONG SrbExtensionSize;
    ULONG BytesPerSector;

    FdoExtension = PdoExtension->FdoExtension;
    BytesPerSector = Interface->BytesPerSector;
    if (!RosDumpIsValidSectorSize(BytesPerSector))
        return STATUS_INVALID_PARAMETER;

    DumpContext = PdoExtension->DumpContext;
    if (DumpContext == NULL)
    {
        DumpContext = ExAllocatePoolWithTag(NonPagedPool, sizeof(*DumpContext), TAG_DUMP_CONTEXT);
        if (DumpContext == NULL)
            return STATUS_INSUFFICIENT_RESOURCES;

        RtlZeroMemory(DumpContext, sizeof(*DumpContext));
        DumpContext->PdoExtension = PdoExtension;
        DumpContext->BytesPerSector = BytesPerSector;

        DumpContext->Irp = IoAllocateIrp(1, FALSE);
        if (DumpContext->Irp == NULL)
            goto Failure;

        SrbExtensionSize = FdoExtension->Miniport.PortConfig.SrbExtensionSize;
        if (SrbExtensionSize != 0)
        {
            DumpContext->SrbExtension = PortAllocateDmaBuffer(
                FdoExtension, SrbExtensionSize, FALSE, &LogicalAddress);
            if (DumpContext->SrbExtension == NULL)
                goto Failure;
        }

        DumpContext->DataBuffer = PortAllocateDmaBuffer(
            FdoExtension, PAGE_SIZE, FALSE, &DumpContext->DataAddress);
        if (!DumpContext->DataBuffer)
            goto Failure;

        DumpContext->SrbContext.SrbExtensionAllocation = DumpContext->SrbExtension;
        DumpContext->SrbContext.Sgl = (PSTOR_SCATTER_GATHER_LIST)&DumpContext->Sgl;
        DumpContext->SrbContext.SglAllocationSize = sizeof(DumpContext->Sgl);
        DumpContext->SrbContext.SrbExtensionSize = SrbExtensionSize;
        DumpContext->Irp->Tail.Overlay.DriverContext[0] = &DumpContext->SrbContext;
        DumpContext->Irp->Tail.Overlay.DriverContext[2] = DumpContext;
        DumpContext->Irp->Tail.Overlay.DriverContext[3] = PORT_DUMP_IRP_MARKER;

        PdoExtension->DumpContext = DumpContext;
    }
    else if (DumpContext->BytesPerSector != BytesPerSector)
    {
        return STATUS_INVALID_DEVICE_STATE;
    }

    RtlZeroMemory(Interface, sizeof(*Interface));
    Interface->Version = ROS_STORAGE_DUMP_INTERFACE_VERSION;
    Interface->Size = sizeof(*Interface);
    Interface->Context = DumpContext;
    Interface->BytesPerSector = DumpContext->BytesPerSector;
    Interface->MaximumTransferLength = PAGE_SIZE;
    Interface->Prepare = PortDumpPrepare;
    Interface->WriteRoutine = PortDumpWrite;
    Interface->Flush = PortDumpFlush;
    return STATUS_SUCCESS;

Failure:
    PortFreeDumpContext(DumpContext);
    return STATUS_INSUFFICIENT_RESOURCES;
}

C_ASSERT(FIELD_OFFSET(STORAGE_REQUEST_BLOCK, Signature) == 8);
#if defined(_WIN64)
C_ASSERT(FIELD_OFFSET(STORAGE_REQUEST_BLOCK, SrbExDataOffset) == 120);
C_ASSERT(sizeof(STORAGE_REQUEST_BLOCK) == 128);
C_ASSERT(sizeof(STOR_ADDR_BTL8) == 16);
C_ASSERT(sizeof(SRBEX_DATA_SCSI_CDB16) == 40);
C_ASSERT(FIELD_OFFSET(PORT_SRBEX_REQUEST, Address) == 128);
C_ASSERT(FIELD_OFFSET(PORT_SRBEX_REQUEST, Scsi) == 144);
#else
C_ASSERT(FIELD_OFFSET(STORAGE_REQUEST_BLOCK, SrbExDataOffset) == 92);
C_ASSERT(sizeof(STORAGE_REQUEST_BLOCK) == 96);
C_ASSERT(sizeof(STOR_ADDR_BTL8) == 12);
C_ASSERT(sizeof(SRBEX_DATA_SCSI_CDB16) == 36);
C_ASSERT(FIELD_OFFSET(PORT_SRBEX_REQUEST, Address) == 96);
C_ASSERT(FIELD_OFFSET(PORT_SRBEX_REQUEST, Scsi) == 108);
#endif

static NTSTATUS PortBuildExtendedSrb(_In_ PFDO_DEVICE_EXTENSION FdoExtension, _In_ PSCSI_REQUEST_BLOCK LegacySrb, _Inout_ PSTOR_SRB_CONTEXT SrbContext)
{
    PPORT_SRBEX_REQUEST Request;

    if (LegacySrb->Function == SRB_FUNCTION_EXECUTE_SCSI && LegacySrb->CdbLength > sizeof(Request->Scsi.Cdb))
        return STATUS_INVALID_PARAMETER;

    if (FdoExtension->RequestPoolsReady)
        Request = ExAllocateFromNPagedLookasideList(&FdoExtension->MiniportSrbLookaside);
    else
        Request = ExAllocatePoolWithTag(NonPagedPool, sizeof(*Request), TAG_SRB_CONTEXT);
    if (Request == NULL)
        return STATUS_INSUFFICIENT_RESOURCES;

    RtlZeroMemory(Request, sizeof(*Request));
    Request->Srb.Length = FIELD_OFFSET(STORAGE_REQUEST_BLOCK, Signature);
    Request->Srb.Function = SRB_FUNCTION_STORAGE_REQUEST_BLOCK;
    Request->Srb.SrbStatus = LegacySrb->SrbStatus;
    Request->Srb.Signature = SRB_SIGNATURE;
    Request->Srb.Version = STORAGE_REQUEST_BLOCK_VERSION_1;
    Request->Srb.SrbFunction = LegacySrb->Function;
    Request->Srb.SrbFlags = LegacySrb->SrbFlags;
    Request->Srb.RequestTag = LegacySrb->QueueTag;
    Request->Srb.RequestAttribute = LegacySrb->QueueAction;
    Request->Srb.TimeOutValue = LegacySrb->TimeOutValue;
    Request->Srb.AddressOffset = FIELD_OFFSET(PORT_SRBEX_REQUEST, Address);
    Request->Srb.DataTransferLength = LegacySrb->DataTransferLength;
    Request->Srb.DataBuffer = LegacySrb->DataBuffer;
    Request->Srb.OriginalRequest = LegacySrb->OriginalRequest;
    Request->Srb.PortContext = SrbContext;
    Request->Srb.MiniportContext = SrbContext->SrbExtensionAllocation;

    Request->Address.Type = STOR_ADDRESS_TYPE_BTL8;
    Request->Address.Port = (USHORT)FdoExtension->PortNumber;
    Request->Address.AddressLength = STOR_ADDR_BTL8_ADDRESS_LENGTH;
    Request->Address.Path = LegacySrb->PathId;
    Request->Address.Target = LegacySrb->TargetId;
    Request->Address.Lun = LegacySrb->Lun;

    if (LegacySrb->Function == SRB_FUNCTION_EXECUTE_SCSI)
    {
        Request->Srb.NumSrbExData = 1;
        Request->Srb.SrbExDataOffset[0] = FIELD_OFFSET(PORT_SRBEX_REQUEST, Scsi);
        Request->Srb.SrbLength = sizeof(*Request);
        Request->Scsi.Type = SrbExDataTypeScsiCdb16;
        Request->Scsi.Length = SRBEX_DATA_SCSI_CDB16_LENGTH;
        Request->Scsi.ScsiStatus = LegacySrb->ScsiStatus;
        Request->Scsi.SenseInfoBufferLength = LegacySrb->SenseInfoBufferLength;
        Request->Scsi.CdbLength = LegacySrb->CdbLength;
        Request->Scsi.SenseInfoBuffer = LegacySrb->SenseInfoBuffer;
        RtlCopyMemory(Request->Scsi.Cdb, LegacySrb->Cdb, LegacySrb->CdbLength);
    }
    else
    {
        Request->Srb.SrbLength = FIELD_OFFSET(PORT_SRBEX_REQUEST, Scsi);
    }

    SrbContext->MiniportSrb = &Request->Srb;
    return STATUS_SUCCESS;
}

VOID PortFreeSrbContext(_In_ PIRP Irp)
{
    PSTOR_SRB_CONTEXT SrbContext;
    PFDO_DEVICE_EXTENSION FdoExtension;
    BOOLEAN Pooled;

    SrbContext = PortGetSrbContext(Irp);
    if (SrbContext == NULL)
        return;

    FdoExtension = SrbContext->FdoExtension;
    Pooled = FdoExtension != NULL && FdoExtension->RequestPoolsReady;

    if (SrbContext->DmaList)
    {
        KIRQL OldIrql;
        KeRaiseIrql(DISPATCH_LEVEL, &OldIrql);
        FdoExtension->DmaAdapter->DmaOperations->PutScatterGatherList(
            FdoExtension->DmaAdapter, SrbContext->DmaList, SrbContext->WriteToDevice);
        KeLowerIrql(OldIrql);
    }

    if (SrbContext->Sgl != NULL)
    {
        if (Pooled && SrbContext->SglAllocationSize == FdoExtension->SglLookasideSize)
            ExFreeToNPagedLookasideList(&FdoExtension->SglLookaside, SrbContext->Sgl);
        else
            ExFreePoolWithTag(SrbContext->Sgl, TAG_SGL);
    }

    if (SrbContext->SrbExtensionAllocation != NULL)
    {
        InterlockedPushEntrySList(&FdoExtension->FreeSrbExtensions,
                                 SrbContext->SrbExtensionAllocation);
    }

    if (SrbContext->MiniportSrb != NULL)
    {
        if (Pooled)
            ExFreeToNPagedLookasideList(&FdoExtension->MiniportSrbLookaside, CONTAINING_RECORD(SrbContext->MiniportSrb, PORT_SRBEX_REQUEST, Srb));
        else
            ExFreePoolWithTag(SrbContext->MiniportSrb, TAG_SRB_CONTEXT);
    }

    if (Pooled)
        ExFreeToNPagedLookasideList(&FdoExtension->SrbContextLookaside, SrbContext);
    else
        ExFreePoolWithTag(SrbContext, TAG_SRB_CONTEXT);

    Irp->Tail.Overlay.DriverContext[0] = NULL;
}


NTSTATUS
NTAPI
PortPdoScsi(
    _In_ PDEVICE_OBJECT DeviceObject,
    _In_ PIRP Irp)
{
    PPDO_DEVICE_EXTENSION PdoExtension;
    PFDO_DEVICE_EXTENSION FdoExtension;
    PIO_STACK_LOCATION Stack;
    PSTOR_SRB_CONTEXT SrbContext;
    PSCSI_REQUEST_BLOCK Srb;
    PVOID MiniportSrb;
    ULONG SrbExtensionSize;
    NTSTATUS Status;
    KIRQL Irql;
    BOOLEAN Pending = FALSE;
    KLOCK_QUEUE_HANDLE LockHandle;

    DPRINT("PortPdoScsi(%p %p)\n", DeviceObject, Irp);

    PdoExtension = (PPDO_DEVICE_EXTENSION)DeviceObject->DeviceExtension;
    FdoExtension = PdoExtension->FdoExtension;

    Stack = IoGetCurrentIrpStackLocation(Irp);
    Srb = Stack->Parameters.Scsi.Srb;

    if (Srb == NULL)
    {
        Status = STATUS_INVALID_PARAMETER;
        goto Fail;
    }

    /* Address the request at the logical unit this PDO represents. */
    Srb->PathId = (UCHAR)PdoExtension->Bus;
    Srb->TargetId = (UCHAR)PdoExtension->Target;
    Srb->Lun = (UCHAR)PdoExtension->Lun;
    Srb->OriginalRequest = Irp;
    Srb->SrbStatus = SRB_STATUS_PENDING;

    /*
     * Device claiming is a port-driver operation; it must not be sent to the
     * hardware miniport as if it were an ATA command.
     */
    if ((Srb->Function == SRB_FUNCTION_CLAIM_DEVICE) ||
        (Srb->Function == SRB_FUNCTION_ATTACH_DEVICE) ||
        (Srb->Function == SRB_FUNCTION_RELEASE_DEVICE))
    {
        KeAcquireInStackQueuedSpinLock(&FdoExtension->PdoListLock, &LockHandle);

        if (Srb->Function == SRB_FUNCTION_RELEASE_DEVICE)
        {
            PdoExtension->DeviceClaimed = FALSE;
            Srb->SrbStatus = SRB_STATUS_SUCCESS;
            Status = STATUS_SUCCESS;
        }
        else if (PdoExtension->DeviceClaimed)
        {
            Srb->SrbStatus = SRB_STATUS_BUSY;
            Status = STATUS_DEVICE_BUSY;
        }
        else
        {
            if (Srb->Function == SRB_FUNCTION_CLAIM_DEVICE)
            {
                PdoExtension->DeviceClaimed = TRUE;
            }

            Srb->DataBuffer = DeviceObject;
            Srb->SrbStatus = SRB_STATUS_SUCCESS;
            Status = STATUS_SUCCESS;
        }

        KeReleaseInStackQueuedSpinLock(&LockHandle);

        Irp->IoStatus.Information = 0;
        Irp->IoStatus.Status = Status;
        IoCompleteRequest(Irp, IO_NO_INCREMENT);
        return Status;
    }

    if (FdoExtension->RequestPoolsReady)
        SrbContext = ExAllocateFromNPagedLookasideList(&FdoExtension->SrbContextLookaside);
    else
        SrbContext = ExAllocatePoolWithTag(NonPagedPool, sizeof(STOR_SRB_CONTEXT), TAG_SRB_CONTEXT);
    if (SrbContext == NULL)
    {
        Status = STATUS_INSUFFICIENT_RESOURCES;
        goto Fail;
    }

    RtlZeroMemory(SrbContext, sizeof(STOR_SRB_CONTEXT));
    Irp->Tail.Overlay.DriverContext[0] = SrbContext;
    SrbContext->LegacySrb = Srb;
    SrbContext->FdoExtension = FdoExtension;

    /*
     * The miniport keeps its per-request hardware state (for AHCI, the command
     * table that the controller DMAs from) in the SRB extension, so it must be
     * physically contiguous and its physical address must be resolvable.
     */
    SrbExtensionSize = FdoExtension->Miniport.PortConfig.SrbExtensionSize;
    if (SrbExtensionSize != 0)
    {
        SrbContext->SrbExtensionAllocation =
            InterlockedPopEntrySList(&FdoExtension->FreeSrbExtensions);
        if (SrbContext->SrbExtensionAllocation == NULL)
        {
            Status = STATUS_INSUFFICIENT_RESOURCES;
            goto Fail;
        }

        RtlZeroMemory(SrbContext->SrbExtensionAllocation, SrbExtensionSize);
        SrbContext->SrbExtensionSize = SrbExtensionSize;
        Srb->SrbExtension = SrbContext->SrbExtensionAllocation;
    }

    /* Data-bearing requests need a scatter gather list for the bus master. */
    if ((Srb->DataTransferLength != 0) && (Irp->MdlAddress != NULL))
    {
        if (Srb->DataTransferLength > MmGetMdlByteCount(Irp->MdlAddress))
        {
            Status = STATUS_INVALID_BUFFER_SIZE;
            goto Fail;
        }

    }

    MiniportSrb = Srb;
    if (FdoExtension->Miniport.PortConfig.SrbType == SRB_TYPE_STORAGE_REQUEST_BLOCK)
    {
        Status = PortBuildExtendedSrb(FdoExtension, Srb, SrbContext);
        if (!NT_SUCCESS(Status))
            goto Fail;
        MiniportSrb = SrbContext->MiniportSrb;
    }

    /*
     * Hand the request to the miniport. HwStartIo is contractually called at
     * DISPATCH_LEVEL, and it completes the request asynchronously through
     * StorPortNotification(RequestComplete), which completes this IRP.
     */
    IoMarkIrpPending(Irp);
    Pending = TRUE;

    if (Srb->DataTransferLength && Irp->MdlAddress)
    {
        PDMA_ADAPTER Adapter = FdoExtension->DmaAdapter;
        if (Adapter->DmaOperations->Size <
                FIELD_OFFSET(DMA_OPERATIONS, CalculateScatterGatherList) ||
            !Adapter->DmaOperations->GetScatterGatherList ||
            !Adapter->DmaOperations->PutScatterGatherList)
        {
            Status = STATUS_NOT_SUPPORTED;
            goto Fail;
        }
        SrbContext->WriteToDevice = !!(Srb->SrbFlags & SRB_FLAGS_DATA_OUT);
        KeRaiseIrql(DISPATCH_LEVEL, &Irql);
        Status = Adapter->DmaOperations->GetScatterGatherList(Adapter, DeviceObject,
            Irp->MdlAddress, MmGetMdlVirtualAddress(Irp->MdlAddress),
            Srb->DataTransferLength, PortDmaListControl, Irp, SrbContext->WriteToDevice);
        KeLowerIrql(Irql);
        if (!NT_SUCCESS(Status))
            goto Fail;
        return STATUS_PENDING;
    }

    if (!MiniportBuildIo(&FdoExtension->Miniport, MiniportSrb))
        return STATUS_PENDING;

    KeRaiseIrql(DISPATCH_LEVEL, &Irql);
    MiniportStartIo(&FdoExtension->Miniport, MiniportSrb);
    KeLowerIrql(Irql);

    return STATUS_PENDING;

Fail:
    DPRINT1("PortPdoScsi: failing request (0x%08lx)\n", Status);

    if (Srb != NULL)
    {
        Srb->SrbStatus = SRB_STATUS_ERROR;
        Srb->SrbExtension = NULL;
    }

    PortFreeSrbContext(Irp);

    Irp->IoStatus.Information = 0;
    Irp->IoStatus.Status = Status;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);

    return Pending ? STATUS_PENDING : Status;
}


static PCSTR
PortPdoGetDeviceType(
    _In_ PINQUIRYDATA InquiryData)
{
    switch (InquiryData->DeviceType)
    {
        case DIRECT_ACCESS_DEVICE:
            return "Disk";

        case READ_ONLY_DIRECT_ACCESS_DEVICE:
            return "CdRom";

        case SEQUENTIAL_ACCESS_DEVICE:
            return "Sequential";

        case OPTICAL_DEVICE:
            return "Optical";

        default:
            return "Other";
    }
}


static PCSTR
PortPdoGetGenericType(
    _In_ PINQUIRYDATA InquiryData)
{
    switch (InquiryData->DeviceType)
    {
        case DIRECT_ACCESS_DEVICE:
            return "GenDisk";

        case READ_ONLY_DIRECT_ACCESS_DEVICE:
            return "GenCdRom";

        case SEQUENTIAL_ACCESS_DEVICE:
            return "GenSequential";

        case OPTICAL_DEVICE:
            return "GenOptical";

        default:
            return "ScsiOther";
    }
}


static VOID
PortPdoCopyIdField(
    _Out_writes_(Length + 1) PCHAR Destination,
    _In_reads_(Length) PUCHAR Source,
    _In_ ULONG Length)
{
    ULONG Index;
    UCHAR Character;

    for (Index = 0; Index < Length; Index++)
    {
        Character = Source[Index];
        if ((Character <= ' ') || (Character >= 0x7F) || (Character == ','))
        {
            Character = '_';
        }

        Destination[Index] = (CHAR)Character;
    }

    Destination[Length] = ANSI_NULL;
}


static PWSTR
PortPdoAllocateId(
    _In_ PCSTR FirstId,
    _In_opt_ PCSTR SecondId,
    _In_ BOOLEAN MultiString)
{
    ULONG Index, Offset, CharacterCount;
    PWSTR Buffer;

    CharacterCount = strlen(FirstId) + 1;
    if (SecondId != NULL)
    {
        CharacterCount += strlen(SecondId) + 1;
    }
    if (MultiString)
    {
        CharacterCount++;
    }

    Buffer = ExAllocatePoolWithTag(PagedPool,
                                   CharacterCount * sizeof(WCHAR),
                                   TAG_PNP_ID);
    if (Buffer == NULL)
    {
        return NULL;
    }

    Offset = 0;
    for (Index = 0; FirstId[Index] != ANSI_NULL; Index++)
    {
        Buffer[Offset++] = (WCHAR)(UCHAR)FirstId[Index];
    }
    Buffer[Offset++] = UNICODE_NULL;

    if (SecondId != NULL)
    {
        for (Index = 0; SecondId[Index] != ANSI_NULL; Index++)
        {
            Buffer[Offset++] = (WCHAR)(UCHAR)SecondId[Index];
        }
        Buffer[Offset++] = UNICODE_NULL;
    }

    if (MultiString)
    {
        Buffer[Offset++] = UNICODE_NULL;
    }

    NT_ASSERT(Offset == CharacterCount);
    return Buffer;
}


static NTSTATUS
PortPdoQueryId(
    _In_ PPDO_DEVICE_EXTENSION PdoExtension,
    _In_ BUS_QUERY_ID_TYPE IdType,
    _Out_ PULONG_PTR Information)
{
    CHAR DeviceId[128];
    CHAR InstanceId[32];
    CHAR Product[17];
    CHAR Revision[5];
    CHAR Vendor[9];
    PCSTR GenericType;
    PCSTR DeviceType;
    PWSTR Buffer;

    if (PdoExtension->InquiryBuffer == NULL)
    {
        return STATUS_NO_SUCH_DEVICE;
    }

    DeviceType = PortPdoGetDeviceType(PdoExtension->InquiryBuffer);
    GenericType = PortPdoGetGenericType(PdoExtension->InquiryBuffer);

    PortPdoCopyIdField(Vendor,
                       PdoExtension->InquiryBuffer->VendorId,
                       sizeof(PdoExtension->InquiryBuffer->VendorId));
    PortPdoCopyIdField(Product,
                       PdoExtension->InquiryBuffer->ProductId,
                       sizeof(PdoExtension->InquiryBuffer->ProductId));
    PortPdoCopyIdField(Revision,
                       PdoExtension->InquiryBuffer->ProductRevisionLevel,
                       sizeof(PdoExtension->InquiryBuffer->ProductRevisionLevel));

    sprintf(DeviceId,
            "SCSI\\%s&Ven_%s&Prod_%s&Rev_%s",
            DeviceType,
            Vendor,
            Product,
            Revision);

    Buffer = NULL;
    switch (IdType)
    {
        case BusQueryDeviceID:
            Buffer = PortPdoAllocateId(DeviceId, NULL, FALSE);
            break;

        case BusQueryHardwareIDs:
            Buffer = PortPdoAllocateId(DeviceId, GenericType, TRUE);
            break;

        case BusQueryCompatibleIDs:
            Buffer = PortPdoAllocateId(GenericType, NULL, TRUE);
            break;

        case BusQueryInstanceID:
            sprintf(InstanceId,
                    "%lx.%lx.%lx",
                    PdoExtension->Bus,
                    PdoExtension->Target,
                    PdoExtension->Lun);
            Buffer = PortPdoAllocateId(InstanceId, NULL, FALSE);
            break;

        default:
            return STATUS_NOT_SUPPORTED;
    }

    if (Buffer == NULL)
    {
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    *Information = (ULONG_PTR)Buffer;
    return STATUS_SUCCESS;
}


static NTSTATUS
PortPdoQueryTargetRelations(
    _In_ PPDO_DEVICE_EXTENSION PdoExtension,
    _Out_ PULONG_PTR Information)
{
    PDEVICE_RELATIONS Relations;

    Relations = ExAllocatePoolWithTag(PagedPool,
                                      sizeof(DEVICE_RELATIONS),
                                      TAG_DEVICE_RELATION);
    if (Relations == NULL)
    {
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    Relations->Count = 1;
    Relations->Objects[0] = PdoExtension->Device;
    ObReferenceObject(PdoExtension->Device);

    *Information = (ULONG_PTR)Relations;
    return STATUS_SUCCESS;
}


NTSTATUS
NTAPI
PortPdoPnp(
    _In_ PDEVICE_OBJECT DeviceObject,
    _In_ PIRP Irp)
{
    NTSTATUS Status;
    ULONG_PTR Information;
    PIO_STACK_LOCATION Stack;
    PPDO_DEVICE_EXTENSION PdoExtension;

    DPRINT("PortPdoPnp(%p %p)\n", DeviceObject, Irp);

    PdoExtension = (PPDO_DEVICE_EXTENSION)DeviceObject->DeviceExtension;
    Stack = IoGetCurrentIrpStackLocation(Irp);
    Status = Irp->IoStatus.Status;
    Information = Irp->IoStatus.Information;

    switch (Stack->MinorFunction)
    {
        case IRP_MN_START_DEVICE:
            PdoExtension->PnpState = dsStarted;
            Status = STATUS_SUCCESS;
            break;

        case IRP_MN_STOP_DEVICE:
            PdoExtension->PnpState = dsStopped;
            Status = STATUS_SUCCESS;
            break;

        case IRP_MN_QUERY_STOP_DEVICE:
        case IRP_MN_CANCEL_STOP_DEVICE:
        case IRP_MN_QUERY_REMOVE_DEVICE:
        case IRP_MN_CANCEL_REMOVE_DEVICE:
            Status = STATUS_SUCCESS;
            break;

        case IRP_MN_SURPRISE_REMOVAL:
            PdoExtension->PnpState = dsSurpriseRemoved;
            Status = STATUS_SUCCESS;
            break;

        case IRP_MN_REMOVE_DEVICE:
            PdoExtension->PnpState = dsRemoved;
            Status = STATUS_SUCCESS;
            break;

        case IRP_MN_QUERY_ID:
            Information = 0;
            Status = PortPdoQueryId(PdoExtension,
                                    Stack->Parameters.QueryId.IdType,
                                    &Information);
            break;

        case IRP_MN_QUERY_DEVICE_RELATIONS:
            if (Stack->Parameters.QueryDeviceRelations.Type == TargetDeviceRelation)
            {
                Information = 0;
                Status = PortPdoQueryTargetRelations(PdoExtension,
                                                     &Information);
            }
            break;

        case IRP_MN_QUERY_CAPABILITIES:
            if (Stack->Parameters.DeviceCapabilities.Capabilities != NULL)
            {
                PDEVICE_CAPABILITIES Capabilities;

                Capabilities = Stack->Parameters.DeviceCapabilities.Capabilities;
                Capabilities->Removable = PdoExtension->InquiryBuffer->RemovableMedia;
                Capabilities->SurpriseRemovalOK = FALSE;
                Capabilities->UniqueID = FALSE;
                Capabilities->Address = PdoExtension->Target;
                Capabilities->UINumber = PdoExtension->Target;
                Status = STATUS_SUCCESS;
            }
            else
            {
                Status = STATUS_INVALID_PARAMETER;
            }
            break;

        case IRP_MN_QUERY_RESOURCES:
        case IRP_MN_QUERY_RESOURCE_REQUIREMENTS:
            Information = 0;
            Status = STATUS_SUCCESS;
            break;

        default:
            break;
    }

    Irp->IoStatus.Information = Information;
    Irp->IoStatus.Status = Status;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    return Status;
}

/* EOF */
