/*
 * PROJECT:     ReactOS Storport Driver
 * LICENSE:     GPL-2.0+ (https://spdx.org/licenses/GPL-2.0+)
 * PURPOSE:     Storport PDO code
 * COPYRIGHT:   Copyright 2017 Eric Kohl (eric.kohl@reactos.org)
 */

/* INCLUDES *******************************************************************/

#include "precomp.h"

#define NDEBUG
#include <debug.h>

#ifndef ALIGN_UP_BY
#define ALIGN_UP_BY(length, alignment) (((length) + ((alignment) - 1)) & ~((alignment) - 1))
#endif

#define SRB_EXTENSION_ALIGNMENT 128

#ifndef SERVICE_ACTION_READ_CAPACITY16
#define SERVICE_ACTION_READ_CAPACITY16 0x10
#endif


/* FUNCTIONS ******************************************************************/

static
VOID
PortDestroyPdo(
    _In_ PPDO_DEVICE_EXTENSION PdoExtension);

VOID
PortpUpdateCapacityFromSrb(
    _Inout_ PPDO_DEVICE_EXTENSION DeviceExtension,
    _In_ PSCSI_REQUEST_BLOCK Srb)
{
    UCHAR opcode;
    ULONG blockLength;
    ULONGLONG lastBlock;

    if (DeviceExtension == NULL || Srb == NULL)
        return;

    if (SRB_STATUS(Srb->SrbStatus) != SRB_STATUS_SUCCESS)
        return;

    if (Srb->Function != SRB_FUNCTION_EXECUTE_SCSI)
        return;

    if (Srb->CdbLength == 0)
        return;

    if (Srb->DataBuffer == NULL)
        return;

    opcode = Srb->Cdb[0];

    if (opcode == SCSIOP_READ_CAPACITY)
    {
        ULONG temp32;

        if (Srb->DataTransferLength < sizeof(READ_CAPACITY_DATA))
            return;

        RtlCopyMemory(&temp32, Srb->DataBuffer, sizeof(temp32));
        if (RtlUlongByteSwap(temp32) == 0xFFFFFFFF)
        {
            /* Expect a READ CAPACITY(16) to follow */
            return;
        }

        RtlCopyMemory(&temp32, (PUCHAR)Srb->DataBuffer + 4, sizeof(temp32));
        blockLength = RtlUlongByteSwap(temp32);
        if (blockLength == 0)
            blockLength = 512;

        RtlCopyMemory(&temp32, Srb->DataBuffer, sizeof(temp32));
        lastBlock = RtlUlongByteSwap(temp32);

        DeviceExtension->BytesPerBlock = blockLength;
        DeviceExtension->LastBlockAddress = lastBlock;
        DeviceExtension->DiskSize = ((ULONGLONG)lastBlock + 1ULL) * (ULONGLONG)blockLength;
        DeviceExtension->CapacityValid = TRUE;
    }
    else if (opcode == SCSIOP_READ_CAPACITY16)
    {
        UCHAR serviceAction;
        ULONGLONG temp64;
        ULONG temp32;

        if (Srb->CdbLength < 16 || Srb->DataTransferLength < 12)
            return;

        serviceAction = Srb->Cdb[1] & 0x1F;
        if (serviceAction != SERVICE_ACTION_READ_CAPACITY16)
            return;

        RtlCopyMemory(&temp64, Srb->DataBuffer, sizeof(temp64));
        lastBlock = RtlUlonglongByteSwap(temp64);

        RtlCopyMemory(&temp32, (PUCHAR)Srb->DataBuffer + 8, sizeof(temp32));
        blockLength = RtlUlongByteSwap(temp32);
        if (blockLength == 0)
            blockLength = 512;

        DeviceExtension->BytesPerBlock = blockLength;
        DeviceExtension->LastBlockAddress = lastBlock;
        DeviceExtension->DiskSize = ((ULONGLONG)lastBlock + 1ULL) * (ULONGLONG)blockLength;
        DeviceExtension->CapacityValid = TRUE;
    }
}

#if 0
static
const char *
SrbFunctionName(
    _In_ UCHAR Function)
{
    switch (Function)
    {
        case SRB_FUNCTION_EXECUTE_SCSI: return "EXECUTE_SCSI";
        case SRB_FUNCTION_ABORT_COMMAND: return "ABORT_COMMAND";
        case SRB_FUNCTION_RELEASE_QUEUE: return "RELEASE_QUEUE";
        case SRB_FUNCTION_FLUSH_QUEUE: return "FLUSH_QUEUE";
        case SRB_FUNCTION_RESET_BUS: return "RESET_BUS";
        case SRB_FUNCTION_RESET_DEVICE: return "RESET_DEVICE";
        case SRB_FUNCTION_CLAIM_DEVICE: return "CLAIM_DEVICE";
        case SRB_FUNCTION_RELEASE_DEVICE: return "RELEASE_DEVICE";
        case SRB_FUNCTION_SHUTDOWN: return "SHUTDOWN";
        case SRB_FUNCTION_FLUSH: return "FLUSH";
        case SRB_FUNCTION_PNP: return "PNP";
        case SRB_FUNCTION_IO_CONTROL: return "IO_CONTROL";
        case SRB_FUNCTION_DUMP_POINTERS: return "DUMP_POINTERS";
#ifdef SRB_FUNCTION_STORAGE_REQUEST_BLOCK
        case SRB_FUNCTION_STORAGE_REQUEST_BLOCK: return "STORAGE_REQUEST_BLOCK";
#endif
#ifdef SRB_FUNCTION_PATH_INQUIRY
        case SRB_FUNCTION_PATH_INQUIRY: return "PATH_INQUIRY";
#endif
        default: return "UNKNOWN";
    }
}
#endif

NTSTATUS
PortCreatePdo(
    _In_ PFDO_DEVICE_EXTENSION FdoDeviceExtension,
    _In_ ULONG Bus,
    _In_ ULONG Target,
    _In_ ULONG Lun,
    _Out_ PPDO_DEVICE_EXTENSION *PdoDeviceExtension)
{
    PPDO_DEVICE_EXTENSION DeviceExtension = NULL;
    PDEVICE_OBJECT Pdo = NULL;
    KLOCK_QUEUE_HANDLE LockHandle;
    NTSTATUS Status;

    DPRINT("PortCreatePdo(%p %p)\n",
           FdoDeviceExtension, PdoDeviceExtension);

    /* Create the port device */
    Status = IoCreateDevice(FdoDeviceExtension->Device->DriverObject,
                            sizeof(PDO_DEVICE_EXTENSION),
                            NULL,
                            FILE_DEVICE_DISK,
                            FILE_DEVICE_SECURE_OPEN | FILE_AUTOGENERATED_DEVICE_NAME,
                            FALSE,
                            &Pdo);
    if (!NT_SUCCESS(Status))
    {
        DPRINT1("IoCreateDevice() failed (Status 0x%lX)\n", Status);
        return Status;
    }

    /* Initialize the device */
    Pdo->Flags |= DO_DIRECT_IO;
    Pdo->Flags |= DO_POWER_PAGABLE;
    Pdo->Flags |= DO_BUS_ENUMERATED_DEVICE;

    DeviceExtension = (PPDO_DEVICE_EXTENSION)Pdo->DeviceExtension;
    RtlZeroMemory(DeviceExtension, sizeof(PDO_DEVICE_EXTENSION));

    DeviceExtension->ExtensionType = PdoExtension;

    DeviceExtension->Device = Pdo;
    DeviceExtension->FdoExtension = FdoDeviceExtension;
    DeviceExtension->PnpState = dsStopped;
    DeviceExtension->Present = FALSE;

    /* Add the PDO to the PDO list*/
    KeAcquireInStackQueuedSpinLock(&FdoDeviceExtension->PdoListLock,
                                   &LockHandle);
    InsertHeadList(&FdoDeviceExtension->PdoListHead,
                   &DeviceExtension->PdoListEntry);
    FdoDeviceExtension->PdoCount++;
    KeReleaseInStackQueuedSpinLock(&LockHandle);

    DeviceExtension->Bus = Bus;
    DeviceExtension->Target = Target;
    DeviceExtension->Lun = Lun;


    // FIXME: More initialization


    /* The device has been initialized */
    Pdo->Flags &= ~DO_DEVICE_INITIALIZING;

    *PdoDeviceExtension = DeviceExtension;

    return STATUS_SUCCESS;
}


NTSTATUS
PortDeletePdo(
    _In_ PPDO_DEVICE_EXTENSION PdoExtension)
{
    DPRINT("PortDeletePdo(%p)\n", PdoExtension);

    if (PdoExtension == NULL)
        return STATUS_INVALID_PARAMETER;

    /*
     * If the device was never started, we can safely destroy the PDO
     * immediately. Otherwise, mark it as not present and wait for PnP
     * to deliver IRP_MN_REMOVE_DEVICE before deleting it.
     */
    if (PdoExtension->PnpState != dsStopped)
    {
        PdoExtension->Present = FALSE;
        return STATUS_PENDING;
    }

    PdoExtension->Present = FALSE;

    /* Fall back to the removal path used during IRP_MN_REMOVE_DEVICE */
    PortDestroyPdo(PdoExtension);
    return STATUS_SUCCESS;
}

static
VOID
PortDestroyPdo(
    _In_ PPDO_DEVICE_EXTENSION PdoExtension)
{
    KLOCK_QUEUE_HANDLE LockHandle;
    PFDO_DEVICE_EXTENSION FdoExtension;
    PDEVICE_OBJECT DeviceObject;

    if (PdoExtension == NULL)
        return;

    FdoExtension = PdoExtension->FdoExtension;
    DeviceObject = PdoExtension->Device;

    DPRINT("PortDestroyPdo(%p)\n", PdoExtension);

    /* Remove the PDO from the list if it is still linked */
    if (FdoExtension != NULL)
    {
        KeAcquireInStackQueuedSpinLock(&FdoExtension->PdoListLock,
                                       &LockHandle);
        if (!IsListEmpty(&PdoExtension->PdoListEntry))
        {
            RemoveEntryList(&PdoExtension->PdoListEntry);
            InitializeListHead(&PdoExtension->PdoListEntry);
            if (FdoExtension->PdoCount > 0)
                FdoExtension->PdoCount--;
        }
        KeReleaseInStackQueuedSpinLock(&LockHandle);
    }

    if (PdoExtension->InquiryBuffer)
    {
        ExFreePoolWithTag(PdoExtension->InquiryBuffer, TAG_INQUIRY_DATA);
        PdoExtension->InquiryBuffer = NULL;
    }

    PdoExtension->Present = FALSE;
    PdoExtension->PnpState = dsRemoved;
    PdoExtension->Device = NULL;
    PdoExtension->FdoExtension = NULL;

    if (DeviceObject != NULL)
    {
        IoDeleteDevice(DeviceObject);
    }
}


static
VOID
PortNormalizeInquiryField(
    _In_reads_bytes_(SourceLength) PCHAR Source,
    _In_ ULONG SourceLength,
    _Out_writes_(DestinationChars) PWCHAR Destination,
    _In_ ULONG DestinationChars)
{
    CHAR Temp[32];
    ULONG Trimmed = SourceLength;
    ULONG i;

    if (DestinationChars == 0)
        return;

    while (Trimmed > 0 && Source[Trimmed - 1] == ' ')
        Trimmed--;

    if (Trimmed >= sizeof(Temp))
        Trimmed = sizeof(Temp) - 1;

    for (i = 0; i < Trimmed; ++i)
    {
        CHAR ch = Source[i];
        if (ch < 0x20)
            ch = ' ';
        Temp[i] = ch;
    }
    Temp[Trimmed] = '\0';

    RtlZeroMemory(Destination, DestinationChars * sizeof(WCHAR));

    if (Trimmed > 0)
    {
        ANSI_STRING Ansi;
        UNICODE_STRING Unicode;

        RtlInitAnsiString(&Ansi, Temp);
        Unicode.Buffer = Destination;
        Unicode.Length = 0;
        Unicode.MaximumLength = (USHORT)(DestinationChars * sizeof(WCHAR));

        if (NT_SUCCESS(RtlAnsiStringToUnicodeString(&Unicode, &Ansi, FALSE)))
            Destination[Unicode.Length / sizeof(WCHAR)] = L'\0';
    }

    for (i = 0; i < DestinationChars && Destination[i] != L'\0'; ++i)
    {
        if (Destination[i] == L' ')
            Destination[i] = L'_';
    }

    if (Destination[0] == L'\0')
    {
        Destination[0] = L'X';
        Destination[1] = L'\0';
    }
}


NTSTATUS
NTAPI
PortPdoScsi(
    _In_ PDEVICE_OBJECT DeviceObject,
    _In_ PIRP Irp)
{
    PPDO_DEVICE_EXTENSION PdoExtension;
    PFDO_DEVICE_EXTENSION FdoExtension;
    PIO_STACK_LOCATION Stack;
    PSCSI_REQUEST_BLOCK Srb = NULL;
    NTSTATUS Status;

    PdoExtension = (PPDO_DEVICE_EXTENSION)DeviceObject->DeviceExtension;
    ASSERT(PdoExtension != NULL);
    FdoExtension = PdoExtension->FdoExtension;
    ASSERT(FdoExtension != NULL);

    Stack = IoGetCurrentIrpStackLocation(Irp);

    switch (Stack->MajorFunction)
    {
        case IRP_MJ_DEVICE_CONTROL:
        {
            ULONG Ioctl = Stack->Parameters.DeviceIoControl.IoControlCode;

            if (Ioctl == IOCTL_SCSI_EXECUTE_IN ||
                Ioctl == IOCTL_SCSI_EXECUTE_OUT)
            {
                Srb = Stack->Parameters.Scsi.Srb;
            }
            break;
        }

        case IRP_MJ_SCSI:
            Srb = Stack->Parameters.Scsi.Srb;
            break;

        default:
            break;
    }

    if (Srb == NULL)
    {
        Irp->IoStatus.Information = 0;
        Irp->IoStatus.Status = STATUS_INVALID_DEVICE_REQUEST;
        IoCompleteRequest(Irp, IO_NO_INCREMENT);
        return STATUS_INVALID_DEVICE_REQUEST;
    }

    if (Srb->Function == SRB_FUNCTION_CLAIM_DEVICE)
    {
        Srb->SrbStatus = SRB_STATUS_SUCCESS;
        Srb->DataBuffer = DeviceObject;
        Srb->DataTransferLength = sizeof(PDEVICE_OBJECT);
        Irp->IoStatus.Information = sizeof(PDEVICE_OBJECT);
        Irp->IoStatus.Status = STATUS_SUCCESS;
        IoCompleteRequest(Irp, IO_NO_INCREMENT);
        return STATUS_SUCCESS;
    }

    if (Srb->Function == SRB_FUNCTION_RELEASE_DEVICE)
    {
        Srb->SrbStatus = SRB_STATUS_SUCCESS;
        Srb->DataTransferLength = 0;
        Irp->IoStatus.Information = 0;
        Irp->IoStatus.Status = STATUS_SUCCESS;
        IoCompleteRequest(Irp, IO_NO_INCREMENT);
        return STATUS_SUCCESS;
    }

#ifdef SRB_FUNCTION_PATH_INQUIRY
    if (Srb->Function == SRB_FUNCTION_PATH_INQUIRY)
    {
        DPRINT("PortPdoScsi: PATH_INQUIRY for target %lu:%lu:%lu (buffer=%p len=%lu)\n",
               PdoExtension->Bus,
               PdoExtension->Target,
               PdoExtension->Lun,
               Srb->DataBuffer,
               (ULONG)Srb->DataTransferLength);
    }
#endif

    /* Make sure the SRB knows which device it targets */
    Srb->PathId = (UCHAR)PdoExtension->Bus;
    Srb->TargetId = (UCHAR)PdoExtension->Target;
    Srb->Lun = (UCHAR)PdoExtension->Lun;
    Srb->OriginalRequest = Irp;

    /* Allocate an SRB extension if the miniport requested one */
    {
        SIZE_T MiniportSize = FdoExtension->Miniport.PortConfig.SrbExtensionSize;
        SIZE_T HeaderSize = sizeof(PORT_SRB_EXTENSION);
        PPORT_SRB_EXTENSION PortSrbExtension;
        PVOID MiniportExtension;
        PMDL IrpMdl;
        PVOID SystemAddress;

        /*
         * Allocate the PORT_SRB_EXTENSION header from NonPagedPool.
         * This is a small fixed-size allocation that doesn't need to be
         * in the uncached extension.
         */
        PortSrbExtension = ExAllocatePoolWithTag(NonPagedPool, HeaderSize, TAG_SRB_EXT);
        if (PortSrbExtension == NULL)
        {
            Irp->IoStatus.Information = 0;
            Irp->IoStatus.Status = STATUS_INSUFFICIENT_RESOURCES;
            IoCompleteRequest(Irp, IO_NO_INCREMENT);
            return STATUS_INSUFFICIENT_RESOURCES;
        }

        RtlZeroMemory(PortSrbExtension, HeaderSize);

        PortSrbExtension->MiniportExtension = NULL;
        PortSrbExtension->MiniportExtensionLength = 0;
        PortSrbExtension->OriginalDataBuffer = Srb->DataBuffer;
        PortSrbExtension->MappedSystemAddress = Srb->DataBuffer;

        Irp->Tail.Overlay.DriverContext[0] = PortSrbExtension;

        /*
         * Allocate the miniport's SRB extension from the SRB extension pool
         * in the uncached extension. This ensures it can be translated to
         * a physical address at any IRQL.
         */
        if (MiniportSize != 0)
        {
            MiniportExtension = PortAllocateSrbExtension(FdoExtension);
            if (MiniportExtension == NULL)
            {
                ExFreePoolWithTag(PortSrbExtension, TAG_SRB_EXT);
                Irp->IoStatus.Information = 0;
                Irp->IoStatus.Status = STATUS_INSUFFICIENT_RESOURCES;
                IoCompleteRequest(Irp, IO_NO_INCREMENT);
                return STATUS_INSUFFICIENT_RESOURCES;
            }

            /* Already zeroed by PortAllocateSrbExtension */
            Srb->SrbExtension = MiniportExtension;
            PortSrbExtension->MiniportExtension = MiniportExtension;
            PortSrbExtension->MiniportExtensionLength = (ULONG)MiniportSize;

            DPRINT("PortPdoScsi: Allocated SRB extension at VA=%p for miniport\n", MiniportExtension);
        }
        else
        {
            Srb->SrbExtension = NULL;
        }

        IrpMdl = Irp->MdlAddress;

        if (IrpMdl != NULL)
        {
            SystemAddress = MmGetSystemAddressForMdlSafe(IrpMdl,
                                                         NormalPagePriority);

            if (SystemAddress == NULL)
            {
                PortpCleanupSrbExtension(Irp);

                Irp->IoStatus.Information = 0;
                Irp->IoStatus.Status = STATUS_INSUFFICIENT_RESOURCES;
                IoCompleteRequest(Irp, IO_NO_INCREMENT);
                return STATUS_INSUFFICIENT_RESOURCES;
            }

            Srb->DataBuffer = SystemAddress;
            PortSrbExtension->MappedSystemAddress = SystemAddress;
        }
        else if (Irp->AssociatedIrp.SystemBuffer != NULL)
        {
            Srb->DataBuffer = Irp->AssociatedIrp.SystemBuffer;
            PortSrbExtension->MappedSystemAddress = Srb->DataBuffer;
        }

        PortSrbExtension->Mdl = IrpMdl;
    }

    /* Serialize HwStartIo calls - miniports expect single-threaded dispatch. */
    {
        KIRQL OldIrql;
        BOOLEAN StartIoResult;

        KeAcquireSpinLock(&FdoExtension->StartIoLock, &OldIrql);
        StartIoResult = MiniportStartIo(&FdoExtension->Miniport, Srb);
        KeReleaseSpinLock(&FdoExtension->StartIoLock, OldIrql);

        if (!StartIoResult)
        {
            PPORT_SRB_EXTENSION PortSrbExtension = PortGetSrbExtensionContext(Srb);
            if (PortSrbExtension != NULL)
            {
                Srb->DataBuffer = PortSrbExtension->OriginalDataBuffer;
            }

            PortpCleanupSrbExtension(Irp);

            Irp->IoStatus.Information = 0;
            Irp->IoStatus.Status = STATUS_DEVICE_BUSY;
            IoCompleteRequest(Irp, IO_NO_INCREMENT);
            return STATUS_DEVICE_BUSY;
        }
    }

    if (SRB_STATUS(Srb->SrbStatus) == SRB_STATUS_PENDING)
    {
        IoMarkIrpPending(Irp);
        return STATUS_PENDING;
    }

    /* The miniport might have completed the request inline via StorPortNotification */
    if (Srb->OriginalRequest == NULL)
    {
        /* StorPortNotification(RequestComplete, ...) already finalized the IRP */
        return StorPortSrbStatusToNtStatus(Srb->SrbStatus);
    }

    Status = StorPortSrbStatusToNtStatus(Srb->SrbStatus);
    if (SRB_STATUS(Srb->SrbStatus) == SRB_STATUS_SUCCESS)
    {
        PortpUpdateCapacityFromSrb(PdoExtension, Srb);
    }
    Irp->IoStatus.Information = Srb->DataTransferLength;
    Irp->IoStatus.Status = Status;

    {
        PPORT_SRB_EXTENSION PortSrbExtension = PortGetSrbExtensionContext(Srb);
        if (PortSrbExtension != NULL && Srb->Function != SRB_FUNCTION_CLAIM_DEVICE)
        {
            Srb->DataBuffer = PortSrbExtension->OriginalDataBuffer;
        }
    }

    PortpCleanupSrbExtension(Irp);

    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    return Status;
}


NTSTATUS
NTAPI
PortPdoPnp(
    _In_ PDEVICE_OBJECT DeviceObject,
    _In_ PIRP Irp)
{
    PPDO_DEVICE_EXTENSION PdoExtension;
    PIO_STACK_LOCATION Stack;
    ULONG_PTR Information = 0;
    NTSTATUS Status = STATUS_SUCCESS;

    DPRINT("PortPdoPnp(%p %p)\n", DeviceObject, Irp);

    PdoExtension = (PPDO_DEVICE_EXTENSION)DeviceObject->DeviceExtension;
    ASSERT(PdoExtension != NULL);

    Stack = IoGetCurrentIrpStackLocation(Irp);

    switch (Stack->MinorFunction)
    {
        case IRP_MN_START_DEVICE:
            DPRINT("PDO PnP: START_DEVICE\n");
            PdoExtension->PnpState = dsStarted;
            break;

        case IRP_MN_STOP_DEVICE:
            DPRINT("PDO PnP: STOP_DEVICE\n");
            PdoExtension->PnpState = dsStopped;
            break;

        case IRP_MN_SURPRISE_REMOVAL:
            DPRINT("PDO PnP: SURPRISE_REMOVAL\n");
            PdoExtension->PnpState = dsSurpriseRemoved;
            PdoExtension->Present = FALSE;
            break;

        case IRP_MN_QUERY_REMOVE_DEVICE:
        case IRP_MN_CANCEL_REMOVE_DEVICE:
        case IRP_MN_QUERY_STOP_DEVICE:
        case IRP_MN_CANCEL_STOP_DEVICE:
            DPRINT("PDO PnP: query/cancel remove/stop (minor 0x%02x)\n",
                   Stack->MinorFunction);
            break;

        case IRP_MN_REMOVE_DEVICE:
            DPRINT("PDO PnP: REMOVE_DEVICE\n");
            PdoExtension->Present = FALSE;
            PortDestroyPdo(PdoExtension);
            break;

        case IRP_MN_QUERY_DEVICE_RELATIONS:
        {
            PDEVICE_RELATIONS Relations;

            DPRINT("PDO PnP: QUERY_DEVICE_RELATIONS type=%lu\n",
                   Stack->Parameters.QueryDeviceRelations.Type);

            if (Stack->Parameters.QueryDeviceRelations.Type == TargetDeviceRelation)
            {
                Relations = (PDEVICE_RELATIONS)ExAllocatePoolWithTag(PagedPool,
                                                                     sizeof(DEVICE_RELATIONS),
                                                                     TAG_DEVICE_RELATIONS);
                if (Relations == NULL)
                {
                    Status = STATUS_INSUFFICIENT_RESOURCES;
                    break;
                }

                Relations->Count = 1;
                Relations->Objects[0] = DeviceObject;
                ObReferenceObject(DeviceObject);
                Information = (ULONG_PTR)Relations;
            }
            else
            {
                Status = STATUS_NOT_SUPPORTED;
            }
            break;
        }

        case IRP_MN_QUERY_ID:
        {
            WCHAR *Buffer;
            SIZE_T Length = 0;
            WCHAR VendorW[16];
            WCHAR ProductW[32];
            WCHAR RevisionW[16];
            WCHAR DeviceIdBuffer[128];
            UNICODE_STRING TempString;
            WCHAR InstanceBuffer[16];
            PINQUIRYDATA Inquiry = PdoExtension->InquiryBuffer;

            if (Inquiry != NULL)
            {
                PortNormalizeInquiryField((PCHAR)Inquiry->VendorId,
                                          sizeof(Inquiry->VendorId),
                                          VendorW,
                                          RTL_NUMBER_OF(VendorW));
                PortNormalizeInquiryField((PCHAR)Inquiry->ProductId,
                                          sizeof(Inquiry->ProductId),
                                          ProductW,
                                          RTL_NUMBER_OF(ProductW));
                PortNormalizeInquiryField((PCHAR)Inquiry->ProductRevisionLevel,
                                          sizeof(Inquiry->ProductRevisionLevel),
                                          RevisionW,
                                          RTL_NUMBER_OF(RevisionW));
            }
            else
            {
                RtlStringCchCopyW(VendorW, RTL_NUMBER_OF(VendorW), L"ReactOS");
                RtlStringCchCopyW(ProductW, RTL_NUMBER_OF(ProductW), L"AHCI_Disk");
                RtlStringCchCopyW(RevisionW, RTL_NUMBER_OF(RevisionW), L"0001");
            }

            /* Use correct SCSI device class prefix based on DeviceType */
            Status = RtlStringCbPrintfW(DeviceIdBuffer,
                                        sizeof(DeviceIdBuffer),
                                        (PdoExtension->Device->DeviceType == FILE_DEVICE_CD_ROM)
                                            ? L"SCSI\\CdRom%ws_%ws_%ws"
                                            : L"SCSI\\Disk%ws_%ws_%ws",
                                        VendorW,
                                        ProductW,
                                        RevisionW);
            if (!NT_SUCCESS(Status))
            {
                Status = STATUS_INSUFFICIENT_RESOURCES;
                break;
            }

            DPRINT("PDO PnP: QUERY_ID type=%lu\n", Stack->Parameters.QueryId.IdType);

            switch (Stack->Parameters.QueryId.IdType)
            {
                case BusQueryDeviceID:
                    Length = (wcslen(DeviceIdBuffer) + 1) * sizeof(WCHAR);
                    Buffer = ExAllocatePoolWithTag(PagedPool, Length, TAG_PDO_ID);
                    if (Buffer == NULL)
                    {
                        Status = STATUS_INSUFFICIENT_RESOURCES;
                        break;
                    }
                    RtlCopyMemory(Buffer, DeviceIdBuffer, Length);
                    Information = (ULONG_PTR)Buffer;
                    Status = STATUS_SUCCESS;
                    break;

                case BusQueryHardwareIDs:
                case BusQueryCompatibleIDs:
                {
                    PCWSTR GenericId = (PdoExtension->Device->DeviceType == FILE_DEVICE_CD_ROM)
                                       ? L"GenCdRom" : L"GenDisk";
                    SIZE_T DeviceIdChars = wcslen(DeviceIdBuffer) + 1;
                    SIZE_T GenericChars = wcslen(GenericId) + 1;
                    Length = (DeviceIdChars + GenericChars + 1) * sizeof(WCHAR);
                    Buffer = ExAllocatePoolWithTag(PagedPool, Length, TAG_PDO_ID);
                    if (Buffer == NULL)
                    {
                        Status = STATUS_INSUFFICIENT_RESOURCES;
                        break;
                    }
                    RtlZeroMemory(Buffer, Length);
                    RtlCopyMemory(Buffer, DeviceIdBuffer, DeviceIdChars * sizeof(WCHAR));
                    RtlCopyMemory(Buffer + DeviceIdChars, GenericId, GenericChars * sizeof(WCHAR));
                    Information = (ULONG_PTR)Buffer;
                    Status = STATUS_SUCCESS;
                    break;
                }

                case BusQueryInstanceID:
                    TempString.Buffer = InstanceBuffer;
                    TempString.Length = 0;
                    TempString.MaximumLength = sizeof(InstanceBuffer);
                    Status = RtlIntegerToUnicodeString(PdoExtension->Target, 10, &TempString);
                    if (!NT_SUCCESS(Status))
                        break;

                    Length = TempString.Length + sizeof(WCHAR);
                    Buffer = ExAllocatePoolWithTag(PagedPool, Length, TAG_PDO_ID);
                    if (Buffer == NULL)
                    {
                        Status = STATUS_INSUFFICIENT_RESOURCES;
                        break;
                    }
                    RtlZeroMemory(Buffer, Length);
                    RtlCopyMemory(Buffer, TempString.Buffer, TempString.Length);
                    Information = (ULONG_PTR)Buffer;
                    Status = STATUS_SUCCESS;
                    break;

                default:
                    Status = STATUS_NOT_SUPPORTED;
                    break;
            }
            break;
        }

        case IRP_MN_QUERY_CAPABILITIES:
        {
            PDEVICE_CAPABILITIES Caps = Stack->Parameters.DeviceCapabilities.Capabilities;

            DPRINT("PDO PnP: QUERY_CAPABILITIES\n");

            if (Caps == NULL || Caps->Size < sizeof(DEVICE_CAPABILITIES))
            {
                Status = STATUS_INVALID_PARAMETER;
                break;
            }

            RtlZeroMemory(Caps, sizeof(DEVICE_CAPABILITIES));
            Caps->Size = sizeof(DEVICE_CAPABILITIES);
            Caps->Version = 1;
            Caps->DeviceD1 = FALSE;
            Caps->DeviceD2 = FALSE;
            Caps->Address = PdoExtension->Target;
            Caps->UINumber = PdoExtension->Target;
            for (ULONG state = 0; state < PowerSystemMaximum; ++state)
            {
                Caps->DeviceState[state] = (state == PowerSystemWorking) ? PowerDeviceD0 : PowerDeviceD3;
            }
            Caps->DeviceWake = PowerDeviceUnspecified;
            Caps->SystemWake = PowerSystemUnspecified;
            Caps->Removable = FALSE;
            Caps->SurpriseRemovalOK = TRUE;
            Caps->UniqueID = FALSE;
            Status = STATUS_SUCCESS;
            break;
        }

        default:
            DPRINT("PDO PnP: unsupported minor 0x%02x\n", Stack->MinorFunction);
            Status = STATUS_NOT_SUPPORTED;
            break;
    }

    Irp->IoStatus.Information = Information;
    Irp->IoStatus.Status = Status;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    return Status;
}

/* EOF */
