
#define IOCTL_NETIO_START_EVENT_TEST        1
#define IOCTL_NETIO_FINISH_EVENT_TEST       2
#define IOCTL_NETIO_START_PRECEDENCE_TEST   3
#define IOCTL_NETIO_FINISH_PRECEDENCE_TEST  4
#define IOCTL_NETIO_START_DISABLE_TEST      5
#define IOCTL_NETIO_FINISH_DISABLE_TEST     6
#define IOCTL_NETIO_START_CLOSE_ACCEPT_TEST 7
#define IOCTL_NETIO_FINISH_CLOSE_ACCEPT_TEST 8

#define NETIO_TEST_EVENT_PORT               43010
#define NETIO_TEST_PRECEDENCE_PORT          43011
#define NETIO_TEST_DISABLE_PORT             43012
#define NETIO_TEST_CLOSE_ACCEPT_PORT        43013
