@ stdcall Wow64LdrpInitialize()
@ stdcall Wow64LdrpInitializeProcess(ptr ptr)
@ stdcall Wow64LdrpInitializeThread(ptr)
@ stdcall Wow64ProcessInit(ptr)
@ stdcall Wow64ProcessTerm()
@ stdcall Wow64PopPendingApc(ptr)
@ stdcall Wow64DeliverPendingApc()
@ stdcall Wow64DeliverPendingApcEx(long)
@ stdcall Wow64SystemServiceEx(long ptr)
@ stdcall Wow64ApcRoutine(long long long ptr)
@ stdcall Wow64SetThreadContext(ptr)
@ stdcall Wow64GetThreadContext()
@ stdcall Wow64ClearThreadContext()
@ stdcall Wow64IsCurrentThreadWow64()
