@ stdcall SdPortCompleteRequest(ptr long)
@ stdcall SdPortInitialize(ptr ptr ptr)
@ stdcall SdPortInitializeLegacy(ptr ptr ptr)
@ stdcall SdPortPoFxPowerControl(ptr ptr ptr long ptr long ptr)
@ stdcall SdPortGetPciConfigSpace(ptr long ptr long)
@ stdcall SdPortSetPciConfigSpace(ptr long ptr long)
@ stdcall SdPortReadRegisterBufferUchar(ptr long ptr long)
@ stdcall SdPortReadRegisterBufferUlong(ptr long ptr long)
@ stdcall SdPortReadRegisterBufferUshort(ptr long ptr long)
@ stdcall SdPortReadRegisterUchar(ptr long)
@ stdcall SdPortReadRegisterUlong(ptr long)
@ stdcall SdPortReadRegisterUshort(ptr long)
@ stdcall SdPortWait(long)
@ stdcall SdPortWriteRegisterBufferUchar(ptr long ptr long)
@ stdcall SdPortWriteRegisterBufferUlong(ptr long ptr long)
@ stdcall SdPortWriteRegisterBufferUshort(ptr long ptr long)
@ stdcall SdPortWriteRegisterUchar(ptr long long)
@ stdcall SdPortWriteRegisterUlong(ptr long long)
@ stdcall SdPortWriteRegisterUshort(ptr long long)
