add_subdirectory(usbccgp)
add_subdirectory(usbd)
add_subdirectory(usbdwc2)
add_subdirectory(usbehci)
add_subdirectory(usbhub)
add_subdirectory(usbohci)
add_subdirectory(usbport)
add_subdirectory(usbaudio)
add_subdirectory(usbasix)
add_subdirectory(smsc95xx)
add_subdirectory(usbrndis)
add_subdirectory(usbstor)
#add_subdirectory(usbstor_new)
add_subdirectory(usbuhci)
add_subdirectory(usbxhci)
add_subdirectory(usbvideo)
