#pragma once

#ifndef CTL_CODE
#include <winioctl.h>
#endif

#define ACPIPROC_THROTTLE_INFO_VERSION 1
#define ACPIPROC_THERMAL_INFO_VERSION  1

#define ACPIPROC_THROTTLE_INFO_FLAG_TPC_VALID 0x00000001

#define ACPIPROC_THERMAL_INFO_FLAG_HOT_VALID      0x00000001
#define ACPIPROC_THERMAL_INFO_FLAG_CRITICAL_VALID 0x00000002
#define ACPIPROC_THERMAL_INFO_FLAG_HOT_PENDING    0x00000004
#define ACPIPROC_THERMAL_INFO_FLAG_CRITICAL_PENDING 0x00000008

#define ACPIPROC_THERMAL_CLEAR_HOT        0x00000001
#define ACPIPROC_THERMAL_CLEAR_CRITICAL   0x00000002

typedef struct _ACPIPROC_THROTTLE_STATE_INFO {
    ULONG Power;
    ULONG Performance;
    ULONG TransitionLatency;
    ULONG Control;
    ULONG Status;
} ACPIPROC_THROTTLE_STATE_INFO, *PACPIPROC_THROTTLE_STATE_INFO;

typedef struct _ACPIPROC_THROTTLE_INFO {
    ULONG Version;
    ULONG Flags;
    ULONG StateCount;
    ULONG ActiveState;
    ULONG LimitIndex;
    ULONG Reserved;
    ACPIPROC_THROTTLE_STATE_INFO States[ANYSIZE_ARRAY];
} ACPIPROC_THROTTLE_INFO, *PACPIPROC_THROTTLE_INFO;

typedef struct _ACPIPROC_THROTTLE_REQUEST {
    ULONG StateIndex;
} ACPIPROC_THROTTLE_REQUEST, *PACPIPROC_THROTTLE_REQUEST;

typedef struct _ACPIPROC_THERMAL_INFO {
    ULONG Version;
    ULONG Flags;
    ULONG HotTripPoint;
    ULONG CriticalTripPoint;
    ULONG Reserved[2];
} ACPIPROC_THERMAL_INFO, *PACPIPROC_THERMAL_INFO;

typedef struct _ACPIPROC_THERMAL_CLEAR {
    ULONG Flags;
} ACPIPROC_THERMAL_CLEAR, *PACPIPROC_THERMAL_CLEAR;

#define IOCTL_ACPIPROC_QUERY_THROTTLE \
    CTL_CODE(FILE_DEVICE_ACPI, 0x811, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_ACPIPROC_SET_THROTTLE \
    CTL_CODE(FILE_DEVICE_ACPI, 0x812, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_ACPIPROC_QUERY_THERMAL \
    CTL_CODE(FILE_DEVICE_ACPI, 0x813, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_ACPIPROC_CLEAR_THERMAL \
    CTL_CODE(FILE_DEVICE_ACPI, 0x814, METHOD_BUFFERED, FILE_WRITE_DATA)
