/*
 * PROJECT:     ReactOS NT Virtual Memory Subsystem
 * FILE:        ntoskrnl/nvs/include/miarchcheck.h
 * PURPOSE:     Memory manager architecture contract checks
 *
 * SPDX-FileCopyrightText: 2026 Ahmed ARIF
 * SPDX-License-Identifier: GPL-3.0-only
 */

#pragma once

C_ASSERT(MI_ARCH_PAGING_LEVELS >= 1);
C_ASSERT(MI_ARCH_PAGING_LEVELS <= MI_MAX_PAGING_LEVELS);

C_ASSERT(MI_ARCH_PTE_BYTES == 4 || MI_ARCH_PTE_BYTES == 8);
C_ASSERT(MI_ARCH_VA_BITS > 0 && MI_ARCH_VA_BITS <= 64);
C_ASSERT(MI_ARCH_PA_BITS > 0 && MI_ARCH_PA_BITS <= 64);
C_ASSERT(MI_ARCH_PTE_BYTES == 8 || MI_ARCH_VA_BITS <= 32);

C_ASSERT(MI_ARCH_L0_SHIFT == MI_ARCH_PAGE_SHIFT);
C_ASSERT((1 << MI_ARCH_PAGE_SHIFT) == PAGE_SIZE);

C_ASSERT(MI_ARCH_PAGING_LEVELS < 2 || MI_ARCH_L1_SHIFT == MI_ARCH_L0_SHIFT + MI_ARCH_L0_BITS);
C_ASSERT(MI_ARCH_PAGING_LEVELS < 3 || MI_ARCH_L2_SHIFT == MI_ARCH_L1_SHIFT + MI_ARCH_L1_BITS);
C_ASSERT(MI_ARCH_PAGING_LEVELS < 4 || MI_ARCH_L3_SHIFT == MI_ARCH_L2_SHIFT + MI_ARCH_L2_BITS);
C_ASSERT(MI_ARCH_PAGING_LEVELS < 5 || MI_ARCH_L4_SHIFT == MI_ARCH_L3_SHIFT + MI_ARCH_L3_BITS);

C_ASSERT(MI_ARCH_PAGING_LEVELS != 1 || MI_ARCH_L0_SHIFT + MI_ARCH_L0_BITS == MI_ARCH_VA_BITS);
C_ASSERT(MI_ARCH_PAGING_LEVELS != 2 || MI_ARCH_L1_SHIFT + MI_ARCH_L1_BITS == MI_ARCH_VA_BITS);
C_ASSERT(MI_ARCH_PAGING_LEVELS != 3 || MI_ARCH_L2_SHIFT + MI_ARCH_L2_BITS == MI_ARCH_VA_BITS);
C_ASSERT(MI_ARCH_PAGING_LEVELS != 4 || MI_ARCH_L3_SHIFT + MI_ARCH_L3_BITS == MI_ARCH_VA_BITS);
C_ASSERT(MI_ARCH_PAGING_LEVELS != 5 || MI_ARCH_L4_SHIFT + MI_ARCH_L4_BITS == MI_ARCH_VA_BITS);

C_ASSERT(MI_ARCH_LARGE_LEVEL >= 1);
C_ASSERT(MI_ARCH_LARGE_LEVEL < MI_ARCH_PAGING_LEVELS);

C_ASSERT(MI_ARCH_PAGING_LEVELS >= 5 || (MI_ARCH_L4_SHIFT == 0 && MI_ARCH_L4_BITS == 0));
C_ASSERT(MI_ARCH_PAGING_LEVELS >= 4 || (MI_ARCH_L3_SHIFT == 0 && MI_ARCH_L3_BITS == 0));
C_ASSERT(MI_ARCH_PAGING_LEVELS >= 3 || (MI_ARCH_L2_SHIFT == 0 && MI_ARCH_L2_BITS == 0));
