/* Automatically generated by make depend; DO NOT EDIT!! */

#define STANDALONE
#include <wine/test.h>

extern void func_d3d10core(void);

const struct test winetest_testlist[] =
{
    { "d3d10core", func_d3d10core },
    { 0, 0 }
};
