@ stdcall CpuNotify(long ptr ptr)
@ stdcall CpuProcessInit(ptr ptr)
@ stdcall CpuThreadInit(ptr ptr)
@ stdcall CpuThreadTerm(ptr)
@ stdcall CpupReturnFromSimulatedCode()
@ stdcall CpupDoCallBack(long long ptr ptr)
@ stdcall CpupDispatchException(ptr ptr ptr)
@ stdcall Wow64CpuGetContext(ptr ptr long)
@ stdcall Wow64CpuSetContext(ptr ptr long)
@ stdcall Wow64CpuSetPendingApc(ptr ptr long long)
@ stdcall Wow64CpuDispatchPendingApc(ptr)
@ stdcall Wow64CpuPrepareCallback(ptr ptr long ptr long)
@ stdcall Wow64CpuTakePendingApc(ptr ptr)
@ stdcall Wow64PrepareForException(ptr ptr)
@ stdcall Wow64TransitionToCompat(ptr ptr ptr)
@ stdcall Wow64TransitionToNative(ptr ptr ptr)
@ stdcall Wow64Transition()
@ stdcall Wow64cpuSaveFpuContext(ptr)
@ stdcall Wow64cpuRestoreFpuContext(ptr)
