/* Automatically generated by make depend; DO NOT EDIT!! */

#define STANDALONE
#include <wine/test.h>

extern void func_opcservices(void);

const struct test winetest_testlist[] =
{
    { "opcservices", func_opcservices },
    { 0, 0 }
};
