/*
 * PROJECT:     ReactOS API tests
 * LICENSE:     GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later)
 * PURPOSE:     Restricted Core Audio child protocol
 */

#ifndef _MMDEVAPI_APITEST_SANDBOXAUDIO_H
#define _MMDEVAPI_APITEST_SANDBOXAUDIO_H

enum sandbox_audio_result
{
    SANDBOX_AUDIO_COM = 20,
    SANDBOX_AUDIO_EVENTS,
    SANDBOX_AUDIO_DEVICE_INTERFACE,
    SANDBOX_AUDIO_ENUMERATOR,
    SANDBOX_AUDIO_ENDPOINT,
    SANDBOX_AUDIO_ACTIVATE,
    SANDBOX_AUDIO_PROPERTIES,
    SANDBOX_AUDIO_FORMAT,
    SANDBOX_AUDIO_PERIOD,
    SANDBOX_AUDIO_INITIALIZE,
    SANDBOX_AUDIO_EVENT,
    SANDBOX_AUDIO_SET_EVENT,
    SANDBOX_AUDIO_RENDER_SERVICE,
    SANDBOX_AUDIO_BUFFER_SIZE,
    SANDBOX_AUDIO_GET_BUFFER,
    SANDBOX_AUDIO_RELEASE_BUFFER,
    SANDBOX_AUDIO_START,
    SANDBOX_AUDIO_STOP
};

#endif /* _MMDEVAPI_APITEST_SANDBOXAUDIO_H */
