/*
 * LICENSE:     GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later)
 * COPYRIGHT:   Copyright 2026 Ahmed ARIF
 * PURPOSE:     Windows NT PowerPC structure offsets for assembly code
 */

HEADER("Context"),
OFFSET(CxFpr0, CONTEXT, Fpr0),
OFFSET(CxFpr14, CONTEXT, Fpr14),
OFFSET(CxFpscr, CONTEXT, Fpscr),
OFFSET(CxGpr0, CONTEXT, Gpr0),
OFFSET(CxGpr1, CONTEXT, Gpr1),
OFFSET(CxGpr2, CONTEXT, Gpr2),
OFFSET(CxGpr3, CONTEXT, Gpr3),
OFFSET(CxGpr13, CONTEXT, Gpr13),
OFFSET(CxGpr14, CONTEXT, Gpr14),
OFFSET(CxCr, CONTEXT, Cr),
OFFSET(CxXer, CONTEXT, Xer),
OFFSET(CxMsr, CONTEXT, Msr),
OFFSET(CxIar, CONTEXT, Iar),
OFFSET(CxLr, CONTEXT, Lr),
OFFSET(CxCtr, CONTEXT, Ctr),
OFFSET(CxContextFlags, CONTEXT, ContextFlags),
SIZE(ContextFrameLength, CONTEXT),
CONSTANT(CONTEXT_FULL),
CONSTANT(STATUS_NOT_IMPLEMENTED),

HEADER("Trap frame"),
OFFSET(TfDar, KTRAP_FRAME, Dar),
OFFSET(TfDsisr, KTRAP_FRAME, Dsisr),
OFFSET(TfVector, KTRAP_FRAME, Vector),
OFFSET(TfPreviousTrapFrame, KTRAP_FRAME, PreviousTrapFrame),
OFFSET(TfPreviousIrql, KTRAP_FRAME, PreviousIrql),
OFFSET(TfPreviousMode, KTRAP_FRAME, PreviousMode),
SIZE(TrapFrameLength, KTRAP_FRAME),

HEADER("Processor control region"),
OFFSET(PcIrql, KPCR, CurrentIrql),
OFFSET(PcSoftwareInterrupts, KPCR, SoftwareInterrupts),
OFFSET(PcTrapActive, KPCR, TrapActive),
OFFSET(PcPhysicalAddress, KPCR, PhysicalAddress),
OFFSET(PcPageTableRoot, KPCR, PageTableRoot),
OFFSET(PcHashTable, KPCR, HashTable),
OFFSET(PcHashTableMask, KPCR, HashTableMask),
OFFSET(PcHashReplace, KPCR, HashReplace),
OFFSET(PcInitialStack, KPCR, InitialStack),
OFFSET(PcPanicStack, KPCR, PanicStack),
OFFSET(PcTrapVector, KPCR, TrapVector),
OFFSET(PcTrapDar, KPCR, TrapDar),
OFFSET(PcTrapDsisr, KPCR, TrapDsisr),
OFFSET(PcReloadScratch, KPCR, ReloadScratch),
OFFSET(PcTrapScratch, KPCR, TrapScratch),
OFFSET(PcExitScratch, KPCR, ExitScratch),
OFFSET(PcPanicFrame, KPCR, PanicFrame),
OFFSET(PcPrcb, KPCR, Prcb),
OFFSET(PcCurrentThread, KPCR, Prcb.CurrentThread),

HEADER("Processor control block"),
OFFSET(PbCurrentThread, KPRCB, CurrentThread),
OFFSET(PbNextThread, KPRCB, NextThread),
OFFSET(PbIdleThread, KPRCB, IdleThread),
OFFSET(PbDpcStack, KPRCB, DpcStack),

HEADER("Start frame"),
OFFSET(SfSystemRoutine, KSTART_FRAME, SystemRoutine),
OFFSET(SfStartRoutine, KSTART_FRAME, StartRoutine),
OFFSET(SfStartContext, KSTART_FRAME, StartContext),
OFFSET(SfReturn, KSTART_FRAME, Return),
SIZE(StartFrameLength, KSTART_FRAME),

HEADER("Switch frame"),
OFFSET(SwFpr14, KSWITCH_FRAME, Fpr14),
OFFSET(SwGpr14, KSWITCH_FRAME, Gpr14),
OFFSET(SwCr, KSWITCH_FRAME, Cr),
OFFSET(SwLr, KSWITCH_FRAME, Lr),
OFFSET(SwGpr2, KSWITCH_FRAME, Gpr2),
OFFSET(SwApcBypass, KSWITCH_FRAME, ApcBypass),
SIZE(SwitchFrameLength, KSWITCH_FRAME),

HEADER("User callback kernel frame"),
OFFSET(CoFpr14, KCALLOUT_FRAME, Fpr14),
OFFSET(CoGpr14, KCALLOUT_FRAME, Gpr14),
OFFSET(CoCr, KCALLOUT_FRAME, Cr),
OFFSET(CoLr, KCALLOUT_FRAME, Lr),
OFFSET(CoGpr2, KCALLOUT_FRAME, Gpr2),
OFFSET(CoMsr, KCALLOUT_FRAME, Msr),
OFFSET(CoCallbackStack, KCALLOUT_FRAME, CallbackStack),
OFFSET(CoInitialStack, KCALLOUT_FRAME, InitialStack),
OFFSET(CoTrapFrame, KCALLOUT_FRAME, TrapFrame),
OFFSET(CoOutputBuffer, KCALLOUT_FRAME, OutputBuffer),
OFFSET(CoOutputLength, KCALLOUT_FRAME, OutputLength),
SIZE(CalloutFrameLength, KCALLOUT_FRAME),
