/*
 * PROJECT:     ReactOS SDK
 * LICENSE:     LGPL-2.1-or-later (https://spdx.org/licenses/LGPL-2.1-or-later)
 * PURPOSE:     Resource Hub client definitions
 * COPYRIGHT:   Copyright 2026 Ahmed ARIF <arif.ing@outlook.com>
 */

#pragma once

#if (NTDDI_VERSION >= NTDDI_WIN8)

#ifdef UMDF_DRIVER
#define RESOURCE_HUB_DEVICE_NAME L"\\\\.\\RESOURCE_HUB"
#else
#define RESOURCE_HUB_DEVICE_NAME L"\\Device\\RESOURCE_HUB"
#endif

#define RESOURCE_HUB_SYMBOLIC_NAME L"\\DosDevices\\RESOURCE_HUB"
#define RESOURCE_HUB_DEVICE_NAME_PREFIX RESOURCE_HUB_DEVICE_NAME L"\\"

#define RESOURCE_HUB_CONNECTION_FILE_SIZE \
    ((sizeof(LARGE_INTEGER) * 2 * sizeof(WCHAR)) + sizeof(UNICODE_NULL))
#define RESOURCE_HUB_CONNECTION_PATH_SIZE \
    (sizeof(RESOURCE_HUB_DEVICE_NAME_PREFIX) + RESOURCE_HUB_CONNECTION_FILE_SIZE - sizeof(UNICODE_NULL))
#define RESOURCE_HUB_CONNECTION_FILE_CHARS \
    ((RESOURCE_HUB_CONNECTION_FILE_SIZE + sizeof(WCHAR) - 1) / sizeof(WCHAR))
#define RESOURCE_HUB_CONNECTION_PATH_CHARS \
    ((RESOURCE_HUB_CONNECTION_PATH_SIZE + sizeof(WCHAR) - 1) / sizeof(WCHAR))

#define RESOURCE_HUB_FILE_SIZE RESOURCE_HUB_CONNECTION_FILE_SIZE
#define RESOURCE_HUB_PATH_SIZE RESOURCE_HUB_CONNECTION_PATH_SIZE
#define RESOURCE_HUB_FILE_CHARS RESOURCE_HUB_CONNECTION_FILE_CHARS
#define RESOURCE_HUB_PATH_CHARS RESOURCE_HUB_CONNECTION_PATH_CHARS

#define FILE_DEVICE_RESOURCE_HUB FILE_DEVICE_BUS_EXTENDER

#define IOCTL_RH_QUERY_CONNECTION_PROPERTIES \
    CTL_CODE(FILE_DEVICE_RESOURCE_HUB, 0x0, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_RH_ALLOCATE_CONNECTION \
    CTL_CODE(FILE_DEVICE_RESOURCE_HUB, 0x1, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_RH_FREE_CONNECTION \
    CTL_CODE(FILE_DEVICE_RESOURCE_HUB, 0x2, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_RH_UPDATE_CONNECTION_PROPERTIES \
    CTL_CODE(FILE_DEVICE_RESOURCE_HUB, 0x3, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_RH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY \
    CTL_CODE(FILE_DEVICE_RESOURCE_HUB, 0x4, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_RH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY \
    CTL_CODE(FILE_DEVICE_RESOURCE_HUB, 0x5, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#define RH_QUERY_CONNECTION_PROPERTIES_INPUT_VERSION 1
#define RH_QUERY_CONNECTION_PROPERTIES_OUTPUT_VERSION 1
#define RH_ALLOCATE_CONNECTION_INPUT_VERSION 1
#define RH_ALLOCATE_CONNECTION_OUTPUT_VERSION 1
#define RH_FREE_CONNECTION_INPUT_VERSION 1
#define RH_FREE_CONNECTION_OUTPUT_VERSION 1
#define RH_UPDATE_CONNECTION_PROPERTIES_INPUT_VERSION 1
#define RH_UPDATE_CONNECTION_PROPERTIES_OUTPUT_VERSION 1
#define RH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_VERSION 1
#define RH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_VERSION 1
#define RH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_VERSION 1
#define RH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_VERSION 1

#define RH_UPDATE_CONNECTIONAL_MASK_ALL 0xFFFF

#define GPIO_INTERRUPT_IO_DESCRIPTOR 0x8c
#define FUNCTION_CONFIG_DESCRIPTOR 0x8d

#define PNP_FUNCTION_CONFIG_DESCRIPTOR_REVISION 0x1
#define PNP_FUNCTION_CONFIG_DESCRIPTOR_REVISION_MINIMUM 0x1

#ifndef INVALID_PIN_NUMBER
#define INVALID_PIN_NUMBER 0xFFFF
#endif

#define PNP_GPIO_IRQ_DESCRIPTOR_REVISION 0x1
#define PNP_GPIO_IRQ_DESCRIPTOR_TYPE_INTERRUPT 0x0
#define PNP_GPIO_IRQ_DESCRIPTOR_TYPE_IO 0x1
#define PNP_GPIO_IRQ_DESCRIPTOR_REVISION_MINIMUM (0x1)

#define PNP_GPIO_IRQ_RESOURCE_CONSUMER_ONLY 0x01
#define PNP_GPIO_IRQ_MODE 0x01
#define PNP_GPIO_IRQ_POLARITY 0x06
#define PNP_GPIO_IRQ_SHARED 0x08
#define PNP_GPIO_IRQ_WAKE_HINT 0x10

#ifndef PNP_GPIO_IRQ_MODE_EDGE
#define PNP_GPIO_IRQ_MODE_EDGE 0x01
#define PNP_GPIO_IRQ_MODE_LEVEL 0x00
#define PNP_GPIO_IRQ_POLARITY_LOW 0x02
#define PNP_GPIO_IRQ_POLARITY_HIGH 0x00
#define PNP_GPIO_IRQ_POLARITY_BOTH 0x04
#endif

#define SERIAL_BUS_DESCRIPTOR 0x8e
#define SERIAL_BUS_DESCRIPTOR_REVISION 0x01
#define SERIAL_BUS_DESCRIPTOR_REVISION_V2 0x02
#define SERIAL_BUS_I2C_DESCRIPTOR_TYPE 1
#define SERIAL_BUS_SPI_DESCRIPTOR_TYPE 2
#define SERIAL_BUS_UART_DESCRIPTOR_TYPE 3
#define SERIAL_BUS_FLAG_SHARED_DESCRIPTOR 0x4

typedef enum _RH_QUERY_CONNECTION_PROPERTIES_INPUT_TYPE
{
    ConnectionIdType,
    InterruptVectorType
} RH_QUERY_CONNECTION_PROPERTIES_INPUT_TYPE, *PRH_QUERY_CONNECTION_PROPERTIES_INPUT_TYPE;

typedef struct _RH_QUERY_CONNECTION_PROPERTIES_INPUT_BUFFER
{
    ULONG Version;
    RH_QUERY_CONNECTION_PROPERTIES_INPUT_TYPE QueryType;
    union
    {
        LARGE_INTEGER ConnectionId;
        ULONG InterruptVector;
    } u;
} RH_QUERY_CONNECTION_PROPERTIES_INPUT_BUFFER, *PRH_QUERY_CONNECTION_PROPERTIES_INPUT_BUFFER;

typedef struct _RH_QUERY_CONNECTION_PROPERTIES_OUTPUT_BUFFER
{
    ULONG Version;
    ULONG PropertiesLength;
    UCHAR ConnectionProperties[ANYSIZE_ARRAY];
} RH_QUERY_CONNECTION_PROPERTIES_OUTPUT_BUFFER, *PRH_QUERY_CONNECTION_PROPERTIES_OUTPUT_BUFFER;

typedef enum _RH_CONNECTION_PROPERTIES_INPUT_TYPE
{
    GpioIoType,
    GpioInterruptType,
    SpiConnectionType,
    I2cConnectionType,
    UartConnectionType
} RH_CONNECTION_PROPERTIES_INPUT_TYPE, *PRH_CONNECTION_PROPERTIES_INPUT_TYPE;

typedef struct _RH_GPIO_IO_CONNECTION_PARAMETERS
{
    LARGE_INTEGER ConnectionId;
    USHORT UpdateMask;
    UCHAR PinConfiguration;
    USHORT DebounceTimeout;
    USHORT DriveStrength;
} RH_GPIO_IO_CONNECTION_PARAMETERS, *PRH_GPIO_IO_CONNECTION_PARAMETERS;

typedef struct _RH_GPIO_INTERRUPT_CONNECTION_PARAMETERS
{
    ULONG InterruptVector;
    USHORT UpdateMask;
    UCHAR InterruptMode;
    UCHAR InterruptPolarity;
    UCHAR PinConfiguration;
    USHORT DebounceTimeout;
} RH_GPIO_INTERRUPT_CONNECTION_PARAMETERS, *PRH_GPIO_INTERRUPT_CONNECTION_PARAMETERS;

typedef struct _RH_SPI_CONNECTION_PARAMETERS
{
    LARGE_INTEGER ConnectionId;
    USHORT UpdateMask;
    USHORT DeviceSelection;
    ULONG ConnectionSpeed;
    UCHAR ClockPolarity;
    UCHAR ClockPhase;
    UCHAR DevicePolarity;
    UCHAR DataBitLength;
} RH_SPI_CONNECTION_PARAMETERS, *PRH_SPI_CONNECTION_PARAMETERS;

typedef struct _RH_I2C_CONNECTION_PARAMETERS
{
    LARGE_INTEGER ConnectionId;
    USHORT UpdateMask;
    USHORT TypeSpecificFlags;
    ULONG ConnectionSpeed;
    USHORT SlaveAddress;
} RH_I2C_CONNECTION_PARAMETERS, *PRH_I2C_CONNECTION_PARAMETERS;

typedef struct _RH_UART_CONNECTION_PARAMETERS
{
    LARGE_INTEGER ConnectionId;
    USHORT UpdateMask;
    ULONG BaudRate;
    USHORT TypeSpecificFlags;
    USHORT RxBufferSize;
    USHORT TxBufferSize;
    UCHAR Parity;
} RH_UART_CONNECTION_PARAMETERS, *PRH_UART_CONNECTION_PARAMETERS;

typedef struct _RH_ALLOCATE_UPDATE_CONNECTION_INPUT_BUFFER
{
    ULONG Version;
    RH_CONNECTION_PROPERTIES_INPUT_TYPE ConnectionType;
    union
    {
        RH_GPIO_IO_CONNECTION_PARAMETERS IoConnection;
        RH_GPIO_INTERRUPT_CONNECTION_PARAMETERS InterruptConnection;
        RH_SPI_CONNECTION_PARAMETERS SpiConnection;
        RH_I2C_CONNECTION_PARAMETERS I2cConnection;
        RH_UART_CONNECTION_PARAMETERS UartConnection;
    } u;
} RH_ALLOCATE_UPDATE_CONNECTION_INPUT_BUFFER, *PRH_ALLOCATE_UPDATE_CONNECTION_INPUT_BUFFER;

typedef struct _RH_ALLOCATE_CONNECTION_OUTPUT_BUFFER
{
    ULONG Version;
    LARGE_INTEGER ConnectionId;
} RH_ALLOCATE_CONNECTION_OUTPUT_BUFFER, *PRH_ALLOCATE_CONNECTION_OUTPUT_BUFFER;

typedef struct _RH_UPDATE_CONNECTION_PROPERTIES_OUTPUT_BUFFER
{
    ULONG Version;
} RH_UPDATE_CONNECTION_PROPERTIES_OUTPUT_BUFFER, *PRH_UPDATE_CONNECTION_PROPERTIES_OUTPUT_BUFFER;

typedef struct _RH_FREE_CONNECTION_INPUT_BUFFER
{
    ULONG Version;
    LARGE_INTEGER ConnectionId;
} RH_FREE_CONNECTION_INPUT_BUFFER, *PRH_FREE_CONNECTION_INPUT_BUFFER;

typedef struct _RH_FREE_CONNECTION_OUTPUT_BUFFER
{
    ULONG Version;
} RH_FREE_CONNECTION_OUTPUT_BUFFER, *PRH_FREE_CONNECTION_OUTPUT_BUFFER;

typedef struct _RH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_BUFFER
{
    ULONG Version;
    ULONG InterruptVector;
} RH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_BUFFER, *PRH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_BUFFER;

typedef struct _RH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_BUFFER
{
    ULONG Version;
    UCHAR InitialPolarity;
} RH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_BUFFER, *PRH_QUERY_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_BUFFER;

typedef struct _RH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_BUFFER
{
    ULONG Version;
    ULONG InterruptVector;
    BOOLEAN InitialPolarity;
} RH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_BUFFER, *PRH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_INPUT_BUFFER;

typedef struct _RH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_BUFFER
{
    ULONG Version;
} RH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_BUFFER, *PRH_UPDATE_ACTIVE_BOTH_INITIAL_POLARITY_OUTPUT_BUFFER;

#include <pshpack1.h>

typedef struct _PNP_GPIO_INTERRUPT_IO_DESCRIPTOR
{
    UCHAR Tag;
    USHORT Length;
    UCHAR Revision;
    UCHAR DescriptorType;
    USHORT GeneralFlags;
    USHORT InterruptIoFlags;
    UCHAR PinConfiguration;
    USHORT DriveStrength;
    USHORT DebounceTimeout;
    USHORT PinTableOffset;
    UCHAR ResourceSourceIndex;
    USHORT ResourceSourceOffset;
    USHORT VendorDataOffset;
    USHORT VendorDataLength;
} PNP_GPIO_INTERRUPT_IO_DESCRIPTOR, *PPNP_GPIO_INTERRUPT_IO_DESCRIPTOR;

typedef struct _PNP_LARGE_VENDOR_DESCRIPTOR
{
    UCHAR Tag;
    USHORT Length;
    UCHAR SubType;
    GUID UUID;
    UCHAR VendorDescriptor[ANYSIZE_ARRAY];
} PNP_LARGE_VENDOR_DESCRIPTOR, *PPNP_LARGE_VENDOR_DESCRIPTOR;

typedef struct _PNP_FUNCTION_CONFIG_DESCRIPTOR
{
    UCHAR Tag;
    USHORT Length;
    UCHAR Revision;
    USHORT Flags;
    UCHAR PinConfiguration;
    USHORT FunctionNumber;
    USHORT PinTableOffset;
    UCHAR ResourceSourceIndex;
    USHORT ResourceSourceOffset;
    USHORT VendorDataOffset;
    USHORT VendorDataLength;
} PNP_FUNCTION_CONFIG_DESCRIPTOR, *PPNP_FUNCTION_CONFIG_DESCRIPTOR;

typedef struct _PNP_SERIAL_BUS_DESCRIPTOR
{
    UCHAR Tag;
    USHORT Length;
    UCHAR RevisionId;
    UCHAR ResourceSourceIndex;
    UCHAR SerialBusType;
    UCHAR GeneralFlags;
    USHORT TypeSpecificFlags;
    UCHAR TypeSpecificRevisionId;
    USHORT TypeDataLength;
} PNP_SERIAL_BUS_DESCRIPTOR, *PPNP_SERIAL_BUS_DESCRIPTOR;

#include <poppack.h>

#define PNP_GPIO_INTERRUPT_IO_DESCRIPTOR_LENGTH sizeof(PNP_GPIO_INTERRUPT_IO_DESCRIPTOR)
#define PNP_LARGE_VENDOR_DESCRIPTOR_LENGTH sizeof(PNP_LARGE_VENDOR_DESCRIPTOR)
#define PNP_FUNCTION_CONFIG_DESCRIPTOR_LENGTH sizeof(PNP_FUNCTION_CONFIG_DESCRIPTOR)
#define PNP_SERIAL_BUS_DESCRIPTOR_LENGTH sizeof(PNP_SERIAL_BUS_DESCRIPTOR)

#ifdef RESHUB_USE_HELPER_ROUTINES

#if defined(_KERNEL_MODE) || defined(_NTDDK_) || defined(_WDMDDK_)
#include <ntstrsafe.h>

FORCEINLINE
NTSTATUS
RESOURCE_HUB_CREATE_PATH_FROM_ID(
    _Inout_ PUNICODE_STRING FileName,
    _In_ ULONG IdLowPart,
    _In_ ULONG IdHighPart)
{
    if (FileName->MaximumLength < RESOURCE_HUB_CONNECTION_PATH_SIZE)
        return STATUS_BUFFER_TOO_SMALL;

    return RtlUnicodeStringPrintf(FileName,
                                  RESOURCE_HUB_DEVICE_NAME_PREFIX L"%08lx%08lx",
                                  IdHighPart,
                                  IdLowPart);
}
#endif /* kernel mode */

#endif /* RESHUB_USE_HELPER_ROUTINES */

#endif /* NTDDI_VERSION >= NTDDI_WIN8 */
