/*
 * PROJECT:     ReactOS Resource Hub public interface
 * LICENSE:     LGPL-2.1-or-later
 * PURPOSE:     Windows-compatible connection property query ABI
 */

#pragma once

#define RESOURCE_HUB_DEVICE_NAME L"\\Device\\RESOURCE_HUB"
#define RESOURCE_HUB_SYMBOLIC_NAME L"\\DosDevices\\RESOURCE_HUB"
#define RESOURCE_HUB_DEVICE_NAME_PREFIX RESOURCE_HUB_DEVICE_NAME L"\\"

#define FILE_DEVICE_RESOURCE_HUB FILE_DEVICE_BUS_EXTENDER

#define IOCTL_RH_QUERY_CONNECTION_PROPERTIES CTL_CODE(FILE_DEVICE_RESOURCE_HUB, 0x0, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#define RH_QUERY_CONNECTION_PROPERTIES_INPUT_VERSION 1
#define RH_QUERY_CONNECTION_PROPERTIES_OUTPUT_VERSION 1

typedef enum _RH_QUERY_CONNECTION_PROPERTIES_INPUT_TYPE
{
    ConnectionIdType,
    InterruptVectorType
} RH_QUERY_CONNECTION_PROPERTIES_INPUT_TYPE, *PRH_QUERY_CONNECTION_PROPERTIES_INPUT_TYPE;

typedef struct _RH_QUERY_CONNECTION_PROPERTIES_INPUT_BUFFER
{
    ULONG Version;
    RH_QUERY_CONNECTION_PROPERTIES_INPUT_TYPE QueryType;
    union
    {
        LARGE_INTEGER ConnectionId;
        ULONG InterruptVector;
    } u;
} RH_QUERY_CONNECTION_PROPERTIES_INPUT_BUFFER, *PRH_QUERY_CONNECTION_PROPERTIES_INPUT_BUFFER;

typedef struct _RH_QUERY_CONNECTION_PROPERTIES_OUTPUT_BUFFER
{
    ULONG Version;
    ULONG PropertiesLength;
    UCHAR ConnectionProperties[ANYSIZE_ARRAY];
} RH_QUERY_CONNECTION_PROPERTIES_OUTPUT_BUFFER, *PRH_QUERY_CONNECTION_PROPERTIES_OUTPUT_BUFFER;
