#ifndef __WINDOT11_H__
#define __WINDOT11_H__

#ifndef _NTDDNDIS_
#include <ntddndis.h>
#endif
#include <wlantypes.h>

/* Enumerations */

#if defined(__midl) || defined(__WIDL__)
typedef [v1_enum] enum _DOT11_PHY_TYPE {
#else
typedef enum _DOT11_PHY_TYPE {
#endif
    dot11_phy_type_unknown,
    dot11_phy_type_any,
    dot11_phy_type_fhss,
    dot11_phy_type_dsss,
    dot11_phy_type_irbaseband,
    dot11_phy_type_ofdm,
    dot11_phy_type_hrdsss,
    dot11_phy_type_erp,
    dot11_phy_type_ht,
    dot11_phy_type_IHV_start,
    dot11_phy_type_IHV_end
} DOT11_PHY_TYPE;

typedef enum _DOT11_AUTH_ALGORITHM {
    DOT11_AUTH_ALGO_80211_OPEN         = 1,
    DOT11_AUTH_ALGO_80211_SHARED_KEY,
    DOT11_AUTH_ALGO_WPA,
    DOT11_AUTH_ALGO_WPA_PSK,
    DOT11_AUTH_ALGO_WPA_NONE,
    DOT11_AUTH_ALGO_RSNA,
    DOT11_AUTH_ALGO_RSNA_PSK,
    DOT11_AUTH_ALGO_WPA3,
#if (NTDDI_VERSION >= NTDDI_WIN10_FE)
    DOT11_AUTH_ALGO_WPA3_ENT_192       = DOT11_AUTH_ALGO_WPA3,
#endif
    DOT11_AUTH_ALGO_WPA3_SAE,
#if (NTDDI_VERSION >= NTDDI_WIN10_VB)
    DOT11_AUTH_ALGO_OWE,
#endif
#if (NTDDI_VERSION >= NTDDI_WIN10_FE)
    DOT11_AUTH_ALGO_WPA3_ENT,
#endif
    DOT11_AUTH_ALGO_IHV_START          = 0x80000000,
    DOT11_AUTH_ALGO_IHV_END            = 0xffffffff
} DOT11_AUTH_ALGORITHM;

typedef enum _DOT11_CIPHER_ALGORITHM {
    DOT11_CIPHER_ALGO_NONE            = 0x00,
    DOT11_CIPHER_ALGO_WEP40           = 0x01,
    DOT11_CIPHER_ALGO_TKIP            = 0x02,
    DOT11_CIPHER_ALGO_CCMP            = 0x04,
    DOT11_CIPHER_ALGO_WEP104          = 0x05,
    DOT11_CIPHER_ALGO_WPA_USE_GROUP   = 0x100,
    DOT11_CIPHER_ALGO_RSN_USE_GROUP   = 0x100,
    DOT11_CIPHER_ALGO_WEP             = 0x101,
    DOT11_CIPHER_ALGO_IHV_START       = 0x80000000,
    DOT11_CIPHER_ALGO_IHV_END         = 0xffffffff
} DOT11_CIPHER_ALGORITHM;

/* Types */

#if defined(__midl) || defined(__WIDL__)
typedef struct _DOT11_MAC_ADDRESS {
    UCHAR ucDot11MacAddress[6];
} DOT11_MAC_ADDRESS, *PDOT11_MAC_ADDRESS;
#else
typedef UCHAR DOT11_MAC_ADDRESS[6];
typedef DOT11_MAC_ADDRESS* PDOT11_MAC_ADDRESS;
#endif

typedef struct _DOT11_SSID {
    ULONG uSSIDLength;
    UCHAR ucSSID[DOT11_SSID_MAX_LENGTH];
} DOT11_SSID, *PDOT11_SSID;

typedef struct _DOT11_BSSID_LIST {
#define DOT11_BSSID_LIST_REVISION_1     1
    NDIS_OBJECT_HEADER Header;
    ULONG uNumOfEntries;
    ULONG uTotalNumOfEntries;
#if defined(__midl) || defined(__WIDL__)
    [size_is(uTotalNumOfEntries)] DOT11_MAC_ADDRESS BSSIDs[*];
#else
    DOT11_MAC_ADDRESS BSSIDs[1];
#endif
} DOT11_BSSID_LIST, *PDOT11_BSSID_LIST;

/* ============================================================================
 * Native 802.11 (NDIS 6.20) miniport interface — OIDs and operation structures.
 * ============================================================================ */

#define DOT11_MAX_PDU_SIZE          2346
#define DOT11_MIN_PDU_SIZE          256
#define DOT11_RATE_SET_MAX_LENGTH   126
#define DOT11_MAX_NUM_DEFAULT_KEY   4

/* A counted byte array used by several dot11 OIDs. */
typedef struct _DOT11_BYTE_ARRAY {
#define DOT11_BYTE_ARRAY_REVISION_1     1
    NDIS_OBJECT_HEADER Header;
    ULONG uNumOfBytes;
    ULONG uTotalNumOfBytes;
    UCHAR ucBuffer[1];
} DOT11_BYTE_ARRAY, *PDOT11_BYTE_ARRAY;

typedef struct _DOT11_RATE_SET {
    ULONG uRateSetLength;
    UCHAR ucRateSet[DOT11_RATE_SET_MAX_LENGTH];
} DOT11_RATE_SET, *PDOT11_RATE_SET;

typedef struct DOT11_PHY_TYPE_LIST {
#define DOT11_PHY_TYPE_LIST_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    ULONG uNumOfEntries;
    ULONG uTotalNumOfEntries;
    DOT11_PHY_TYPE dot11PhyType[1];
} DOT11_PHY_TYPE_LIST, *PDOT11_PHY_TYPE_LIST;

/* --- OID definition macros ------------------------------------------------ */
#define OID_DOT11_NDIS_START        0x0D010300

#define NWF_MANDATORY_OID           (0x01U)
#define NWF_OPTIONAL_OID            (0x02U)
#define NWF_OPERATIONAL_OID         (0x01U)
#define NWF_STATISTICS_OID          (0x02U)

#define NWF_DEFINE_OID(Seq, o, m)   ((0x0E000000U) | ((o) << 16) | ((m) << 8) | (Seq))

/* --- Core station (STA) OIDs (NDIS_START block) --------------------------- */
#define OID_DOT11_OFFLOAD_CAPABILITY            (OID_DOT11_NDIS_START + 0)
#define OID_DOT11_MPDU_MAX_LENGTH               (OID_DOT11_NDIS_START + 6)
#define OID_DOT11_OPERATION_MODE_CAPABILITY     (OID_DOT11_NDIS_START + 7)
#define OID_DOT11_CURRENT_OPERATION_MODE        (OID_DOT11_NDIS_START + 8)
#define OID_DOT11_CURRENT_PACKET_FILTER         (OID_DOT11_NDIS_START + 9)
#define OID_DOT11_ATIM_WINDOW                   (OID_DOT11_NDIS_START + 10)
#define OID_DOT11_SCAN_REQUEST                  (OID_DOT11_NDIS_START + 11)
#define OID_DOT11_CURRENT_PHY_TYPE              (OID_DOT11_NDIS_START + 12)
#define OID_DOT11_JOIN_REQUEST                  (OID_DOT11_NDIS_START + 13)
#define OID_DOT11_START_REQUEST                 (OID_DOT11_NDIS_START + 14)
#define OID_DOT11_UPDATE_IE                     (OID_DOT11_NDIS_START + 15)
#define OID_DOT11_RESET_REQUEST                 (OID_DOT11_NDIS_START + 16)
#define OID_DOT11_NIC_POWER_STATE               (OID_DOT11_NDIS_START + 17)
#define OID_DOT11_STATION_ID                    (OID_DOT11_NDIS_START + 20)
#define OID_DOT11_OPERATIONAL_RATE_SET          (OID_DOT11_NDIS_START + 26)
#define OID_DOT11_BEACON_PERIOD                 (OID_DOT11_NDIS_START + 27)
#define OID_DOT11_MAC_ADDRESS                   (OID_DOT11_NDIS_START + 30)
#define OID_DOT11_RTS_THRESHOLD                 (OID_DOT11_NDIS_START + 31)
#define OID_DOT11_SHORT_RETRY_LIMIT             (OID_DOT11_NDIS_START + 32)
#define OID_DOT11_LONG_RETRY_LIMIT              (OID_DOT11_NDIS_START + 33)
#define OID_DOT11_FRAGMENTATION_THRESHOLD       (OID_DOT11_NDIS_START + 34)
#define OID_DOT11_COUNTERS_ENTRY                (OID_DOT11_NDIS_START + 37)
#define OID_DOT11_SUPPORTED_PHY_TYPES           (OID_DOT11_NDIS_START + 38)
#define OID_DOT11_CURRENT_REG_DOMAIN            (OID_DOT11_NDIS_START + 39)
#define OID_DOT11_CURRENT_CHANNEL_NUMBER        (OID_DOT11_NDIS_START + 47)
#define OID_DOT11_CURRENT_FREQUENCY             (OID_DOT11_NDIS_START + 66)
#define OID_DOT11_SUPPORTED_DATA_RATES_VALUE    (OID_DOT11_NDIS_START + 65)

/* --- Managed STA control OIDs (NWF_DEFINE_OID block) ---------------------- */
#define OID_DOT11_AUTO_CONFIG_ENABLED               NWF_DEFINE_OID(120, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_ENUM_BSS_LIST                     NWF_DEFINE_OID(121, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_FLUSH_BSS_LIST                    NWF_DEFINE_OID(122, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_POWER_MGMT_REQUEST                NWF_DEFINE_OID(123, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_DESIRED_SSID_LIST                 NWF_DEFINE_OID(124, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_EXCLUDED_MAC_ADDRESS_LIST         NWF_DEFINE_OID(125, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_DESIRED_BSSID_LIST                NWF_DEFINE_OID(126, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_DESIRED_BSS_TYPE                  NWF_DEFINE_OID(127, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_PMKID_LIST                        NWF_DEFINE_OID(128, NWF_OPERATIONAL_OID, NWF_OPTIONAL_OID)
#define OID_DOT11_CONNECT_REQUEST                   NWF_DEFINE_OID(129, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_EXCLUDE_UNENCRYPTED               NWF_DEFINE_OID(130, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_STATISTICS                        NWF_DEFINE_OID(131, NWF_STATISTICS_OID, NWF_MANDATORY_OID)
#define OID_DOT11_PRIVACY_EXEMPTION_LIST            NWF_DEFINE_OID(132, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_ENABLED_AUTHENTICATION_ALGORITHM  NWF_DEFINE_OID(133, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_SUPPORTED_UNICAST_ALGORITHM_PAIR  NWF_DEFINE_OID(134, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_ENABLED_UNICAST_CIPHER_ALGORITHM  NWF_DEFINE_OID(135, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_SUPPORTED_MULTICAST_ALGORITHM_PAIR NWF_DEFINE_OID(136, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_ENABLED_MULTICAST_CIPHER_ALGORITHM NWF_DEFINE_OID(137, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_CIPHER_DEFAULT_KEY_ID             NWF_DEFINE_OID(138, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_CIPHER_DEFAULT_KEY                NWF_DEFINE_OID(139, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_CIPHER_KEY_MAPPING_KEY            NWF_DEFINE_OID(140, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_ENUM_ASSOCIATION_INFO             NWF_DEFINE_OID(141, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_DISCONNECT_REQUEST                NWF_DEFINE_OID(142, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_UNICAST_USE_GROUP_ENABLED         NWF_DEFINE_OID(143, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_HARDWARE_PHY_STATE                NWF_DEFINE_OID(144, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_DESIRED_PHY_LIST                  NWF_DEFINE_OID(145, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_CURRENT_PHY_ID                    NWF_DEFINE_OID(146, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_MEDIA_STREAMING_ENABLED           NWF_DEFINE_OID(147, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_UNREACHABLE_DETECTION_THRESHOLD   NWF_DEFINE_OID(148, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_ACTIVE_PHY_LIST                   NWF_DEFINE_OID(149, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_EXTSTA_CAPABILITY                 NWF_DEFINE_OID(150, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_DATA_RATE_MAPPING_TABLE           NWF_DEFINE_OID(151, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_SUPPORTED_COUNTRY_OR_REGION_STRING NWF_DEFINE_OID(152, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_DESIRED_COUNTRY_OR_REGION_STRING  NWF_DEFINE_OID(153, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_PORT_STATE_NOTIFICATION           NWF_DEFINE_OID(154, NWF_OPERATIONAL_OID, NWF_OPTIONAL_OID)
#define OID_DOT11_SAFE_MODE_ENABLED                 NWF_DEFINE_OID(157, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_HIDDEN_NETWORK_ENABLED            NWF_DEFINE_OID(158, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)
#define OID_DOT11_ASSOCIATION_PARAMS                NWF_DEFINE_OID(159, NWF_OPERATIONAL_OID, NWF_MANDATORY_OID)

typedef struct DOT11_DATA_RATE_MAPPING_ENTRY {
    UCHAR ucDataRateIndex;
    UCHAR ucDataRateFlag;
    USHORT usDataRateValue;
} DOT11_DATA_RATE_MAPPING_ENTRY, *PDOT11_DATA_RATE_MAPPING_ENTRY;

typedef struct _DOT11_DATA_RATE_MAPPING_TABLE {
#define DOT11_DATA_RATE_MAPPING_TABLE_REVISION_1    1
    NDIS_OBJECT_HEADER Header;
    ULONG uDataRateMappingLength;
    DOT11_DATA_RATE_MAPPING_ENTRY DataRateMappingEntries[DOT11_RATE_SET_MAX_LENGTH];
} DOT11_DATA_RATE_MAPPING_TABLE, *PDOT11_DATA_RATE_MAPPING_TABLE;

#define DOT11_DATA_RATE_NON_STANDARD                0x01U
#define DOT11_DATA_RATE_INDEX_MASK                  0x7FU

/* --- Private dot11 OIDs (1024 reserved entries above NDIS_START) ---------- */
#define OID_DOT11_PRIVATE_OIDS_START                (OID_DOT11_NDIS_START + 1024)
#define OID_DOT11_CURRENT_ADDRESS                   (OID_DOT11_PRIVATE_OIDS_START + 2)
#define OID_DOT11_PERMANENT_ADDRESS                 (OID_DOT11_PRIVATE_OIDS_START + 3)
#define OID_DOT11_MULTICAST_LIST                    (OID_DOT11_PRIVATE_OIDS_START + 4)
#define OID_DOT11_MAXIMUM_LIST_SIZE                 (OID_DOT11_PRIVATE_OIDS_START + 5)

/* --- Operation mode (OID_DOT11_OPERATION_MODE_CAPABILITY) ----------------- */
#define DOT11_OPERATION_MODE_UNKNOWN            0x00000000
#define DOT11_OPERATION_MODE_STATION            0x00000001
#define DOT11_OPERATION_MODE_AP                 0x00000002
#define DOT11_OPERATION_MODE_EXTENSIBLE_STATION 0x00000004
#define DOT11_OPERATION_MODE_EXTENSIBLE_AP      0x00000008
#define DOT11_OPERATION_MODE_WFD_DEVICE         0x00000010
#define DOT11_OPERATION_MODE_WFD_GROUP_OWNER    0x00000020
#define DOT11_OPERATION_MODE_WFD_CLIENT         0x00000040
#define DOT11_OPERATION_MODE_MANUFACTURING      0x40000000
#define DOT11_OPERATION_MODE_NETWORK_MONITOR    0x80000000

typedef struct _DOT11_OPERATION_MODE_CAPABILITY {
    ULONG uReserved;
    ULONG uMajorVersion;
    ULONG uMinorVersion;
    ULONG uNumOfTXBuffers;
    ULONG uNumOfRXBuffers;
    ULONG uOpModeCapability;
} DOT11_OPERATION_MODE_CAPABILITY, *PDOT11_OPERATION_MODE_CAPABILITY;

typedef struct _DOT11_CURRENT_OPERATION_MODE {
    ULONG uReserved;
    ULONG uCurrentOpMode;
} DOT11_CURRENT_OPERATION_MODE, *PDOT11_CURRENT_OPERATION_MODE;

/* --- Packet filter (OID_DOT11_CURRENT_PACKET_FILTER) ---------------------- */
#define DOT11_PACKET_TYPE_DIRECTED_CTRL         0x00000001
#define DOT11_PACKET_TYPE_DIRECTED_MGMT         0x00000002
#define DOT11_PACKET_TYPE_DIRECTED_DATA         0x00000004
#define DOT11_PACKET_TYPE_MULTICAST_CTRL        0x00000008
#define DOT11_PACKET_TYPE_MULTICAST_MGMT        0x00000010
#define DOT11_PACKET_TYPE_MULTICAST_DATA        0x00000020
#define DOT11_PACKET_TYPE_BROADCAST_CTRL        0x00000040
#define DOT11_PACKET_TYPE_BROADCAST_MGMT        0x00000080
#define DOT11_PACKET_TYPE_BROADCAST_DATA        0x00000100
#define DOT11_PACKET_TYPE_PROMISCUOUS_CTRL      0x00000200
#define DOT11_PACKET_TYPE_PROMISCUOUS_MGMT      0x00000400
#define DOT11_PACKET_TYPE_PROMISCUOUS_DATA      0x00000800
#define DOT11_PACKET_TYPE_ALL_MULTICAST_CTRL    0x00001000
#define DOT11_PACKET_TYPE_ALL_MULTICAST_MGMT    0x00002000
#define DOT11_PACKET_TYPE_ALL_MULTICAST_DATA    0x00004000

/* --- Scan (OID_DOT11_SCAN_REQUEST) ---------------------------------------- */
typedef enum _DOT11_SCAN_TYPE {
    dot11_scan_type_active = 1,
    dot11_scan_type_passive = 2,
    dot11_scan_type_auto = 3,
    dot11_scan_type_forced = 0x80000000
} DOT11_SCAN_TYPE, *PDOT11_SCAN_TYPE;

typedef enum _CH_DESCRIPTION_TYPE {
    ch_description_type_logical = 1,
    ch_description_type_center_frequency = 2,
    ch_description_type_phy_specific = 3
} CH_DESCRIPTION_TYPE, *PCH_DESCRIPTION_TYPE;

typedef struct _DOT11_SCAN_REQUEST {
    DOT11_BSS_TYPE dot11BSSType;
    DOT11_MAC_ADDRESS dot11BSSID;
    DOT11_SSID dot11SSID;
    DOT11_SCAN_TYPE dot11ScanType;
    BOOLEAN bRestrictedScan;
    BOOLEAN bUseRequestIE;
    ULONG uRequestIDsOffset;
    ULONG uNumOfRequestIDs;
    ULONG uPhyTypesOffset;
    ULONG uNumOfPhyTypes;
    ULONG uIEsOffset;
    ULONG uIEsLength;
    UCHAR ucBuffer[1];
} DOT11_SCAN_REQUEST, *PDOT11_SCAN_REQUEST;

typedef struct _DOT11_PHY_TYPE_INFO {
    DOT11_PHY_TYPE dot11PhyType;
    BOOLEAN bUseParameters;
    ULONG uProbeDelay;
    ULONG uMinChannelTime;
    ULONG uMaxChannelTime;
    CH_DESCRIPTION_TYPE ChDescriptionType;
    ULONG uChannelListSize;
    UCHAR ucChannelListBuffer[1];
} DOT11_PHY_TYPE_INFO, *PDOT11_PHY_TYPE_INFO;

typedef struct _DOT11_SCAN_REQUEST_V2 {
    DOT11_BSS_TYPE dot11BSSType;
    DOT11_MAC_ADDRESS dot11BSSID;
    DOT11_SCAN_TYPE dot11ScanType;
    BOOLEAN bRestrictedScan;
    ULONG udot11SSIDsOffset;
    ULONG uNumOfdot11SSIDs;
    BOOLEAN bUseRequestIE;
    ULONG uRequestIDsOffset;
    ULONG uNumOfRequestIDs;
    ULONG uPhyTypeInfosOffset;
    ULONG uNumOfPhyTypeInfos;
    ULONG uIEsOffset;
    ULONG uIEsLength;
    UCHAR ucBuffer[1];
} DOT11_SCAN_REQUEST_V2, *PDOT11_SCAN_REQUEST_V2;

/* --- Data-path out-of-band contexts (per-NBL MediaSpecificInformation) -----
 * An ExtSTA miniport carries these on each NET_BUFFER_LIST: the send context
 * on transmit, the receive context (RSSI, rate, channel, timestamp) on
 * indicate. */
/* Values for DOT11_EXTSTA_SEND_CONTEXT.usExemptionActionType: control whether a
 * frame is sent in the clear on an otherwise-encrypted link (used for EAPOL). */
#define DOT11_EXEMPT_NO_EXEMPTION                       0
#define DOT11_EXEMPT_ALWAYS                             1
#define DOT11_EXEMPT_ON_KEY_MAPPING_KEY_UNAVAILABLE     2

typedef struct DOT11_EXTSTA_SEND_CONTEXT {
#define DOT11_EXTSTA_SEND_CONTEXT_REVISION_1    1
    NDIS_OBJECT_HEADER Header;
    USHORT usExemptionActionType;
    ULONG uPhyId;
    ULONG uDelayedSleepValue;
    PVOID pvMediaSpecificInfo;
    ULONG uSendFlags;
} DOT11_EXTSTA_SEND_CONTEXT, *PDOT11_EXTSTA_SEND_CONTEXT;

#define DOT11_RECV_FLAG_RAW_PACKET              0x00000001U
#define DOT11_RECV_FLAG_RAW_PACKET_FCS_FAILURE  0x00000002U
#define DOT11_RECV_FLAG_RAW_PACKET_TIMESTAMP    0x00000004U

typedef struct DOT11_EXTSTA_RECV_CONTEXT {
#define DOT11_EXTSTA_RECV_CONTEXT_REVISION_1    1
    NDIS_OBJECT_HEADER Header;
    ULONG uReceiveFlags;
    ULONG uPhyId;
    ULONG uChCenterFrequency;
    USHORT usNumberOfMPDUsReceived;
    LONG lRSSI;
    UCHAR ucDataRate;
    ULONG uSizeMediaSpecificInfo;
    PVOID pvMediaSpecificInfo;
    ULONGLONG ullTimestamp;
} DOT11_EXTSTA_RECV_CONTEXT, *PDOT11_EXTSTA_RECV_CONTEXT;

/* ============================================================================
 * Scan-result, connection/association indication payloads, and cipher-key
 * set structures.
 * ============================================================================ */

/* --- Status indication payload (NDIS_STATUS_MEDIA_SPECIFIC_INDICATION) ----- *
 * Carried by simple confirm indications such as NDIS_STATUS_DOT11_SCAN_CONFIRM:
 * uStatusType identifies the confirm (DOT11_STATUS_SCAN_CONFIRM, etc.) and
 * ndisStatus is the per-operation result. */
typedef struct _DOT11_STATUS_INDICATION {
    ULONG uStatusType;
    NDIS_STATUS ndisStatus;
} DOT11_STATUS_INDICATION, *PDOT11_STATUS_INDICATION;

#define DOT11_STATUS_SCAN_CONFIRM                   1
#define DOT11_STATUS_JOIN_CONFIRM                   2
#define DOT11_STATUS_START_CONFIRM                  3
#define DOT11_STATUS_RESET_CONFIRM                  4
#define DOT11_STATUS_AP_JOIN_CONFIRM                5
#define DOT11_STATUS_MPDU_MAX_LENGTH_CHANGED        6

/* --- Connection/association lists (OID_DOT11_DESIRED_SSID_LIST etc.) ------- */

/* A list of DOT11_SSID (OID_DOT11_DESIRED_SSID_LIST). */
typedef struct DOT11_SSID_LIST {
#define DOT11_SSID_LIST_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    ULONG uNumOfEntries;
    ULONG uTotalNumOfEntries;
    DOT11_SSID SSIDs[1];
} DOT11_SSID_LIST, *PDOT11_SSID_LIST;

/* A list of DOT11_MAC_ADDRESS (OID_DOT11_EXCLUDED_MAC_ADDRESS_LIST). */
typedef struct DOT11_MAC_ADDRESS_LIST {
#define DOT11_MAC_ADDRESS_LIST_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    ULONG uNumOfEntries;
    ULONG uTotalNumOfEntries;
    DOT11_MAC_ADDRESS MacAddrs[1];
} DOT11_MAC_ADDRESS_LIST, *PDOT11_MAC_ADDRESS_LIST;

/* A list of DOT11_AUTH_ALGORITHM (OID_DOT11_ENABLED_AUTHENTICATION_ALGORITHM). */
typedef struct DOT11_AUTH_ALGORITHM_LIST {
#define DOT11_AUTH_ALGORITHM_LIST_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    ULONG uNumOfEntries;
    ULONG uTotalNumOfEntries;
    DOT11_AUTH_ALGORITHM AlgorithmIds[1];
} DOT11_AUTH_ALGORITHM_LIST, *PDOT11_AUTH_ALGORITHM_LIST;

/* A list of DOT11_CIPHER_ALGORITHM (OID_DOT11_ENABLED_UNICAST/MULTICAST_CIPHER). */
typedef struct DOT11_CIPHER_ALGORITHM_LIST {
#define DOT11_CIPHER_ALGORITHM_LIST_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    ULONG uNumOfEntries;
    ULONG uTotalNumOfEntries;
    DOT11_CIPHER_ALGORITHM AlgorithmIds[1];
} DOT11_CIPHER_ALGORITHM_LIST, *PDOT11_CIPHER_ALGORITHM_LIST;

/* --- Scan result list (OID_DOT11_ENUM_BSS_LIST) --------------------------- *
 * Returned as a DOT11_BYTE_ARRAY whose ucBuffer is a packed sequence of
 * variable-length DOT11_BSS_ENTRY records (each uBufferLength bytes of IEs
 * follow the fixed part). */
#define DOT11_BSS_ENTRY_BYTE_ARRAY_REVISION_1   1

typedef union DOT11_BSS_ENTRY_PHY_SPECIFIC_INFO {
    ULONG uChCenterFrequency;
    struct {
        ULONG uHopPattern;
        ULONG uHopSet;
        ULONG uDwellTime;
    } FHSS;
} DOT11_BSS_ENTRY_PHY_SPECIFIC_INFO, *PDOT11_BSS_ENTRY_PHY_SPECIFIC_INFO;

typedef struct DOT11_BSS_ENTRY {
    ULONG uPhyId;
    DOT11_BSS_ENTRY_PHY_SPECIFIC_INFO PhySpecificInfo;
    DOT11_MAC_ADDRESS dot11BSSID;
    DOT11_BSS_TYPE dot11BSSType;
    LONG lRSSI;
    ULONG uLinkQuality;
    BOOLEAN bInRegDomain;
    USHORT usBeaconPeriod;
    ULONGLONG ullTimestamp;
    ULONGLONG ullHostTimestamp;
    USHORT usCapabilityInformation;
    ULONG uBufferLength;
    UCHAR ucBuffer[1];          /* Must be the last field. */
} DOT11_BSS_ENTRY, *PDOT11_BSS_ENTRY;

/* --- Association / connection / disassociation indication payloads -------- */

typedef struct DOT11_ASSOCIATION_START_PARAMETERS {
#define DOT11_ASSOCIATION_START_PARAMETERS_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    DOT11_MAC_ADDRESS MacAddr;
    DOT11_SSID SSID;
    ULONG uIHVDataOffset, uIHVDataSize;
} DOT11_ASSOCIATION_START_PARAMETERS, *PDOT11_ASSOCIATION_START_PARAMETERS;

#define DOT11_ENCAP_RFC_1042     1
#define DOT11_ENCAP_802_1H       2
typedef struct DOT11_ENCAP_ENTRY {
    USHORT usEtherType;
    USHORT usEncapType;     /* DOT11_ENCAP_RFC_1042 or DOT11_ENCAP_802_1H */
} DOT11_ENCAP_ENTRY, *PDOT11_ENCAP_ENTRY;

typedef enum DOT11_DS_INFO {
    DOT11_DS_CHANGED,
    DOT11_DS_UNCHANGED,
    DOT11_DS_UNKNOWN
} DOT11_DS_INFO, *PDOT11_DS_INFO;

/* Association status codes (DOT11_ASSOC_STATUS / DOT11_CONNECTION_STATUS). */
typedef ULONG DOT11_ASSOC_STATUS;

#define DOT11_ASSOC_STATUS_SUCCESS                          0
#define DOT11_ASSOC_STATUS_FAILURE                          0x00000001U
#define DOT11_ASSOC_STATUS_UNREACHABLE                      0x00000002U
#define DOT11_ASSOC_STATUS_RADIO_OFF                        0x00000003U
#define DOT11_ASSOC_STATUS_PHY_DISABLED                     0x00000004U
#define DOT11_ASSOC_STATUS_CANCELLED                        0x00000005U
#define DOT11_ASSOC_STATUS_CANDIDATE_LIST_EXHAUSTED         0x00000006U
#define DOT11_ASSOC_STATUS_DISASSOCIATED_BY_OS              0x00000007U
#define DOT11_ASSOC_STATUS_DISASSOCIATED_BY_ROAMING         0x00000008U
#define DOT11_ASSOC_STATUS_DISASSOCIATED_BY_RESET           0x00000009U
#define DOT11_ASSOC_STATUS_SYSTEM_ERROR                     0x0000000aU
#define DOT11_ASSOC_STATUS_ROAMING_BETTER_AP_FOUND          0x0000000bU
#define DOT11_ASSOC_STATUS_ROAMING_ASSOCIATION_LOST         0x0000000cU
#define DOT11_ASSOC_STATUS_ROAMING_ADHOC                    0x0000000dU
#define DOT11_ASSOC_STATUS_PEER_DEAUTHENTICATED             0x00010000U
#define DOT11_ASSOC_STATUS_PEER_DEAUTHENTICATED_START       DOT11_ASSOC_STATUS_PEER_DEAUTHENTICATED
#define DOT11_ASSOC_STATUS_PEER_DEAUTHENTICATED_END         0x0001ffffU
#define DOT11_ASSOC_STATUS_PEER_DISASSOCIATED               0x00020000U
#define DOT11_ASSOC_STATUS_PEER_DISASSOCIATED_START         DOT11_ASSOC_STATUS_PEER_DISASSOCIATED
#define DOT11_ASSOC_STATUS_PEER_DISASSOCIATED_END           0x0002ffffU
#define DOT11_ASSOC_STATUS_ASSOCIATION_RESPONSE             0x00030000U
#define DOT11_ASSOC_STATUS_ASSOCIATION_RESPONSE_START       DOT11_ASSOC_STATUS_ASSOCIATION_RESPONSE
#define DOT11_ASSOC_STATUS_ASSOCIATION_RESPONSE_END         0x0003ffffU
#define DOT11_ASSOC_STATUS_REASON_CODE_MASK                 0xffffU
#define DOT11_ASSOC_STATUS_IHV_START                        0x80000000U
#define DOT11_ASSOC_STATUS_IHV_END                          0xffffffffU

typedef struct DOT11_ASSOCIATION_COMPLETION_PARAMETERS {
#define DOT11_ASSOCIATION_COMPLETION_PARAMETERS_REVISION_1  1
#define DOT11_ASSOCIATION_COMPLETION_PARAMETERS_REVISION_2  2
    NDIS_OBJECT_HEADER Header;
    DOT11_MAC_ADDRESS MacAddr;

    DOT11_ASSOC_STATUS uStatus;

    BOOLEAN bReAssocReq;
    BOOLEAN bReAssocResp;
    ULONG uAssocReqOffset, uAssocReqSize;
    ULONG uAssocRespOffset, uAssocRespSize;
    ULONG uBeaconOffset, uBeaconSize;
    ULONG uIHVDataOffset, uIHVDataSize;

    /* The following fields are valid only for a successful association;
     * for a failure they are zero-ed out. */
    DOT11_AUTH_ALGORITHM AuthAlgo;
    DOT11_CIPHER_ALGORITHM UnicastCipher;
    DOT11_CIPHER_ALGORITHM MulticastCipher;
    ULONG uActivePhyListOffset, uActivePhyListSize;
    BOOLEAN bFourAddressSupported;
    BOOLEAN bPortAuthorized;
    UCHAR ucActiveQoSProtocol;
    DOT11_DS_INFO DSInfo;
    ULONG uEncapTableOffset, uEncapTableSize;
#if (NTDDI_VERSION >= NTDDI_WIN8)
    /* 802.11w parameters. */
    DOT11_CIPHER_ALGORITHM MulticastMgmtCipher;
    ULONG uAssocComebackTime;
#endif
} DOT11_ASSOCIATION_COMPLETION_PARAMETERS, *PDOT11_ASSOCIATION_COMPLETION_PARAMETERS;

typedef struct DOT11_CONNECTION_START_PARAMETERS {
#define DOT11_CONNECTION_START_PARAMETERS_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    DOT11_BSS_TYPE BSSType;
    DOT11_MAC_ADDRESS AdhocBSSID;   /* adhoc mode only */
    DOT11_SSID AdhocSSID;           /* adhoc mode only */
} DOT11_CONNECTION_START_PARAMETERS, *PDOT11_CONNECTION_START_PARAMETERS;

/* For uStatus in DOT11_CONNECTION_COMPLETION/DOT11_ROAMING_COMPLETION. */
#define DOT11_CONNECTION_STATUS_SUCCESS                     DOT11_ASSOC_STATUS_SUCCESS
#define DOT11_CONNECTION_STATUS_FAILURE                     DOT11_ASSOC_STATUS_FAILURE
#define DOT11_CONNECTION_STATUS_CANDIDATE_LIST_EXHAUSTED    DOT11_ASSOC_STATUS_CANDIDATE_LIST_EXHAUSTED
#define DOT11_CONNECTION_STATUS_PHY_POWER_DOWN              DOT11_ASSOC_STATUS_RADIO_OFF
#define DOT11_CONNECTION_STATUS_CANCELLED                   DOT11_ASSOC_STATUS_CANCELLED
#define DOT11_CONNECTION_STATUS_IHV_START                   DOT11_ASSOC_STATUS_IHV_START
#define DOT11_CONNECTION_STATUS_IHV_END                     DOT11_ASSOC_STATUS_IHV_END

typedef struct DOT11_CONNECTION_COMPLETION_PARAMETERS {
#define DOT11_CONNECTION_COMPLETION_PARAMETERS_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    DOT11_ASSOC_STATUS uStatus;     /* DOT11_CONNECTION_STATUS_XXXX */
} DOT11_CONNECTION_COMPLETION_PARAMETERS, *PDOT11_CONNECTION_COMPLETION_PARAMETERS;

typedef struct DOT11_ROAMING_START_PARAMETERS {
#define DOT11_ROAMING_START_PARAMETERS_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    DOT11_MAC_ADDRESS AdhocBSSID;   /* adhoc mode only */
    DOT11_SSID AdhocSSID;           /* adhoc mode only */
    DOT11_ASSOC_STATUS uRoamingReason;
} DOT11_ROAMING_START_PARAMETERS, *PDOT11_ROAMING_START_PARAMETERS;

typedef struct DOT11_ROAMING_COMPLETION_PARAMETERS {
#define DOT11_ROAMING_COMPLETION_PARAMETERS_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    DOT11_ASSOC_STATUS uStatus;     /* DOT11_CONNECTION_STATUS_XXXX */
} DOT11_ROAMING_COMPLETION_PARAMETERS, *PDOT11_ROAMING_COMPLETION_PARAMETERS;

#define DOT11_DISASSOC_REASON_OS                    DOT11_ASSOC_STATUS_DISASSOCIATED_BY_OS
#define DOT11_DISASSOC_REASON_PEER_UNREACHABLE      DOT11_ASSOC_STATUS_UNREACHABLE
#define DOT11_DISASSOC_REASON_PEER_DEAUTHENTICATED  DOT11_ASSOC_STATUS_PEER_DEAUTHENTICATED
#define DOT11_DISASSOC_REASON_PEER_DISASSOCIATED    DOT11_ASSOC_STATUS_PEER_DISASSOCIATED
#define DOT11_DISASSOC_REASON_RADIO_OFF             DOT11_ASSOC_STATUS_RADIO_OFF
#define DOT11_DISASSOC_REASON_PHY_DISABLED          DOT11_ASSOC_STATUS_PHY_DISABLED
#define DOT11_DISASSOC_REASON_IHV_START             DOT11_ASSOC_STATUS_IHV_START
#define DOT11_DISASSOC_REASON_IHV_END               DOT11_ASSOC_STATUS_IHV_END

typedef struct DOT11_DISASSOCIATION_PARAMETERS {
#define DOT11_DISASSOCIATION_PARAMETERS_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    DOT11_MAC_ADDRESS MacAddr;
    DOT11_ASSOC_STATUS uReason;
    ULONG uIHVDataOffset, uIHVDataSize;
} DOT11_DISASSOCIATION_PARAMETERS, *PDOT11_DISASSOCIATION_PARAMETERS;

/* --- Link quality indication (NDIS_STATUS_DOT11_LINK_QUALITY) -------------- */

typedef struct DOT11_LINK_QUALITY_ENTRY {
    DOT11_MAC_ADDRESS PeerMacAddr;
    UCHAR ucLinkQuality;
} DOT11_LINK_QUALITY_ENTRY, *PDOT11_LINK_QUALITY_ENTRY;

typedef struct DOT11_LINK_QUALITY_PARAMETERS {
#define DOT11_LINK_QUALITY_PARAMETERS_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    ULONG uLinkQualityListSize;
    ULONG uLinkQualityListOffset;
} DOT11_LINK_QUALITY_PARAMETERS, *PDOT11_LINK_QUALITY_PARAMETERS;

/* --- MAC/PHY reset request (OID_DOT11_RESET_REQUEST) ----------------------- */

typedef enum _DOT11_RESET_TYPE {
    dot11_reset_type_phy = 1,
    dot11_reset_type_mac = 2,
    dot11_reset_type_phy_and_mac = 3
} DOT11_RESET_TYPE, *PDOT11_RESET_TYPE;

typedef struct _DOT11_RESET_REQUEST {
    DOT11_RESET_TYPE dot11ResetType;
    DOT11_MAC_ADDRESS dot11MacAddress;
    BOOLEAN bSetDefaultMIB;
} DOT11_RESET_REQUEST, *PDOT11_RESET_REQUEST;

/* --- Cipher-key set structures (OID_DOT11_CIPHER_DEFAULT_KEY / MAPPING) ---- */

typedef struct DOT11_CIPHER_DEFAULT_KEY_VALUE {
#define DOT11_CIPHER_DEFAULT_KEY_VALUE_REVISION_1  1
    NDIS_OBJECT_HEADER Header;
    ULONG uKeyIndex;
    DOT11_CIPHER_ALGORITHM AlgorithmId;
    DOT11_MAC_ADDRESS MacAddr;
    BOOLEAN bDelete;
    BOOLEAN bStatic;
    USHORT usKeyLength;
    UCHAR ucKey[1];             /* Must be the last field. */
} DOT11_CIPHER_DEFAULT_KEY_VALUE, *PDOT11_CIPHER_DEFAULT_KEY_VALUE;

typedef struct DOT11_KEY_ALGO_TKIP_MIC {
    UCHAR ucIV48Counter[6];
    ULONG ulTKIPKeyLength;
    ULONG ulMICKeyLength;
    UCHAR ucTKIPMICKeys[1];     /* Must be the last field. */
} DOT11_KEY_ALGO_TKIP_MIC, *PDOT11_KEY_ALGO_TKIP_MIC;

typedef struct DOT11_KEY_ALGO_CCMP {
    UCHAR ucIV48Counter[6];
    ULONG ulCCMPKeyLength;
    UCHAR ucCCMPKey[1];
} DOT11_KEY_ALGO_CCMP, *PDOT11_KEY_ALGO_CCMP;

typedef enum DOT11_DIRECTION {
    DOT11_DIR_INBOUND = 1,
    DOT11_DIR_OUTBOUND,
    DOT11_DIR_BOTH
} DOT11_DIRECTION, *PDOT11_DIRECTION;

#define DOT11_CIPHER_KEY_MAPPING_KEY_VALUE_BYTE_ARRAY_REVISION_1  1
typedef struct DOT11_CIPHER_KEY_MAPPING_KEY_VALUE {
    DOT11_MAC_ADDRESS PeerMacAddr;
    DOT11_CIPHER_ALGORITHM AlgorithmId;
    DOT11_DIRECTION Direction;
    BOOLEAN bDelete;
    BOOLEAN bStatic;
    USHORT usKeyLength;
    UCHAR ucKey[1];             /* Must be the last field. */
} DOT11_CIPHER_KEY_MAPPING_KEY_VALUE, *PDOT11_CIPHER_KEY_MAPPING_KEY_VALUE;

#endif
