add_library(it8613sensor MODULE it8613sensor.c it8613sensor.rc)
set_module_type(it8613sensor kernelmodedriver)
target_link_libraries(it8613sensor wdmguid)
add_importlibs(it8613sensor ntoskrnl hal)
add_cd_file(TARGET it8613sensor DESTINATION reactos/system32/drivers FOR all)
add_driver_inf(it8613sensor it8613sensor.inf)
