@ cdecl UCNV_FROM_U_CALLBACK_SKIP(ptr ptr ptr long long long ptr)
@ cdecl UCNV_FROM_U_CALLBACK_STOP(ptr ptr ptr long long long ptr)
@ cdecl UCNV_FROM_U_CALLBACK_SUBSTITUTE(ptr ptr ptr long long long ptr)
@ cdecl UCNV_TO_U_CALLBACK_SKIP(ptr ptr ptr long long ptr)
@ cdecl UCNV_TO_U_CALLBACK_STOP(ptr ptr ptr long long ptr)
@ cdecl UCNV_TO_U_CALLBACK_SUBSTITUTE(ptr ptr ptr long long ptr)
@ cdecl u_errorName(long)
@ cdecl ucnv_cbFromUWriteUChars(ptr ptr ptr long ptr)
@ cdecl ucnv_cbToUWriteUChars(ptr ptr long long ptr)
@ cdecl ucnv_close(ptr)
@ cdecl ucnv_countAvailable()
@ cdecl ucnv_fromUCountPending(ptr ptr)
@ cdecl ucnv_fromUnicode(ptr ptr ptr ptr ptr ptr long ptr)
@ cdecl ucnv_getAvailableName(long)
@ cdecl ucnv_getFromUCallBack(ptr ptr ptr)
@ cdecl ucnv_getMaxCharSize(ptr)
@ cdecl ucnv_getName(ptr ptr)
@ cdecl ucnv_getStandardName(str str ptr)
@ cdecl ucnv_getToUCallBack(ptr ptr ptr)
@ cdecl ucnv_open(str ptr)
@ cdecl ucnv_reset(ptr)
@ cdecl ucnv_setFromUCallBack(ptr ptr ptr ptr ptr ptr)
@ cdecl ucnv_setToUCallBack(ptr ptr ptr ptr ptr ptr)
@ cdecl ucnv_toUCountPending(ptr ptr)
@ cdecl ucnv_toUnicode(ptr ptr ptr ptr ptr ptr long ptr)
