add_definitions(-DUSE_WINE_TODOS -DWINETEST_USE_DBGSTR_HSTRING -D__WINESRC__)

add_executable(windows_storage_applicationdata_winetest data.c testlist.c)
set_module_type(windows_storage_applicationdata_winetest win32cui)
add_importlibs(windows_storage_applicationdata_winetest combase msvcrt kernel32 ntdll)
add_rostests_file(TARGET windows_storage_applicationdata_winetest RENAME wsdata.exe)
