# D3DKMT thunk stubs (ordinals 1-10) -- return S_OK
1  stdcall D3DKMTCloseAdapter(ptr)
2  stdcall D3DKMTDestroyAllocation(ptr)
3  stdcall D3DKMTDestroyContext(ptr)
4  stdcall D3DKMTDestroyDevice(ptr)
5  stdcall D3DKMTDestroySynchronizationObject(ptr)
6  stdcall D3DKMTQueryAdapterInfo(ptr)
7  stdcall D3DKMTSetDisplayPrivateDriverFormat(ptr)
8  stdcall D3DKMTSignalSynchronizationObject(ptr)
9  stdcall D3DKMTUnlock(ptr)
10 stdcall D3DKMTWaitForSynchronizationObject(ptr)

# Core D3D10 layer functions (ordinals 11-16)
11 stdcall OpenAdapter10(ptr)
12 stdcall OpenAdapter10_2(ptr)
13 stdcall D3D10CoreCreateDevice(ptr ptr long ptr long long ptr)
14 stdcall D3D10CoreGetSupportedVersions(long ptr ptr)
15 stdcall D3D10CoreGetVersion()
16 stdcall D3D10CoreRegisterLayers()

# D3DKMT thunk stubs (ordinals 17-40)
17 stdcall D3DKMTCreateAllocation(ptr)
18 stdcall D3DKMTCreateContext(ptr)
19 stdcall D3DKMTCreateDevice(ptr)
20 stdcall D3DKMTCreateSynchronizationObject(ptr)
21 stdcall D3DKMTEscape(ptr)
22 stdcall D3DKMTGetContextSchedulingPriority(ptr)
23 stdcall D3DKMTGetDeviceState(ptr)
24 stdcall D3DKMTGetDisplayModeList(ptr)
25 stdcall D3DKMTGetMultisampleMethodList(ptr)
26 stdcall D3DKMTGetRuntimeData(ptr)
27 stdcall D3DKMTGetSharedPrimaryHandle(ptr)
28 stdcall D3DKMTLock(ptr)
29 stdcall D3DKMTOpenAdapterFromHdc(ptr)
30 stdcall D3DKMTOpenResource(ptr)
31 stdcall D3DKMTPresent(ptr)
32 stdcall D3DKMTQueryAllocationResidency(ptr)
33 stdcall D3DKMTQueryResourceInfo(ptr)
34 stdcall D3DKMTRender(ptr)
35 stdcall D3DKMTSetAllocationPriority(ptr)
36 stdcall D3DKMTSetContextSchedulingPriority(ptr)
37 stdcall D3DKMTSetDisplayMode(ptr)
38 stdcall D3DKMTSetGammaRamp(ptr)
39 stdcall D3DKMTSetVidPnSourceOwner(ptr)
40 stdcall D3DKMTWaitForVerticalBlankEvent(ptr)
