@ stdcall WppAutoLogStart(ptr ptr ptr)
@ stdcall WppAutoLogStop(ptr)
@ varargs WppAutoLogTrace(ptr long long ptr long)
@ stdcall imp_WppRecorderConfigure(ptr ptr)
@ stdcall imp_WppRecorderIsDefaultLogAvailable(ptr)
@ stdcall imp_WppRecorderLogCreate(ptr ptr ptr)
@ stdcall imp_WppRecorderLogDelete(ptr ptr)
@ stdcall imp_WppRecorderLogGetDefault(ptr)
@ stdcall imp_WppRecorderReplay(ptr int64 long long)
