add_definitions(-DUSE_WINE_TODOS -DWINETEST_USE_DBGSTR_HSTRING -D__WINESRC__)

spec2def(application.exe application.spec)
add_executable(windows_applicationmodel_helper application.c ${CMAKE_CURRENT_BINARY_DIR}/application.def)
set_target_properties(windows_applicationmodel_helper PROPERTIES OUTPUT_NAME application)
set_module_type(windows_applicationmodel_helper win32cui)
target_link_libraries(windows_applicationmodel_helper wine)
add_importlibs(windows_applicationmodel_helper combase advapi32 shlwapi msvcrt kernel32 ntdll)

add_executable(windows_applicationmodel_winetest model.c resource.rc testlist.c)
set_source_files_properties(resource.rc OBJECT_DEPENDS windows_applicationmodel_helper)
add_dependencies(windows_applicationmodel_winetest windows_applicationmodel_helper)
set_module_type(windows_applicationmodel_winetest win32cui)
add_importlibs(windows_applicationmodel_winetest combase advapi32 shlwapi msvcrt kernel32 ntdll)
add_rostests_file(TARGET windows_applicationmodel_winetest RENAME wapp.exe)
