/*
 * PROJECT:     ReactOS Simple Peripheral Bus stack
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Internal Resource Hub to SPB controller interface
 * COPYRIGHT:   Copyright 2026 Ahmed ARIF <arif.ing@outlook.com>
 */

#pragma once

#include <spb.h>

DEFINE_GUID(GUID_REACTOS_SPB_CONTROLLER,
    0x77d4e5c1, 0x861b, 0x4d7c, 0x91, 0x7a, 0x6c, 0x47, 0xf4, 0x58, 0x3e, 0x6c);

#define REACTOS_SPB_INTERFACE_VERSION 1
#define REACTOS_SPB_MAX_TRANSFERS 16

#define IOCTL_INTERNAL_SPB_QUERY_CONTROLLER \
    CTL_CODE(FILE_DEVICE_CONTROLLER, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTERNAL_SPB_EXECUTE_TRANSFER_LIST \
    CTL_CODE(FILE_DEVICE_CONTROLLER, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTERNAL_SPB_LOCK_CONTROLLER \
    CTL_CODE(FILE_DEVICE_CONTROLLER, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTERNAL_SPB_UNLOCK_CONTROLLER \
    CTL_CODE(FILE_DEVICE_CONTROLLER, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define REACTOS_SPB_TRANSFER_FLAG_CONTROLLER_LOCKED 0x00000001

typedef struct _REACTOS_SPB_CONTROLLER_INFO
{
    ULONG Version;
    ULONG Segment;
    ULONG BusNumber;
    ULONG Address;
} REACTOS_SPB_CONTROLLER_INFO, *PREACTOS_SPB_CONTROLLER_INFO;

typedef struct _REACTOS_SPB_TRANSFER
{
    SPB_TRANSFER_DIRECTION Direction;
    ULONG DelayInUs;
    PVOID Buffer;
    ULONG Length;
} REACTOS_SPB_TRANSFER, *PREACTOS_SPB_TRANSFER;

typedef struct _REACTOS_SPB_TRANSFER_LIST
{
    ULONG Version;
    USHORT SlaveAddress;
    USHORT TypeSpecificFlags;
    ULONG ConnectionSpeed;
    ULONG Flags;
    ULONG TransferCount;
    REACTOS_SPB_TRANSFER Transfers[REACTOS_SPB_MAX_TRANSFERS];
} REACTOS_SPB_TRANSFER_LIST, *PREACTOS_SPB_TRANSFER_LIST;
