# PROJECT:     ReactOS Build System
# PURPOSE:     Define the shared compatibility runtime target manifest
# LICENSE:     GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later)
# COPYRIGHT:   Copyright 2026 Ahmed ARIF <arif.ing@outlook.com>

# Portable system DLLs shared by the ARM64EC and i386 WoW64 runtimes.
# Include dynamically loaded DLLs as well as static import dependencies.
# Each nested build compiles these targets for its own architecture.

set(COMPAT_RUNTIME_MODULES
    actxprxy
    advapi32
    advapi32_vista
    advpack
    apphelp
    appxalluserstore
    authz
    avicap32
    avrt
    bcp47langs
    bcrypt
    bcryptprimitives
    browseui
    cabinet
    cfgmgr32
    combase
    comctl32
    comdlg32
    coml2
    compstui
    crypt32
    cryptnet
    cryptsp
    cryptui
    d3dwine
    dbghelp
    d3d10
    d3d10_1
    d3d10core
    d3d11
    d3d12
    d3d8
    d3d9
    d2d1
    d3dcompiler_39
    d3dcompiler_43
    d3dcompiler_47
    dxdiagn
    dcomp
    ddraw
    devmgr
    dhcpcsvc
    dinput8
    dnsapi
    dsound
    dui70
    dwmapi
    dwrite
    dxgi
    dxva2
    evr
    fmifs
    fontsub
    gdi32
    gdi32_vista
    gdiplus
    glu32
    hhctrl
    hid
    hlink
    hnetcfg
    ieframe
    iertutil
    imagehlp
    imm32
    iphlpapi
    jsproxy
    kernel32
    kernel32_vista
    kernelbase_ros
    ksuser
    libjpeg
    libpng
    libtiff
    libxslt
    lpk
    mbedtls
    mf
    mfplat
    mfreadwrite
    mlang
    mmdevapi
    mpr
    msacm32
    msafd
    msctf
    msctfime
    msi
    msimg32
    mspatcha
    msvcrt
    mswsock
    msxml3
    msxml6
    ncrypt
    netapi32
    newdev
    nfs41_np
    normaliz
    nsi
    ntdll_vista
    ntmarta
    ntobjshex
    odbccp32
    ole32
    oleacc
    oleaut32
    opengl32
    powrprof
    printui
    profapi
    propsys
    psapi
    rasadhlp
    riched20
    rpcrt4
    rsaenh
    rtworkq
    samlib
    schannel
    sechost
    secur32
    sensapi
    settingsyncpolicy
    setupapi
    shcore
    shdocvw
    shell32
    shfolder
    shlwapi
    slc
    sndvolsso
    sspicli
    sxs
    twinapi
    ucrtbase
    uiautomationcore
    urlmon
    user32
    user32_vista
    userenv
    usp10
    uxtheme
    version
    vulkan-1
    wbemdisp
    wbemprox
    win32u
    winusb
    windows_ui
    windowscodecs
    winhttp
    wininet
    winlangdb
    winmm
    wdmaud.drv
    winspool
    winsta
    wintrust
    wkscli
    wldap32
    ws2_32
    ws2help
    wshtcpip
    wshunix
    wtsapi32
    wsock32
    xinput1_1
    xinput1_2
    xinput1_3
    xinput1_4
    xinput9_1_0
    xaudio2_9
    xmllite)

# These targets share an output basename with a regular module. Package them
# only under these aliases so they cannot overwrite the regular DLL.
set(COMPAT_RUNTIME_AUXILIARY_MODULES
    comctl32_v6)

set(COMPAT_RUNTIME_ALIASES
    "comctl32_v6=comctl32_v6.dll"
    "kernelbase_ros=kernelbase.dll")
