# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Ahmed ARIF <arif.ing@outlook.com>

function(_optional_write_if_different _path _content)
    if(EXISTS "${_path}")
        file(READ "${_path}" _old)
        if(_old STREQUAL _content)
            return()
        endif()
    endif()
    file(WRITE "${_path}" "${_content}")
endfunction()

set(_optional_entries "")
if(DEFINED OPTIONAL AND EXISTS "${OPTIONAL}")
    file(STRINGS "${OPTIONAL}" _optional_entries)
endif()

if(MODE STREQUAL "list")
    set(_present "")
    foreach(_entry IN LISTS _optional_entries)
        string(FIND "${_entry}" "=" _separator)
        if(_separator LESS 1)
            continue()
        endif()
        math(EXPR _start "${_separator} + 1")
        string(SUBSTRING "${_entry}" ${_start} -1 _source)
        if(EXISTS "${_source}")
            string(APPEND _present "${_entry}\n")
        endif()
    endforeach()

    file(READ "${BASE}" _base)
    string(FIND "${_base}" "\n" _eol)
    set(_content "${_present}${_base}")
    if(_eol GREATER -1)
        string(SUBSTRING "${_base}" 0 ${_eol} _first)
        if(NOT _first MATCHES "=")
            math(EXPR _rest "${_eol} + 1")
            string(SUBSTRING "${_base}" 0 ${_rest} _head)
            string(SUBSTRING "${_base}" ${_rest} -1 _tail)
            set(_content "${_head}${_present}${_tail}")
        endif()
    endif()
    _optional_write_if_different("${OUTPUT}" "${_content}")
elseif(MODE STREQUAL "dff")
    set(_content "")
    foreach(_entry IN LISTS _optional_entries)
        if(NOT _entry MATCHES "^\"([^\"]+)\"")
            continue()
        endif()
        set(_source "${CMAKE_MATCH_1}")
        if(EXISTS "${_source}")
            file(TIMESTAMP "${_source}" _stamp "%Y%m%d%H%M%S" UTC)
            file(SIZE "${_source}" _size)
            string(APPEND _content "; ${_stamp} ${_size}\n${_entry}\n")
        endif()
    endforeach()
    _optional_write_if_different("${OUTPUT}" "${_content}")
elseif(MODE STREQUAL "stamp")
    set(_content "")
    foreach(_entry IN LISTS _optional_entries)
        if(EXISTS "${_entry}")
            file(TIMESTAMP "${_entry}" _stamp "%Y%m%d%H%M%S" UTC)
            file(SIZE "${_entry}" _size)
            string(APPEND _content "${_entry} ${_stamp} ${_size}\n")
        endif()
    endforeach()
    _optional_write_if_different("${OUTPUT}" "${_content}")
elseif(MODE STREQUAL "binary")
    set(_files "${BASE}")
    foreach(_entry IN LISTS _optional_entries)
        string(FIND "${_entry}" "|" _separator)
        if(_separator LESS 1)
            continue()
        endif()
        string(SUBSTRING "${_entry}" 0 ${_separator} _required)
        math(EXPR _start "${_separator} + 1")
        string(SUBSTRING "${_entry}" ${_start} -1 _file)
        if(EXISTS "${_required}")
            list(APPEND _files "${_file}")
        endif()
    endforeach()

    set(_temporary "${OUTPUT}.tmp")
    if(CMAKE_HOST_WIN32)
        set(_sources "")
        foreach(_file IN LISTS _files)
            file(TO_NATIVE_PATH "${_file}" _native)
            if(_sources STREQUAL "")
                set(_sources "${_native}")
            else()
                string(APPEND _sources " + ${_native}")
            endif()
        endforeach()
        file(TO_NATIVE_PATH "${_temporary}" _native_temporary)
        execute_process(COMMAND cmd.exe /C "copy /Y /B ${_sources} ${_native_temporary} > nul"
                        RESULT_VARIABLE _result)
    else()
        execute_process(COMMAND cat ${_files} OUTPUT_FILE "${_temporary}" RESULT_VARIABLE _result)
    endif()
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "Cannot concatenate ${_files} into ${_temporary}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${_temporary}" "${OUTPUT}"
                    RESULT_VARIABLE _result)
    file(REMOVE "${_temporary}")
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "Cannot update ${OUTPUT}")
    endif()
else()
    message(FATAL_ERROR "optional_files.cmake: unknown MODE '${MODE}'")
endif()
