# Generate build-owned assembly from the native module description.
set(_export_names ${EXPORTS})
foreach(_forwarder IN LISTS FORWARDERS)
    if(NOT _forwarder MATCHES "^([A-Za-z_][A-Za-z0-9_]*)=([A-Za-z0-9_.]+\\.[A-Za-z_][A-Za-z0-9_]*)$")
        message(FATAL_ERROR "Invalid RISC-V forwarded export: ${_forwarder}")
    endif()
    set(_forward_name "${CMAKE_MATCH_1}")
    set("_forward_target_${_forward_name}" "${CMAKE_MATCH_2}")
    list(APPEND _export_names "${_forward_name}")
endforeach()
list(LENGTH _export_names _export_count)
list(REMOVE_DUPLICATES _export_names)
list(LENGTH _export_names _unique_export_count)
if(NOT _export_count EQUAL _unique_export_count)
    message(FATAL_ERROR "Duplicate RISC-V native export")
endif()
list(SORT _export_names)

# RVAs are differences between linked symbols, not absolute addresses.
# ADD32/SUB32 pairs must not become HIGHLOW/DIR64 base relocations.
set(_asm "/* Generated PE tables; do not edit. */\n.option norelax\n.option nopic\n.macro rva symbol\n .4byte \\symbol - __riscv_text_start + 0x1000\n.endm\n.section .rdata.ntpe,\"a\",@progbits\n.balign 4\n.globl __riscv_export_start\n__riscv_export_start:\n .4byte 0, 0\n .2byte 0, 0\n rva .Ldll_name\n .4byte 1, ${_export_count}, ${_export_count}\n rva .Leat\n rva .Lnames\n rva .Lordinals\n.Leat:\n")
foreach(_symbol IN LISTS _export_names)
    set(_forward_var "_forward_target_${_symbol}")
    if(DEFINED "${_forward_var}")
        string(APPEND _asm " rva .Lforward_${_symbol}\n")
    else()
        string(APPEND _asm " rva ${_symbol}\n")
    endif()
endforeach()
string(APPEND _asm ".Lnames:\n")
foreach(_symbol IN LISTS _export_names)
    string(APPEND _asm " rva .Lexport_${_symbol}\n")
endforeach()
string(APPEND _asm ".Lordinals:\n")
set(_ordinal 0)
foreach(_symbol IN LISTS _export_names)
    string(APPEND _asm " .2byte ${_ordinal}\n")
    math(EXPR _ordinal "${_ordinal} + 1")
endforeach()
string(APPEND _asm ".Ldll_name: .asciz \"${FILENAME}\"\n")
foreach(_symbol IN LISTS _export_names)
    string(APPEND _asm ".Lexport_${_symbol}: .asciz \"${_symbol}\"\n")
endforeach()
foreach(_symbol IN LISTS _export_names)
    set(_forward_var "_forward_target_${_symbol}")
    if(DEFINED "${_forward_var}")
        string(APPEND _asm ".Lforward_${_symbol}: .asciz \"${${_forward_var}}\"\n")
    endif()
endforeach()
string(APPEND _asm ".globl __riscv_export_end\n__riscv_export_end:\n")

# IMPORTS contains module:function pairs. Only named function imports are
# supported by this bootstrap path; data imports need compiler support.
set(_providers)
set(_imported_symbols)
foreach(_import IN LISTS IMPORTS)
    if(NOT _import MATCHES "^([A-Za-z0-9_.]+):([A-Za-z_][A-Za-z0-9_]*)$")
        message(FATAL_ERROR "Invalid RISC-V function import: ${_import}")
    endif()
    set(_provider "${CMAKE_MATCH_1}")
    set(_symbol "${CMAKE_MATCH_2}")
    if(_symbol IN_LIST _imported_symbols OR _symbol IN_LIST _export_names)
        message(FATAL_ERROR "Conflicting RISC-V function import: ${_import}")
    endif()
    list(APPEND _imported_symbols "${_symbol}")
    list(APPEND _providers "${_provider}")
    list(APPEND _imports_${_provider} "${_symbol}")
endforeach()
list(REMOVE_DUPLICATES _providers)
string(APPEND _asm ".balign 4\n.globl __riscv_import_start\n__riscv_import_start:\n")
foreach(_provider IN LISTS _providers)
    string(APPEND _asm " rva .Lilt_${_provider}\n .4byte 0, 0\n rva .Lmodule_${_provider}\n rva .Liat_${_provider}\n")
endforeach()
string(APPEND _asm " .4byte 0, 0, 0, 0, 0\n.globl __riscv_import_end\n__riscv_import_end:\n")
foreach(_provider IN LISTS _providers)
    string(APPEND _asm ".Lmodule_${_provider}: .asciz \"${_provider}\"\n.balign 8\n.Lilt_${_provider}:\n")
    foreach(_symbol IN LISTS _imports_${_provider})
        string(APPEND _asm " rva .Lhint_${_symbol}\n .4byte 0\n")
    endforeach()
    string(APPEND _asm " .8byte 0\n")
    foreach(_symbol IN LISTS _imports_${_provider})
        string(APPEND _asm ".balign 2\n.Lhint_${_symbol}: .2byte 0\n .asciz \"${_symbol}\"\n")
    endforeach()
endforeach()
string(APPEND _asm ".section .data.ntiat,\"aw\",@progbits\n.balign 8\n.globl __riscv_iat_start\n__riscv_iat_start:\n")
foreach(_provider IN LISTS _providers)
    string(APPEND _asm ".Liat_${_provider}:\n")
    foreach(_symbol IN LISTS _imports_${_provider})
        string(APPEND _asm ".globl __imp_${_symbol}\n__imp_${_symbol}:\n rva .Lhint_${_symbol}\n .4byte 0\n")
    endforeach()
    string(APPEND _asm " .8byte 0\n")
endforeach()
string(APPEND _asm ".globl __riscv_iat_end\n__riscv_iat_end:\n.section .text.ntimports,\"ax\",@progbits\n.balign 4\n")
foreach(_symbol IN LISTS _imported_symbols)
    # t0 is caller-saved. Tail transfer preserves ra, sp, and every argument.
    string(APPEND _asm ".globl ${_symbol}\n.type ${_symbol},@function\n${_symbol}:\n lla t0, __imp_${_symbol}\n ld t0, 0(t0)\n jr t0\n.size ${_symbol}, .-${_symbol}\n")
endforeach()
file(WRITE "${OUTPUT}" "${_asm}")
