set(_files)
set(_collect_files FALSE)
math(EXPR _last_argument "${CMAKE_ARGC} - 1")
foreach(_index RANGE 0 ${_last_argument})
    set(_argument_name "CMAKE_ARGV${_index}")
    set(_argument "${${_argument_name}}")
    if(_collect_files)
        list(APPEND _files "${_argument}")
    elseif(_argument STREQUAL "--")
        set(_collect_files TRUE)
    endif()
endforeach()

if(NOT _files)
    message(FATAL_ERROR "No WoW64 i386 files were provided for validation")
endif()

foreach(_file IN LISTS _files)
    if(NOT EXISTS "${_file}")
        message(FATAL_ERROR "Missing WoW64 i386 file: ${_file}")
    endif()

    file(READ "${_file}" _dos_header LIMIT 64 HEX)
    string(SUBSTRING "${_dos_header}" 0 4 _dos_signature)
    if(NOT _dos_signature STREQUAL "4d5a")
        message(FATAL_ERROR "WoW64 file has no DOS header: ${_file}")
    endif()

    string(SUBSTRING "${_dos_header}" 120 2 _offset_0)
    string(SUBSTRING "${_dos_header}" 122 2 _offset_1)
    string(SUBSTRING "${_dos_header}" 124 2 _offset_2)
    string(SUBSTRING "${_dos_header}" 126 2 _offset_3)
    math(EXPR _pe_offset "0x${_offset_3}${_offset_2}${_offset_1}${_offset_0}")

    file(READ "${_file}" _pe_header OFFSET ${_pe_offset} LIMIT 26 HEX)
    string(SUBSTRING "${_pe_header}" 0 8 _pe_signature)
    string(SUBSTRING "${_pe_header}" 8 4 _machine)
    string(SUBSTRING "${_pe_header}" 48 4 _optional_magic)
    if(NOT _pe_signature STREQUAL "50450000" OR NOT _machine STREQUAL "4c01" OR NOT _optional_magic STREQUAL "0b01")
        message(FATAL_ERROR "WoW64 file is not PE32/i386: ${_file}")
    endif()
endforeach()

list(LENGTH _files _file_count)
message(STATUS "Validated ${_file_count} WoW64 PE32/i386 files")
