/* Automatically generated by make depend; DO NOT EDIT!! */

#define STANDALONE
#include <wine/test.h>

extern void func_msvcirt(void);

const struct test winetest_testlist[] =
{
    { "msvcirt", func_msvcirt },
    { 0, 0 }
};
