/* Automatically generated by make depend; DO NOT EDIT!! */

#define STANDALONE
#include <wine/test.h>

extern void func_crypto(void);

const struct test winetest_testlist[] =
{
    { "crypto", func_crypto },
    { 0, 0 }
};
