@ stdcall WskCaptureProviderNPI(ptr long ptr)
@ stdcall WskDeregister(ptr)
@ stdcall WskRegister(ptr ptr)
@ stdcall WskReleaseProviderNPI(ptr)

; Network Module Registrar (NMR) stubs — dev-nt6-1 branch
@ stdcall NmrRegisterClient(ptr ptr ptr)
@ stdcall NmrDeregisterClient(ptr)
@ stdcall NmrWaitForClientDeregisterComplete(ptr)
@ stdcall NmrRegisterProvider(ptr ptr ptr)
@ stdcall NmrDeregisterProvider(ptr)
@ stdcall NmrWaitForProviderDeregisterComplete(ptr)
@ stdcall NmrClientAttachProvider(ptr ptr ptr ptr ptr)
@ stdcall NmrClientDetachProviderComplete(ptr)
@ stdcall NmrProviderDetachClientComplete(ptr)

; Windows Filtering Platform (WFP) kernel stubs — dev-nt6-1 branch
@ stdcall FwpsCalloutRegister0(ptr ptr ptr)
@ stdcall FwpsCalloutUnregisterById0(long)
@ stdcall FwpsCalloutUnregisterByKey0(ptr)
@ stdcall FwpsAllocateCloneNetBufferList0(ptr ptr ptr long ptr)
@ stdcall FwpsFreeCloneNetBufferList0(ptr long)
@ stdcall FwpsAllocateNetBufferAndNetBufferList0(ptr long long ptr long long ptr)
@ stdcall FwpsInjectNetworkSendAsync0(ptr ptr long long ptr ptr ptr)
@ stdcall FwpsInjectNetworkReceiveAsync0(ptr ptr long long long long ptr ptr ptr)
@ stdcall FwpsInjectionHandleCreate0(long long ptr)
@ stdcall FwpsInjectionHandleDestroy0(ptr)
@ stdcall FwpmEngineOpen0(ptr long ptr ptr ptr)
@ stdcall FwpmEngineClose0(ptr)
@ stdcall FwpmTransactionBegin0(ptr long)
@ stdcall FwpmTransactionCommit0(ptr)
@ stdcall FwpmTransactionAbort0(ptr)
@ stdcall FwpmFilterAdd0(ptr ptr ptr ptr)
@ stdcall FwpmFilterDeleteByKey0(ptr ptr)
@ stdcall FwpmFilterDeleteById0(ptr double)
@ stdcall FwpmFilterGetByKey0(ptr ptr ptr)
@ stdcall FwpmFilterGetById0(ptr double ptr)
@ stdcall FwpmCalloutAdd0(ptr ptr ptr ptr)
@ stdcall FwpmCalloutDeleteByKey0(ptr ptr)
@ stdcall FwpmCalloutDeleteById0(ptr long)
@ stdcall FwpmProviderAdd0(ptr ptr ptr)
@ stdcall FwpmProviderDeleteByKey0(ptr ptr)
@ stdcall FwpmFreeMemory0(ptr)
@ stdcall FwpsCalloutRegister3(ptr ptr ptr)
@ stdcall FwpsFreeNetBufferList0(ptr)
@ stdcall FwpsQueryPacketInjectionState0(ptr ptr ptr)
@ stdcall FwpsVirtualIfTunnelInfoSet0(ptr ptr)
@ stdcall FwpmBfeStateGet0()
@ stdcall FwpmBfeStateSubscribeChanges0(ptr ptr ptr ptr)
@ stdcall FwpmBfeStateUnsubscribeChanges0(ptr)
@ stdcall FwpmSubLayerAdd0(ptr ptr ptr)
@ stdcall FwpmProviderContextAdd3(ptr ptr ptr ptr)
@ stdcall FwpmProviderContextDeleteById0(ptr int64)
@ stdcall FwpmSubLayerDeleteByKey0(ptr ptr)
@ stdcall FwpsCalloutRegister1(ptr ptr ptr)
@ stdcall FwpsCalloutRegister2(ptr ptr ptr)
@ stdcall FwpsFlowAssociateContext0(int64 long long int64)
@ stdcall FwpsFlowRemoveContext0(int64 long long)
@ stdcall FwpsReferenceNetBufferList0(ptr long)
@ stdcall FwpsDereferenceNetBufferList0(ptr long)
@ stdcall FwpsInjectTransportSendAsync0(ptr ptr int64 long ptr long long ptr ptr ptr)
@ stdcall FwpsInjectTransportSendAsync1(ptr ptr int64 long ptr long long ptr ptr ptr)
@ stdcall FwpsInjectTransportReceiveAsync0(ptr ptr ptr long long long long long ptr ptr ptr)
@ stdcall FwpsConstructIpHeaderForTransportPacket0(ptr long long ptr ptr long int64 ptr long long ptr long long)
@ stdcall FwpsCopyStreamDataToBuffer0(ptr ptr ptr ptr)
@ stdcall WfpShimRegister(ptr)
@ stdcall WfpShimDatagramActive()
@ stdcall WfpShimClassifyDatagram(ptr)
@ stdcall WfpShimEndpointClosed(int64)
@ stdcall WfpShimStreamActive()
@ stdcall WfpShimEstablishFlow(ptr)
@ stdcall WfpShimClassifyStream(int64 long ptr long)
@ stdcall IPsecGetStatistics0(ptr ptr)
@ stdcall IPsecSaContextAddInbound1(ptr int64 ptr)
@ stdcall IPsecSaContextAddOutbound1(ptr int64 ptr)
@ stdcall IPsecSaContextCreate1(ptr ptr ptr ptr ptr)
@ stdcall IPsecSaContextCreateEnumHandle0(ptr ptr ptr)
@ stdcall IPsecSaContextDeleteById0(ptr int64)
@ stdcall IPsecSaContextEnum1(ptr ptr long ptr ptr)
@ stdcall IPsecSaContextGetSpi1(ptr int64 ptr ptr)
@ stdcall IPsecSaContextSetSpi0(ptr int64 ptr long)
@ stdcall IPsecSaCreateEnumHandle0(ptr ptr ptr)
@ stdcall IPsecSaDestroyEnumHandle0(ptr ptr)
@ stdcall IPsecSaEnum1(ptr ptr long ptr ptr)

@ stdcall CancelMibChangeNotify2(ptr)
@ stdcall ConvertInterfaceLuidToGuid(ptr ptr)
@ stdcall CreateIpForwardEntry2(ptr)
@ stdcall CreateUnicastIpAddressEntry(ptr)
@ stdcall DeleteIpForwardEntry2(ptr)
@ stdcall DeleteUnicastIpAddressEntry(ptr)
@ stdcall FreeMibTable(ptr)
@ stdcall GetIfEntry2(ptr)
@ stdcall GetIfTable2(ptr)
@ stdcall GetIpForwardTable2(long ptr)
@ stdcall GetIpInterfaceEntry(ptr)
@ stdcall GetIpInterfaceTable(long ptr)
@ stdcall GetUnicastIpAddressEntry(ptr)
@ stdcall GetUnicastIpAddressTable(long ptr)
@ stdcall InitializeIpForwardEntry(ptr)
@ stdcall InitializeIpInterfaceEntry(ptr)
@ stdcall InitializeUnicastIpAddressEntry(ptr)
@ stdcall NotifyIpInterfaceChange(long ptr ptr long ptr)
@ stdcall NotifyUnicastIpAddressChange(long ptr ptr long ptr)
@ stdcall SetInterfaceDnsSettings(long long long long ptr)
@ stdcall SetIpInterfaceEntry(ptr)
