/* Automatically generated by make depend; DO NOT EDIT!! */

#define STANDALONE
#include <wine/test.h>

extern void func_d3d10_1(void);
extern void func_reflection(void);

const struct test winetest_testlist[] =
{
    { "d3d10_1", func_d3d10_1 },
    { "reflection", func_reflection },
    { 0, 0 }
};
