add_executable(runtimeexports_apitest runtimeexports.c)
set_module_type(runtimeexports_apitest win32cui)
target_link_libraries(runtimeexports_apitest ${PSEH_LIB})
add_importlibs(runtimeexports_apitest msvcrt kernel32 ntdll)
add_rostests_file(TARGET runtimeexports_apitest)

add_executable(managedloader_apitest managedloader.c)
set_module_type(managedloader_apitest win32cui)
add_importlibs(managedloader_apitest msvcrt kernel32 ntdll)
add_rostests_file(TARGET managedloader_apitest)

add_executable(nlssortkey_apitest nlssortkey.c)
set_module_type(nlssortkey_apitest win32cui)
add_importlibs(nlssortkey_apitest msvcrt kernel32 ntdll)
add_rostests_file(TARGET nlssortkey_apitest)

add_executable(nlsfind_apitest nlsfind.c)
set_module_type(nlsfind_apitest win32cui)
add_importlibs(nlsfind_apitest msvcrt kernel32 ntdll)
add_rostests_file(TARGET nlsfind_apitest)

if(ARCH STREQUAL "arm64")
    add_executable(unwindptrs_apitest unwindptrs.c)
    set_module_type(unwindptrs_apitest win32cui)
    add_importlibs(unwindptrs_apitest msvcrt kernel32 ntdll)
    add_rostests_file(TARGET unwindptrs_apitest)
endif()

add_executable(localeparent_apitest localeparent.c)
set_module_type(localeparent_apitest win32cui)
add_importlibs(localeparent_apitest msvcrt kernel32 ntdll)
add_rostests_file(TARGET localeparent_apitest)

if(ARCH STREQUAL "arm64")
    add_executable(fanlaunch_apitest fanlaunch.c)
    set_module_type(fanlaunch_apitest win32cui)
    add_importlibs(fanlaunch_apitest msvcrt user32 kernel32 ntdll)
    add_rostests_file(TARGET fanlaunch_apitest)
endif()
