/*
 * PROJECT:     ReactOS WDDM 2.x Graphics Memory Manager and Scheduler
 * LICENSE:     GPL-2.0-or-later
 * PURPOSE:     Private typed contract between dxgkrnl.sys and dxgmms2.sys
 */

#ifndef _REACTOS_DXGMMS2_H_
#define _REACTOS_DXGMMS2_H_

#include <ntddk.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DXGMMS2_ABI_VERSION_1                         0x00010000UL
#define DXGMMS2_ABI_VERSION_2                         0x00020000UL
#define DXGMMS2_ABI_VERSION_3                         0x00030000UL
#define DXGMMS2_SCHEDULER_TIMELINE_VERSION_1          0x00010000UL
#define DXGMMS2_CONTEXT_STREAM_VERSION_1              0x00010000UL

#define DXGMMS2_TIMELINE_FEATURE_FENCE_IDENTITIES     0x00000001UL
#define DXGMMS2_TIMELINE_FEATURE_VALID_MASK           0x00000001UL
#define DXGMMS2_TIMELINE_NOTIFY_PREEMPTED             0x00000001UL
#define DXGMMS2_TIMELINE_NOTIFY_VALID_MASK             0x00000001UL

#define DXGMMS2_ADAPTER_FLAG_DISPLAY_ONLY             0x00000001UL
#define DXGMMS2_ADAPTER_FLAG_PHYSICAL_ADDRESSING      0x00000002UL
#define DXGMMS2_ADAPTER_FLAG_VIRTUAL_ADDRESSING       0x00000004UL
#define DXGMMS2_ADAPTER_FLAG_VALID_MASK               0x00000007UL

#define DXGMMS2_SUBSYSTEM_SCHEDULER                   0x0000000000000001ULL
#define DXGMMS2_SUBSYSTEM_VIDMM                       0x0000000000000002ULL
#define DXGMMS2_SUBSYSTEM_VALID_MASK                  0x0000000000000003ULL

#define DXGMMS2_COMPLETE_STOP_HARDWARE_RETIRED        0x00000001UL
#define DXGMMS2_COMPLETE_STOP_VALID_MASK              0x00000001UL

typedef PVOID DXGMMS2_REGISTRATION_HANDLE;
typedef PVOID DXGMMS2_ADAPTER_HANDLE;
typedef PVOID DXGMMS2_SCHEDULER_TIMELINE_HANDLE;
typedef PVOID DXGMMS2_CONTEXT_STREAM_HANDLE;

typedef enum _DXGMMS2_STOP_REASON
{
    Dxgmms2StopReasonPnpStop = 1,
    Dxgmms2StopReasonRemove = 2,
    Dxgmms2StopReasonSurpriseRemove = 3,
    Dxgmms2StopReasonStartRollback = 4
} DXGMMS2_STOP_REASON;

typedef BOOLEAN (NTAPI *PDXGMMS2_REFERENCE_ADAPTER)(_In_opt_ PVOID ClientContext, _In_ PVOID AdapterCookie);
typedef VOID (NTAPI *PDXGMMS2_DEREFERENCE_ADAPTER)(_In_opt_ PVOID ClientContext, _In_ PVOID AdapterCookie);

/* These callbacks guard future transient reverse calls; v1 retains no adapter reference. */
typedef struct _DXGMMS2_DXGKRNL_INTERFACE_V1
{
    ULONG Size;
    ULONG Version;
    PVOID ClientContext;
    PDXGMMS2_REFERENCE_ADAPTER ReferenceAdapter;
    PDXGMMS2_DEREFERENCE_ADAPTER DereferenceAdapter;
} DXGMMS2_DXGKRNL_INTERFACE_V1, *PDXGMMS2_DXGKRNL_INTERFACE_V1;

typedef struct _DXGMMS2_CREATE_ADAPTER_INFO_V1
{
    ULONG Size;
    ULONG Version;
    PVOID AdapterCookie;
    ULONG AdapterFlags;
    ULONG Reserved;
} DXGMMS2_CREATE_ADAPTER_INFO_V1, *PDXGMMS2_CREATE_ADAPTER_INFO_V1;

typedef struct _DXGMMS2_START_ADAPTER_INFO_V1
{
    ULONG Size;
    ULONG Version;
    ULONG MiniportDdiVersion;
    ULONG RequestedWddmVersion;
    ULONG NodeCount;
    ULONG SegmentCount;
    ULONG AdapterFlags;
    ULONG SchedulingCaps;
} DXGMMS2_START_ADAPTER_INFO_V1, *PDXGMMS2_START_ADAPTER_INFO_V1;

typedef struct _DXGMMS2_START_ADAPTER_RESULT_V1
{
    ULONG Size;
    ULONG Version;
    ULONGLONG EnabledSubsystems;
    ULONG HighestCompleteWddmVersion;
    ULONG Reserved;
} DXGMMS2_START_ADAPTER_RESULT_V1, *PDXGMMS2_START_ADAPTER_RESULT_V1;

typedef struct _DXGMMS2_STOP_ADAPTER_INFO_V1
{
    ULONG Size;
    ULONG Version;
    ULONG Reason;
    ULONG Flags;
} DXGMMS2_STOP_ADAPTER_INFO_V1, *PDXGMMS2_STOP_ADAPTER_INFO_V1;

typedef NTSTATUS (NTAPI *PDXGMMS2_CREATE_ADAPTER)(_In_ DXGMMS2_REGISTRATION_HANDLE Registration, _In_ const DXGMMS2_CREATE_ADAPTER_INFO_V1 *Info, _Out_ DXGMMS2_ADAPTER_HANDLE *Adapter);
typedef NTSTATUS (NTAPI *PDXGMMS2_START_ADAPTER)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ const DXGMMS2_START_ADAPTER_INFO_V1 *Info, _Inout_ DXGMMS2_START_ADAPTER_RESULT_V1 *Result);
typedef NTSTATUS (NTAPI *PDXGMMS2_BEGIN_STOP_ADAPTER)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ const DXGMMS2_STOP_ADAPTER_INFO_V1 *Info);
typedef NTSTATUS (NTAPI *PDXGMMS2_COMPLETE_STOP_ADAPTER)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ const DXGMMS2_STOP_ADAPTER_INFO_V1 *Info);
typedef NTSTATUS (NTAPI *PDXGMMS2_DESTROY_ADAPTER)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter);

typedef struct _DXGMMS2_PROVIDER_INTERFACE_V1
{
    ULONG Size;
    ULONG Version;
    ULONG ProviderFlags;
    ULONG Reserved;
    DXGMMS2_REGISTRATION_HANDLE RegistrationHandle;
    PDXGMMS2_CREATE_ADAPTER CreateAdapter;
    PDXGMMS2_START_ADAPTER StartAdapter;
    PDXGMMS2_BEGIN_STOP_ADAPTER BeginStopAdapter;
    PDXGMMS2_COMPLETE_STOP_ADAPTER CompleteStopAdapter;
    PDXGMMS2_DESTROY_ADAPTER DestroyAdapter;
} DXGMMS2_PROVIDER_INTERFACE_V1, *PDXGMMS2_PROVIDER_INTERFACE_V1;

typedef struct _DXGMMS2_FENCE_SNAPSHOT_V1
{
    ULONG Size;
    ULONG Version;
    ULONG Generation;
    ULONG NodeOrdinal;
    ULONG LastSubmittedFence;
    ULONG LastCompletedFence;
    ULONG GlobalLastCompletedFence;
    ULONG Reserved;
} DXGMMS2_FENCE_SNAPSHOT_V1, *PDXGMMS2_FENCE_SNAPSHOT_V1;

/* Allocate, Reserve, Publish, Notify, Is, and Release are nonpaged,
 * nonblocking callbacks callable from ISR/DIRQL. Notify supplies the ISR
 * snapshot. Reset and Query are PASSIVE_LEVEL-only maintenance operations. */
typedef ULONG (NTAPI *PDXGMMS2_ALLOCATE_FENCE)(_In_ DXGMMS2_SCHEDULER_TIMELINE_HANDLE Timeline, _In_ ULONG Generation);
typedef BOOLEAN (NTAPI *PDXGMMS2_RESERVE_FENCE)(_In_ DXGMMS2_SCHEDULER_TIMELINE_HANDLE Timeline, _In_ ULONG Generation, _In_ ULONG NodeOrdinal, _In_ ULONG FenceId);
typedef BOOLEAN (NTAPI *PDXGMMS2_PUBLISH_FENCE)(_In_ DXGMMS2_SCHEDULER_TIMELINE_HANDLE Timeline, _In_ ULONG Generation, _In_ ULONG NodeOrdinal, _In_ ULONG FenceId);
typedef NTSTATUS (NTAPI *PDXGMMS2_NOTIFY_FENCE_COMPLETION)(_In_ DXGMMS2_SCHEDULER_TIMELINE_HANDLE Timeline, _In_ ULONG Generation, _In_ ULONG NodeOrdinal, _In_ ULONG FenceId, _In_ ULONG Flags, _Inout_ DXGMMS2_FENCE_SNAPSHOT_V1 *Snapshot);
typedef BOOLEAN (NTAPI *PDXGMMS2_IS_FENCE_PUBLISHED)(_In_ DXGMMS2_SCHEDULER_TIMELINE_HANDLE Timeline, _In_ ULONG Generation, _In_ ULONG NodeOrdinal, _In_ ULONG FenceId);
typedef BOOLEAN (NTAPI *PDXGMMS2_RELEASE_FENCE)(_In_ DXGMMS2_SCHEDULER_TIMELINE_HANDLE Timeline, _In_ ULONG Generation, _In_ ULONG NodeOrdinal, _In_ ULONG FenceId);
typedef NTSTATUS (NTAPI *PDXGMMS2_RESET_FENCE_IDENTITIES)(_In_ DXGMMS2_SCHEDULER_TIMELINE_HANDLE Timeline, _In_ ULONG Generation);
typedef NTSTATUS (NTAPI *PDXGMMS2_QUERY_FENCE_SNAPSHOT)(_In_ DXGMMS2_SCHEDULER_TIMELINE_HANDLE Timeline, _In_ ULONG Generation, _In_ ULONG NodeOrdinal, _Inout_ DXGMMS2_FENCE_SNAPSHOT_V1 *Snapshot);

typedef struct _DXGMMS2_SCHEDULER_TIMELINE_INTERFACE_V1
{
    ULONG Size;
    ULONG Version;
    ULONG FeatureFlags;
    ULONG Generation;
    DXGMMS2_SCHEDULER_TIMELINE_HANDLE TimelineHandle;
    ULONG NodeCount;
    ULONG Reserved;
    PDXGMMS2_ALLOCATE_FENCE AllocateFence;
    PDXGMMS2_RESERVE_FENCE ReserveFence;
    PDXGMMS2_PUBLISH_FENCE PublishFence;
    PDXGMMS2_NOTIFY_FENCE_COMPLETION NotifyFenceCompletion;
    PDXGMMS2_IS_FENCE_PUBLISHED IsFencePublished;
    PDXGMMS2_RELEASE_FENCE ReleaseFence;
    PDXGMMS2_RESET_FENCE_IDENTITIES ResetFenceIdentities;
    PDXGMMS2_QUERY_FENCE_SNAPSHOT QueryFenceSnapshot;
} DXGMMS2_SCHEDULER_TIMELINE_INTERFACE_V1, *PDXGMMS2_SCHEDULER_TIMELINE_INTERFACE_V1;

typedef NTSTATUS (NTAPI *PDXGMMS2_QUERY_SCHEDULER_TIMELINE_INTERFACE)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _Inout_ DXGMMS2_SCHEDULER_TIMELINE_INTERFACE_V1 *TimelineInterface);

typedef struct _DXGMMS2_PROVIDER_INTERFACE_V2
{
    ULONG Size;
    ULONG Version;
    ULONG ProviderFlags;
    ULONG Reserved;
    DXGMMS2_REGISTRATION_HANDLE RegistrationHandle;
    PDXGMMS2_CREATE_ADAPTER CreateAdapter;
    PDXGMMS2_START_ADAPTER StartAdapter;
    PDXGMMS2_BEGIN_STOP_ADAPTER BeginStopAdapter;
    PDXGMMS2_COMPLETE_STOP_ADAPTER CompleteStopAdapter;
    PDXGMMS2_DESTROY_ADAPTER DestroyAdapter;
    PDXGMMS2_QUERY_SCHEDULER_TIMELINE_INTERFACE QuerySchedulerTimelineInterface;
} DXGMMS2_PROVIDER_INTERFACE_V2, *PDXGMMS2_PROVIDER_INTERFACE_V2;

/* The context-stream contract is an internal phase-1 ordering primitive.  It
 * does not advertise a WDDM level or transfer public scheduler ownership.
 * All callbacks are PASSIVE_LEVEL-only. ClientTag and ObjectId are opaque and
 * remain caller-owned. Every successful admission produces exactly one
 * retirement record, including cancellation/TDR/stop paths; callers must
 * drain those records before destroying a stream. Every successful action
 * claim must be committed exactly once, and stop remains busy until claims
 * are returned. All pointed-to descriptors, arrays, and output buffers must
 * remain resident and stable for the duration of a callback. */
#define DXGMMS2_CONTEXT_STREAM_DEFAULT_QUEUE_DEPTH     64UL
#define DXGMMS2_CONTEXT_STREAM_MIN_QUEUE_DEPTH         2UL
#define DXGMMS2_CONTEXT_STREAM_MAX_QUEUE_DEPTH         1024UL
/* D3DKMT signal2 permits 64 additional broadcast contexts in addition to
 * the owning hContext, so an atomic transaction can contain 65 streams. */
#define DXGMMS2_CONTEXT_STREAM_MAX_BROADCAST_CONTEXTS  65UL

#define DXGMMS2_CONTEXT_SIGNAL_AT_SUBMISSION           0x00000001UL
#define DXGMMS2_CONTEXT_SIGNAL_VALID_MASK              0x00000001UL

#define DXGMMS2_CONTEXT_CANCEL_FORCE_SUBMITTED         0x00000001UL
#define DXGMMS2_CONTEXT_CANCEL_TDR                      0x00000002UL
#define DXGMMS2_CONTEXT_CANCEL_VALID_MASK               0x00000003UL

typedef enum _DXGMMS2_CONTEXT_STREAM_PUBLIC_STATE
{
    Dxgmms2ContextStreamPublicActive = 1,
    Dxgmms2ContextStreamPublicClosing = 2
} DXGMMS2_CONTEXT_STREAM_PUBLIC_STATE;

typedef enum _DXGMMS2_CONTEXT_ACTION_TYPE
{
    Dxgmms2ContextActionWork = 1,
    Dxgmms2ContextActionSignal = 2,
    Dxgmms2ContextActionWait = 3
} DXGMMS2_CONTEXT_ACTION_TYPE;

typedef struct _DXGMMS2_CREATE_CONTEXT_STREAM_INFO_V1
{
    ULONG Size;
    ULONG Version;
    ULONG NodeOrdinal;
    ULONG QueueDepth;
    ULONG Flags;
    ULONG Reserved;
} DXGMMS2_CREATE_CONTEXT_STREAM_INFO_V1, *PDXGMMS2_CREATE_CONTEXT_STREAM_INFO_V1;

typedef struct _DXGMMS2_ADMIT_CONTEXT_WORK_V1
{
    ULONG Size;
    ULONG Version;
    ULONGLONG ClientTag;
} DXGMMS2_ADMIT_CONTEXT_WORK_V1, *PDXGMMS2_ADMIT_CONTEXT_WORK_V1;

typedef struct _DXGMMS2_ADMIT_CONTEXT_WAIT_V1
{
    ULONG Size;
    ULONG Version;
    ULONG Flags;
    ULONG Reserved;
    ULONGLONG ObjectId;
    ULONGLONG FenceValue;
    ULONGLONG ClientTag;
} DXGMMS2_ADMIT_CONTEXT_WAIT_V1, *PDXGMMS2_ADMIT_CONTEXT_WAIT_V1;

typedef struct _DXGMMS2_ADMIT_CONTEXT_SIGNAL_V1
{
    ULONG Size;
    ULONG Version;
    ULONG Flags;
    ULONG ContextCount;
    const DXGMMS2_CONTEXT_STREAM_HANDLE *ContextHandles;
    ULONGLONG *Sequences;
    ULONGLONG ObjectId;
    ULONGLONG FenceValue;
    ULONGLONG ClientTag;
} DXGMMS2_ADMIT_CONTEXT_SIGNAL_V1, *PDXGMMS2_ADMIT_CONTEXT_SIGNAL_V1;

typedef struct _DXGMMS2_CONTEXT_ACTION_V1
{
    ULONG Size;
    ULONG Version;
    ULONG Type;
    ULONG Flags;
    DXGMMS2_CONTEXT_STREAM_HANDLE ContextHandle;
    ULONGLONG Sequence;
    ULONGLONG TransactionId;
    ULONGLONG ClaimToken;
    ULONGLONG ObjectId;
    ULONGLONG FenceValue;
    ULONGLONG ClientTag;
} DXGMMS2_CONTEXT_ACTION_V1, *PDXGMMS2_CONTEXT_ACTION_V1;

typedef struct _DXGMMS2_CANCEL_CONTEXT_STREAM_INFO_V1
{
    ULONG Size;
    ULONG Version;
    ULONG Flags;
    ULONG Reason;
} DXGMMS2_CANCEL_CONTEXT_STREAM_INFO_V1, *PDXGMMS2_CANCEL_CONTEXT_STREAM_INFO_V1;

typedef struct _DXGMMS2_CONTEXT_STREAM_SNAPSHOT_V1
{
    ULONG Size;
    ULONG Version;
    ULONG Generation;
    ULONG State;
    ULONG NodeOrdinal;
    ULONG QueueDepth;
    ULONG QueuedEntryCount;
    ULONG ActiveClaimCount;
    ULONG CancelReason;
    ULONG RetiredEntryCount;
    ULONGLONG LastAdmittedSequence;
    ULONGLONG LastSubmittedSequence;
    ULONGLONG LastCompletedSequence;
} DXGMMS2_CONTEXT_STREAM_SNAPSHOT_V1, *PDXGMMS2_CONTEXT_STREAM_SNAPSHOT_V1;

typedef struct _DXGMMS2_CONTEXT_RETIREMENT_V1
{
    ULONGLONG Sequence;
    ULONGLONG TransactionId;
    ULONGLONG ClientTag;
    NTSTATUS TerminalStatus;
    ULONG Type;
    ULONG Flags;
    ULONG Reserved;
} DXGMMS2_CONTEXT_RETIREMENT_V1, *PDXGMMS2_CONTEXT_RETIREMENT_V1;

typedef NTSTATUS (NTAPI *PDXGMMS2_CREATE_CONTEXT_STREAM)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ const DXGMMS2_CREATE_CONTEXT_STREAM_INFO_V1 *Info, _Out_ DXGMMS2_CONTEXT_STREAM_HANDLE *Context);
typedef NTSTATUS (NTAPI *PDXGMMS2_DESTROY_CONTEXT_STREAM)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ DXGMMS2_CONTEXT_STREAM_HANDLE Context);
typedef NTSTATUS (NTAPI *PDXGMMS2_ADMIT_CONTEXT_WORK)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ DXGMMS2_CONTEXT_STREAM_HANDLE Context, _In_ const DXGMMS2_ADMIT_CONTEXT_WORK_V1 *Info, _Out_ ULONGLONG *Sequence);
typedef NTSTATUS (NTAPI *PDXGMMS2_ADMIT_CONTEXT_WAIT)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ DXGMMS2_CONTEXT_STREAM_HANDLE Context, _In_ const DXGMMS2_ADMIT_CONTEXT_WAIT_V1 *Info, _Out_ ULONGLONG *Sequence);
typedef NTSTATUS (NTAPI *PDXGMMS2_ADMIT_CONTEXT_SIGNAL)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ const DXGMMS2_ADMIT_CONTEXT_SIGNAL_V1 *Info, _Out_ ULONGLONG *TransactionId);
typedef NTSTATUS (NTAPI *PDXGMMS2_RESOLVE_CONTEXT_WAIT)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ DXGMMS2_CONTEXT_STREAM_HANDLE Context, _In_ ULONGLONG Sequence, _In_ NTSTATUS WaitStatus);
typedef NTSTATUS (NTAPI *PDXGMMS2_CLAIM_CONTEXT_ACTION)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ DXGMMS2_CONTEXT_STREAM_HANDLE Context, _Inout_ DXGMMS2_CONTEXT_ACTION_V1 *Action);
typedef NTSTATUS (NTAPI *PDXGMMS2_COMMIT_CONTEXT_ACTION)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ DXGMMS2_CONTEXT_STREAM_HANDLE Context, _In_ ULONGLONG Sequence, _In_ ULONGLONG ClaimToken, _In_ NTSTATUS ActionStatus);
typedef NTSTATUS (NTAPI *PDXGMMS2_COMPLETE_CONTEXT_WORK)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ DXGMMS2_CONTEXT_STREAM_HANDLE Context, _In_ ULONGLONG Sequence, _In_ NTSTATUS CompletionStatus);
typedef NTSTATUS (NTAPI *PDXGMMS2_CANCEL_CONTEXT_STREAM)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ DXGMMS2_CONTEXT_STREAM_HANDLE Context, _In_ const DXGMMS2_CANCEL_CONTEXT_STREAM_INFO_V1 *Info);
typedef NTSTATUS (NTAPI *PDXGMMS2_QUERY_CONTEXT_STREAM)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ DXGMMS2_CONTEXT_STREAM_HANDLE Context, _Inout_ DXGMMS2_CONTEXT_STREAM_SNAPSHOT_V1 *Snapshot);
typedef NTSTATUS (NTAPI *PDXGMMS2_DRAIN_CONTEXT_RETIREMENTS)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _In_ DXGMMS2_CONTEXT_STREAM_HANDLE Context, _Out_writes_to_(RecordCapacity, *RetiredCount) DXGMMS2_CONTEXT_RETIREMENT_V1 *Records, _In_ ULONG RecordCapacity, _Out_ ULONG *RetiredCount);

typedef struct _DXGMMS2_CONTEXT_STREAM_INTERFACE_V1
{
    ULONG Size;
    ULONG Version;
    ULONG InterfaceFlags;
    ULONG Generation;
    DXGMMS2_ADAPTER_HANDLE AdapterHandle;
    ULONG MaximumQueueDepth;
    ULONG MaximumBroadcastContexts;
    PDXGMMS2_CREATE_CONTEXT_STREAM CreateContextStream;
    PDXGMMS2_DESTROY_CONTEXT_STREAM DestroyContextStream;
    PDXGMMS2_ADMIT_CONTEXT_WORK AdmitWork;
    PDXGMMS2_ADMIT_CONTEXT_WAIT AdmitWait;
    PDXGMMS2_ADMIT_CONTEXT_SIGNAL AdmitSignal;
    PDXGMMS2_RESOLVE_CONTEXT_WAIT ResolveWait;
    PDXGMMS2_CLAIM_CONTEXT_ACTION ClaimNextAction;
    PDXGMMS2_COMMIT_CONTEXT_ACTION CommitAction;
    PDXGMMS2_COMPLETE_CONTEXT_WORK CompleteWork;
    PDXGMMS2_CANCEL_CONTEXT_STREAM CancelContextStream;
    PDXGMMS2_QUERY_CONTEXT_STREAM QueryContextStream;
    PDXGMMS2_DRAIN_CONTEXT_RETIREMENTS DrainRetirements;
} DXGMMS2_CONTEXT_STREAM_INTERFACE_V1, *PDXGMMS2_CONTEXT_STREAM_INTERFACE_V1;

typedef NTSTATUS (NTAPI *PDXGMMS2_QUERY_CONTEXT_STREAM_INTERFACE)(_In_ DXGMMS2_ADAPTER_HANDLE Adapter, _Inout_ DXGMMS2_CONTEXT_STREAM_INTERFACE_V1 *ContextStreamInterface);

typedef struct _DXGMMS2_PROVIDER_INTERFACE_V3
{
    ULONG Size;
    ULONG Version;
    ULONG ProviderFlags;
    ULONG Reserved;
    DXGMMS2_REGISTRATION_HANDLE RegistrationHandle;
    PDXGMMS2_CREATE_ADAPTER CreateAdapter;
    PDXGMMS2_START_ADAPTER StartAdapter;
    PDXGMMS2_BEGIN_STOP_ADAPTER BeginStopAdapter;
    PDXGMMS2_COMPLETE_STOP_ADAPTER CompleteStopAdapter;
    PDXGMMS2_DESTROY_ADAPTER DestroyAdapter;
    PDXGMMS2_QUERY_SCHEDULER_TIMELINE_INTERFACE QuerySchedulerTimelineInterface;
    PDXGMMS2_QUERY_CONTEXT_STREAM_INTERFACE QueryContextStreamInterface;
} DXGMMS2_PROVIDER_INTERFACE_V3, *PDXGMMS2_PROVIDER_INTERFACE_V3;

#define DXGMMS2_DXGKRNL_INTERFACE_V1_SIZE             ((ULONG)sizeof(DXGMMS2_DXGKRNL_INTERFACE_V1))
#define DXGMMS2_CREATE_ADAPTER_INFO_V1_SIZE            ((ULONG)sizeof(DXGMMS2_CREATE_ADAPTER_INFO_V1))
#define DXGMMS2_START_ADAPTER_INFO_V1_SIZE             ((ULONG)sizeof(DXGMMS2_START_ADAPTER_INFO_V1))
#define DXGMMS2_START_ADAPTER_RESULT_V1_SIZE           ((ULONG)sizeof(DXGMMS2_START_ADAPTER_RESULT_V1))
#define DXGMMS2_STOP_ADAPTER_INFO_V1_SIZE              ((ULONG)sizeof(DXGMMS2_STOP_ADAPTER_INFO_V1))
#define DXGMMS2_PROVIDER_INTERFACE_V1_SIZE              ((ULONG)sizeof(DXGMMS2_PROVIDER_INTERFACE_V1))
#define DXGMMS2_PROVIDER_INTERFACE_V2_SIZE              ((ULONG)sizeof(DXGMMS2_PROVIDER_INTERFACE_V2))
#define DXGMMS2_PROVIDER_INTERFACE_V3_SIZE              ((ULONG)sizeof(DXGMMS2_PROVIDER_INTERFACE_V3))
#define DXGMMS2_SCHEDULER_TIMELINE_INTERFACE_V1_SIZE    ((ULONG)sizeof(DXGMMS2_SCHEDULER_TIMELINE_INTERFACE_V1))
#define DXGMMS2_FENCE_SNAPSHOT_V1_SIZE                  ((ULONG)sizeof(DXGMMS2_FENCE_SNAPSHOT_V1))
#define DXGMMS2_CREATE_CONTEXT_STREAM_INFO_V1_SIZE      ((ULONG)sizeof(DXGMMS2_CREATE_CONTEXT_STREAM_INFO_V1))
#define DXGMMS2_ADMIT_CONTEXT_WORK_V1_SIZE              ((ULONG)sizeof(DXGMMS2_ADMIT_CONTEXT_WORK_V1))
#define DXGMMS2_ADMIT_CONTEXT_WAIT_V1_SIZE              ((ULONG)sizeof(DXGMMS2_ADMIT_CONTEXT_WAIT_V1))
#define DXGMMS2_ADMIT_CONTEXT_SIGNAL_V1_SIZE            ((ULONG)sizeof(DXGMMS2_ADMIT_CONTEXT_SIGNAL_V1))
#define DXGMMS2_CONTEXT_ACTION_V1_SIZE                  ((ULONG)sizeof(DXGMMS2_CONTEXT_ACTION_V1))
#define DXGMMS2_CANCEL_CONTEXT_STREAM_INFO_V1_SIZE      ((ULONG)sizeof(DXGMMS2_CANCEL_CONTEXT_STREAM_INFO_V1))
#define DXGMMS2_CONTEXT_STREAM_SNAPSHOT_V1_SIZE         ((ULONG)sizeof(DXGMMS2_CONTEXT_STREAM_SNAPSHOT_V1))
#define DXGMMS2_CONTEXT_RETIREMENT_V1_SIZE               ((ULONG)sizeof(DXGMMS2_CONTEXT_RETIREMENT_V1))
#define DXGMMS2_CONTEXT_STREAM_INTERFACE_V1_SIZE        ((ULONG)sizeof(DXGMMS2_CONTEXT_STREAM_INTERFACE_V1))

NTSTATUS NTAPI DxgkMms2Register(_In_ const DXGMMS2_DXGKRNL_INTERFACE_V1 *DxgkrnlInterface, _Inout_ DXGMMS2_PROVIDER_INTERFACE_V1 *ProviderInterface);
NTSTATUS NTAPI DxgkMms2Unregister(_In_ DXGMMS2_REGISTRATION_HANDLE Registration);

#ifdef __cplusplus
}
#endif

#endif /* _REACTOS_DXGMMS2_H_ */
