#!/usr/bin/env python3
#
# PROJECT:     LiberNT NetIO driver
# LICENSE:     GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later)
# PURPOSE:     Generates the WFP layer and field table from the WDK fwpsk.h and fwpmk.h
# COPYRIGHT:   Copyright 2026 Ahmed ARIF <arif.ing@outlook.com>
#

import re
import sys

HEADER = '''/*
 * PROJECT:     LiberNT NetIO driver
 * LICENSE:     GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later)
 * PURPOSE:     WFP layer and field identifiers, generated by genlayers.py
 * COPYRIGHT:   Copyright 2026 Ahmed ARIF <arif.ing@outlook.com>
 */

#include "wfp.h"
'''


def strip_comments(text):
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
    return re.sub(r'//[^\n]*', '', text)


def active_lines(text):
    stack = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith('#if'):
            stack.append('NTDDI_VERSION == NTDDI_WIN7' not in stripped and
                         'NTDDI_VERSION < ' not in stripped)
        elif stripped.startswith('#else'):
            stack[-1] = not stack[-1]
        elif stripped.startswith('#endif'):
            stack.pop()
        elif all(stack):
            yield line


def enums(text):
    body = '\n'.join(active_lines(strip_comments(text)))
    for match in re.finditer(r'typedef enum (\w+)_\s*\{(.*?)\}\s*(\w+);', body, re.S):
        yield match.group(3), re.findall(r'^\s*(\w+)\s*(?:=[^,\n]*)?,?\s*$', match.group(2), re.M)


def guid_values(text):
    values = {}
    pattern = r'DEFINE_GUID\(\s*(\w+)\s*,((?:\s*0x[0-9a-fA-F]+\s*,){10}\s*0x[0-9a-fA-F]+)\s*\)'
    for name, body in re.findall(pattern, strip_comments(text)):
        parts = [int(part, 16) for part in re.findall(r'0x[0-9a-fA-F]+', body)]
        values[name] = '{ 0x%08x, 0x%04x, 0x%04x, { %s } }' % (
            parts[0], parts[1], parts[2], ', '.join('0x%02x' % part for part in parts[3:]))
    return values


def main():
    fwpsk = open(sys.argv[1], encoding='latin-1').read()
    fwpmk = open(sys.argv[2], encoding='latin-1').read()
    guids = guid_values(fwpmk)
    aliases = dict(re.findall(r'#define\s+(FWPM_CONDITION_\w+)\s*\\?\s*(FWPM_CONDITION_\w+)', fwpmk))
    tables = dict(enums(fwpsk))
    layers = [name for name in tables['FWPS_BUILTIN_LAYERS'] if name != 'FWPS_BUILTIN_LAYER_MAX']
    zero = '{ 0 }'
    out = [HEADER]
    rows = []
    for layer in layers:
        short = layer[len('FWPS_LAYER_'):]
        key = guids.get('FWPM_LAYER_' + short, zero)
        base = short
        fields = tables.get('FWPS_FIELDS_' + base)
        if fields is None and short.endswith('_DISCARD'):
            base = short[:-len('_DISCARD')]
            fields = tables.get('FWPS_FIELDS_' + base)
        if fields is None:
            rows.append('    { %s, NULL, 0 },' % key)
            continue
        if base == short:
            prefix = 'FWPS_FIELD_' + base + '_'
            out.append('static const GUID WfpFields_%s[] =\n{' % base)
            for field in fields:
                if field.endswith('_MAX'):
                    continue
                condition = 'FWPM_CONDITION_' + field[len(prefix):] if field.startswith(prefix) else ''
                condition = aliases.get(condition, condition)
                out.append('    %s,' % guids.get(condition, zero))
            out.append('};\n')
        rows.append('    { %s, WfpFields_%s, RTL_NUMBER_OF(WfpFields_%s) },' % (key, base, base))
    out.append('const WFP_LAYER WfpLayers[] =\n{')
    out.extend(rows)
    out.append('};\n')
    out.append('const ULONG WfpLayerCount = RTL_NUMBER_OF(WfpLayers);')
    print('\n'.join(out))


if __name__ == '__main__':
    main()
