/*
 * PROJECT:     ReactOS WDDM API Tests
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Precompiled header for dxgkrnl API tests
 * COPYRIGHT:   Copyright 2026 ReactOS WDDM Team
 */

#ifndef _DXGKRNL_APITEST_PRECOMP_H_
#define _DXGKRNL_APITEST_PRECOMP_H_

#define WIN32_NO_STATUS
#include <apitest.h>

#include <windef.h>
#include <winbase.h>
#include <wingdi.h>
#include <winioctl.h>

/*
 * D3DKMT types — pull in d3dkmthk.h for the D3DKMT_* structures.
 * On ReactOS this is available in the SDK.
 */
#include <d3dkmthk.h>

/* ---- IOCTL code definitions (mirror dxgkrnl d3dkmt.h) ---- */

#define DXGKRNL_DEVICE_TYPE     0x23

#define IOCTL_D3DKMT_ENUMADAPTERS \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x100, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_ENUMADAPTERS2 \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x101, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_OPENADAPTERFROMLUID \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x102, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_CLOSEADAPTER \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x103, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_QUERYADAPTERINFO \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x104, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_GETDISPLAYMODELIST \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x105, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_OPENADAPTERFROMHDC \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x110, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_OPENADAPTERFROMGDIDISPLAYNAME \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x111, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_OPENADAPTERFROMDEVICENAME \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x112, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_CREATEDEVICE \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x120, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_DESTROYDEVICE \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x121, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_CREATEALLOCATION \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x130, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_DESTROYALLOCATION \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x131, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_LOCK \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x132, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_UNLOCK \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x133, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_RENDER \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x140, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_PRESENT \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x141, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_WAITFORSYNCHRONIZATIONOBJECT \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x150, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_SIGNALSYNCHRONIZATIONOBJECT \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x151, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_SETDISPLAYMODE \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x160, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_CREATECONTEXT \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x122, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_DESTROYCONTEXT \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x123, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_CREATESYNCHRONIZATIONOBJECT \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x152, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_DESTROYSYNCHRONIZATIONOBJECT \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x153, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_ESCAPE \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x170, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_SETALLOCATIONPRIORITY \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x162, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_QUERYALLOCATIONRESIDENCY \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x163, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_GETSHAREDPRIMARYHANDLE \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x136, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_GETPRESENTHISTORY \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x142, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_SETVIDPNSOURCEOWNER \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x161, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_GETDEVICESTATE \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x124, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_SETCONTEXTSCHEDULINGPRIORITY \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x125, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_GETCONTEXTSCHEDULINGPRIORITY \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x126, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_WAITFORIDLE \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x16B, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_CHECKVIDPNEXCLUSIVEOWNERSHIP \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x165, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_WAITFORVERTICALBLANKEVENT \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x166, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_GETSCANLINE \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x167, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_CHECKMONITORPOWERSTATE \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x168, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_D3DKMT_POLLDISPLAYCHILDREN \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x179, METHOD_BUFFERED, FILE_ANY_ACCESS)

/* ---- WDDM 2.0: GPU virtual addressing IOCTLs ---- */
#define IOCTL_D3DKMT_MAKERESIDENT \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x180, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_EVICT \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x181, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_MAPGPUVIRTUALADDRESS \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x182, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_RESERVEGPUVIRTUALADDRESS \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x183, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_FREEGPUVIRTUALADDRESS \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x184, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_D3DKMT_UPDATEGPUVIRTUALADDRESS \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x185, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DXGKRNL_EXCHANGE_INTERFACE \
    CTL_CODE(DXGKRNL_DEVICE_TYPE, 0x200, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define DXGKRNL_INTERFACE_VERSION_1  1

/* ---- D3DKMT types not available at Vista level ---- */

#ifndef MAX_ENUM_ADAPTERS
#define MAX_ENUM_ADAPTERS   16
#endif

#ifndef _D3DKMT_ADAPTERINFO_DEFINED
#define _D3DKMT_ADAPTERINFO_DEFINED
typedef struct _D3DKMT_ADAPTERINFO
{
    D3DKMT_HANDLE       hAdapter;
    LUID                AdapterLuid;
    ULONG               NumOfSources;
    BOOL                bPrecisePresentRegionsPreferred;
} D3DKMT_ADAPTERINFO;
#endif

#ifndef _D3DKMT_ENUMADAPTERS_DEFINED
#define _D3DKMT_ENUMADAPTERS_DEFINED
typedef struct _D3DKMT_ENUMADAPTERS
{
    ULONG               NumAdapters;
    D3DKMT_ADAPTERINFO  Adapters[MAX_ENUM_ADAPTERS];
} D3DKMT_ENUMADAPTERS;
#endif

#ifndef _D3DKMT_ENUMADAPTERS2_DEFINED
#define _D3DKMT_ENUMADAPTERS2_DEFINED
typedef struct _D3DKMT_ENUMADAPTERS2
{
    ULONG               NumAdapters;
    D3DKMT_ADAPTERINFO *pAdapters;
} D3DKMT_ENUMADAPTERS2;
#endif

#ifndef _D3DKMT_OPENADAPTERFROMLUID_DEFINED
#define _D3DKMT_OPENADAPTERFROMLUID_DEFINED
typedef struct _D3DKMT_OPENADAPTERFROMLUID
{
    LUID                AdapterLuid;
    D3DKMT_HANDLE       hAdapter;
} D3DKMT_OPENADAPTERFROMLUID;
#endif

#ifndef _D3DKMT_SEGMENTSIZEINFO_DEFINED
#define _D3DKMT_SEGMENTSIZEINFO_DEFINED
typedef struct _D3DKMT_SEGMENTSIZEINFO
{
    ULONGLONG           DedicatedVideoMemorySize;
    ULONGLONG           DedicatedSystemMemorySize;
    ULONGLONG           SharedSystemMemorySize;
} D3DKMT_SEGMENTSIZEINFO;
#endif

/* ---- WDDM 2.0 GPU VA test types (local copies) ---- */

typedef ULONGLONG D3DGPU_VIRTUAL_ADDRESS_TEST;

typedef struct _TEST_MAPGPUVA
{
    D3DKMT_HANDLE               hPagingQueue;
    D3DGPU_VIRTUAL_ADDRESS_TEST BaseAddress;
    D3DGPU_VIRTUAL_ADDRESS_TEST MinimumAddress;
    D3DGPU_VIRTUAL_ADDRESS_TEST MaximumAddress;
    D3DKMT_HANDLE               hAllocation;
    UINT64                      OffsetInPages;
    UINT64                      SizeInPages;
    UINT64                      Protection;
    UINT64                      DriverProtection;
    UINT                        Reserved0;
    UINT64                      Reserved1;
    D3DGPU_VIRTUAL_ADDRESS_TEST VirtualAddress;
    UINT64                      PagingFenceValue;
} TEST_MAPGPUVA;

typedef struct _TEST_RESERVEGPUVA
{
    D3DKMT_HANDLE               hPagingQueue;
    D3DGPU_VIRTUAL_ADDRESS_TEST BaseAddress;
    D3DGPU_VIRTUAL_ADDRESS_TEST MinimumAddress;
    D3DGPU_VIRTUAL_ADDRESS_TEST MaximumAddress;
    UINT64                      Size;
    UINT                        ReservationType;
    UINT64                      DriverProtection;
    D3DGPU_VIRTUAL_ADDRESS_TEST VirtualAddress;
    UINT64                      PagingFenceValue;
} TEST_RESERVEGPUVA;

typedef struct _TEST_FREEGPUVA
{
    D3DKMT_HANDLE               hAdapter;
    D3DGPU_VIRTUAL_ADDRESS_TEST BaseAddress;
    UINT64                      Size;
} TEST_FREEGPUVA;

typedef struct _TEST_MAKERESIDENT
{
    D3DKMT_HANDLE               hPagingQueue;
    UINT                        NumAllocations;
    CONST D3DKMT_HANDLE        *AllocationList;
    CONST UINT                 *PriorityList;
    UINT                        FlagsValue;
    UINT64                      PagingFenceValue;
    UINT64                      NumBytesToTrim;
} TEST_MAKERESIDENT;

typedef struct _TEST_EVICT
{
    D3DKMT_HANDLE               hDevice;
    UINT                        NumAllocations;
    CONST D3DKMT_HANDLE        *AllocationList;
    UINT                        FlagsValue;
    UINT64                      NumBytesToTrim;
} TEST_EVICT;

/* ---- Helper to open \Device\DxgKrnl ---- */
static inline HANDLE
OpenDxgKrnl(void)
{
    return CreateFileW(L"\\\\.\\DxgKrnl",
                       GENERIC_READ | GENERIC_WRITE,
                       0, NULL, OPEN_EXISTING,
                       FILE_ATTRIBUTE_NORMAL, NULL);
}

/* ---- Helper to send IOCTL ---- */
static inline BOOL
SendDxgIoctl(
    _In_ HANDLE hDevice,
    _In_ DWORD dwIoControlCode,
    _In_opt_ LPVOID lpInBuffer,
    _In_ DWORD nInBufferSize,
    _Out_opt_ LPVOID lpOutBuffer,
    _In_ DWORD nOutBufferSize,
    _Out_opt_ LPDWORD lpBytesReturned)
{
    DWORD BytesReturned = 0;
    if (!lpBytesReturned)
        lpBytesReturned = &BytesReturned;
    return DeviceIoControl(hDevice, dwIoControlCode,
                           lpInBuffer, nInBufferSize,
                           lpOutBuffer, nOutBufferSize,
                           lpBytesReturned, NULL);
}

#endif /* _DXGKRNL_APITEST_PRECOMP_H_ */
