/* Automatically generated by make depend; DO NOT EDIT!! */

#define STANDALONE
#include <wine/test.h>

extern void func_connectivity(void);

const struct test winetest_testlist[] =
{
    { "connectivity", func_connectivity },
    { 0, 0 }
};
