# D3DKMT kernel thunk exports (ordinals 1-10)
1  stdcall D3DKMTCloseAdapter(ptr)
2  stdcall D3DKMTDestroyAllocation(ptr)
3  stdcall D3DKMTDestroyContext(ptr)
4  stdcall D3DKMTDestroyDevice(ptr)
5  stdcall D3DKMTDestroySynchronizationObject(ptr)
6  stdcall D3DKMTQueryAdapterInfo(ptr)
7  stdcall D3DKMTSetDisplayPrivateDriverFormat(ptr)
8  stdcall D3DKMTSignalSynchronizationObject(ptr)
9  stdcall D3DKMTUnlock(ptr)
10 stdcall D3DKMTWaitForSynchronizationObject(ptr)

# Diagnostic export (ordinal 11)
11 stdcall DXGIDumpJournal()

# UMD loading exports (ordinals 12-13)
12 stdcall OpenAdapter10(ptr)
13 stdcall OpenAdapter10_2(ptr)

# Factory creation exports (ordinals 14-15)
14 stdcall CreateDXGIFactory(ptr ptr)
15 stdcall CreateDXGIFactory1(ptr ptr)

# D3DKMT kernel thunk exports (ordinals 16-39)
16 stdcall D3DKMTCreateAllocation(ptr)
17 stdcall D3DKMTCreateContext(ptr)
18 stdcall D3DKMTCreateDevice(ptr)
19 stdcall D3DKMTCreateSynchronizationObject(ptr)
20 stdcall D3DKMTEscape(ptr)
21 stdcall D3DKMTGetContextSchedulingPriority(ptr)
22 stdcall D3DKMTGetDeviceState(ptr)
23 stdcall D3DKMTGetDisplayModeList(ptr)
24 stdcall D3DKMTGetMultisampleMethodList(ptr)
25 stdcall D3DKMTGetRuntimeData(ptr)
26 stdcall D3DKMTGetSharedPrimaryHandle(ptr)
27 stdcall D3DKMTLock(ptr)
28 stdcall D3DKMTOpenAdapterFromHdc(ptr)
29 stdcall D3DKMTOpenResource(ptr)
30 stdcall D3DKMTPresent(ptr)
31 stdcall D3DKMTQueryAllocationResidency(ptr)
32 stdcall D3DKMTQueryResourceInfo(ptr)
33 stdcall D3DKMTRender(ptr)
34 stdcall D3DKMTSetAllocationPriority(ptr)
35 stdcall D3DKMTSetContextSchedulingPriority(ptr)
36 stdcall D3DKMTSetDisplayMode(ptr)
37 stdcall D3DKMTSetGammaRamp(ptr)
38 stdcall D3DKMTSetVidPnSourceOwner(ptr)
39 stdcall D3DKMTWaitForVerticalBlankEvent(ptr)

# D3D10 device creation exports (ordinals 40-43)
40 stdcall DXGID3D10CreateDevice(ptr ptr ptr long ptr long ptr)
41 stdcall DXGID3D10CreateLayeredDevice(ptr)
42 stdcall DXGID3D10GetLayeredDeviceSize(ptr long)
43 stdcall DXGID3D10RegisterLayers(ptr long)

# Adapter configuration reporting (ordinal 44)
44 stdcall DXGIReportAdapterConfiguration(long)
