[FREELOADER]
DefaultOS=LiveImg_RamDisk_Debug
TimeOut=1

[Display]
TitleText=ReactOS Boot Media
MinimalUI=Yes

[Operating Systems]
LiveImg="ReactOS"
LiveImg_Debug="ReactOS - Debug"
LiveImg_Debug_SingleCPU="ReactOS - Debug Single CPU"
LiveImg_Debug_SMP="ReactOS - Debug SMP"
LiveImg_Screen="ReactOS - Screen"
LiveImg_RamDisk_Normal="ReactOS Ramdisk - Normal"
LiveImg_RamDisk_Debug="ReactOS Ramdisk - Debug"
LiveImg_RamDisk_Debug_SingleCPU="ReactOS Ramdisk - Debug Single CPU"
LiveImg_RamDisk_Debug_SMP="ReactOS Ramdisk - Debug SMP"
LiveImg_RamDisk_Screen="ReactOS Ramdisk - Screen"
; ROSCONFIG_PROFILE_OS_ENTRIES

[LiveImg]
BootType=Windows2003
SystemPath=\reactos
Options=/KERNEL=ntkrnlmp.exe /FASTDETECT /MININT

[LiveImg_Debug]
BootType=Windows2003
SystemPath=\reactos
Options=/KERNEL=ntkrnlmp.exe /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /FASTDETECT /MININT /LOADSYMBOLS

[LiveImg_Debug_SingleCPU]
BootType=Windows2003
SystemPath=\reactos
Options=/DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /FASTDETECT /MININT /LOADSYMBOLS

[LiveImg_Debug_SMP]
BootType=Windows2003
SystemPath=\reactos
Options=/KERNEL=ntkrnlmp.exe /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /FASTDETECT /MININT /SMPDIAG

[LiveImg_Screen]
BootType=Windows2003
SystemPath=\reactos
Options=/KERNEL=ntkrnlmp.exe /DEBUG /DEBUGPORT=SCREEN /SOS /FASTDETECT /MININT

[LiveImg_RamDisk_Normal]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/KERNEL=ntkrnlmp.exe /FASTDETECT /MININT /RDPATH= /RDRAMSIZE=64M
;Options=/FASTDETECT /MININT /RDPATH=liveimg.iso /RDRAMSIZE=64M

[LiveImg_RamDisk_Debug]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/KERNEL=ntkrnlmp.exe /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /FASTDETECT /MININT /RDPATH= /RDRAMSIZE=64M /LOADSYMBOLS

[LiveImg_RamDisk_Debug_SingleCPU]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /FASTDETECT /MININT /RDPATH= /RDRAMSIZE=64M /LOADSYMBOLS

[LiveImg_RamDisk_Debug_SMP]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/KERNEL=ntkrnlmp.exe /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /FASTDETECT /MININT /RDPATH= /RDRAMSIZE=64M /SMPDIAG

[LiveImg_RamDisk_Screen]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/KERNEL=ntkrnlmp.exe /DEBUG /DEBUGPORT=SCREEN /SOS /FASTDETECT /MININT /RDPATH= /RDRAMSIZE=64M

; ROSCONFIG_PROFILE_BOOT_ENTRIES
