[FREELOADER]
DefaultOS=LiveImg_RamDisk_Normal
TimeOut=1

[Display]
TitleText=LiberNT
MinimalUI=Yes

[Operating Systems]
LiveImg_RamDisk_Normal="LiberNT"
; ROSCONFIG_PROFILE_OS_ENTRIES

[LiveImg_RamDisk_Normal]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
BootLogo=LiberNT
Options=/KERNEL=ntkrnlmp.exe /FASTDETECT /MININT /RDPATH= /RDRAMSIZE=64M

; ROSCONFIG_PROFILE_BOOT_ENTRIES
