[FREELOADER]
DefaultOS=ReactOS
TimeOut=1

[Display]
TitleText=LiberNT
MinimalUI=Yes

[Operating Systems]
ReactOS="LiberNT"
; ROSCONFIG_PROFILE_OS_ENTRIES

[ReactOS]
BootType=Windows2003
SystemPath=partition(2)\ReactOS
BootLogo=LiberNT
Options=/KERNEL=ntkrnlmp.exe /FASTDETECT /KDWATCHDOG=0

; ROSCONFIG_PROFILE_BOOT_ENTRIES
